chroma-core/chroma

- bin/getting-started.py
- chroma/api/fastapi.py
- chroma/api/local.py
- chroma/server/fastapi/__init__.py
- chroma/server/fastapi/types.py
The local api implementation uses ```unlabeled_dataset_name``` however the fastapi version is outdated - using ``` inference_dataset_name```.  This breaks calls like process() since they have the wrong dataset name.
> [WIP] Rename inference_dataset_name to unlabeled_dataset_name to match local API implementation

- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/test_api.py
@atroyn please review to assure this does what you expect. 
Context: if a user deleted the client mid-script, the `__del__` would not get run via garbage collection until after the program exited. In rare cases (like in tests) - you want to be able to explicitly call `.persist`. This pipes that through.
> Explicit persist

- chromadb/api/types.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/test/test_api.py
This PR adds support for comparators in where clauses. gt, lt, gte, lte are supported on numbers (ints, floats). ne is supported on (ints, floats, strings). This PR is stacked on #121, please see that before looking at this.
All changes
1. Add operator expression typing. 
2. Update where validation for operator expressions
3. Add support for operators in duckdb and clickhouse
4. Add tests for all functionality
> Add comparator support: gt, lt, gte, lte, ne

- chromadb/api/local.py
- chromadb/api/models/Collection.py
- chromadb/api/types.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/test/test_api.py
This PR enables users to add int/float metadata and to filter on it as part of where clauses.
**All changes**
1. Add int and float support in metadata 
2. Add metadata validation
3. Add int and float support in where clauses
4. Add where validation
5. Add handling in duckdb and clickhouse for int/float filtering
6. Add extensive tests for added functionality 
7. Remove unnecessary validation and one_to_many logic (cleanup)
8. Adds comparator support from stacked pr #122
> Support ints/floats in metadata and for where clauses

- chromadb/db/clickhouse.py
This fixes nondeterministic failures of integration tests.
> Initialize clickhouse conn on demand instead of startup

- chromadb/api/types.py
Older versions of python don't support Union as |. Use Union instead.
> Update typing for older python versions

- chromadb/api/types.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/test/test_api.py
This PR adds $and as well as $or support for where as well as where_document fields during get, query, and delete. This PR is stacked on #130 so please read that before this.
All changes
1. Add typing for logical operators $and + $or
2. Add validation and validation tests for logical operators
3. Add support in clickhouse and duckdb. The code is duplicative across dbs but we expect this to change soon so leaving for now since footprint is minimal.
You can use this functionality like so
```
items = collection.get(
where_document={
"$or": [
{"$contains": "first"},
{"$contains": "second"},
]
},
where={
"int_value": {"$ne": 2},
},
)
```
> $and + $or support

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/api/models/Collection.py
- chromadb/api/types.py
- chromadb/db/__init__.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/server/fastapi/__init__.py
- chromadb/server/fastapi/types.py
- chromadb/test/test_api.py
This PR adds support for doing string $contains on the document provided (if any). It is a fairly naive solution for now, to get the API in place. We can add a more performant solution in the future!
All changes
- Add support for WhereDocument type
- Add validator to WhereDocument type
- Plumb WhereDocument validator and as a flag to query, get, delete
- Add support for string contains in clickhouse and duckdb
From stacked #133 
Add typing for logical operators $and + $or
Add validation and validation tests for logical operators
Add support in clickhouse and duckdb. The code is duplicative across dbs but we expect this to change soon so leaving for now since footprint is minimal.
> Add document string $contains, $or, $and

- chromadb/api/local.py
- chromadb/test/test_api.py
If where_document is None at the Collection call, delete should pass an empty dict down to the client. Add back tests to catch this case. They were commented out.
> Add delete tests back and where_document null handling

- Dockerfile
- bin/docker_entrypoint.sh
This PR changes the default Docker launch script to rebuild hnswlib before starting uvicorn.
This is required to ensure that instruction set used by the hnswlib native build matches the actual running hardware. Previous to this fix, the process could fail with a SIGILL, because the Docker image is originally built on a system with AVX2 available, but some target systems on AWS EC2 do not support AVX2.
This change makes a tradeoff: the docker image now takes longer to start, but it guarantees not only that there won't be invalid instructions, but that hnsw will be compiled in a way that is optimal for the hardware the user is actually using.
Integration tests will indicate that this did not cause any regressions
No documentation changes necessary for this change: documentation will be …
> Rebuild hnswlib on Docker launch

- .github/workflows/chroma-release.yml
- bin/generate_cloudformation.py
- bin/templates/docker-compose.yml
- bin/test-remote
- chromadb/test/test_api.py
- Add script to generate CloudFormation template
- Add utilities to tests to make it easy to test that a remote instance is working
- Update Github Actions script to generate the template and push it to S3 upon release.
Manually tested
How to use the CF template will be documented in the Docs repo.
> Tools to create a CloudFormation template for a simple deploy

- pyproject.toml
This addresses #147 by relaxing the requirements to known-good lower bounds. We could perhaps go lower than these bounds but without spending too much time this unblocks users trying to use newer versions of python that have transitive dependencies that are pinned to a non-compatible version.
- Change package dependencies to only require lower bounds
- None
By Integration and Release CI pipelines.
None required.
> Migrate to lower bounds for pyproject.toml

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/api/models/Collection.py
- chromadb/api/types.py
- chromadb/db/__init__.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/server/fastapi/__init__.py
- chromadb/server/fastapi/types.py
- chromadb/test/test_api.py
This PR adds support for includes fields while query()ing. These new parameters control if what data is returned (and queried in the db).
All changes:
- Add includes_[documents,embeddings,metadatas,distances] to query and pass it through to client.
- Add logic in db to support controlling which columns are selected
- Wire up client to support column selection
- Tests for includes fields
> Add support for query "include"

- examples/local_persistence.ipynb
This PR adds a simple example notebook demonstrating how to persist the local / in-memory Chroma database to disk, and load it again. 
Simply run the notebook. 
None, this is documentation.
> Persistence example notebook

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/test/test_api.py
- Fix a bug where persistence and `embedding_function`s are fundamentally incompatible. We do not allow a user to get_collection and supply an embedding function. Previously, if they were to `create_collection` with an `embedding_function` and then create a new client, `get_collection `would not be aware of the `embedding_function`, leading to it use the default. This change allows get'ing a collection and allowing for an `embedding_function `to be passed.
Thanks to @wpnbos for finding this bug!
A test was added for the bug-fixed case.
All docstrings are now up to date.  Documentation PR is here https://github.com/chroma-core/docs/pull/4
> Allow embedding_function to be passed to get_collection

- chromadb/api/local.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/test/test_api.py
There was a bug where distances did not line up with returned documents/metadata/etc because of the db resorting things. This fixes that.
There is a test
None
> line up distances with documents for queries

- chromadb/api/local.py
- chromadb/db/__init__.py
- chromadb/db/duckdb.py
- chromadb/test/test_api.py
- This addresses #170 by throwing an error if the collection does not exist on get_collection
- None
Adds a test to check for errors. I did not add verification of the error contents, as the server version does not transmit errors back down to the client until #150 lands exception middleware.
No changes needed.
> Add error on get_collection fail

- bin/generate_cloudformation.py
Remove "Region" parameter from generated CF template. It is not necessary since the AWS Region is already configured in the AWS CLI or console, 
Tested manually by generating a CF template locally and deploying to an arbitrary region.
https://github.com/chroma-core/docs/pull/9
> Use current region instead of explicit param

- bin/generate_cloudformation.py
Previously, it was easy to accidentally release the CF template to the /latest path in S3 when building locally.
Tested the negative case locally, only possible to test the positive case by actually running it on CI.
Not a user-facing change.
> Only push cf template to /latest for release versions

- chromadb/api/models/Collection.py
Addresses #171 
- Our handling of embedding functions is a bit odd since we require it whenever we get/create/get_or_create an embedding_function. In order to make the behavior clear to users we should log when we use the default.
- None
Not testing as its just a logging change.
None needed. The docs address this behavior. Although it being a source of confusion is perhaps a flag to address it in a cleaner way.
> Log embedding function

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/api/models/Collection.py
- chromadb/db/__init__.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/test_api.py
- This PR properly returns metadata as a part of collection. This functionality was previously a bit broken as if you added metadata to a collection you could never access it. This makes progress towards #183 
- None
Tests were added for creating, retrieving, modifying and listing collections with metadata
None required
> Return metadata as part of collection

- chromadb/db/clickhouse.py
- As per https://clickhouse.com/docs/en/integrations/language-clients/python/options/ - clickhouse-connect autogenerates session_ids per client by default. However clickhouse by default creates a unique session_id internally per query, which is the behavior we want. This disables clickhouse-connects autogeneration of a persistent session_id across queries. This was previously breaking concurrent requests from succeeding on occasion
- None
Existing tests capture the changes
None required
> Allow clickhouse to create session_id per request

- chromadb/utils/embedding_functions.py
Add embedding wrapper for http request to hugging faces embedding api
- allows user to supply their hf token and use hf models for embeddings
Locally tested the code as I cannot provide an API key for automated testing
Yeah, worth mentioning this is available
> Add embedding wrapper for http request to hugging faces embedding api

- chromadb/utils/embedding_functions.py
> In my experience T5 is much better, add comment with that as an option.

- chromadb/__init__.py
- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/config.py
- chromadb/db/__init__.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/server/fastapi/__init__.py
- chromadb/telemetry/__init__.py
- chromadb/telemetry/events.py
- chromadb/telemetry/posthog.py
- pyproject.toml
- requirements.txt
Adds telemetry for chroma
- Added types for delete return 
- Added telemetry which has a type for `TelemetryEvent`s and a `Telemetry` base class.
- `Telemetry` stores the user id in ~/cache/chroma and also stores the context for events. Context contains settings and if the client is running in the server.
- Added `Posthog` which extends Telemetry and implements capture() while respecting anonymized_telemetry
- Added events for client create, add and delete
- Added a __ version __ to chroma **this must now be set for every update**
Tested manually. No functionality changes.
*Are all docstrings for user-facing APIs updated if required? Do we need to make documentation …
> Add telemetry

- chromadb/__init__.py
> new version

- chromadb/db/__init__.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/db/index/__init__.py
- chromadb/db/index/hnswlib.py
- chromadb/test/test_api.py
This PR supersedes #228 with a different approach.
- Change the Hnswlib class from being a singleton to being one instance per index
- Allows multiple indexes to be loaded at the same time, prevents index thrashing
- Configure at initialization time based on collection metadata
- Support for non-uuid embedding IDs (to support future work)
- Resizes the index by a factor of the current size to prevent resizing on every insert
Unit test suite
TODO: Document how to set HNSW params by setting collection metadata.
> Support parameters for HNSW indexes using metadata

- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/test_api.py
- enables getting the current version. closes https://github.com/chroma-core/chroma/issues/145
*How are these changes tested?* - There is a new test. 
Docs will be updated separately.
> get current version

- chromadb/config.py
- chromadb/server/fastapi/__init__.py
- clients/js/examples/browser/README.md
closes https://github.com/chroma-core/chroma/issues/215
I'd like feedback on this. 
None implemented yet
> configurable cors

- chromadb/db/duckdb.py
The collection uuid returned by `create_collection` method on `DuckDB` is different from the one inserted into the db.
The following files were created with the wrong uuid:
- id_to_uuid_{collection_uuid}.pkl
- index_{collection_uuid}.pkl
- index_metadata_{collection_uuid}.pkl
- uuid_to_id_{collection_uuid}.pkl
No need.
> Fix Collection UUID bug on DuckDB

- chromadb/db/index/hnswlib.py
This was a very stupid error, forgetting to rename one of the variables after refactoring the hnswlib implementation.
It should have been caught by an existing unit test: `test_persist_index_loading` exists precisely to validate this behavior. 
However, something in the implementation is cacheing the loaded index, so the unit test test does not catch the fact that the `hnswlib._load()` method was completely broken. This is why it took (relatively) long to debug, we thought the simple case was ruled out.
I'll keep working on figuring out the caching issue so we can get a proper unit test, we need to have test coverage of index save/load cycle. Meanwhile, this fixes the critical issue for our users.
Manually, by creating a persistent ChromaDB, persisting it, shutting down the entire python …
> Fix bug with loading a saved index

- chromadb/db/index/hnswlib.py
- chromadb/test/test_api.py
A recent refactoring contained an error where certain index information was cached on a per-class basis, rather than a per-instance basis. 
This will result in inconsistent embedding IDs being returned when using multiple collections in the same process.
This change also ensures that our unit tests properly cover persistence(and demonstrate the bug fixed in #265.)
Added a new unit test demonstrating the failure, watched it fail, fixed the problem, watched it pass.
Bugfix, no doc change required.
> Fix bug with multiple collections

- chromadb/db/duckdb.py
An Exception was raised upon instanciating a `chromadb.db.duckdb.DuckDB` class, as the constructor tries to install the `json` extension. This installation step is superfluous, as the `json` extension is already loaded into the python client. Removing the attempted installation solves the issue.
For further details, see: https://github.com/duckdb/duckdb/issues/6931
- No `IOException` error when connecting to DuckDB
- None
Tested manually.
No changes in the documentation required.
> superfluous extension loading makes DuckDB raise IOException

- chromadb/__init__.py
- chromadb/db/index/hnswlib.py
Fixes #276 which was introduced by #271 
- Fixed a use of dict with subscript which breaks on older python versions
- None
Manually installed older python 3.8.16 and tested the break exists and then goes away
None required.
> dict -> Dict

- chromadb/db/clickhouse.py
- chromadb/test/test_api.py
A bug was introduced in #245. [Here](https://github.com/chroma-core/chroma/pull/245/files#diff-e9db4ed78af14ad050bb2ef1f4946b60f50f4eb3bf284c0b40745f683d49ac64L274) we changed from passing uuids into the index to ids, which leads to breakage. This is a bugfix that fixes the functionality by passing in uuids, along with a test. 
A new test was added that
- Adds a record
- Updates it
- Queries for it to check if it was valid
None required
> Fix update bug

- examples/where_filtering.ipynb
Added n_results parameter for query in `examples/where_filtering.ipynb` as mentioned in #315 
> updated n_results parameter in example query

- examples/local_persistence.ipynb
- Change the spelling of Srart to Start
Running the chroma/examples/local_persistence.ipynb notebook.
None
> Change the spelling of Srart to Start

- examples/deployments/google-cloud-compute/startup.sh
- Remove sudo usage
- Upgrade Google Cloud Example chroma version
> Remove sudo usage from Google Cloud deployment example

- chromadb/api/__init__.py
- chromadb/api/local.py
- chromadb/api/models/Collection.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/test/configurations.py
- chromadb/test/property/test_collections.py
- chromadb/utils/embedding_functions.py
- Fix collection name validation
- Don't reinitialize the default function every time a Collection model object is constructed (1000x perf improvement, thanks @HammadB !)
- When doing an "upsert" on a collection (`get_or_create`), update the metadata if it's different from the previous value.
These changes are to satisfy the new property-based tests for Collections, which now pass.
No user facing changes; documented behavior was not changed.
> Fixes for collections property tests

- chromadb/utils/embedding_functions.py
The [OpenAI documentation](https://platform.openai.com/docs/guides/rate-limits/error-mitigation) warns that "the response object may not return completions in the order of the prompts, so always remember to match responses back to prompts using the index field."
This PR sorts the returned embeddings by index so that they are guaranteed to be in order.
I apologize but I was in a hurry and haven't tested this yet, so hopefully a kind maintainer will run a test for me. I wanted to get the PR in because this could be a silent but deadly bug.
Bug fix, no user facing changes
> [bugfix] Ensure Openai batch embeddings are sorted by index

- chromadb/db/clickhouse.py
- chromadb/test/property/test_embeddings.py
Fixes bug where when updating multiple records at the same time, the user-facing IDs and internal UUIDs were mismapped leading towards invalid HNSW indices.
Hypothesis state machine
N/A
> Fix updates by ensuring correct ID ordering

- chromadb/test/property/test_collections.py
Hypothesis tests would occasionally fail when they stumbled on a scenario like the following:
```python
state = CollectionStateMachine(api)
state.initialize()
v1 = state.create_coll(coll={"name": "A11", "metadata": {"foo": "bar"}})
state.get_or_create_coll(coll={"name": "A11", "metadata": None})
state.teardown()
```
This PR allows the tests to pass by not making the assertion in the special case of `metadata=None`.
This cannot be fixed in code, because we have already designed passing `metadata=None` to mean "do not update the metadata." As such, there is no way to explicitly set the metadata to None without making user-facing API changes, and so the tests should not try to do so.
This fixes a failure in the existing tests.
N/A
> Fix occasional Hypothesis test failure when calling `get_or_create_collection`

- bin/setup_linux.sh
- bin/setup_mac.sh
the github personal access token in install_linux and install_mac.sh were expired. 
Removed them due to being able to clone publicly without permissions. 
Ran on a fresh ubuntu 22.04 server box and I get errors due to docker version differences(docker compose vs docker-compose), however the change itself runs correctly in the script. 
I don't have a mac so I can't test the full use case of these changes
> Removing pat due to public repo being clonable with no permissions

- clients/js/src/index.ts
Class OpenAIEmbeddingFunction() is initiated with an optional parameter - model (string). But inside the generate() function of the class, the optional parameter is forgotten to be used when making API Call to OpenAI. Instead of the parameter, a string literal "text-embedding-ada-002" is used.
- ...
- ...
> Fix OpenAIEmbeddingFunction in JS to use passed model name

- .gitignore
Simplified patterns.
1. **/.DS_Store includes the .DS_Store pattern.
2. **/__pycache__ includes the __pycache__ pattern.
3. index_data includes the /index_data pattern.
> Remove duplication from .gitignore

- chromadb/api/local.py
- chromadb/api/models/Collection.py
Improved docstrings for https://github.com/chroma-core/docs/pull/28
> much improved doc strings for client

- chromadb/test/property/invariants.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_embeddings.py
This PR further generalizes the ANN test to more than the 1st neighbor. We can now test for any number of neighbors. 
For now we use the embeddings in the EmbeddingSet as the query, but this could be generalized still further by adding (random) query vectors not in the collection / embedding set.
These are the tests 
N/A
> Generalized ANN Tests

- chromadb/test/property/strategies.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/property/test_persist.py
Adds a way for hnsw params to be increased during tests to values that will work with hypothesis more consistently. The only downside to this is we no longer test metadata: none or metadata:{} cases in the test_embeddings state machine or test_add. A stacked PR to come will add unit tests.
These are tests.
None required.
> Ann invariant increase hnsw params

- chromadb/db/index/hnswlib.py
- chromadb/test/property/invariants.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/property/test_embeddings.py
Add support for multiple distance metrics in tests.
1. We coin-flip and sometimes add a space when using hnsw_params
2. Added the distance functions to the invariant and use them when needed.
In the process of writing this test I discovered a bug with our implementation of update that was revealed by the inner product space. Since the inner product is not a true metric, a point may not be a neighbor to itself. Our update code was strictly appending to the index due to the a bug with how we manage string UUID vs UUID objects. In l2 and cosine spaces, this usually was fine in the eyes of tests since the results returned were correct with the updated data. But IP exacerbated the issue by making the results not always be the same point. 
These are tests!
None required!
> Add support for multiple spaces

- chromadb/api/models/Collection.py
- chromadb/db/index/hnswlib.py
- chromadb/test/property/invariants.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/property/test_filtering.py
- chromadb/test/property/test_persist.py
This PR adds embedding functions to the test suite. This allows us to test the by-document testing flow, throughout the test suite. 
It introduces a simple embedding function based on hashing, which ensures unique hashes per-document. This also allows us to test identical documents being added, and likewise identical embeddings. 
Along the way we discovered some numerical stability problems, which we address by an adaptive threshold in the ANN accuracy test. 
These are the tests.
> Test embedding functions

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/api/models/Collection.py
- chromadb/db/__init__.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/errors.py
- chromadb/server/fastapi/__init__.py
- clients/js/src/generated/api.ts
- clients/js/src/index.ts
- clients/js/test/client.test.ts
- clients/js/test/collection.client.test.ts
- Use Collection UUID everywhere we can instead of collection name
- Private methods only, does not affect user-facing APIs
- Prevents extra DB calls to look up the ID from the name (should improve perf)
- Forward-compatible with enterprise architecture refactor
- Fixes #138 
Tagged as a draft because this does change the REST API, so I will need to update the Node client in tandem. However, the Python code is ready for review and merge.
Unit and integration tests continue to pass without changes.
No user facing changes, no docs required.
> Use collection id instead of name

- chromadb/test/conftest.py
Our hypothesis timeout deadline seems to not be long enough for larger datasets on github actions, which is leading to flakiness. 
Existing tests.
None required
> Extend deadline for hypothesis

- chromadb/db/index/hnswlib.py
Addresses #337 by using multiprocessing.cpu_count() instead of 4 as the default. This cpu_count could over-report the true number of physical cores on processors supporting hyperthreading. However so does the underlying hnswlib std::hardware_concurrency that is used by default that we were overriding. Unfortunately, there isn't a good platform-independent, dependency-free, or reliable way to get a more accurate count (that I can find) so this is our best stdlib based approach for now.
Existing tests should capture this change as hnswlib is trivially parallel under the FFI.
None required.
> Increase hnswlib num_threads to match cpu_count

- .pre-commit-config.yaml
- chromadb/db/clickhouse.py
- chromadb/test/property/test_collections.py
Fix a error in the Hypothesis state machine that can cause a rare failure.
Also fixes types for `chromadb/test/property/test_collections.py`
The scenario this guards against is:
```python
state = CollectionStateMachine(api)
state.initialize()
c1 = strategies.Collection(
name="A00",
metadata=None,
dimension=2,
dtype=np.float16,
known_metadata_keys={},
known_document_keywords=[],
has_documents=False,
has_embeddings=True,
embedding_function=lambda x: [[0, 0]],
)
v1 = state.create_coll(coll=c1)
c2 = strategies.Collection(
name="A00",
metadata=None,
dimension=2,
dtype=np.float16,
known_metadata_keys={},
known_document_keywords=[],
has_documents=False,
has_embeddings=True,
embedding_function=lambda x: [[0, 0]],
)
v2 = state.get_or_create_coll(c2)
state.delete_coll(coll=v2) …
```
> Guard against missing collection in Collection hypothesis tests

- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/test/property/test_collections.py
- chromadb/test/test_api.py
Previously, it was possible to create two collections with the same name using `Collection.modify` to modify a collection to have the same name as an existing one.
Hypothesis tests updated to expect this case.
N/A
> Prevent duplicate collection names

- chromadb/server/fastapi/types.py
#524 Introduced a bug in the js client which depends on the default value of the empty dict {} for where and where document. It got merged because not all of our test matrix was marked as required. That is now fixed. Since that PR is supposed to just be type changes, we revert back to that default for now instead of fixing the upstream client.
Existing tests.
None
> Fix query bug

- chromadb/api/__init__.py
- chromadb/api/local.py
- chromadb/api/models/Collection.py
- chromadb/db/__init__.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
This PR adds a bunch of types and improved docstrings for the python docs 
https://github.com/chroma-core/docs/pull/28
there are some `#type: ignore`s used. in some cases its because we are going to remove the functionality soon anyway, in other cases the `Sequence` return types were not legible to me.
> Python docstings and types for docs

- chromadb/test/property/test_cross_version_persist.py
Change cross version tests to use standard import from path as opposed to importlib
In #541 we began to import settings as chromadb.config.Settings. This broke cross version tests after the release of v0.3.23. Due to the import changing for settings in LocalAPI's constructor, it highlighted an issue with how we import modules in cross version tests. Namely, nested modules are not imported unless explicit. When crossing the process boundary, we don't import this module and so it breaks when referred to. We now instead use standard python imports instead which works because of the path being overridden. This is also generally simpler and better. 
Existing tests.
I verified that a manually introduced bug (same as #386) breaks the tests.
I printed sys.modules and verified that all paths are …
> Change cross version tests to use standard import from path 

- pyproject.toml
The `overrides` library was added in #480, however, we missed adding it to `pyproject.toml`.
`requirements.txt` and `pyproject.toml` are required to match but we have no automated mechanism for ensuring that this is the case aside from the "release" CI job, which doesn't run on PRs, only on `main`.
As a separate task, we should configure CI for PRs to exercise this functionality so we don't run into this issue again.
None, there is currently no way to test the "release" job aside from letting it run in CI on main.
N/A
> Add new `overrides` lib to pyproject.toml

- clients/js/src/index.ts
- clients/js/src/types.ts
- clients/js/test/add.collections.test.ts
- clients/js/test/client.test.ts
- clients/js/test/collection.client.test.ts
- clients/js/test/collection.test.ts
- clients/js/test/delete.collection.test.ts
- clients/js/test/get.collection.test.ts
- clients/js/test/initClient.ts
- clients/js/test/peek.collection.test.ts
- clients/js/test/query.collection.test.ts
- clients/js/test/update.collection.test.ts
- clients/js/test/upsert.collections.test.ts
- clients/js/tsconfig.json
In this PR
- docstrings! 
- types!
- named params! 
This is a breaking change to the JS Client - it switches from positional to named arguments originally brought up by @transitive-bullshit in https://github.com/chroma-core/chroma/issues/254
Example: 
```
// before
const collection = await chroma.createCollection("test");
//after
const collection = await chroma.createCollection({ name: "test" });
```
This is especially nice when you are only using a few params. 
This PR does not bump the `npm` version number - we will cut a new release on Monday. 
We will need to land an update to our docs at that time as well. TBD
> switch to named params for JS client

- chromadb/utils/embedding_functions.py
This related to #547 issue.
- New functionality added:
- add optional organization_id parameter to OpenAIEmbeddingFunction.
- Create the class object without organization_id and no errors expected.
- Create the class object with organization_id.
- The class optional parameters are not mentioned explicitly.
> Add organization_id to openai embeddings

- chromadb/api/types.py
- chromadb/db/clickhouse.py
- chromadb/db/index/hnswlib.py
- chromadb/test/hnswlib/test_hnswlib.py
@jeffchuber observed in #360 that hnswlib does not correctly bookkeep deletes. This PR adds the bookkeeping so that the index tracks its element count correctly.
We adds a simple unit test that reaches into the object to check its state keeping.
None
> Add bookkeep on delete

- chromadb/api/local.py
- chromadb/db/clickhouse.py
- chromadb/db/index/hnswlib.py
- chromadb/errors.py
- chromadb/test/property/test_filtering.py
- chromadb/test/test_api.py
Return 0 results Instead of raising NoDatapointException on an empty filter result. This will be a breaking change for anyone depending on the existing error.
Addresses #435
Modified existing state machine test for this case, added a new test solely for this case.
We don't currently document the behavior so not required.
> Return 0 results Instead of raising NoDatapointException on an empty filter

- chromadb/api/types.py
- chromadb/test/test_api.py
Validate len(array) > 0 - address #437
They are not tested in a new way. These cases previously error'ed in the validation code since all validation for lists checks the datatype of the first element. Now we ensure the list has length > 0.
None required.
> Validate len(array) > 0 - address #437

- README.md
- docker-compose.server.example.yml
Update docker-compose.yml to fix the persistence volume issue and run the docker-compose up -d command without building a local image.
1. index_data mount fixed - It was mounted to the root of the server container, but it should be mounted to /chroma/.chroma/index location, that's where indexes are generated.
2. clickhouse mount fixed - Added mount location where actual database is stored.
[- (https://github.com/chroma-core/chroma/issues/527) ] 
1. docker compose up -d
2. create collection
3. add documents
4. query documents
5. docker compose down
6. docker compose up -d
7. query documents - Output will be httpError, data is lost when step 5 was performed
- Users can directly run the following command, …
> docker-compose data persistence fix and docker compose up without build

- clients/js/src/Collection.ts
- clients/js/test/client.test.ts
- clients/js/test/get.collection.test.ts
- clients/js/test/query.collection.test.ts
Switch from `snake_case` to `camelCase` for JS named inputs
> switch to camelcase inputs

- clients/js/package.json
Since our release process is manual - this does not need to land before release.
> bump JS to 1.5.0

- .github/workflows/chroma-client-integration-test.yml
- .github/workflows/chroma-integration-test.yml
- .github/workflows/chroma-release-python-client.yml
- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/api/models/Collection.py
- chromadb/config.py
- chromadb/test/test_api.py
- chromadb/utils/embedding_functions.py
- clients/python/README.md
- clients/python/build_python_thin_client.sh
- clients/python/integration-test.sh
- clients/python/is_thin_client.py
- clients/python/pyproject.toml
- docker-compose.test.yml
- Typing cleanup
- Changes embedding function defaults to work through the default params as opposed to via None so that None now means - NO embedding function as opposed to use the default. This is technically a breaking change. 
- Adds a thin client that restricts what you can create to the REST api client and builds it separately so it can be published to its own pypi package. The thin client restricts the default embedding function to be None always - forcing manual specification of the embedding function while using the thin client. 
- The thin client is built with its own pyproject.toml with a limited set of dependencies and a is_thin_client.py file that acts as a compile flag. The build script …
> Add a thin client

- clients/js/src/ChromaClient.ts
- clients/js/test/get.collection.test.ts
When fetching a collection that does not exist, the JS client would fail silently, returning a collection with `undefined` for all its attributes.
-  `ChromaClient.getCollection` will throw an error if there is an error in the API response
- closes: #634 
Passed tests with `$ yarn test`
None
> Catch and throw error in ChromaClient.getCollection

- clients/js/src/embeddings/WebAIEmbeddingFunction.ts
Added a new JavaScript embedding function to generate embeddings for text and images using the [Web AI](https://github.com/visheratin/web-ai) library. The users will now be able to generate the embeddings in both NodeJS and (IMO more importantly) in the browser. This, along with the existing JS library design, enables the decoupling of embeddings generation from storage (see example demo below).
I created a demo to check how the function works in web apps - https://web-ai-chroma.vercel.app/
The embeddings are generated on the client side and sent to the server to add to the collection or query for similar items.
Likely this change will require changes in the documentation.
> Web AI embedder for JS library

- chromadb/segment/__init__.py
- chromadb/segment/impl/metadata/sqlite.py
- chromadb/segment/impl/vector/local_hnsw.py
- chromadb/test/segment/test_metadata.py
- chromadb/test/segment/test_vector.py
- chromadb/types.py
Adds a `VectorReader` segment implementation using HNSWlib.
This PR's implementation only runs in memory. In this scenario, because the data is already persisted to the embedding queue, persisting the index itself is purely a performance improvement and can be implemented in a separate PR.
Unit tests included and will be exercised by property tests once the new architecture is extended to the `API` interface.
N/A
> Local in-memory HNSWlib segment implementation

- clients/js/src/embeddings/TransformersEmbeddingFunction.ts
- clients/js/src/index.ts
- Add support for [Transformers.js](https://github.com/xenova/transformers.js). This allows users to run Hugging Face transformers directly from their JS applications. For more information, see https://huggingface.co/docs/transformers.js.
I followed the [JS "Getting started" guide](https://docs.trychroma.com/getting-started?lang=js) to ensure it works as intended. Here's the script, and its output:
```js
const {ChromaClient, TransformersEmbeddingFunction} = require('chromadb');
const client = new ChromaClient();
// Create the embedder. In this case, I just use the defaults, but you can change the model,
// quantization, revision, or add a progress callback, if desired.
const embedder = new …
```
> Add embedding support for Transformers.js

- chromadb/api/local.py
- chromadb/test/test_api.py
- Return ns since epoch on /heartbeat, fixes #711 
- Updated the unit tests to check that the returned time is _near_ now and implicitly that it can be parsed as nanoseconds
- This makes the code match the [documentated returned vlaue](https://docs.trychroma.com/usage-guide#initiating-the-chroma-client)
> client.heartbeat() # returns a nanosecond heartbeat. Useful for making sure the client remains connected.
> Return ns since epoch on /heartbeat

- Dockerfile
I have seen this issue on WSL2, mac, and linux. Sometimes one of the dependencies for build-essential can't be retrieved and this flag should fix this problem. Add --fix-missing flags to address periodically failing hnswlib (build-essential is needed for hnswlib) installs during docker builds.
Add --fix-missing flags to address periodically failing hnswlib failures during docker builds
Build the docker image, should build successfully. Would be helpful to get the people who reported this issue to test out this fix since it can be difficult to replicate if you have never had build issues.
N/A
> #642 - Fix for hnswlib docker build issues

- clients/js/src/ChromaClient.ts
- clients/js/src/Collection.ts
- clients/js/src/types.ts
connect #725
Add a new `fetchOptions` parameter on the JS ChromaClient creation that allows you to pass in custom `fetch` options.
Example:
```
const chroma = new ChromaClient({
path: "http://localhost:8000",
fetchOptions: {
headers: {
'X-Api-Token': "sk-live-Hunt3r2", // Works like regular node-fetch headers!
}
}
});
```
The existing test suite was run and validated as passing. 
Typescript would allow the developer to know that these options are available. I do not think it currently requires updates to the Chroma Documentation - especially since this change is only impacting the JS client.
> Enable custom JS Client headers during request to Chroma Instance

- chromadb/utils/embedding_functions.py
Added support to the use of normalize embeddings in the `SentenceTransformerEmbeddingFunction` class by adding a new attribute to the class and use it when calling the `encode` function.
I was planning to add a new test case where an object was created with `normalize_embeddings=True` but I haven't found any test which is currently testing `SentenceTransformerEmbeddingFunction` (I guess that should be in the folder `test/utils`).
The document talking about [embeddings] should be changed. In the section *Sentence Transformers* it should be mentioned the possiblitiy of using an optional parameter `normalize_embeddings`. A similar text to the one in the SentenceTransformer documentation could be used (or adapted):
> If set to True, returned vectors will have length 1. In that case, the …
> Normalized embeddings

- .github/workflows/chroma-client-integration-test.yml
- .github/workflows/chroma-integration-test.yml
- .github/workflows/chroma-test.yml
- .pre-commit-config.yaml
- chromadb/api/local.py
- chromadb/api/models/Collection.py
- chromadb/api/segment.py
- chromadb/api/types.py
- chromadb/db/mixins/sysdb.py
- chromadb/segment/impl/metadata/sqlite.py
- chromadb/test/property/invariants.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_collections.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/property/test_filtering.py
- chromadb/test/property/test_persist.py
1. The new sqlite refactor cannot represent None and the empty dict in metadata. We make the choice here to change all of our code to validate against the empty dict for metadata. The metadata can now only be None or a non-empty dictionary. We add validation for this and modify the old and new clients to match the behavior. These changes affect both collection and embedding metadata.
2. The new API allows partial updates for existing ID's. If we add 1,2,3 and then add 1,2,3,4. 4 will still get added while 1,2,3 will silently fail. We modify the old API to match this behavior. 
3. The new API will merge metadata on upsert, the tests special case this for the new api as porting this to the old api is not worth the investment at this time. 
4. The …
> Fix empty metadata, partial updates. 

- clients/js/genapi.sh
- clients/js/package-lock.json
- clients/js/package.json
- clients/js/src/generated/runtime.ts
- clients/js/yarn.lock
Related issue #684 
- npm client is now cross compatible for Node versions <18. 
- I tested 4 versions: 18.16.0 PASS, 16.18.1 PASS, 14.21.3 PASS, 10.24.1 FAIL
The same tests in [root/client/js/test](https://github.com/chroma-core/chroma/tree/main/clients/js/test) must successfully pass under different Node versions for this to work (they did pass).
Perhaps add here https://docs.trychroma.com/api-reference the supported version range.
The core of this improvement is incredibly simple, it boils down to adding 
```ts
import 'isomorphic-fetch';
```
to [runtime.ts](https://github.com/chroma-core/chroma/blob/main/clients/js/src/generated/runtime.ts).
Due to the fact that `openapi-generator-plus` is being used I included some commands to the …
> cross compatible fetch with generation pipeline integration

- chromadb/api/segment.py
- clients/js/src/Collection.ts
The new segment based API was missing telemetry. This adds it in.
They are not tested explicitly. We should see the new api_impl fire events in posthog.
None required.
> Add missing telemetry from segment.py

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/segment.py
- chromadb/db/__init__.py
- chromadb/server/fastapi/__init__.py
- chromadb/telemetry/__init__.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/property/test_persist.py
- chromadb/test/test_api.py
- clients/js/src/ChromaClient.ts
- clients/js/src/Collection.ts
- clients/js/src/generated/api.ts
- clients/js/src/generated/models.ts
The SQLite storage persists on call, we do not need an explicit persist()
Existing persistence tests still validate that data is saved.
We will want to update documentation to remove references to persist()
> Remove persist() from API

- pyproject.toml
- requirements.txt
[dont hard pin to ](https://github.com/chroma-core/chroma/issues/774) jump to pydantic v2
we dont want to go there yet so we pinned to 1.9, but langchian uses 1.10. this PR adds a valid range from 1.9 to < 2.0
> add verison range for pydantic

- chromadb/config.py
Add an error message when thin client is used incorrectly that was incorrectly removed in #662
> Add back thin client error from bad merge

- chromadb/db/impl/sqlite_pool.py
Ensures that the `uri=is_uri` is passed to `sqlite3.connect` so that SQLite will have [URI filenames enabled](https://www.sqlite.org/uri.html) and correctly create an in-memory database instead of a file named `file::memory:?cache=shared `
- closes: #822 
Existing tests are passing
```python
client = chromadb.Client()
```
does not create a file
> Enable SQLite URI filename capability

- bin/docker_entrypoint.sh
- bin/templates/docker-compose.yml
- chromadb/segment/impl/vector/local_persistent_hnsw.py
- clients/python/README.md
- docker-compose.test.yml
- docker-compose.yml
- examples/basic_functionality/alternative_embeddings.ipynb
- examples/basic_functionality/local_persistence.ipynb
- examples/basic_functionality/where_filtering.ipynb
Updates various docs and examples to be relevant for the sqlite refactor, adds a small QoL fix to prevent a confusing log.
1. Update docker-entrypoint.sh to point to chroma-hnswlib
2. Update docker-compose in bin/templates to not use clickhouse
3. Update local_persistent_hnsw to not overquery underlying index past its size as it will result in a confusing double log. This doesn't modify the logic as the underlying index was re-performing this logic before. But it led to a confusing log where we repeatedly told you we were changing your query
4. Update the thin client readme to use HttpClient
5. Make the dockerfile and compose files use IS_PERSISTENT=TRUE since its false by default and the default client/server path should be persistent.
6. Update all notebooks that used the old client by …
> Add docs, and minor logging fix

- chromadb/server/fastapi/__init__.py
- chromadb/test/test_api.py
- pyproject.toml
- requirements.txt
bump to a higher range of fastapi 
- more up to date is better
- conflict with https://github.com/hwchase17/langchain/pull/7749, specific failing tests https://github.com/hwchase17/langchain/actions/runs/5560775388/jobs/10157995239?pr=7749
> bump fastAPI to accomodate langchain version mismatch

- chromadb/migrations/metadb/00001-embedding-metadata.sqlite.sql
Because of inconsistent bundling, not all python versions on all platforms ship with a SQLite which has the trigrams tokenizer, and the same python version may have different SQLites on different platforms. 
This creates problems for users of Chroma `0.4.0` which uses the trigram tokenizer. This change reverts to using the default tokenizer of whatever SQLite is available on the system. The tradeoff is reduced full-text search performance, but this simplifies installation and maintenance. 
This should address:
https://github.com/chroma-core/chroma/issues/837
https://github.com/chroma-core/chroma/issues/836
The test suite should pass. 
Tested in colab via pypi test.
```python
!pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple …
```
> Revert trigram tokenizer

- chromadb/config.py
Update error message to be more verbose in the case of users who do not want to migrate any data and are just following an old guide.
Manually verified the error
None required.
> Update error message to be more verbose

- chromadb/__init__.py
Because the Colab python environment uses a very old version of SQLite, Chroma would break for users in Colab notebooks. This workaround hotswaps the system `sqlite3` module with the binary `pysqlite3-binary` module when Chroma is imported, bypassing the issue. 
We didn't catch this when addressing other issues with SQLite because we didn't try to `collection.add`. 
This addresses:
https://github.com/chroma-core/chroma/issues/850
- Tests pass
- Tested locally by bumping the required version to `(3, 70, 0)`
- Tested with a pytest version in colab using:
```python
!python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple chromadb==0.4.2.dev2
client = chromadb.Client()
collection = client.get_or_create_collection("test") …
```
> Colab SQLite Workaround

- chromadb/api/segment.py
- chromadb/test/property/test_cross_version_persist.py
After #808, we need to reenable cross version tests pegged to a min version of 0.4.1. Additionally, this handles a corner case with metadata getting cleaned incorrectly when containing chroma: prefixed strings if the metadata is empty when retrieved.
These are tests!
None required.
> Reenable cross version tests

- clients/js/DEVELOP.md
- clients/js/package.json
- bump to 1.5.5 (already released)
- fix release instructions
> bump version and release instructions

- .dockerignore
Ignore .conda from docker build ,which is huge for local development (500M+)
- imporve the local docker build speed
- N/A
- build with local machine
N/A
> Ignore .conda in .dockerignore

- .github/workflows/chroma-test.yml
- chromadb/segment/impl/manager/local.py
- chromadb/segment/impl/vector/local_persistent_hnsw.py
- chromadb/test/stress/test_high_collections.py
- chromadb/test/stress/test_many_collections.py
- chromadb/utils/lru_cache.py
- pyproject.toml
- requirements.txt
- Adds an LRU cache for segment file handle management to make sure we respect OS file handle limits
- ...
Added a stress test which creates many collections and forces them to open index files by writing to them
We should add a troubleshooting section about filesystem limits so that users can set max limits more appropriately - similar to https://www.mongodb.com/docs/manual/reference/ulimit/
> Add LRU cache FD management

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/segment.py
- chromadb/db/__init__.py
- chromadb/server/fastapi/__init__.py
- chromadb/server/fastapi/types.py
- clients/python/pyproject.toml
- pyproject.toml
- requirements.txt
This is technically a breaking change since we remove the endpoint for `raw_sql`. `raw_sql` was an undocumented internal tool so we should discuss how we want to handle this.
> remove raw_sql and pandas

- chromadb/utils/embedding_functions.py
- Update the API endpoint for Google VertexEmbedding
- ...
At the moment, there is any unit test for embedding function. However I have tested the new code change locally and it worked.
1. The default model_name should be textembedding-gecko instead of textembedding-gecko-001
2. The _api_url should be changed to
3. The json payload should take in only 1 string instead of array of strings. Thus I made a for loop to call the api endpoint in the event there are arrays of text documents passed into the _call() …
> fix: update api request

- chromadb/segment/impl/manager/local.py
- chromadb/segment/impl/vector/local_persistent_hnsw.py
Close #913.
- Previously we were not reset'ing() in vector segments which persist data to disk. Leading to orphaned files since the sqlite db was reset. This cleans up the index files. 
- ...
Manually verified that after reset()'ing, vector index files are cleared.
None required.
> #913 Persistent vector segments to be cleaned up on reset()

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/models/Collection.py
- chromadb/api/segment.py
- chromadb/db/__init__.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/test_api.py
This PR is another breaking change - though we don't expect to affect any users. This removes the `create_index` function from the API, which we no longer use.
> remove create_index which we dont use

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/models/Collection.py
- chromadb/api/segment.py
- chromadb/db/__init__.py
- chromadb/server/fastapi/__init__.py
- chromadb/server/fastapi/types.py
- chromadb/test/test_api.py
Removes increment index which is no longer in use.
Technically a breaking change, but I dont think anyone is using it since it is technically a no-op.
> remove increment index

- chromadb/server/fastapi/types.py
- chromadb/test/property/test_add.py
- Allow fast api to consume none for add/update
- ...
Manually tested by passing none to the API. Added a unit test. 
None required.
> Allow fast api to consume none for add/update types

- chromadb/server/fastapi/__init__.py
https://github.com/chroma-core/chroma/issues/895
Serve registered API routes regardless of whether they end in "/".
In the linked bug @HammadB and I discussed looping over all the routes at the end of `__init__`, but the typechecker complains: the only thing we know about `self._app.routes` is that they're instances of `BaseRoute`, which may not have the fields we need. Rather than do type coercion I subclassed `fastapi.APIRouter`.
The logic to set `kwargs["include_in_schema"]` is maybe too clever, should we just do an if-else instead?
```
0 ~ beggers % curl http://localhost:8000/api/v1/collections/ -v
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET /api/v1/collections/ HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/8.1.2
> Accept: */*
> 
< …
```
> Serve resources from API routes ending in /

- clients/js/package.json
- clients/js/src/ChromaClient.ts
- clients/js/src/generated/api.ts
- clients/js/src/generated/models.ts
This cleans up the JS API
- remove `increment_index`
- removes `createIndex`
- removes `rawSql`
It also bumps the version to 1.5.6 (not yet released) and fixes a type that changed.
> clean up JS API, remove increment_index, createIndex and rawSql

- examples/deployments/google-cloud-compute/README.md
- examples/deployments/google-cloud-compute/chroma.tf
- examples/deployments/google-cloud-compute/startup.sh
- examples/deployments/google-cloud-compute/variables.tf
- The project will now clone the chroma repo and deploy docker-compose from it
- Introduced a new TF var chroma_release to be able to deploy a any (oh well almost any, chroma version, defaults to 0.4.5)
- Added output instance_public_ip var to print out the IP address of the VM
Refs: #950
- Made it possible to deploy any version of chroma through TF var chroma_release (defaults to 0.4.5)
- Made it so that the VM would clone the repo and checkout the release tag then run docker compose from it
- Added output of the public IP of the VM after TF deployment
- Improved slightly the README.md
```bash
gcloud auth application-default login
cd examples/deployments/google-cloud-compute
terraform init …
```
> feat: Improved GCP deployment instructions

- chromadb/__init__.py
Closes Issue: #923 
Adds the following types available as a top-level import in addition to the `Collection` class:
- `CollectionMetadata`,
- `Documents`,
- `EmbeddingFunction`,
- `Embeddings`,
- `IDs`,
- `Include`,
- `Metadata`,
- `Where`,
- `QueryResult`,
- `GetResult`,
- `WhereDocument`,
- `UpdateCollectionMetadata`,
- No additional tests were added
- It might make sense to make clear these cans can be used from the top level.
> ENH: Chroma types available as top-level imports 

- chromadb/segment/impl/metadata/sqlite.py
Previously we were not using the FTS search index correctly. https://sqlite.org/fts5.html#full_text_query_syntax Expects that you query using the table name of the FTS table, not  using the column name. If you want to query by column name, you have to use column filters as discussed in the link above. We opt to take the path suggested here https://sqlite.org/forum/forumpost/1d45a7f6e17a3460 and match on id in addition to filtering that specific column. The query planner leverages this appropriately as confirmed in EXPLAIN. 
Since we were doing speculative delete queries, assuming the index was leveraged, this was incredibly slow. However now it is much faster.
Explain Before
```-- SCAN VIRTUAL TABLE INDEX 0:``` -> Full table scan.
Explain After 
``` -- SCAN VIRTUAL TABLE INDEX 0:M2 ``` -> …
> [PERF] Make the index correctly use FTS

- chromadb/api/types.py
- Improves the performance of the duplicate ID validator. I noticed this while trying to add > 100k records to a collection. I had duplicates in my ID array (which I didn't know at the time), and I eventually terminated the operation because it was taking so long. I happened to notice in the traceback that it was stuck in the `validate_ids` function, which looks like it might be O(N^2).
- This PR currently changes just the implementation. That said, it would be easy to display only the e.g. top 10 most common dupes (so as to avoid printing over 1k IDs to console output, as happened in my case :upside_down_face: ). Let me know if you would prefer that.
1. I tested the implementation within a …
> [PERF] Improve performance of duplicate ID validator

- chromadb/utils/embedding_functions.py
The current function is looking for the tar.gz file instead of checking if the folder already exists, so if the tar.gz gets deleted after extraction, it downloads it again..  This PR resolves this and checks for the model in the extracted folder before attempting to download or extract again.
By using it
I didn't find any documentation about how this does the download.
> Fix model download for ONNX embedder

- clients/js/package.json
Currently not all bundlers will chose the correct CJS/ESM build when importing the js client because we don't define them using [conditional-exports](https://nodejs.org/api/packages.html#conditional-exports). This change adds the required configuration in the package.json to fix that.
- support conditional exports in js client
I have tested this manually. We have a Next.js setup which throws an error with v1.5.6, we make use of that to detect which build (cjs/esm) nextjs tries to load. In both cases we expect an error with the path from which nextjs loads the module.
- checkout https://github.com/jeffchuber/nextjs-chroma/commit/2df1a216866b383f4205eb319a37c5c7d88ad02c
- run yarn && yarn dev
- open http://localhost:3000/
- you should see the following error in …
> feat: support conditional exports in js client

- chromadb/db/mixins/embeddings_queue.py
- chromadb/ingest/__init__.py
- chromadb/test/ingest/test_producer_consumer.py
- In v0.4.6 we introduced batching at the sqlite layer for the embeddings_queue to maximize throughput through submit_embeddings calls. SQlite has a max size of variables it can bind at once that is defined at compile time. This changes makes the embeddings_queue introspect its compile time flags to inform its max_batch_size. Max_batch_size is a new property method added to the Producer class that indicates the maximum batch size submit_embeddings() will accept. Right now we use the error internal to submit_embeddings in the sqlite impl, but callers could use this to pre-validate input and throw a message as well. 
- None
Added a test for the below and above batch size cases.
We should update the usage …
> [ENH] Max batch size warning

- chromadb/api/models/Collection.py
- chromadb/api/segment.py
- chromadb/db/mixins/embeddings_queue.py
- chromadb/segment/impl/vector/local_persistent_hnsw.py
- chromadb/test/conftest.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/segment/test_vector.py
- chromadb/test/test_api.py
Addresses #948, #583, #970
- Prevent unrestricted deletes and instead point users to more explicit alternatives. 
- Make embeddings_queue properly log the exception in mock_async mode
- In tests, reraise from embeddings_queue
- Fix a related bug where delete() on an empty segment throws a misleading error by checking if index in segment is initialized (#970)
- None
Added unit tests validating that error cases are properly error'ing. Existing tests should make sure delete still works.
None required.
> [ENH] Prevent unrestricted delete

- chromadb/auth/registry.py
- chromadb/config.py
- docs/CIP_2_Auth_Providers_Proposal.md
- Updated logger level to avoid confusion
- Changed logger level message when registering new Auth providers to debug to avoid confusing developers.
- Change the status of the CIP to `Accepted`
- Added `/docs` and `/openapi.json` to the publicly accessible endpoints (this may or many not be a security concern - TBD)
Local tests are passing—no new tests.
N/A
> [BUG]: CIP-2 Auth Providers - Clean-up

- chromadb/config.py
Note: Cross-version testing was failing as it was loading config twice which caused the issue with pydantic.
- Fixing `chromadb/test/property/test_cross_version_persist.py` test failures.
No docs need updating
> [BUG]: Added allow_reuse=True to pydantic validators

- clients/python/pyproject.toml
- #799 introduced a max version for pydantic but this change was not propagated to the thin client. This makes the same change in the thin client.
- ...
Existing tests for client
None
> [BUG] Add dep fix for pydantic in thin client

- .github/workflows/chroma-release.yml
Currently our ghrc (and future dockerhub) builds will not run on Mac. 
This should build `linux/amd64` and `linux/arm64` in serial. 
In the future, we can add ` linux/amd64/v2, linux/amd64/v3` and parallelize the builds. 
https://docs.docker.com/build/ci/github-actions/multi-platform/
Plan
1. let tests pass
2. merge into `main` and see if `latest` release branch works
> multiplatform docker release builds

- clients/js/package.json
- clients/js/src/embeddings/TransformersEmbeddingFunction.ts
- clients/js/src/embeddings/WebAIEmbeddingFunction.ts
- clients/js/src/utils.ts
- clients/js/yarn.lock
resolves #953
-  Bug fixes
- implement a workaround in clients/js/src/embeddings/WebAIEmbeddingFunction.ts to resolve #953
At present, we lack a testing setup specifically tailored for a browser environment. Implementing this would be a necessary step to implement tests for changes in this branch.
I've tested it locally using this change: https://github.com/jeffchuber/nextjs-chroma/pull/1/files
- http://localhost:3000/api/hello (node version) works fine
- http://localhost:3000 (browser version) works fine
> fix: use workaround for dynamic import

- chromadb/auth/token/__init__.py
- chromadb/test/auth/test_token_auth.py
Refs: #1066
- Small bugfix to extend the range of allowed characters to include printable ascii without whitespaces
Docs updated - https://github.com/chroma-core/docs/pull/128
> [BUG]: Fixed Static Auth Token range of allowed chars

- chromadb/segment/__init__.py
- chromadb/segment/impl/manager/local.py
- chromadb/segment/impl/metadata/sqlite.py
- chromadb/segment/impl/vector/local_hnsw.py
- chromadb/segment/impl/vector/local_persistent_hnsw.py
- chromadb/test/segment/test_vector.py
Note:  Cherry-picked from original PR #1010
Refs: 1009
- Fixed an issue where the collection's persistent segment dir was not removed; thus, many dirs with segment data were left on the device.
N/A
> [BUG]: Local Segment Dir Removal

- chromadb/api/types.py
- chromadb/segment/impl/metadata/sqlite.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_filtering.py
- chromadb/types.py
- clients/js/test/client.test.ts
- docs/CIP_4_In_Nin_Metadata_Filters.md
- examples/basic_functionality/in_not_in_filtering.ipynb
Cherry-picked from #1029
- Added support for `$in` and `$nin` metadata filters
> Note: See CIP in `docs/` or example notebook for more info
TBD
> [ENH]: CIP-4: In and Not In Metadata Filters

- .gitignore
- docker-compose.server.example.yml
- docker-compose.yml
Fixes #1035
- Default persistent directory isn't `/index_data` it's located at `/chroma/chroma/` [config.py#L85](https://github.com/chroma-core/chroma/blob/main/chromadb/config.py#L85) fixing it in serveur core docker-compose
- Removing misleading volume `/index_data` in main docker-compose.yaml file, that clearly induce in error users
- Adding comment in main docker-compose.yaml file so that Chroma users won't waste time seeking for this directory path
Does it introduce a breaking change ?
- With this change data will now be persistent for users using `docker-compose.server.example.yml` as it's a exemple file this shouldn't be considered as a breaking change.
*Are all …
> [BUG] docker-compose default persistent directory path updated

- examples/deployments/aws-terraform/README.md
- examples/deployments/aws-terraform/chroma.tf
- examples/deployments/aws-terraform/startup.sh
- examples/deployments/aws-terraform/variables.tf
Refactored and Rebased version of #1059
This template includes the following:
- Create a security group with required ports open (22 and 8000)
- Create EC2 instance with Ubuntu 22 and deploy Chroma using docker compose
- Create a data volume (ESB) for Chroma data
- Mount the data volume to the EC2 instance
- Format the data volume with ext4
- Start Chroma
- Enable (by default) Token Auth with randomly generated token
- Terraform tests performed
The template contains README with a tutorial on how to use it.
> [ENH]: AWS Deployment

- chromadb/api/fastapi.py
- chromadb/config.py
- chromadb/test/property/test_client_url.py
Refs: #1019
The HTTP Client now supports a variety of URIs:
- URLs: `http://example.com/`
- Hostnames: `localhost` or chroma (existing)
- Domains `example.com`
- Paths in URLs/Domains - `http://example.com/my_path`
TBD - perhaps some clarifications on the HttpClient
> [ENH]: Improved HttpClient URL support

- chromadb/api/fastapi.py
- chromadb/test/property/test_client_url.py
- Added additional validations to URLs - URLs like api-gw.aws.com/dev will now trigger an error asking the user to correctly specify the URL with http or https
- When the full URL (http(s)://example.com) is provided by the user, the port parameter is ignored (debug message is logged). An assumption is made that the URL is entirely defined, thus not requiring additional alterations such as injecting the port.
- Added negative test cases for invalid URLs
TBD
> [BUG]: URL Parsing And Validation

- pyproject.toml
- requirements.txt
- Bump HNSWlib to latest version that has precompiled binaries. Use alpha release for CI tests before releasing
Existing tests should over functionality. Build compatibility of the binaries was manually verified.
We should add how to force recompiling with AVX to the docs.
> [CHORE] Bump HNSWlib to latest version that has precompiled binaries

- clients/js/package.json
https://semver.npmjs.com/
npm strictly checks peer dep ranges, which means the `npm install` of anything with a peer dep on Chroma was affected by this.
> Fix broken peer OpenAI dep dependency range

- clients/js/package.json
Bump to release to 1.5.9 to release https://github.com/chroma-core/chroma/pull/1142
> bump JS to 1.5.9

- chromadb/segment/impl/vector/local_persistent_hnsw.py
Refs: #989
- When the BF index overflows (batch_size upon insertion of large batch it is cleared, if a subsequent delete request comes to delete Ids which were in the cleared BF index a warning is raised for non-existent embedding. The issue was resolved by separately checking if BF the record exists in the BF index and conditionally execute the BF removal
N/A
> [BUG]: Fixed BF index overflow issue with subsequent delete

- clients/js/package.json
- clients/js/test/add.collections.test.ts
Refs: #1104
- Expanding Cohere version also to support 6.x This plays nice with the rest of the ecosystem
N/A
> [BUG]: Added cohere version 6.x support in peer dependencies

- bin/docker_entrypoint.sh
- Initial CLI PR (https://github.com/chroma-core/chroma/pull/1032) moved the logging config inside chromadb. If image is built with the current setup it will result in Error: Invalid value for '--log-config': Path 'log_config.yml' does not exist.
Steps to reproduce (prior to this PR):
- `docker build -t chroma:canary .`
- `docker run --rm -it chroma:canary`
> [BUG]: Docker entrypoint logging path

- chromadb/__init__.py
Releasing a hotfix for #1159 which addresses #1164 which breaks the docker image
> [RELEASE] 0.4.12 to fix Dockerfile log issue

- clients/js/src/index.ts
The `IncludeEnum` enum is not exported, cause lint errors when using `.get` or `.query`, as follows:
```js
const result = await collection.query({
queryTexts: [query],
// THIS LINE WILL PRODUCE LINT ERROR as it needs IncludeEnum.Distances etc.
include: ['distances', 'documents', 'metadatas'],
nResults: 2,
})
```
Nil
Nil
> export IncludeEnum as it is required by #get and #query

- examples/deployments/aws-terraform/README.md
- examples/deployments/aws-terraform/chroma.tf
- examples/deployments/aws-terraform/variables.tf
`lifecycle` blocks don't allow variables. Right now our example deployment for AWS doesn't work. @tazarov has a fix for this and a few other things in https://github.com/chroma-core/chroma/pull/1173 but I'd like to get the basic fix out before the weekend.
local `terraform init` failed before, now works.
> Fix failing example terraform

- chromadb/__init__.py
- chromadb/api/segment.py
- chromadb/telemetry/__init__.py
- chromadb/telemetry/events.py
- chromadb/telemetry/posthog.py
- chromadb/utils/embedding_functions.py
This PR accomplishes two things:
- Adds batching to metrics to decrease load to Posthog
- Adds more metric instrumentation
Each `TelemetryEvent` type now has a `batch_size` member defining how many of that Event to include in a batch. `TelemetryEvent`s with `batch_size > 1` must also define `can_batch()` and `batch()` methods to do the actual batching -- our posthog client can't do this itself since different `TelemetryEvent`s use different count fields. The Posthog client combines events until they hit their `batch_size` then fires them off as one event.
NB: this means we can drop up to `batch_size` events -- since we only batch `add()` calls right now this seems fine, though we may want to address it in the future.
As for the additional telemetry, I pretty much copied Anton's draft …
> [ENH] Metric batching and more metrics

- chromadb/api/models/Collection.py
- chromadb/auth/providers.py
- chromadb/config.py
- chromadb/test/property/test_cross_version_persist.py
- pyproject.toml
- requirements.txt
Closes #893 
- Adds support for pydantic v2.0 by changing how Collection model inits - this simple change fixes pydantic v2
- Fixes the cross version tests to handle pydantic specifically
- Conditionally imports pydantic-settings based on what is available. In v2 BaseSettings was moved to a new package. 
- N/A
Existing tests were run with the following configs
1. Fastapi < 0.100, Pydantic >= 2.0 - Unsupported as the fastapi dependencies will not allow it. They likely should, as pydantic.v1 imports would support this, but this is a downstream issue.
2. Fastapi >= 0.100, Pydantic >= 2.0, Supported via normal imports  ✅  (Tested with fastapi==0.103.1, pydantic==2.3.0)
3. Fastapi < 0.100 Pydantic < 2.0, …
> [CHORE] Add support for pydantic v2

- requirements.txt
Our pyproject.toml is less restrictive than requirements.txt, which makes the published package support 3.11, but not in local dev. 
- Updates requirements.txt to resolve for 3.11
- None
Pyenv was updated to 3.11.4 and tested locally. 
We can update docs to remove any verbiage restricting 3.11.
> [BUG] Update requirements for 3.11 support

- clients/js/src/index.ts
- examples/deployments/aws-terraform/README.md
- examples/deployments/aws-terraform/chroma.tf
- examples/deployments/aws-terraform/variables.tf
Refs: #1172 and #1135
- Added support for restoring from snapshot
- Added snapshotting volume before destroy
- Bumped default Chroma version to 0.4.12
- Added support for persistent volume mounts (in fstab)
- Improved tagging
- Made source ranges for the Security Group configurable
- Made external Chroma port configurable
- Switched to use a GH startup script.
Tests not yet executed.
Updated README.md of the blueprint
> [ENH]: AWS Terraform Blueprint Improvements

- examples/chat_with_your_documents/load_data.py
In https://github.com/chroma-core/chroma/issues/1115 @BChip noticed flaky retrieval performance. 
The issue was difficult to replicate because of nondeterminism inherent in the HNSW graph construction on loading, but I was able to track it down through repeated testing. 
The issue is caused by ingesting all the empty lines in the document, which make up 50% of all the lines in each file, which outputs the same embedding for all of them, causing the HNSW graph to sometimes be degenerate. 
The fix is to skip the empty lines. We should consider how we can mitigate this in the future since this is not easy to detect after the fact, and is likely to be something users run into. 
Failures no longer occur after manual invocation. 
N/A
> [BUG]: Chat with your documents example exhibits flaky retrieval

- chromadb/__init__.py
Refs: #1206
- Conditional import of sqlite for python client
Additional test in older disto (debian buster) was run:
```
pip install chromadb-client
root@c26a0fadfcdc:~# python
Python 3.10.12 (main, Jun 13 2023, 12:02:28) [GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>> print(sqlite3.sqlite_version_info)
(3, 27, 2)
>>> import chromadb
>>>
```
N/A
> [BUG]: Python client sqlite issue

- requirements.txt
#1235 
- TQDM version pinning was causing issues with other deps that required a higher version.
Local pip install tests.
N/A
> [BUG]: Unpinned tqdm version in requirements.txt

- docs/CIP_6_OpenTelemetry_Monitoring.md
- A CIP proposing adding OpenTelemetry observability to Chroma.
> Observability  cip

- .gitignore
- chromadb/api/segment.py
- chromadb/telemetry/events.py
- chromadb/telemetry/posthog.py
- Increase add() batch size.
- Flatten server context so we can do things like group by version.
- Add a few things to `.gitignore` which seem to be created by test runs.
- Batch query() calls (batch size = 20, where we started for add()).
- Change `collection.get()` so its fields are `int` instead of `bool` since I imagine we'll eventually batch it as well.
```python
>>> import chromadb
>>> chroma_client = chromadb.Client()
bf9b885c-b86e-4194-97b4-d9701d293cce ClientStartEvent {'batch_size': 1, 'chroma_version': '0.4.14', 'server_context': 'None', 'chroma_api_impl': 'chromadb.api.segment.SegmentAPI', 'is_persistent': False, 'chroma_server_ssl_enabled': False}
>>> …
```
> Further posthog improvements (and a little .gitignore)

- chromadb/api/segment.py
- chromadb/config.py
- chromadb/db/impl/grpc/client.py
- chromadb/db/mixins/sysdb.py
- chromadb/db/system.py
- chromadb/ingest/__init__.py
- chromadb/ingest/impl/simple_policy.py
- chromadb/test/db/test_system.py
- Adds a CollectionAssignmentPolicy and moves topic creation down into SysDB
- Changes SysDB to not accept a Collection Object in create_collection() but params instead 
- None
TODO: 
Existing tests were modified with the refactor and ensured to pass.
None required
> [STACKED #1229] [ENH] Add a CollectionAssignmentPolicy and move topic creation into SysDB using the policy

- chromadb/telemetry/opentelemetry/__init__.py
- 
- When (for some reason) the tracer is not defined, we seem to be returning None, added original function return for completeness
- Added _transform_attributes method as this seemed to be throwing an exception
Manual testing with Zipkin/Jaeger 
N/A
> [BUG]: Added return of the original function result when tracer not defined

- chromadb/config.py
- Fixes an issue where the empty string was not being handled by pydantic validation. Here we treat the empty string as None.
- ...
None
> [BUG] validate nofile limit in case of empty string

- chromadb/__init__.py
Refs: #1302
- Removed defaulting of headers for HttpClient as this causes differences in settings when clients are initialized from HttpClient and Client with the same settings which raises an error
N/A
> [BUG]: Removed defaulting HttpClient headers to empty dict

- chromadb/test/ef/test_multimodal_ef.py
Because the multimodal embedding function test generates random images and documents, it's possible for it to randomly get into a degenerate state with respect to the index. 
To avoid this, we fix the seed.  
This is the test. 
None
> [ENH] Fix random seed in multimodal EF test 

- chromadb/db/mixins/sysdb.py
- chromadb/test/client/test_database_tenant.py
- Fixes a bug with multitenancy where name= filtering path is always being called. If ID is given, we don't need any filtering.
- ...
I added tests to verify collections can be added to across database and tenants
None required
> [BUG] Fix multitenancy

- chromadb/config.py
- chromadb/db/migrations.py
- chromadb/test/db/test_hash.py
- Support FIPS-compliance by allowing SHA256 hashing algorithm for database migrations (instead of MD5)
- New configuration setting to allow changing the migration hashing algorithm to SHA256 (defaults to MD5)
I've tested creating a new client with settings and ensured they're passed through. I also tested that the right hashlib alg actually gets called. These are the scenarios:
- without specifying the hashing algorithm (should default to MD5)
- with "md5" (should end up with MD5)
- with "sha256" (should use sha256)
- and an invalid hashing algorithm (should raise an exception)
*Are all docstrings for user-facing APIs updated if required? Do we need to make …
> ENH: add new setting for configuring the db migration hashing algorithm (add sha256)

- chromadb/utils/embedding_functions.py
- Allows users to pass custom headers to OpenAI API, enabling intermediary proxies with different authentication methods.
- New optional `default_headers` input at the `OpenAIEmbeddingFunction` class.
Since this is a relatively specific feature, I believe it won't require an usage example in the docs.
> ENH: Allow default headers to be passed to OpenAI API

- chromadb/api/segment.py
- chromadb/proto/chroma_pb2.py
- chromadb/proto/chroma_pb2.pyi
- chromadb/proto/convert.py
- chromadb/test/ingest/test_producer_consumer.py
- chromadb/test/segment/test_metadata.py
- chromadb/test/segment/test_vector.py
- chromadb/types.py
- idl/chromadb/proto/chroma.proto
In the distributed architecture, collections are multiplexed onto topics, so messages from the ingest need to be tagged with their collection_id so consumers know which collection it belongs to. In the single node collections are 1:1 with topics so this mapping is not strictly needed since the topic implicitly tells consumers which collection they are reading. This PR adds the collection id to the type that gets written on the log. It also adds an optional collection_id to the type consumed from the log. This must be optional for backwards compatibility on single node chroma. A backfill would have no data to populate that field, and rather than populate it with a bad placeholder, I think its better to be specific that it …
> [ENH] Update SubmitEmbeddingRecord to take collection_id. Update EmbeddingRecord to take collection_id

- chromadb/config.py
- Fixes https://github.com/chroma-core/chroma/issues/1404
This is one contiguous terminal session, broken into parts so shell and python syntax highlighting both look nice:
```sh
(.venv) 0 beggers % git checkout main
M	chromadb/cli/cli.py
Already on 'main'
Your branch is up to date with 'origin/main'.
(.venv) 0 beggers % export CHROMA_SERVER_NOFILE=9223372036854775808                                                      ~/chroma/chroma
(.venv) 0 beggers % python
```
```python
Python 3.11.6 (main, Oct  2 2023, 20:46:14) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import chromadb
>>> c = chromadb.Client()
Traceback …
```
> [CLN] Warn when chroma_server_nofile is higher than sys hard limit

- chromadb/errors.py
- chromadb/server/fastapi/__init__.py
This change adds FastAPI server-side verification that clients are using HTTP 1.1 or 2, and adds an appropriate `ChromaError` called `InvalidHTTPVersion` if they're not. 
The `requests` library used by the Chroma python client uses 1.1 by default so no changes are needed. 
Tested manually by setting 
https://github.com/chroma-core/chroma/blob/2e6602072a3191407a2aff189e398ba73ba952fc/chromadb/server/fastapi/__init__.py#L95
to instead be
```python
http_version not in ["1"]
```
And observed that attempting to connect raises the appropriate exception, propagated from the server:
```
Traceback (most recent call last):
File "/Users/antontroynikov/Projects/chroma/chromadb/api/client.py", line 427, in _validate_tenant_database
self._admin_client.get_tenant(name=tenant)
File …
```
> [ENH] Verify clients use HTTP 1.1 + 

- .github/workflows/chroma-release-python-client.yml
- clients/python/pyproject.toml
- clients/python/requirements.txt
- clients/python/requirements_dev.txt
- Python client now has correct dependencies.
Prior to this change (in a virtualenv with only `chromadb-client` installed):
```python
client = chromadb.HttpClient()
client.create_collection('test1231231232321')
File ~/experiments/chroma-experiments/client-embedding-f-issue-1429/venv/lib/python3.11/site-packages/chromadb/api/fastapi.py:36
15 from chromadb.api.types import (
16     DataLoader,
17     Documents,
(...)
31     validate_batch,
32 )
33 from chromadb.auth import (
34     ClientAuthProvider,
35 )
---> 36 from chromadb.auth.providers import RequestsClientAuthProtocolAdapter
37 from chromadb.auth.registry import resolve_provider
38 from chromadb.config import …
```
> Opentelemetry requirements in Python client

- chromadb/utils/embedding_functions.py
`requests` is imported in line 17, and hence required:
https://github.com/chroma-core/chroma/blob/33289e8c5b0b5d65132a2995ab7199e83eaeacdf/chromadb/utils/embedding_functions.py#L17
> Remove redundant check for "requests" module

- examples/observability/README.md
- examples/observability/docker-compose.local-observability.yml
- examples/observability/otel-collector-config.yaml
- Added the possibility to run the observability stack (OTEL collector + Zipkin) alongside Chroma server in a docker-compose
Observability section on chroma docs updated - https://github.com/chroma-core/docs/pull/149
> [ENH]: Local Observability Stack with OTEL and Zipkin

- chromadb/api/types.py
- chromadb/segment/impl/metadata/sqlite.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_filtering.py
- chromadb/test/segment/test_metadata.py
- chromadb/types.py
- examples/basic_functionality/where_filtering.ipynb
- Fixes https://github.com/chroma-core/chroma/issues/1082
There are some formatting changes included
will update [docs]user-guide
added an example to Where Filtering
> [ENH] add not contains filter to where clause

- chromadb/api/fastapi.py
- chromadb/test/test_api.py
- Error response was containing status code and stack massage altered to chroma error to make uniform response to user. followed same logic as add. 
To reproduce:
https://gist.github.com/tazarov/35539b3a52bd02814edc0b565ec227eb
> [BUG] - corrected error response for update and upsert #1466

- go/coordinator/internal/metastore/db/dbcore/core.go
- Escape the postgres URL in the coordinator. Right now it breaks if the password contains special characters.
> [BUG] Escape URLs in coordinator

- chromadb/__init__.py
- chromadb/api/client.py
- chromadb/auth/__init__.py
- chromadb/auth/fastapi.py
- chromadb/config.py
- chromadb/errors.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/client/test_cloud_client.py
This PR adds the Chroma `CloudClient` as a client type. It takes an API key (or reads it from the environment, or prompts the user for it if it's not found) , and tries to connect to the Chroma cloud using the API key.
Under the hood, this is a specialized HTTPClient with ssl always turned on, and which uses token-based authentication with the API key as the token. 
This PR also moves the `AuthorizationError` from auth to the general set of errors, so it can be handled elsewhere by the Chroma system. 
Added a new test, `test_cloud_client`, which creates a mock 'cloud' server and then tests connection with valid and invalid API keys. 
Cloud is not yet available, so `CloudClient` is for now not to be used by external users of Chroma. Therefore, we won't land documentation changes with this …
> [ENH] Cloud client

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/src/config.rs
- rust/worker/src/lib.rs
- None
- Adds a boot up config management system for rust, this allows for a file chroma_config.yaml in the CWD, enviornment variables for the worker and specifying the path.
- The explicit decision is made to panic if configuration boot up fails
Added tests which validate defaults, loading from the default file, the standard file etc.
None required. The code is well documented for internal use.
> [ENH] Add Rust Configuration

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/src/assignment/mod.rs
- rust/worker/src/assignment/rendezvous_hash.rs
- rust/worker/src/errors.rs
- rust/worker/src/lib.rs
- /
- This adds the rendezvous hashing to the rust code so that it may be used by assigners.
- It also introduces our philosophy on error handling in the rust codebase. We will use the 17 standard error codes in the  grpc codebase, this is used so lower levels can send their codes higher, and in higher levels of the code we can Box<> a dyn Chroma Error to allow for generic handling over the codes. Lower levels will have to be specific, at the expense of verbosity in the errors they propagate and wrap. We will use the thiserror library, widely adopted in rust, in order to easily derive our errors. If a type needs to wrap a source error, thiserror provides  #[from] in order to allow callers to have more …
> [ENH] Add rust rendezvous hashing and errors

- rust/worker/src/assignment/assignment_policy.rs
- rust/worker/src/assignment/config.rs
- rust/worker/src/assignment/mod.rs
- rust/worker/src/assignment/rendezvous_hash.rs
- rust/worker/src/config.rs
- Adds the `configurable` trait for static configuration of components. 
- In rust, our pattern will be that a root worker configurable object is consumed by components implementing the "Configurable" trait. Structs can then initialize themselves if the valid config exists. DI dispatch will happen by adding a dispatch type in the config.rs method of each module (not included here). Without any fancy macro programming, I think this is the best way to do it. 
- Calling code can `Box<dyn configurable>` and pass in the worker config to any components in need of configuration.
- Adds the rust assignment policy based on the python and go versions
Added tests for booting the assignment policy config
None …
> [ENH] Add rust assignmenment policy and config management

- clients/js/package.json
Bump JS client to 1.7.1 to release new functionality
- multi-tenancy
- gemini embedding support
> release JS to 1.7.1

- go/coordinator/internal/metastore/db/dbcore/core.go
- Only call `url.QueryEscape` on `username` and `password`. At present we format out the `=` and other characters in the string so the connection doesn't work.
> Only url.QueryEscape() username and password

- go/coordinator/internal/metastore/db/dbcore/core.go
- Don't url-escape username and password. The library does this automatically and query-escaping is a non-idempotent operation, so this leads to errors
Originally we weren't running the coordinator using `/bin/sh` in kubernetes, which defaults to using Linux's `exec` environment. Because of this, the `$PASSWORD` flag wasn't being correctly populated -- it was being passed in as the literal string `"$PASSWORD"`. The resulting error, `invalid characters in username or password` (or something like that) made me think we needed to query-escape the password when in reality, the fix was to use `/bin/sh` to execute the coordinator command and properly hydrate the `--password` flag. Now that we're using `/bin/sh` and properly …
> Remove URL-escaping for coordinator password and username

- clients/js/README.md
Incorrect comma, should have been a colon.
- No bug fixes
- No new functionality
No functionality changes
Incorrect comma, should have been a colon.
> JS client: fixed syntax error in npm readme

- chromadb/test/ef/test_default_ef.py
- chromadb/utils/embedding_functions.py
Refs: #883
- Verify ONNX all-MiniLM-L6 model model download from s3 with static SHA256 (within the python code)
N/A
> [ENH]: SHA256 sum check of Chroma's onnx model.

- chromadb/auth/fastapi.py
- Defer fastapi type imports in auth code so as not to get a circular import. Fixes #1554 
> Defer fastapi type imports in auth

- .github/workflows/chroma-coordinator-test.yaml
- .gitignore
- go/coordinator/cmd/grpccoordinator/cmd.go
- Fix coordinator segfault on start due to trying to copy a value into non-initialized struct.
- Add coordinator binary and testdata to `.gitignore`
- Coordinator CI
> Fix coordinator segfault, gitignore tests, CI

- go/coordinator/internal/coordinator/apis_test.go
- go/coordinator/internal/metastore/coordinator/model_db_convert_test.go
- Fix flaky test due to collection comparisons
- ...
> [BUG] Fix flaky test due to collection comparisons

- .github/workflows/chroma-release-python-client.yml
- clients/python/requirements_dev.txt
- Python client build has not been working for a few releases now. Appears that `build` module is not longer available in default GH runner setup and needs to be explicitly installed
Manual test:
```bash
python -m pip install -r ./clients/python/requirements.txt && python -m pip install -r ./clients/python/requirements_dev.txt
....
Installing collected packages: sortedcontainers, pypika, websockets, uvloop, sniffio, pyyaml, python-dotenv, pluggy, packaging, opentelemetry-util-http, iniconfig, httptools, h11, click, attrs, asgiref, uvicorn, pytest, hypothesis, anyio, watchfiles, starlette, opentelemetry-instrumentation, opentelemetry-instrumentation-asgi, fastapi, …
```
> [BUG]: Fix for failing chromadb-client build

- chromadb/test/db/test_system.py
- k8s/deployment/kubernetes.yaml
- This fixes integration test caused by topic assignment algorithm change
- ...
> [BUG] Fix integration test

- clients/python/requirements.txt
- pyproject.toml
- Add `build` back as a dependency for the client. A do-over of https://github.com/chroma-core/chroma/pull/1561 now that main CI is passing.
> Make build an explicit dependency for client

- .github/workflows/pr-review-checklist.yml
- Fixed the Typo in github workflow
NA
> Fixed typo for Readability

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- Added emojis to make reporting bugs and feature-requests look better.
- All the big/good repos contain a link to their community as one of their issue templates, I added a similar one for our Chroma which links to the discord.
After merging this PR, It will look similar to this for the `Bug Report`, `Feature-Request`, and `Questions` templates.
No documentation changes are needed.
> ENH: Added `emojis` for issue templates and a `config.yml` file to redirect to discord for help/doubts/questions

- chromadb/test/db/test_system.py
We need to sort by segment ID not type, since two of these have the same type and may be returned in either order by sysdb.
- Fix sysdb test flakiness by sorting by ID instead of type
> Fix sysdb test flakiness

- chromadb/proto/convert.py
- chromadb/segment/impl/manager/distributed.py
- chromadb/segment/impl/metadata/sqlite.py
1. In the following line we are using `|` instead of `Union`.
https://github.com/chroma-core/chroma/blob/47447b6f9846fb63cc17d3f458df405387f46127/chromadb/proto/convert.py#L45
2. Here we are using `type[S]` instead of `Type[S]`
https://github.com/chroma-core/chroma/blob/47447b6f9846fb63cc17d3f458df405387f46127/chromadb/segment/impl/manager/distributed.py#L81
3. Here we are annotation using `list` instead of `List`
https://github.com/chroma-core/chroma/blob/47447b6f9846fb63cc17d3f458df405387f46127/chromadb/segment/impl/metadata/sqlite.py#L489
I see that project targets Python versions <= 3.10 and >=3.8.
So, if someone is using Python 3.8 or 3.9 using these annotations will cause runtime errors.
Closes #1581 
No documentation …
> TYP: Fixed `type annotations` based on required python versions

- chromadb/api/types.py
- chromadb/db/mixins/embeddings_queue.py
- chromadb/ingest/impl/pulsar.py
At few places in the codebase we are checking the type of something but raising `ValueError` instead of `TypeError`. 
**Improvements & Bug fixes**
Raising Proper error messages will be good for both the developers and users.
No documentation changes needed
> ENH: Fixed raising `TypeError` instead or `ValueError` for invalid type

- chromadb/utils/embedding_functions.py
- Move `import json` out of Amazon Bedrock EF and to top-level imports
> [CLN] Import json at top-level in embedding_functions

- chromadb/utils/embedding_functions.py
- Fixes #1193: race condition in `ONNXMiniLM_L6_V2._init_model_and_tokenizer`
> Replace ONNXMiniLM_L6_V2._init_model_and_tokenizer with tokenizer and model cached properties

- chromadb/auth/fastapi.py
- chromadb/errors.py
- chromadb/server/fastapi/__init__.py
- chromadb/server/fastapi/utils.py
- clients/python/pyproject.toml
- clients/python/requirements.txt
- clients/python/requirements_dev.txt
This fix resolved an issue with the latest Python client (`chromed-client-0.4.23.dev0`):
- Move build to dev dependencies (it is not a runtime dependency)
- Remove client dependency on fastapi package by moving fastapi_json_response to a utility module under fastapi server
- Added tenacity dependency - required for retries
- Added PyYAML dependency - required for authz (not strictly required for client, future refactor of authz to split the client/server side can be useful)
N/A
> [BUG]: Client dependency fix

- chromadb/api/types.py
- chromadb/test/api/test_types.py
Requested in https://github.com/chroma-core/chroma/issues/1488
- Raise an exception when an external embedding function doesn't return embeddings in the expected format
> ENH: Validate response of embedding function to be in the expected format during runtime

- chromadb/cli/cli.py
- chromadb/cli/utils.py
- chromadb/test/test_cli.py
Refs: #1624, #1591
- Added `--log--path` support to the CLI. A naive implementation that works with Chroma's `log_config.yml`
TBD
> [ENH]: CLI log path parameter support

- .github/workflows/chroma-worker-test.yml
- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/Dockerfile
- rust/worker/build.rs
- rust/worker/src/config.rs
- rust/worker/src/lib.rs
- rust/worker/src/types/collection.rs
- rust/worker/src/types/embedding_record.rs
- rust/worker/src/types/metadata.rs
- rust/worker/src/types/mod.rs
- rust/worker/src/types/operation.rs
- rust/worker/src/types/scalar_encoding.rs
- rust/worker/src/types/segment.rs
- rust/worker/src/types/segment_scope.rs
- rust/worker/src/types/types.rs
- Update dockerfile to use a fetched protoc since that is needed for protoc to include/ WKT
- Adds a build.rs so that we can build the protos into rust bindings
- Adds a types/ folder with types and rust-y/idiomatic TryFrom conversions so that callers can just do .try_from() and get type inference.
- Adds a macro for error type wrapping and impl'ing ChromaError on the macro.
- All types are rexported from types/ so that the rest of the code can easily use it.
- Add _very_ rudimentary tests for conversion. We should do a pass where we add some more rigorous conversion testing.
None required.
> [ENH] Add rust protobufs and conversion. Add build.rs, protobufs, and conversions

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/src/assignment/assignment_policy.rs
- rust/worker/src/config.rs
- rust/worker/src/lib.rs
- rust/worker/src/memberlist/config.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- rust/worker/src/memberlist/mod.rs
- rust/worker/src/system/executor.rs
- rust/worker/src/system/mod.rs
- rust/worker/src/system/system.rs
- rust/worker/src/system/types.rs
- / 
- Adds a component system which allows for an actor-like framework for processing messages. A component is a stateful object and its handle + sender can be used to send it messages. 
- Adds the k8s CR memberlist provider, which is a component
The component is tested with 
The memberlist provider is currently manually tested, I will add proper intergration tests in a follow on PR
None required.
> [ENH] Add component system + memberlist provider

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/chroma_config.yaml
- rust/worker/src/assignment/assignment_policy.rs
- rust/worker/src/assignment/mod.rs
- rust/worker/src/bin/worker.rs
- rust/worker/src/config.rs
- rust/worker/src/errors.rs
- rust/worker/src/ingest/config.rs
- rust/worker/src/ingest/ingest.rs
- rust/worker/src/ingest/mod.rs
- rust/worker/src/lib.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- rust/worker/src/memberlist/mod.rs
- rust/worker/src/system/system.rs
- rust/worker/src/system/types.rs
- Adds a proper binary for the worker
- Add an entry point for the worker the binary can use
- Allow returning of join handles in component handles
- Adds pulsar subscriptions for the ingest, this watches the memberlist, and then spawns/removes sub-components that will subscribe to the correct stream and deserialize the message. Processing of this stream will be a following PR, this is big enough as is. 
- There are quite a few TODOs that are about error handling in here, I will do a clean up pass in a following PR.
None required.
> [ENH] add Rust pulsar and topic management

- rust/worker/src/ingest/message_id.rs
- rust/worker/src/ingest/mod.rs
- Adds a pulsar MsgID to our SeqID conversion based on the python version. I think we may need to revisit this encoding, as it reduces the range of the various fields, unless I am thinking about it incorrectly. For now I duplicated what we had, and we can revisit in the future.
- /
> [ENH] Add rust message id conversion for pulsar

- rust/worker/chroma_config.yaml
- rust/worker/src/config.rs
- rust/worker/src/ingest/ingest.rs
- rust/worker/src/ingest/message_id.rs
- rust/worker/src/lib.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- rust/worker/src/sysdb/config.rs
- rust/worker/src/sysdb/mod.rs
- rust/worker/src/sysdb/sysdb.rs
- rust/worker/src/system/executor.rs
- rust/worker/src/system/mod.rs
- rust/worker/src/system/sender.rs
- rust/worker/src/system/system.rs
- rust/worker/src/system/types.rs
- This allows the system to have a mutable handle to the component in handlers. Which is needed if you want to avoid wrapping everything in Locks. Since we can now mutate the component in the handler.
- Adds a Wrapper<> Type so that we can wrap messages and dispatch to the handler without needing to leak the Component Type everywhere
- Adds a Receiver type that allows us to use the components handle to get a sender pointed at it for a given message, this is used in the Memberlist to allow for subscribing to changes. 
- /
*Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the [docs …
> [ENH] Refactor system to allow mutable handles, wrapped messages, single M recievers

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/chroma_config.yaml
- rust/worker/src/config.rs
- rust/worker/src/index/hnsw.rs
- rust/worker/src/index/mod.rs
- rust/worker/src/index/types.rs
- rust/worker/src/ingest/ingest.rs
- rust/worker/src/ingest/mod.rs
- rust/worker/src/ingest/scheduler.rs
- rust/worker/src/lib.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- rust/worker/src/segment/config.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
- rust/worker/src/segment/mod.rs
- rust/worker/src/segment/segment_ingestor.rs
- rust/worker/src/segment/segment_manager.rs
- rust/worker/src/system/sender.rs
- rust/worker/src/system/system.rs
- rust/worker/src/system/types.rs
- rust/worker/src/types/metadata.rs
- rust/worker/src/types/segment.rs
- Adds a tenant-level RR scheduler and uses sysdb to look up tenants, this is not cached for now.
- The scheduler can be slept/awoken
- Adds a segment concept with tracking for user ids -> internal ids
- /
Apologies for the larger diff, my stack got messed up
> [ENH] Add ingest dispatch + scheduler + segment

- chromadb/auth/fastapi_utils.py
- chromadb/server/fastapi/__init__.py
- chromadb/server/fastapi/utils.py
- fastapi_utils needs to push the uuid as a UUID type not str to get_collection.
- Refactored _uuid into a util
- None
> [BUG] UUID should be uuid type not str

- chromadb/test/db/test_system.py
- go/coordinator/cmd/grpccoordinator/cmd.go
- k8s/deployment/kubernetes.yaml
- k8s/deployment/segment-server.yaml
- This aligns the coordinator, rust worker, and python client on default/default as the pulsar tenant/namespace
> [BUG] Fix coordinator pulsar tenant and namespace

- bin/docker_entrypoint.sh
- Docker gracefully shutdown (#1646  )
Tested locally with docker.
```
[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
DEBUG:    [16-01-2024 23:24:47] Registering provider: token_config
DEBUG:    [16-01-2024 23:24:47] Registering provider: user_token_config
DEBUG:    [16-01-2024 23:24:47] Registering provider: token
DEBUG:    [16-01-2024 23:24:47] Registering provider: token
WARNING:  [16-01-2024 23:24:47] chroma_server_nofile is set to 65535, but this is less than current soft limit of 1048576. chroma_server_nofile will not be set.
INFO:     [16-01-2024 23:24:47] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
DEBUG: …
```
> [BUG] fix docker don't shutdown gracefully

- Dockerfile
- bin/docker_entrypoint.sh
- examples/advanced/hadrware-optimized-image.md
- Removed the re-download of hnsw in docker entrypoint
- Removed build dependencies in final image to reduce size (by about 100M)
- Added flag for rebuilding hnsw lib from source
- Added docs how to build in image with hardware-optimized hnsw
Example of building AVX-optimized image added under `examples/`.
> [PERF]: Optimized docker image

- chromadb/migrations/metadb/00005-fts-secure-delete.sqlite.sql
- chromadb/segment/impl/metadata/sqlite.py
- chromadb/test/segment/test_metadata.py
Without FTS clean-up, the SQLite file grows over time as collections are added and removed:
No clean-up:
With clean-up:
- Enabled secure-delete option in FTS
- Removing entries for deleted segments from FTS
> [BUG]: FTS delete

- chromadb/api/types.py
- chromadb/test/segment/test_metadata.py
Closes: #1717
- Fixed an issue where if the metadata key is set to `chroma:document` it is either ignore when inserting or overrides the actual document when updating records by `id`
N/A
> [BUG]: Adding validation check for "chroma:document" in metadata.

- chromadb/api/segment.py
- chromadb/config.py
- chromadb/quota/__init__.py
- chromadb/quota/test_provider.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/conftest.py
- chromadb/test/quota/test_static_quota_enforcer.py
-  Add quota check, it will be use to be able to rate limit, apply static check to payload etc. 
CIP doc
> [ENH] Add quota component and test for static

- chromadb/test/property/test_collections.py
Needed to fix the failing property tests in #1715 
- Moved the  model update after conditional checks for new_name and metadata.
- ...
Failure logs + Error analysis:
```
>       assert c.metadata == self.model[coll.name]
E       AssertionError: assert {'g': 1.1, 'n...': 31734, ...} == {'3': 'd71IL'...235e-208, ...}
E         
E         Left contains 5 more items:
E         {'g': 1.1,
E          'n1dUTalF-MY': -1000000.0,
E          'ugXZ_hK': 5494,
E          'xVW09xUpDZA': 31734,
E          'y': 'G3EtXTZ'}
E         Right contains 9 more items:
E         {'3': 'd71IL',
E          '45227B': '65',
E          '7DjCkbusc-K': 'vc94',
E          '8-tD9nJd': …
```
> [BUG]: Fixed test_collections.py property test

- chromadb/__init__.py
- chromadb/api/fastapi.py
- chromadb/config.py
- chromadb/test/client/test_cloud_client.py
- chromadb/test/conftest.py
- chromadb/test/test_chroma.py
- chromadb/test/test_client.py
- Stringify all paremeters to `Client`s which are meant to be strings. At present some parameters -- `port` in particular -- can be reasonably passed as integers which causes weird and unexpected behavior.
- Fixes #1573
> [BUG] Make sure Client parameters are strings

- .github/workflows/chroma-client-integration-test.yml
- .github/workflows/chroma-release-python-client.yml
- .github/workflows/chroma-test.yml
- DEVELOP.md
- requirements.txt
Chroma did not support Python 3.12 because of our dependency on the ONNX runtime for our default embedding function. As of version 1.17.0, ONNX supports python 3.12: https://github.com/microsoft/onnxruntime/issues/17842#issuecomment-1936484800
This already automatically fixes the issue for Chroma users when they install the new version of ONNX / reinstall Chroma. This PR is just to update our test and release actions to also use python 3.12. 
These are changes to test workers. 
N/A
> [ENH] Upgrade tests and release to Python 3.12

- chromadb/utils/embedding_functions.py
After 1.17, ONNXRuntime produces scary warnings on mac platforms, because it tries to put our default embedding function into the CoreML execution environment, where it doesn't fit. 
This PR suppresses warnings from ONNX within the default embedding function so that users don't see scary warnings. 
Locally tested via the `start_here` notebook.
N/A
> [ENH] Remove ONNX Logspam

- requirements_dev.txt
- The newest version of hypothesis seems to be breaking our tests. This pegs us to a lower version for now.
- None
None
> [TST] Peg hypothesis to working version

- chromadb/test/property/strategies.py
- chromadb/test/property/test_collections.py
- Fix test flakiness mentioned in https://github.com/chroma-core/chroma/pull/1716 and seen after.
The problem was subtle:
- There are three places Collection state is stored: in Hypothesis's Bundle (== test data ~randomly generated according to our models), in our test's `.model` field, and in Chroma itself.
- Each test step gets a random Collection from the Bundle. Our test code is responsible for doing stuff with it, modifying the test model, executing operations on Chroma itself, and verifying that model state matches Chroma's state.
- Hypothesis's Bundle has (but no longer will once this PR lands) a full Collection model with all internal bookeeping, incl UUID and other fields. So we could have two Collections in the …
> [BUG] Fix test flakiness

- Tiltfile
- bin/cluster-test.sh
- chromadb/test/db/test_system.py
- k8s/distributed-chroma/templates/coordinator.yaml
- k8s/distributed-chroma/values.yaml
- `port-forward` to `-lb` services correctly. This fixes the hanging CI.
- Remove unused var in cluster-test.sh.
- Remove `coordinator.port` helm chart config for consistency -- we can add them all later.
- Fix tiltfile deps so the cluster comes up correctly.
- Explicitly pass coordinator port to sysdb client instantiation in tests.
> [CLN] Fix CI and a couple other cleanups

- chromadb/config.py
- chromadb/rate_limiting/__init__.py
- chromadb/rate_limiting/test_provider.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/rate_limiting/test_rate_limiting.py
- Add rate limiting service. If no rate limit service is provided, it will not do anything.
Unit test on rate limiting service.
> [ENH]: add rate limiting

- Dockerfile
- docker-compose.yml
- added docker compose restart policy - "unless-stopped" as default
- added docker compose health checks
- added ports in quotes to follow the docker spec
Manual tests
```bash
(venv) [chroma-core-taz-sprint-8]docker compose ps
NAME                                IMAGE     COMMAND                  SERVICE   CREATED              STATUS                        PORTS
chroma-core-taz-sprint-8-server-1   server    "/docker_entrypoint.…"   server    About a minute ago   Up About a minute (healthy)   0.0.0.0:8000->8000/tcp
(venv) [chroma-core-taz-sprint-8]       
(venv) [chroma-core-taz-sprint-8]docker exec chroma-core-taz-sprint-8-server-1 /bin/bash -c "kill 1"
(venv) …
```
> [PERF]: Minor docker compose quality of life improvements

- rust/worker/Dockerfile
- Use docker cache for faster tilt restart.
- With tilt
> [ENH]: make rust docker image build faster with cache

- go/README.md
per discussion, adding a local postgres setup readme doc
> [ENH] readme for local postgres setup

- .github/workflows/chroma-cluster-test.yml
- Tiltfile
- bin/cluster-test.sh
- chromadb/config.py
- chromadb/db/mixins/logservice.py
- chromadb/logservice/logservice.py
- chromadb/test/conftest.py
- chromadb/test/test_logservice.py
- go/internal/coordinator/grpc/collection_service.go
- go/internal/coordinator/grpc/server.go
- k8s/distributed-chroma/templates/coordinator.yaml
- k8s/distributed-chroma/templates/frontend-server.yaml
- k8s/distributed-chroma/templates/logservice.yaml
- k8s/test/logservice_service.yaml
https://linear.app/trychroma/issue/CHR-242/fe-talks-to-log-service
- FE talks to logservice
> [ENH] FE talks to logservice

- chromadb/telemetry/opentelemetry/grpc.py
- Add grpc client interceptor to propagate trace information for distributed tracing.
Tested locally using tilt and golang rpc
> [ENH]: add grpc python client interceptor

- rust/worker/build.rs
- rust/worker/src/config.rs
- rust/worker/src/lib.rs
- rust/worker/src/log/config.rs
- rust/worker/src/log/log.rs
- rust/worker/src/log/mod.rs
- rust/worker/src/types/embedding_record.rs
- ...
- This PR adds functionality to read logs from log service and get collections to compact. 
> [ENH] Add rust client to log service

- .github/workflows/chroma-release.yml
Will be put back once hosted-chroma k8s is in its proper state -- this is a temporary measure to keep OSS CI green
> [BLD] Remove hosted chroma workflow dispatches

- chromadb/utils/embedding_functions.py
Ref: https://discord.com/channels/1073293645303795742/1214028592372252682
- Added `device` optional param to OpenCLIP EF
> **NOTE:** It doesn't see we have OpenCLIP EF docs. Will have to add.
> [ENH]: OpenCLIP EF `device` param

- clients/js/src/types.ts
- clients/js/test/get.collection.test.ts
- clients/js/test/query.collection.test.ts
- Added missing `$not_contains` WhereDocument op
N/A
> [BUG]: Added missing $not_contains operator for WhereDocument

- chromadb/api/types.py
Refs: #1694
- Shortened validation error printouts to improve log readability
N/A
> [ENH]: Updates to validation errors

- rust/worker/src/blockstore/arrow_blockfile/block/iterator.rs
- rust/worker/src/blockstore/arrow_blockfile/block/mod.rs
- rust/worker/src/blockstore/arrow_blockfile/block/types.rs
- None
- Adds a basic block iterator to allow for easily cloning a block into a BlockDelta
None
> [ENH] Block iterator

- rust/worker/src/compactor/scheduler.rs
- rust/worker/src/log/log.rs
- Fixes an issue with the scheduler test where tiebreaks on 0 last compaction time are random. This uses contains instead of order. When @Ishiihara adds a the api for last compaction time to the sysdb this will be fixed and reverted! 
- None
None
> [TST] Scheduler test fix

- rust/worker/Dockerfile
- Adds the ability to build dockerfile for rust worker in release mdoe
- /
I manually modified the arg and made sure the expected control flow was followed.
None required.
> [BLD] Add docker arg to build in release mode

- rust/worker/src/blockstore/arrow_blockfile/block/delta.rs
- rust/worker/src/blockstore/arrow_blockfile/block/mod.rs
- rust/worker/src/blockstore/arrow_blockfile/block/types.rs
- rust/worker/src/blockstore/arrow_blockfile/blockfile.rs
- rust/worker/src/blockstore/arrow_blockfile/mod.rs
- rust/worker/src/blockstore/arrow_blockfile/provider.rs
- rust/worker/src/blockstore/types.rs
- None
- Adds a BlockDelta which is used to mutate a block. It reads the contents of a block and then can allows changes to be applied directly to it.
- Adds the ability to apply() a block delta
- Add a BlockProvider, which is the interface for loading and managing blocks.
None
> [ENH] Block delta

- rust/worker/src/blockstore/arrow_blockfile/block/delta.rs
- rust/worker/src/blockstore/arrow_blockfile/block/mod.rs
- rust/worker/src/blockstore/arrow_blockfile/block/types.rs
- rust/worker/src/blockstore/arrow_blockfile/blockfile.rs
- rust/worker/src/blockstore/arrow_blockfile/sparse_index.rs
- rust/worker/src/blockstore/types.rs
- Adds roaring bitmap value types, builders etc
- Adds the base of the blockfile implementation for the arrow-backed blockfile.
Basic
None
> [ENH] Add Arrow-backed blockfile

- rust/worker/src/segment/mod.rs
- rust/worker/src/segment/types.rs
- Adds an interface type for segments. We can add flush etc here in the future. I will move hnsw to use this in a stacked PR.
- None.
No logical changes. These are just interfaces.
None
> [ENH] Add Segment Interfaces

- rust/worker/src/blockstore/arrow_blockfile/block/delta.rs
- rust/worker/src/blockstore/arrow_blockfile/block/iterator.rs
- rust/worker/src/blockstore/arrow_blockfile/block/types.rs
- rust/worker/src/blockstore/arrow_blockfile/blockfile.rs
- rust/worker/src/blockstore/types.rs
- rust/worker/src/index/fulltext/types.rs
- Lets the blockfile use uint vals and keys.
- Some name cleanup / unification
- /
Basic sanity tests.
None
> [ENH] Add uint blockfile key/val

- go/Dockerfile.migration
- k8s/distributed-chroma/templates/sysdb-migration.yaml
- Run the SysDB migration in `/bin/sh` so we can sub in env vars as needed. This requires installing atlas into a debian image instead of using the atlas image directly.
> [ENH] Run the sysdb migration in sh so we can do env var substitition

- go/Dockerfile
- go/Dockerfile.migration
- We use jq for some env var stuff. We need it in the migration, not the sysdb service (which knows how to correctly URL-escape args)
> [BUG] install jq in migration, not sysdb

- rust/worker/Cargo.toml
- rust/worker/chroma_config.yaml
- rust/worker/src/bin/query_service.rs
- rust/worker/src/bin/worker.rs
- rust/worker/src/config.rs
- rust/worker/src/errors.rs
- rust/worker/src/execution/config.rs
- rust/worker/src/execution/dispatcher.rs
- rust/worker/src/execution/mod.rs
- rust/worker/src/execution/operator.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/orchestration/mod.rs
- rust/worker/src/execution/worker_thread.rs
- rust/worker/src/lib.rs
- rust/worker/src/log/mod.rs
- rust/worker/src/server.rs
- rust/worker/src/sysdb/mod.rs
- rust/worker/src/sysdb/sysdb.rs
- rust/worker/src/system/scheduler.rs
- rust/worker/src/system/system.rs
- Add a new entrypoint for query-service. Delete the old worker entrypoint that did not have read/write decoupling.
- Make dispatcher configurable
- Wrapped hnsw orchestrator logic into run() so server is unaware of it
- Make server struct {} have the resources it needs
- Add dynamic creation for log
- Add dynamic creation for sysdb
- Make server respond to query by using orchestrator 
None
> [ENH] Add query-service server

- rust/worker/build.rs
- Auto rebuild protos if they change in rust
- None
None
> [BLD] Auto rebuild protos if they change in rust

- rust/worker/src/errors.rs
- rust/worker/src/execution/dispatcher.rs
- rust/worker/src/execution/operator.rs
- rust/worker/src/execution/operators/pull_log.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- Allows errors to be propagated from operators back to the original caller of the task. 
- None
Compile checks show that the error propagates as expected. 
None
> [ENH] Operator/Executor error handling

- chromadb/config.py
- chromadb/segment/impl/distributed/server.py
- go/cmd/coordinator/cmd.go
- rust/worker/chroma_config.yaml
- rust/worker/src/memberlist/memberlist_provider.rs
- We renamed the memberlist to query-service-memberlist given the query/compactor split. 
- This aligns all the defaults with that name
- None
None
> [BUG] Rename memberlist to match new memberlist name

- rust/worker/Dockerfile
- Remove the build cache for the query service. Right now it makes the stagnig query node recompile the binary.
> [BUG] remove query service build cache - breaks staging

- Tiltfile
- go/Dockerfile
- rust/worker/Dockerfile
- Tighten up dockerfiles and tiltfile: Get rid of Alpine linux, make dockerfiles a little friendlier to cache and make the final images smaller, and tell tilt only to reload some of the dockerfiles on certain path reloads.
> [PERF] Make tilt and docker faster

- rust/worker/chroma_config.yaml
- rust/worker/src/config.rs
- Point the query service to port 50051 on the log service, not 50052. We only use 50052 for the external-facing service during testing since it conflicts with the sysdb on 50051.
> [BUG] Point query service to the right logservice port

- rust/worker/src/execution/orchestration/hnsw.rs
- Match the timestamp with the LogService, which uses nanoseconds. 
- ...
> [BUG] Use nano seconds as end_timestamp

- go/README.md
- go/pkg/logservice/grpc/record_log_service.go
- go/pkg/logservice/grpc/record_log_service_test.go
- Log service incorrectly did not return the collection ID of the record. I suspect that we meant to strip the collection id and rehydrate it into the proto for space reasons. I honored this intent and rehydrate the colleciton id.
- Add some readme for running tests locally with PG
- Fixed a bug in the log_service test where the input is mutated, which makes the source of truth have no collection id. This was passing when we incorrectly returned no collection id but was correctly failing now. I patched the test by cloning the records for a SOT.
- For the test I fixed, the expected vs actual order was incorrect.
- None
None
> [BUG] Log service incorrectly doesn't hydrate collection id

- rust/worker/src/execution/operators/pull_log.rs
- The rust log service makes an additional query when it doesn't need to if the timestamp is provided and we read less than a batch size. This means that we are done reading the log and don't need to fetch again.
- None
None
> [BUG] Log service N+1 query

- rust/worker/src/lib.rs
- Rust server boot code should wire up the system.
- None
None
> [BUG] Rust server should wire up system

- rust/worker/src/execution/operators/brute_force_knn.rs
- The brute force operator should return min(data_size, k)
- None
None
> [BUG] BF operator should min(data, k) to prevent panic

- rust/worker/src/execution/orchestration/hnsw.rs
- This is a low-quality commit of wiring up the BF operator just to get things working e2e. We will rewrite a lot of this marginally when the chunk abstraction lands.
- None
None
> [ENH] make hnsw query orchestrator use BF operator

- rust/worker/chroma_config.yaml
- rust/worker/src/assignment/assignment_policy.rs
- rust/worker/src/assignment/mod.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/compactor/scheduler.rs
- rust/worker/src/config.rs
- rust/worker/src/execution/dispatcher.rs
- rust/worker/src/lib.rs
- rust/worker/src/log/log.rs
- rust/worker/src/log/mod.rs
- rust/worker/src/memberlist/config.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- rust/worker/src/server.rs
- rust/worker/src/storage/s3.rs
- rust/worker/src/sysdb/mod.rs
- rust/worker/src/sysdb/sysdb.rs
- ...
- This PR adds memberlist consumption for the compaction service and filter collections based on memberlist using Rendezvous assignment policy. 
> [ENH] Add memberlist for compaction service

- chromadb/api/segment.py
- chromadb/auth/fastapi.py
- chromadb/config.py
- chromadb/db/impl/sqlite.py
- chromadb/server/fastapi/__init__.py
- chromadb/telemetry/opentelemetry/__init__.py
- chromadb/test/client/test_multiple_clients_concurrency.py
This is PR #1695 migrated to Chroma repo for stacking the outstanding changes.
- Added orjson serialization improving serialization performance especially on large batches 100+ docs 2x faster (tested with locust)
- Added async body serialization further improving performance (tested with locust)
- ⚠️ Fixed an issue with SQLite lack of case_sensitive_like for FastAPI Server thread pool connections
For performance tests, **5** concurrent clients were querying, and **1** was adding pre-computed OpenAI (ada-02) embeddings (runtime **~1m**)
**Batch size**: 100 (1000 also attached in a zip)
Tests with existing `main` codebase:
Tests with orjson + async: …
> [PERF]: Improved server-side serialization with orjson + async

- chromadb/quota/__init__.py
- chromadb/test/quota/test_static_quota_enforcer.py
- Add more test cases in [test_static_quota_enforcer.py](https://github.com/chroma-core/chroma/blob/main/chromadb/test/quota/test_static_quota_enforcer.py) to find the buggy corner cases.
- Fix the bug in [QuotaEnforcer](https://github.com/chroma-core/chroma/blob/main/chromadb/quota/__init__.py) and pass the above corner cases.
- None.
- No change is required for documentation.
> [BUG] QuotaEnforcer fails to check out the corner cases.

- clients/js/examples/browser/yarn.lock
- clients/js/src/AdminClient.ts
- clients/js/src/ChromaClient.ts
- clients/js/src/ChromaFetch.ts
- clients/js/src/Collection.ts
- clients/js/src/Errors.ts
- clients/js/src/embeddings/OllamaEmbeddingFunction.ts
- clients/js/src/index.ts
- clients/js/src/utils.ts
- clients/js/test/auth.basic.test.ts
- clients/js/test/auth.token.test.ts
- clients/js/test/client.test.ts
- clients/js/test/get.collection.test.ts
- clients/js/test/offline.test.ts
This PR reworks the way error handling works with the JavaScript client. Previously, the api would return objects with error messages under certain circumstances and throw errors in other circumstances. This standardizes that by supplying a custom fetch implementation that translates the http error codes and the server error responses, into a standardized set of errors that are thrown by the client functions. 
- This is a breaking change to the API of the client so this should be documented.
> [ENH]: Improved error reporting

- go/cmd/coordinator/cmd.go
- go/pkg/coordinator/grpc/server.go
- go/pkg/memberlist_manager/memberlist_manager.go
- go/pkg/memberlist_manager/memberlist_manager_test.go
- This PR add batch processing of pod related events. 
- This diff reduces the unnecessary number of memberlist propagation to the downstream in the following cases:
- Pod delete followed by a pod add
- Multiple pods added to the deployment at similar time. 
- A follow up PR will be added to the compaction and query service to allow graceful shutdown to speed up the propagation of deleted pods by the informer to the memberlist manager. 
- ...
> [ENH] Batch process pod events for memberlist manager

- go/pkg/memberlist_manager/memberlist_manager.go
- go/pkg/memberlist_manager/memberlist_manager_test.go
- This PR improves the memberlist updates to downstream. Only memberlist change will  be updated Kubernetes and thus reduces the unnecessary updates.  
- ...
> [ENH] Only update memberlist when their is a change

- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/compactor/scheduler.rs
- rust/worker/src/compactor/scheduler_policy.rs
- rust/worker/src/compactor/types.rs
- rust/worker/src/execution/data/data_chunk.rs
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/flush_sysdb.rs
- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/execution/operators/pull_log.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/log/log.rs
- rust/worker/src/sysdb/sysdb.rs
- rust/worker/src/sysdb/test_sysdb.rs
- rust/worker/src/types/flush.rs
- rust/worker/src/types/mod.rs
- rust/worker/src/types/segment.rs
- This PR adds flush sysdb operator to compaction orchestrator. 
- Changes include
- A new sysdb API to write to the sysdb on the new compaction metadata.
- A flush_sysdb operator which will be used by the compaction orchestrator to register the compaction result to sysdb. 
- ...
> [ENH] Add flush sysdb to compactor

- rust/worker/src/execution/operators/flush_s3.rs
- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/execution/operators/write_segments.rs
- rust/worker/src/execution/orchestration/compact.rs
- This PR adds skeleton code for write segments and flush S3 operator to prepare for integration with Blockfile. 
- ...
> [ENH] Rust write segments and flush S3 operator skeleton

- go/pkg/memberlist_manager/memberlist_manager_test.go
- Make the gracefulperiod to be 0 for pod deletion
- ...
> [BUG] Make the gracefulperiod to be 0 for pod deletion

- chromadb/test/db/test_system.py
The test_system.py tests fail sporadically with "Address already in use". This is an attempt for fix those sporadic test failures. Example failed build: https://github.com/chroma-core/chroma/actions/runs/8743308262/job/23994159391?pr=2027#logs
> [TST] Try to fix a sporadic test failure

- Cargo.lock
- k8s/distributed-chroma/values.yaml
- rust/worker/Cargo.toml
- rust/worker/src/bin/query_service.rs
- rust/worker/src/execution/dispatcher.rs
- rust/worker/src/execution/operator.rs
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/pull_log.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/worker_thread.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- rust/worker/src/server.rs
- rust/worker/src/system/executor.rs
- rust/worker/src/system/scheduler.rs
- rust/worker/src/system/sender.rs
- rust/worker/src/system/system.rs
- rust/worker/src/system/types.rs
This PR integrates end-to-end tracing for the Query Service (specifically the `query_vectors()` RPC). The main highlights are:
- Span inheritance by component - whenever a component is started the executor executes the `run()` function inside a child span with the current span as the parent. This works even across threads now for e.g. if the component was spawned in `inherited` mode but it invoked the receive msg handler on a different thread, etc.
- Span propagation across components. For e.g. when the HNSW Query orchestrator submits the Pull logs request or brute force KNN request to the worker (via the dispatcher), the worker invokes the task handler inside a child span with parent span as the HNSW orchestrator. This is implemented by adding a new field to the `Task` struct - the span …
> [ENH] Integrate e2e tracing for query vectors endpoint

- go/pkg/metastore/db/dao/collection_test.go
Issue:
A particular order for collections is expected. The collections are currently returned ordered by id which is UUID -> random. This makes the test flaky and fails ~ every second run.
Fix:
Fix the tests to expect the collections returned in the appropriate order.
> [TST] Fix a flaky metastore collection test

- rust/worker/src/execution/data/data_chunk.rs
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/partition.rs
- rust/worker/src/execution/operators/pull_log.rs
- rust/worker/src/execution/orchestration/compact.rs
- Makes DataChunk a generic Chunk<T> and refactors for Chunk<LogRecord> where appropriate.
- None
None
> [ENH] Change DataChunk to Chunk and make Generic

- rust/worker/src/execution/mod.rs
- rust/worker/src/segment/mod.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/segment/types.rs
- Adds a materialized record type for consumption downstream.
- None.
> [ENH] Add a materialized record type as well as make segment interface chunk

- go/pkg/memberlist_manager/memberlist_manager.go
- go/pkg/memberlist_manager/memberlist_manager_test.go
- This PR fixes the issue that the memberlist manager is not propagating the memberlist to downstream. The issue is that the Get function for the worker queue is blocking when the queue is empty. The end result is that if the number of events is not cumulated to the batch size, the memberlist may block waiting and not propagate the memberlist with timeout. 
- ...
> [BUG] Refactor memberlist reconciliation in MemberlistManager

- chromadb/segment/impl/metadata/grpc_segment.py
- Fixes a bug where the segment was returning an empty [] despite constructing the correct result
- None
We should have a test for this! For now I am getting the bug fix up and we can discuss how to test.
- [!!!!] Tests pass locally with `pytest` for python, `yarn test` for js, `cargo test` for rust
None
> [BUG] GRPC Metadata segment should return results

- go/pkg/log/repository/log.go
- go/pkg/log/server/property_test.go
- go/shared/libs/db_utils.go
pg.Connect is returning only one connection, which is not thread safe and cause an error. When running in grpc, each request run on a different go routine, and in parallel. pgpool will create and manage a set of connection.
- Use pg pool to use threadsafe connection.
> [ENH]: use pgpool for log services

- chromadb/segment/impl/metadata/grpc_segment.py
Not sure if this is correct but type checker was complaining so putting up for thoughts
- Fixes a (assumed) bug where we were converting the wrong type
- None
We should to discuss the testing here / why this worked
- [!!!] Tests pass locally with `pytest` for python, `yarn test` for js, `cargo test` for rust
None
> [BUG] Double comparison proto conversion

- chromadb/api/fastapi.py
- chromadb/api/segment.py
- chromadb/api/types.py
- chromadb/test/property/test_filtering.py
- chromadb/test/test_api.py
- clients/js/src/types.ts
- clients/js/test/get.collection.test.ts
- clients/js/test/query.collection.test.ts
Helps clarify behavior when fields like `embeddings` are returned as `None`. Not a breaking change.
I didn't see any relevant documentation that needs to be updated.
> [ENH] add `included` to `.get()` & `.query()` response

- chromadb/api/segment.py
- chromadb/test/test_api.py
- clients/js/src/ChromaFetch.ts
- clients/js/src/Errors.ts
- clients/js/test/add.collections.test.ts
- clients/js/test/delete.collection.test.ts
- clients/js/test/get.collection.test.ts
- clients/js/test/peek.collection.test.ts
- clients/js/test/query.collection.test.ts
- clients/js/test/update.collection.test.ts
- clients/js/test/upsert.collections.test.ts
Use the InvalidCollectionException consistently in the Python client and APIs.
Introduce InvalidCollectionError to the JS client and handle it accordingly.
This is the first step to improving error handling in both client and completing #565.
Add tests for all related scenarios.
> [ENH] Use InvalidCollectionException/Error consistently

- .github/workflows/chroma-lint.yml
- .pre-commit-config.yaml
Exclude Helm templates from YAML linting as they are not valid YAML
Fixes #2053
> [ENH] Enable check-yaml in CI

- chromadb/telemetry/opentelemetry/grpc.py
- go/cmd/logservice/main.go
- go/pkg/grpcutils/service.go
- go/pkg/log/configuration/config.go
- go/shared/otel/main.go
- k8s/distributed-chroma/values.yaml
> [ENH]: add distributed tracing

- rust/worker/src/lib.rs
- Load from evn path for 
- None
None
> [ENH] Allow rust worker to load config path from env var

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/src/benches/distance_metrics.rs
- rust/worker/src/distance/distance_avx.rs
- rust/worker/src/distance/distance_neon.rs
- rust/worker/src/distance/distance_sse.rs
- rust/worker/src/distance/mod.rs
- rust/worker/src/distance/types.rs
- rust/worker/src/lib.rs
Adds SIMD vectorization for euclidean, cosine and inner product for x86, x86_64 and arm. Instruction sets whose support has been added are SSE, AVX and NEON.
- [+] Tests pass locally with `pytest` for python, `yarn test` for js, `cargo test` for rust
No
> [ENH] SIMD vectorization for distance metrics

- rust/worker/src/sysdb/sysdb.rs
- The go sysdb expects this if id is set
- None
None
> [BUG] Rust sysdb should send default string value

- clients/js/src/AdminClient.ts
- clients/js/test/admin.test.ts
Previously, the admin client was throwing `Response`s rather than Errors. It now uses the same helper as the data plane client to throw well-formatted errors.
> [ENH] JS admin client should throw well-formatted errors rather than Responses

- bin/ts-integration-test
- chromadb/__init__.py
- chromadb/auth/__init__.py
- chromadb/auth/basic_authn/__init__.py
- chromadb/auth/token_authn/__init__.py
- chromadb/test/auth/strategies.py
- chromadb/test/client/test_cloud_client.py
- Added random jitter to mitigate timing attacks on early exist conditions
- Added generic AuthError for early exist conditions
- Added checks for missing headers(as this was throwing key error)
- Made it possible to use the TokenTransportHeader Enum when defining client-side auth(docs also updated)
- Improved validation of wrong Token transport headers with a friendlier user message
- Broader exception handling now logs only exception type and line number to prevent unintentional information disclosure(A02: 2021-Cryptographic Failures - owasp top10)
- Aligned both token and basic auth logic flow with exist conditions
- Fixed an issue with replacement of auth headers Basic and Bearer with regex which aligns well with …
> [BUG][SEC]: Fixes AuthN server-side providers

- k8s/distributed-chroma/templates/query-service.yaml
- k8s/distributed-chroma/values.yaml
- Add configmap for query service - mirroring compaction
- None
- 
None
> [ENH] Add configmap for query service

- rust/worker/src/execution/operators/pull_log.rs
- The PullLogOperator does not correctly update the offset after the first fetch as it might return less records than the batch size. 
- ...
> [BUG] PullLog Operator should update the next pull offset to be the last record offset + 1 of previous pull

- rust/worker/src/blockstore/arrow/flusher.rs
- rust/worker/src/blockstore/arrow/provider.rs
- rust/worker/src/index/hnsw_provider.rs
- rust/worker/src/storage/mod.rs
- rust/worker/src/storage/s3.rs
- Improve error propagation and debug for flush
- None
None
> [CLN] Flush error propagation and debug

- rust/worker/src/compactor/compaction_manager.rs
-  This PR cleans up the redundant sysdb initialization in compactor manager. 
- ...
> [CLN] Remove redundant sysdb initialization in compactor manager

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/chroma_config.yaml
- rust/worker/src/bin/query_service.rs
- rust/worker/src/config.rs
- rust/worker/src/lib.rs
- rust/worker/src/tracing/mod.rs
- rust/worker/src/tracing/opentelemetry_config.rs
Export traces and spans in open telemetry format so that it can be consumed by backends like Jaeger and Honeycomb. For Jaeger verified that it works locally. Need to test honeycomb
All existing tests pass. Verified locally via tilt up and tilt down that traces are exported to Jaeger
NA
> [ENH] Add otel support for query and compaction service

- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/compactor/scheduler.rs
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/merge_knn_results.rs
- rust/worker/src/execution/operators/pull_log.rs
- rust/worker/src/execution/operators/register.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/log/log.rs
- Currently, we commit the log position for a collection in both sysdb and log service. The commit to the sysdb must be successful for the files visible to query nodes. The commit to offset is best effort and can be behind in case of failures happening in between the commit to sysdb and to the log service. 
- The log position committed in the log service is used to by compactor to figure out what which collections has new data that needs to be compacted the offsets for the new logs. Since the log position in the log service can be lagged and we need to use the log position in sysdb when fetching from the log during compaction. 
- This PR compares the log position in sysdb and log and use the larger one of the 2. An …
> [ENH] Use log position from sysdb to as the offset to pull from log

- .github/workflows/release-javascript-client.yml
https://github.com/npm/cli/issues/6184
This was removed in #2092. Needs to be added back
> [BUG] Update release-javascript-client.yml with registry URL

- rust/worker/src/execution/operators/brute_force_knn.rs
- This PR explicitly skips deleted records from the log data chunk. 
- ...
> [ENH] BF KNN operator skip deleted records from the log data chunk

- chromadb/segment/impl/vector/grpc_segment.py
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/execution/dispatcher.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/worker_thread.rs
- rust/worker/src/log/log.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- rust/worker/src/server.rs
- rust/worker/src/system/scheduler.rs
- rust/worker/src/system/system.rs
- rust/worker/src/system/types.rs
- rust/worker/src/tracing/mod.rs
- rust/worker/src/tracing/opentelemetry_config.rs
- rust/worker/src/tracing/util.rs
FE passed span and trace id are used as parent for the first span of query service (or compaction service). Rust services also propagate the span and trace id to the sysdb and log service whenever they communicate with it. 
[+ ] Tests pass locally with `pytest` for python, `yarn test` for js, `cargo test` for rust
NA
> [ENH] Connect spans of rust worker services with FE

- rust/worker/src/blockstore/key.rs
- rust/worker/src/blockstore/memory/provider.rs
- rust/worker/src/blockstore/memory/reader_writer.rs
- rust/worker/src/blockstore/memory/storage.rs
- rust/worker/src/blockstore/provider.rs
- rust/worker/src/blockstore/types.rs
- Add Prefix, LT, LTE, GT, and GTE queries to the hashmap blockfile. This required changing a couple of the blockfile API contracts as we discussed (removing references in favor of returning values directly)
> [ENH] Prefix, LT, LTE, GT, GTE queries in hashmap blockfile

- chromadb/segment/__init__.py
- chromadb/segment/impl/manager/distributed.py
- chromadb/segment/impl/metadata/grpc_segment.py
- go/cmd/coordinator/cmd.go
- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/merge_metadata_results.rs
- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/execution/orchestration/metadata.rs
- rust/worker/src/execution/orchestration/mod.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/server.rs
- rust/worker/src/types/record.rs
- rust/worker/src/types/segment.rs
Replaces #2075 for merge conflict reasons :) 
- Fixes a bug in grpc metadata stub that does not pass None for where/where_document
New functionality
- Adds the rust server bindings for metadata reader
- Adds the metadata query orchestrator. For now this only handles get by ids (query_ids) it does not handle where/where_document and will error if requested.
Todo before we merge this
Todo after
None
> [ENH] Add rust metadata grpc reader

- rust/worker/src/index/hnsw.rs
- rust/worker/src/index/types.rs
- This plumbs the delete() function through to hnsw to mark offset ids as deleted
- This enables delete completely from rust
Added a test for delete that ensures we can't get back a deleted result. 
None
> [ENH] rust hnsw index delete plumbing

- rust/worker/src/blockstore/memory/provider.rs
- rust/worker/src/blockstore/memory/reader_writer.rs
- rust/worker/src/blockstore/memory/storage.rs
- rust/worker/src/blockstore/types.rs
- Renamed HashMapBlockfileWriter to "Memory" to align with writer
- Adds delete() in memory blockfiles
A new basic test was added for delete for one type
None
> [ENH] Memory blockfile delete

- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/blockstore/types.rs
- Forwards deletes to the appropriate block delta for the arrow blockfile
- This enables deletes by using essentially just enabling existing logic.
Added a basic test
Noen
> [ENH] Arrow bf deletes

- .github/workflows/release-chromadb.yml
- now we allow tests and dev builds to continue even if tag is not a release one
> [BLD] Py release WF now returns tag_matches=false instead of failure

- rust/worker/src/execution/operators/hnsw_knn.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/server.rs
- This PR pass the allowed ids and disallowed ids to HNSW KNN operator. 
- ...
> [ENH] Pass in allow ids and disallow ids to HNSW KNN operator

- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/blockstore/types.rs
- rust/worker/src/execution/operators/count_records.rs
- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/execution/orchestration/metadata.rs
- rust/worker/src/server.rs
Introduces the orchestrator for count and a basic counting logic where we simply add the number of log records with the number of records in the blockfile. More advanced merging like deduping adds and updates and removing deletes will be a different PR.
None
> [ENH] Add orchestration for count

- rust/worker/src/blockstore/arrow/blockfile.rs
- Locks the BF writer for write operations since we need to make these properly thread safe
- None
None
> [BUG] Lock BF writer

- chromadb/test/distributed/test_sanity.py
- Adds a sanity test which includes=[] the defaults and delays for compaction. The hardcoding of the compaction delay isn't ideal since its implicit across services. This is fine for now but when we standardize config this service could introspect it.
- None
> [TST] Add sanity test which includes defaults and delays for compaction

- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/blockstore/memory/reader_writer.rs
- rust/worker/src/blockstore/memory/storage.rs
- rust/worker/src/blockstore/types.rs
- rust/worker/src/execution/operators/count_records.rs
- rust/worker/src/execution/orchestration/metadata.rs
- rust/worker/src/segment/mod.rs
- rust/worker/src/segment/record_segment.rs
Updates, deletes and duplicate adds are handled for the count API in this PR.
None
> [ENH] Handle deletes and updates for count API

- rust/worker/src/execution/operators/count_records.rs
- Count should handle uninit'ed segments
- None
#2185 should add tests for the count() operator
None
> [BUG] Count should handle uninit'ed segments

- chromadb/segment/impl/metadata/grpc_segment.py
- rust/worker/src/execution/operators/count_records.rs
- rust/worker/src/execution/operators/merge_metadata_results.rs
- rust/worker/src/server.rs
- Metadata merge should handle uninit'ed record segments by not reading the segment.
- Add tracing on demand for debugging in metadata reader
- None
None
> [BUG] Metadata should be handle uninit'ed record segment.

- rust/worker/src/execution/orchestration/metadata.rs
Metadata query orchestrators were pulling logs including the last compacted offset. PR fixes that
None
None
> [BUG] Metadata query orchestrators were pulling logs including the last compacted offset

- rust/worker/src/execution/operators/hnsw_knn.rs
- This PR adds specific error for allow id set and disallow id set overlap. 
- ...
> [ENH] Use specifc error for allow id set and disallow id set overlap

- Cargo.lock
- rust/worker/src/blockstore/arrow/block/delta.rs
- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/blockstore/arrow/provider.rs
- rust/worker/src/blockstore/provider.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/index/hnsw_provider.rs
- rust/worker/src/storage/mod.rs
- Unbox storage. Storage is a String and an Arc'ed type in the case of the s3 storage impl. This does not need to be Box'ed. This was previously implemented this way for dynamic dispatch (ala Box<dyn Storage>) to match Box<dyn Log> and Box<dyn Sysdb>. However we now favor enums over dyn for these cases. We should go change those sites as well. 
- The string in the storage struct will be copied. We may want to introduce https://github.com/xfbs/imstr or similar in the future for these sorts of cases. However for this case, it is overkill. 
- None
Existing tests. This is a non-functional change.
*Are all docstrings for user-facing APIs updated if required? Do we need to …
> [ENH] Unbox storage

- README.md
We broke our tests out and there isn't a good single workflow to pin them on
- ...
- ...
> [DOC] remove test labels from readme since we broke them out

- rust/worker/src/execution/dispatcher.rs
- rust/worker/src/execution/operator.rs
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/flush_s3.rs
- rust/worker/src/execution/operators/hnsw_knn.rs
- rust/worker/src/execution/operators/merge_knn_results.rs
- rust/worker/src/execution/operators/merge_metadata_results.rs
- rust/worker/src/execution/operators/partition.rs
- rust/worker/src/execution/operators/pull_log.rs
- rust/worker/src/execution/operators/register.rs
- rust/worker/src/execution/operators/write_segments.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/orchestration/metadata.rs
- Cleans up Result aliases in the operator since they are clunky and not enforced to follow. Verbose TaskResult<> is preferred.
- This adds a task id to tasks sent to the dispatcher. The task id is sent back in a new TaskResult<> which wraps a Result<> and an id
A test was modified in dispatcher.rs to ensure the ids are sent and received.  
None
> [ENH] Add task id to dispatcher/worker

- rust/worker/src/blockstore/arrow/block/bool_key.rs
- rust/worker/src/blockstore/arrow/block/delta_storage.rs
- rust/worker/src/blockstore/arrow/block/mod.rs
- rust/worker/src/blockstore/memory/mod.rs
- rust/worker/src/blockstore/memory/storage.rs
- rust/worker/src/blockstore/mod.rs
- rust/worker/src/blockstore/types.rs
- rust/worker/src/index/fulltext/types.rs
- rust/worker/src/index/metadata/types.rs
- rust/worker/src/index/mod.rs
- Migrate metadata indices to reader/writer pattern.
- This required adding bool keys to the arrow blockfile, and bool+f32 keys to the memory blockfile
> [ENH] Refactor metadata indices to reader/writer

- chromadb/test/distributed/test_sanity.py
- rust/worker/src/execution/orchestration/hnsw.rs
- Update test_sanity to excercise n > 1 queries.
- This makes the hsnw query orchestrator able to respond to multiple queries, as the contract for it expects.
Updated test_sanity
None
> [ENH] support multiple queries in rust vectorreader

- rust/worker/src/index/metadata/types.rs
- Refactor metadata reader and writer to use enum dispatch over possible types instead of generics
> [ENH] Use enum dispatch in metadata reader and writer

- Tiltfile
- chromadb/segment/impl/distributed/segment_directory.py
- chromadb/test/segment/distributed/test_memberlist_provider.py
- go/pkg/memberlist_manager/memberlist_manager.go
- go/pkg/memberlist_manager/memberlist_manager_test.go
- go/pkg/memberlist_manager/memberlist_store.go
- go/pkg/memberlist_manager/node_watcher.go
- k8s/distributed-chroma/crds/memberlist_crd.yaml
- k8s/distributed-chroma/templates/compaction-service.yaml
- k8s/distributed-chroma/templates/query-service.yaml
- rust/worker/chroma_config.yaml
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/compactor/scheduler.rs
- rust/worker/src/config.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- This PR makes the following changes:
- The SysDb now publishes the pod name instead of the pod IP in the memberlist.
- The compaction and query services are using a Statefulset instead of Deployment to reduce assignment shuffle. 
- Removed the pattern check in the memberlist CRD that only allow valid IPs. 
- Change the compaction and query services configuration from my_ip to my_member_id. 
- ...
> [ENH] Use statefulset for query and compaction services

- rust/worker/src/blockstore/arrow/blockfile.rs
Consider the following scenario - 
1. Block has keys {4, 5, 6, 7} 
2. We want to insert key 2
3. Block is full so it needs to split
4. Split in the middle => block1: {4, 5}, block2: {6, 7}
5. [BUG] We insert the new key (i.e. 2) into the new block ALWAYS (i.e. here block2)
6. After insertion blocks are: block1: {4, 5}, block2: {2, 6, 7}
7. All the keys in Block1 are no longer < Keys in Block2 and we have an invariance violation thus a correctness issue!
Fix is to NOT ALWAYS insert the key into the new block but rather insert it into the block which fits in the range i.e. here in Block1.
Added a unit test
None
> [BUG] Fix bug with blockfile split

- .github/workflows/_python-tests.yml
- chromadb/test/conftest.py
- chromadb/test/distributed/test_sanity.py
- chromadb/test/property/test_add.py
- Moves some distributed test consts into conftest so its shared across tests
- enables test_add
- None
This enables tests
None
> [TST] Enable test_add in distributed tests

- go/pkg/memberlist_manager/memberlist_manager_test.go
-  This PR increases the number of retry to 30 to reduce memberlist test flakyness.
- ...
> [TST] Increase the number of retry to 30 to reduce memberlist test flakyness

- idl/chromadb/proto/chroma.proto
- rust/worker/src/types/metadata.rs
- Rust types for Where and WhereDocument queries.
> [ENH] Rust types for metadata queries

- rust/worker/src/log/log.rs
- This PR fixes the issue when the endtimestamp is not set, the log service returns empty records. 
- ...
> [BUG] LogService return empty records when endtimestamp is None

- rust/worker/src/blockstore/arrow/block/data_record_value.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/execution/operators/count_records.rs
- rust/worker/src/execution/operators/write_segments.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/segment/types.rs
- rust/worker/src/types/metadata.rs
Adds log materializer v2 taking care of updates/deletes/upserts.
Wires the compactor (i.e. record segment writer and hnsw index writer) to use the new materialization
Cleans up the old needless abstraction
Rust test
None
> [ENH] Add log materializer v2 taking care of updates/deletes/upserts + wire compactor to use it + clean up old abstraction

- rust/worker/src/execution/operators/brute_force_metadata_filtering.rs
- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/index/fulltext/types.rs
- rust/worker/src/index/metadata/types.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/types.rs
- rust/worker/src/types/metadata.rs
Introduces an operator that takes the where and where_document clauses and returns a list of offset ids of the log that match the conditions. Note wiring it into the orchestrator is a bit more work and will be a separate PR
None
> [ENH] Brute force metadata filtering operator

- chromadb/segment/__init__.py
- chromadb/segment/impl/manager/distributed.py
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/execution/operators/brute_force_metadata_filtering.rs
- rust/worker/src/execution/operators/count_records.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/orchestration/metadata.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/segment/types.rs
- rust/worker/src/types/segment.rs
- Renames the blockfile record segment to be more specific. The current name doesn't allow for multiple types in the name path.
- None
None required
> [CLN] Rename blockfile record segment appropriately

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/src/blockstore/arrow/concurrency_test.rs
- rust/worker/src/blockstore/arrow/mod.rs
- Adds a [shuttle](https://github.com/awslabs/shuttle) concurrency test of the blockfile writer.
- None
None
> [TST] Shuttle concurrency test of blockfile

- rust/worker/src/blockstore/arrow/concurrency_test.rs
- Uses shuttle rng for the test in #2271 for more exhaustive + determinstic testing.
- None
None
> [TST] Add shuttle rng

- rust/worker/src/blockstore/positional_posting_list_value.rs
- rust/worker/src/index/fulltext/types.rs
- rust/worker/src/index/metadata/types.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/types.rs
- Updates and deletes for metadata and fulltext indices. This required plumbing readers into the indices so they could read old values -- as a side effect, this fixed a bug where we weren't correctly updating compacted values before.
- I would like to test this better but doing so requires the MemoryBlockfileProvider implementing `fork()`, which is a pretty nontrivial amount of work. It should be done as a fast-follow
> [ENH] Metadata and full-text updates and deletes

- chromadb/api/fastapi.py
- chromadb/api/models/Collection.py
- chromadb/api/segment.py
- chromadb/server/fastapi/__init__.py
- clients/js/test/collection.client.test.ts
- This is cleanup borrowed from #1491. It makes Collection.py wrap a model instead of duplicating data into collection.py and implictly treating it as a serializable model. This is a cleaner seperation of concerns. We have the model object, and an API wrapper used to manipulate it via the api. 
- None
> [CLN] Make collection api object wrap model.

- .github/workflows/_python-tests.yml
- .github/workflows/pr.yml
- .github/workflows/release-chromadb.yml
- chromadb/test/conftest.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/property/test_persist.py
Adds property testing "presets": fast, normal, slow (in order of increasing correctness guarantees).
PR checks run under the fast profile and checks before release run under the normal profile.
In the future, we could periodically run the slow profile against `main`.
> [BLD] add hypothesis profiles

- chromadb/api/__init__.py
- chromadb/api/client.py
- chromadb/api/fastapi.py
- chromadb/api/segment.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/property/test_add.py
- chromadb/test/test_api.py
- chromadb/utils/batch_utils.py
- docs/docs.trychroma.com/pages/deployment/migration.md
- docs/docs.trychroma.com/pages/reference/py-client.md
This is needed for https://github.com/chroma-core/chroma/pull/2297 as there doesn't seem to be a good way to automatically detect async properties (when converting a set of async class methods to a synchronous version). Having a property that makes a HTTP request is kinda an antipattern regardless.
This is a breaking change. I will prepare a PR for the docs as well.
> [ENH] max_batch_size -> get_max_batch_size()

- .github/workflows/_python-tests.yml
- For workflows that matrix over multiple tests, we want to not fail fast since it reduces information / time for developers in their CI loop.
- None
None
> [TST] Don't fail fast when we matrix over tests

- .github/workflows/pr.yml
E.x. https://github.com/chroma-core/chroma/pull/2314 only changed docs, so Python tests won't run. But current branch protection rules require Python tests to pass before merging, so merging is blocked.
> [BLD] add workflow job for branch protection

- chromadb/api/segment.py
- chromadb/test/property/test_filtering.py
- rust/worker/src/blockstore/arrow/block/types.rs
- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/blockstore/memory/reader_writer.rs
- rust/worker/src/blockstore/types.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/flush_s3.rs
- rust/worker/src/execution/operators/hnsw_knn.rs
- rust/worker/src/execution/operators/merge_metadata_results.rs
- rust/worker/src/execution/operators/metadata_filtering.rs
- rust/worker/src/execution/operators/write_segments.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/orchestration/metadata.rs
- rust/worker/src/index/fulltext/tokenizer.rs
- rust/worker/src/index/fulltext/types.rs
- rust/worker/src/index/metadata/types.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/record_segment.rs
This PR has a bunch of fixes and improvements to make queries and gets with metadata and full text filtering work. Among these are:
1. Wire in the compactor to also write to metadata segment. This was non trivial and involved changes like making the lifetime of the metadata segment writer in WriteSegmentsOutput and FlushS3Input 'static, introduce tokio::sync::mutex for holding mutexes even when yielding due to an async call, etc
2. Make where clause parsing async - it was incorrectly using futures::executor::block_on. There is no need to keep it sync, I made the recursive function async.
3. Full text search creates n gram tokenizer with wrong parameters - The min and max were incorrectly set. Due to this the search result …
> [ENH] Towards enabling test_filtering

- chromadb/test/distributed/test_sanity.py
- Make test_sanity skip if not cluster
- None
None
> [TST] Make test_sanity skip if not cluster

- .github/workflows/release-javascript-client.yml
- clients/js/package.json
- clients/js/src/ChromaFetch.ts
- docker-compose.test.yml
- JS version bump to `1.9.1`
- Made the error handling more robust for offline errors (works with older Nodejs 16)
- Fixed an issue with test docker-compose file where the port was not being correctly mapped, thus making the release WF tests fail
N/A
> [BLD]: JS client 1.9.1-alpha release

- rust/worker/bindings.cpp
- rust/worker/src/index/hnsw.rs
- rust/worker/src/index/types.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
- Makes distributed hnsw segment resize the index with exclusive Write lock
- Expose resize() so that the hnsw index can be resized as it grows
- bump allocate the segment by 2x
Added a test for resize in the index
None
> [ENH] Add hnsw resize

- docs/docs.trychroma.com/pages/deployment/observability.md
- docs/docs.trychroma.com/pages/integrations/index.md
- docs/docs.trychroma.com/pages/integrations/openlit.md
- This PR adds documentation/integration for OpenLIT which provides OpenTelemetry auto-instrumentation for Chroma (one of the 18 intgerations in the LLM stack)
This is solely a documentation update
> [DOC]: Add OpenLIT to Docs as Integration

- rust/worker/src/lib.rs
- rust/worker/src/server.rs
- This PR adds a graceful shutdown to the tonic GRPC server with serve_with_shutdown method. We pass in a future that captures the sigterm and starts the graceful shutdown process. 
- The behavior of the tonic server graceful shutdown process is as follows: upon receiving the shutdown signal, the server transitions from the "Running" state to the "Draining" state. In this state, the server stops accepting new requests or connections, effectively making it read-only concerning new external interactions. While in the "Draining" state, the server focuses on allowing existing connections and ongoing tasks to be completed gracefully. 
- The above behavior has been verified by code reading and a simple prototype with an RPC …
> [ENH] Add graceful shutdown to tonic server

- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/compactor/scheduler.rs
- rust/worker/src/execution/operators/register.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/orchestration/metadata.rs
- rust/worker/src/server.rs
- rust/worker/src/sysdb/mod.rs
- rust/worker/src/sysdb/sysdb.rs
- rust/worker/src/sysdb/test_sysdb.rs
- Makes sysdb an enum not dyn. We perfer an enum to dyn where the number of impls is fairly bounded - in this case 2 - the real one and a mock.
- None
Existing tests - this is a non-functional refactor.
> [CLN] Make sysdb use enum not dyn

- clients/python/pyproject.toml
- clients/python/requirements.txt
- pyproject.toml
- requirements.txt
- Numpy 2.0 has some type changes which break our code. This was flagged by @itayB in #2352 (Thank you!). We need to extend that PR a bit to include other requirements for the thin client, as well as the pyproject.toml.
- Note: We could fix these type issues but Onnxruntime does not yet support python 2.0 - which we depend on (https://github.com/microsoft/onnxruntime/issues/21063)
- None
We may want to update our docs? I am not sure what makes sense here - input solicited.
> [BUG] Lock numpy to < 2.0.0 across all reqs and pyproject.toml

- rust/worker/src/execution/operators/get_vectors_operator.rs
- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/execution/orchestration/common.rs
- rust/worker/src/execution/orchestration/get_vectors.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/orchestration/mod.rs
- rust/worker/src/server.rs
- rust/worker/src/system/sender.rs
- rust/worker/src/types/record.rs
This PR adds the Get Vectors() RPC for query nodes.
1. Adds the GetVectors instrumented rpc call and associated types
2. Adds a GetVectorsOrchestrator for managing these queries
3. Adds the GetVectorsOperator for reading from the log and record segment to respond to get_vectors
4. Moves common orchestrator functions into a /common and refactors hnsw orchestrator to use this instead (DRY)
5. Adds the `ChromaError` Trait for ChannelError in Sender - needed to use that as Box<dyn ChromaError> elsewhere.
I explicitly make the choice to not have to materialize in this operator since it doesn't need to for any reason.
Tasks
> [ENH] Get vectors orchestrator

- docs/docs.trychroma.com/pages/integrations/_sidenav.js
OpenLIT integration reference was not added to the sidenav in the [previous PR](https://github.com/chroma-core/chroma/pull/2249). This fixes by adding the OpenLIT SDK to the sidenav
> [DOC]: Fix missing OpenLIT reference in Integration sidenav

- rust/worker/src/segment/types.rs
If the log contains Add entries that are invalid and there are no further Updates/Deletes to this id then materializer should not contain this entry at all.
None
> [BUG] Mat logs should not populate invalid Adds

- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/count_records.rs
- rust/worker/src/execution/operators/merge_metadata_results.rs
- rust/worker/src/execution/operators/metadata_filtering.rs
- rust/worker/src/execution/operators/write_segments.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/segment/types.rs
Readers can pass None for the current offset id when materializing and the materializer takes care of using the correct value by reading from the record segment. Writers still need to pass it in since it is shared by writers of different partitions.
None
> [CLN] Refactor log materializer to not need to pass in offset id explicitly for readers

- chromadb/proto/convert.py
- chromadb/test/property/test_embeddings.py
- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/blockstore/positional_posting_list_value.rs
- rust/worker/src/execution/operators/merge_metadata_results.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/index/fulltext/types.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/segment/types.rs
- rust/worker/src/types/metadata.rs
- Handles metadata deletes
- Full text writer adds (token, freq) pair even if freq is 0. Fixes this.
- Full text writer does not remove postings list of documents that have been deleted. Fixes this.
- Fix for test_query_without_add
None
> [ENH] Handle metadata deletes + fix bugs related to Updates/deletes in the metadata writer

- .github/workflows/release-javascript-client.yml
- Adding a step to update package.json org scope to allow publishing the release JS package to GH
Tested with dev release workflow
> [BLD] Fix for JS package in GH

- .github/workflows/_python-tests.yml
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/get_vectors_operator.rs
- rust/worker/src/execution/orchestration/get_vectors.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- Fixes get_vectors brute force add and update logic to account for uninitialized segment
- Fixes get_vectors brute force update logic to also account for adds that happened in the log and not in the segment
- Fixes get_vectors to return ids and embeddings in the same order as the input search ids. This is necessary since the FE relies on this
- Fixes get_vectors to also get triggered on updates/deletes of records that were added in the log itself
- Enables test_embeddings for cluster integration tests
None
> [ENH] Enable test_embeddings

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/src/execution/operators/metadata_filtering.rs
Rust Brute force metadata filtering does not account for % and _ in full text search. In single node, sqlite matches any character for these two. Fix replaces % and _ with . and performs a regex search now.
None
> [ENH] Emulate sqlite fts in brute force metadata filtering

- chromadb/api/__init__.py
- chromadb/api/async_fastapi.py
- chromadb/api/fastapi.py
Closes #2377 #2379
- Making dimension and version lookup optional in the Collection model creation in fastapi client
N/A
> [BUG]: Fix cross version compatibility 0.5.0 or lower with 0.5.1+

- chromadb/db/system.py
Fix a typo in comment section in chromadb/db/system.py
```
"""
Create a new collection any (-> and) associated resources
in the SysDB.
"""
```
Do not need test
Not public facing API documentation change.
> [DOC]: Fix a typo in comment section in chromadb/db/system.py

- docs/docs.trychroma.com/pages/deployment/migration.md
- docs/docs.trychroma.com/pages/getting-started.md
Updates docs to:
* adds a link Github issues on the migrations page
* updates the discord invite link (seems the other one expired)
previewed the markdown locally and links worked.
n/a didn't update these
> [DOC] fix: add github link and update discord invite link

- .github/workflows/_go-tests.yml
- .github/workflows/_javascript-client-tests.yml
- .github/workflows/_python-tests.yml
- .github/workflows/_rust-tests.yml
- .github/workflows/pr.yml
Extracted from https://github.com/chroma-core/chroma/pull/2393 as a more incremental change.
Depot is half the cost and generally faster as well.
> [BLD] use Depot

- chromadb/test/property/invariants.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/property/test_filtering.py
- chromadb/test/property/test_persist.py
- chromadb/test/utils/wait_for_version_increase.py
The primary intent of this PR is to remove the is_metadata_valid invariant which was a workaround for our metadata strategy generating faulty metadata and then us special casing all uses of the record set strategy to handle invalid generations. This PR patches the metadata generation to not generate invalid metadata.
- Adds modes in test_add to add a medium sized record set. This was initially timing out in hypothesis's generation. Hypothesis bounds the buffer size of the bytes it uses to do random generation, so generating larger metadata was resulting in examples being marked at OVERRUN by conjecture (gleaned from issues like https://github.com/HypothesisWorks/hypothesis/issues/3999 + reading hypothesis code + stepping through it). This PR adds …
> [TST] Property Test Generation Fixes

- rust/worker/src/blockstore/positional_posting_list_value.rs
- Uses binary search in PPL since entries are ordered, on a dataset of 1107 posting lists with ~450,000 doc ids, the aggregate time spent inserting was taking ~100 seconds. This reduces it to .01 seconds. :) 
- none
None
> [PERF] Use binary search in positional posting list

- chromadb/api/async_fastapi.py
- chromadb/api/fastapi.py
> [PERF] Use orjson in client

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/chroma_config.yaml
- rust/worker/src/blockstore/arrow/block/delta.rs
- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/blockstore/arrow/concurrency_test.rs
- rust/worker/src/blockstore/arrow/config.rs
- rust/worker/src/blockstore/arrow/mod.rs
- rust/worker/src/blockstore/arrow/provider.rs
- rust/worker/src/blockstore/arrow/sparse_index.rs
- rust/worker/src/blockstore/config.rs
- rust/worker/src/blockstore/memory/provider.rs
- rust/worker/src/blockstore/mod.rs
- rust/worker/src/blockstore/provider.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/config.rs
- rust/worker/src/execution/operators/merge_metadata_results.rs
- rust/worker/src/execution/operators/metadata_filtering.rs
- rust/worker/src/segment/types.rs
- rust/worker/src/server.rs
- rust/worker/src/storage/config.rs
- Makes the block size configurable, leaving default the same as before.
- Add Blockfile provider config, removing a todo 
- Runs config tests in serial, since they can race
- None really
Existing tests, this is a non-functional change
None
> [ENH] Configurable block size

- go/database/log/db/queries.sql.go
- go/database/log/queries/queries.sql
- go/database/log/schema/collection.sql
- go/pkg/log/server/property_test.go
- When revamping the prop tests in #1969 I noticed that the purge code was off by one - this remedies that.
- None
The tests TODO is updated with the correct behavior
None
> [BUG] Log purge off by one

- rust/worker/src/system/system.rs
- rust/worker/src/system/types.rs
It was previously panicking because "there should be no other strong references to the join handle" is not actually a valid assumption as `ConsumableJoinHandle` is clonable.
> [BUG] fix consumable join handle panicking after clone

- rust/worker/src/execution/orchestration/common.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/execution/orchestration/get_vectors.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/orchestration/metadata.rs
Broadly a TODO cleanup PR
- Makes compaction reply with errors
- Abstracted out terminate_with_error since its heavily duplicated
- Trace where it made sense
- NOTE: I left one or two log sites alone, as well as all dispatcher.sends() as I am not sure what to do with these and that is additive.
- None
> [ENH] Compaction error replies

- chromadb/test/property/test_embeddings.py
- Before https://github.com/chroma-core/hnswlib/pull/17 - hnswlib did not support persisting a single record, this test exercises that case. This is possible since you can bypass min_compaction_size by adding and deleting many of the same records. 
- None
None
> [BUG] Allow hnswlinb to single record persist test

- rust/worker/src/segment/metadata_segment.rs
- Addresses the scenario when a metadata key has a value of type string for e.g. and user updates the same key to a value of some other type for e.g. float
- Makes apply_materialized_log_chunk for metadata segment a bit more robust: panicking in cases when it should and returning proper errors at other times
- Adds tests for metadata updates and deletes and document updates
Added unit test
None
> [ENH] Support metadata update to value of different type

- .github/workflows/_python-tests.yml
- bin/get-logs.sh
- chromadb/test/property/test_add.py
- Upload service logs as artifacts in github actions for cluster tests
None
> [BLD] Service logs as artifacts

- .github/workflows/release-chromadb.yml
- chromadb/auth/__init__.py
- chromadb/auth/basic_authn/__init__.py
- chromadb/auth/token_authn/__init__.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/auth/test_base_class_behavior.py
- chromadb/utils/embedding_functions/onnx_mini_lm_l6_v2.py
Closes #2459
- Fixed imports for onnxruntime and auth module to avoid import failures for the thin client
> [BUG]: Thin client imports

- rust/worker/chroma_config.yaml
- rust/worker/src/storage/s3.rs
- Tests can timeout when the s3 flush takes long. For blockfile we expect small timeouts to be ok, but for HNSW segments in test of a reasonable size, it can still be slow. I picked 60 seconds as the S3 timeout as that is ~6GB / 180 MB/s * 2. 
- None
None
> [CLN] Increasing timeouts && S3 storage error tracing

- chromadb/segment/impl/distributed/segment_directory.py
- chromadb/test/conftest.py
- chromadb/test/distributed/test_sanity.py
- go/cmd/coordinator/cmd.go
Objective of this PR is making CI faster by reducing waiting time to the minimal required time
- Change go memberlist reconcilation to be higher frequency
- Change the memberlist reset() logic in frontend to use a threading event to only wait until the ML is updated
- Now waits for ~0.3 seconds instead of 5
- None
These changes are covered by existing tests.
None
> [CLN] Make memberlist reset() not wait longer than it needs to

- chromadb/api/__init__.py
- chromadb/api/async_api.py
- chromadb/api/async_client.py
- chromadb/api/async_fastapi.py
- chromadb/api/client.py
- chromadb/api/fastapi.py
- chromadb/api/segment.py
- chromadb/server/fastapi/__init__.py
- chromadb/telemetry/product/events.py
- chromadb/test/auth/rbac_test_executors.py
- chromadb/test/conftest.py
- chromadb/test/data_loader/test_data_loader.py
- chromadb/test/distributed/test_sanity.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_collections.py
- chromadb/test/property/test_collections_with_database_tenant.py
- chromadb/test/property/test_collections_with_database_tenant_overwrite.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/property/test_filtering.py
- chromadb/test/property/test_persist.py
- chromadb/test/stress/test_many_collections.py
- chromadb/test/test_api.py
- chromadb/test/test_logservice.py
- chromadb/test/test_multithreaded.py
- chromadb/test/utils/wait_for_version_increase.py
This PR refactors the `ServerAPI` classes so that their methods only return the `Collection` model, not the `Collection` object itself, i.e. the view on the data.
This is a much cleaner separation of concerns than we had before, and should enable faster iteration in parts. For example, the ServerAPI no longer needs to know about EmbeddingFunction or DataLoader etc - these only exist for Clients. 
We will probably re-add them when we start moving some of that functionality server-side for cloud, but for now this is a fine solution. 
Most the LoC in this PR are changing tests to use the ClientAPI and fixture instead of the ServerAPI and fixture. This does put the client in the line, but I think this is fine. 
Tests pass in CI. 
N/A
> [CLN] ServerAPI to use Collection model

- chromadb/api/segment.py
- chromadb/db/impl/grpc/client.py
- go/pkg/coordinator/apis.go
- go/pkg/coordinator/apis_test.go
- go/pkg/coordinator/grpc/collection_service.go
- go/pkg/metastore/catalog.go
- go/pkg/metastore/coordinator/table_catalog.go
- go/pkg/metastore/coordinator/table_catalog_test.go
- In #1835 the sysdb client in python was made to not respect the `created` flag. This fixes the python code to do that, as well as updates the go code to appropriately return that flag. 
- None
Added a test in the go side to check that created is false when get_or_create'ing a collection that already exists
None
> [BUG] Make go sysdb return created flag. Respect created flag

- chromadb/segment/impl/distributed/segment_directory.py
- #2473 introduced a change to wait less, this flaps for some reason. In the interest of speeding up the test but not wasting time on debugging this as its only a test harness related change, just sleep to let the ML converge.
- ...
> [TST] ML sleep

- rust/worker/src/execution/dispatcher.rs
- rust/worker/src/execution/operator.rs
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/count_records.rs
- rust/worker/src/execution/operators/flush_s3.rs
- rust/worker/src/execution/operators/get_vectors_operator.rs
- rust/worker/src/execution/operators/hnsw_knn.rs
- rust/worker/src/execution/operators/merge_knn_results.rs
- rust/worker/src/execution/operators/merge_metadata_results.rs
- rust/worker/src/execution/operators/metadata_filtering.rs
- rust/worker/src/execution/operators/normalize_vectors.rs
- rust/worker/src/execution/operators/partition.rs
- rust/worker/src/execution/operators/pull_log.rs
- rust/worker/src/execution/operators/register.rs
- rust/worker/src/execution/operators/write_segments.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/worker_thread.rs
- rust/worker/src/segment/types.rs
- rust/worker/src/server.rs
- Auto trace all operators by name
- Add materialize logs instrumentation span where called
- Add count event for pull logs inside operator
- None
> [CHORE] Add tracing for task names, materialize logs tracing, and pull logs count

- rust/worker/src/system/receiver.rs
- rust/worker/src/system/system.rs
- rust/worker/src/system/types.rs
- rust/worker/src/system/wrapped_message.rs
Panics inside component handlers are now caught and propagated to the caller if they used `.request()`. Otherwise, the panic is silently ignored (besides being recorded by the existing tracing hook).
See new test for how this works.
> [ENH] catch panics in handlers

- rust/worker/src/blockstore/arrow/blockfile.rs
- Adds some tracing to reading block from cache/storage
- Adds some tracing to read from the block itself
- None
None
> [CHORE] Add tracing to blockfile gets

- chromadb/db/mixins/embeddings_queue.py
- chromadb/segment/impl/metadata/sqlite.py
- chromadb/segment/impl/vector/batch.py
- chromadb/segment/impl/vector/brute_force_index.py
- chromadb/segment/impl/vector/local_hnsw.py
- chromadb/segment/impl/vector/local_persistent_hnsw.py
- chromadb/test/ingest/test_producer_consumer.py
- Fixes a typed dict related mypy error where we propagated an incorrect name
- Fixes other or ignores other type errors
- none
Existing tests
None
> [CLN] LogRecord TypedDict attr name incorrect

- chromadb/auth/basic_authn/__init__.py
- chromadb/auth/token_authn/__init__.py
- chromadb/errors.py
- Removing dynamic import of FastAPI HTTPException in hot path and replacing it with custom ChromaAuthError handled by exception middleware. This retains the user facing error message and removes the need for dynamic import addressing @HammadB comments 
N/A
> [CLN]: Replacing FastAPI HTTPException with custom ChromaAuthError in basic/token auth

- chromadb/__init__.py
- chromadb/server/fastapi/__init__.py
- chromadb/server/fastapi/types.py
- pyproject.toml
- requirements.txt
- Release 0.5.4
- Pin hnswlib upgrades
- Configuration b/w compat
> [RELEASE] Release 0.5.4. Pin hnswlib upgrade. Configuration b/w compat.

- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/blockstore/arrow/provider.rs
- rust/worker/src/index/hnsw.rs
- rust/worker/src/index/hnsw_provider.rs
- Cleaner tracing for reading blocks
- Cleaner tracing for reading hnsw
- None
None
> [PERF] Better tracing for storage access

- chromadb/test/property/test_cross_version_persist.py
- 0.5.4 release breaks CVP tests because the server API no longer returns the collection object and instead returns a model
- Added a fix for this by special casing the version (no other way really)
- Added BASELINE_VERSIONS to also test 0.5.3 
- None
None
> [BUG] Fix cross version persistence tests after 0.5.4 release

- chromadb/test/conftest.py
Our nightly tests sometimes hit the 6h time limit.
> [BLD] reduce max number of examples on slow prop test preset

- rust/worker/src/blockstore/arrow/provider.rs
- rust/worker/src/index/hnsw_provider.rs
- Minor tracing improvements to print sizes read
- None
None
> [PERF] Trace block read size

- rust/worker/src/blockstore/arrow/block/types.rs
- Copies std lib implementation and modifies for 2 nested level comparisons (prefix and key)
None
> [ENH] Binary search for blockfile get()

- chromadb/segment/impl/vector/local_persistent_hnsw.py
Didn't catch after a refactor in https://github.com/chroma-core/chroma/pull/2499.
This is not a correctness bug, this would have resulted in a persist/flush after every mutation if enough invalid operations had accumulated.
> [BUG] fix invalid operation persist check

- chromadb/test/property/test_embeddings.py
Hoping that this will fix an issue on our nightly tests where the runner seems to crash without giving a reason--often can be due to CPU/memory starvation.
> [ENH] delete collection during teardown of state machine

- Cargo.lock
- go/pkg/log/repository/log.go
- rust/worker/Cargo.toml
- rust/worker/chroma_config.yaml
- rust/worker/src/blockstore/arrow/block/delta.rs
- rust/worker/src/blockstore/arrow/block/mod.rs
- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/blockstore/arrow/concurrency_test.rs
- rust/worker/src/blockstore/arrow/config.rs
- rust/worker/src/blockstore/arrow/flusher.rs
- rust/worker/src/blockstore/arrow/mod.rs
- rust/worker/src/blockstore/arrow/provider.rs
- rust/worker/src/blockstore/arrow/sparse_index.rs
- rust/worker/src/blockstore/mod.rs
- rust/worker/src/blockstore/provider.rs
- rust/worker/src/blockstore/types.rs
- rust/worker/src/cache/cache.rs
- rust/worker/src/cache/config.rs
- rust/worker/src/cache/mod.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/config.rs
- rust/worker/src/execution/operators/merge_metadata_results.rs
- rust/worker/src/execution/operators/metadata_filtering.rs
- rust/worker/src/lib.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/types.rs
- rust/worker/src/server.rs
- rust/worker/src/storage/config.rs
- rust/worker/src/storage/local.rs
- This PR fixes bugs that readers and writers share the cache. The fix is as follows: 1. fork calls get instead of getting data from the read cache 2. commit returns the newly created blocks 3. flush takes the newly created blocks as input. 
- Temporarily disable the shuttle test as there is a compatibility issue between tokio filesystem calls and shuttle runtime. Tokio filesystem call will panic if not wrapped in tokio runtime. 
- This PR introduces cache with eviction policies. Foyer (https://github.com/MrCroxx/foyer) is used as the cache. In the future, Foyer will be used as a hybrid cache. 
- Introduced cache-related configs to be used by different components. 
*Are …
> [ENH] Use foyer for block cache

- rust/worker/src/blockstore/arrow/concurrency_test.rs
- rust/worker/src/blockstore/arrow/provider.rs
- rust/worker/src/index/hnsw_provider.rs
- rust/worker/src/storage/config.rs
- rust/worker/src/storage/mod.rs
- rust/worker/src/storage/s3.rs
- rust/worker/src/storage/stream.rs
- rust/worker/src/storage/sync_local.rs
- The tokio filesystem API will trigger panic if not invoked in the tokio runtime. However, the shuttle concurrency test has its runtime and can not properly run if tokio filesystem APIs are called. 
- To fix the above issue, this PR introduces the stream abstraction to support sync and async local filesystem APIs. 
- ...
> [ENH] Introduce stream abstraction and enable concurrency test for blockfile

- bin/docker_entrypoint.sh
Ref: #1404
- CHROMA_SERVER_NOFILE is not correctly overriden by user env var provided in docker compose or .env file; defaults to 65536 otherwise. 
Manually tested
N/A
> [BUG] CHROMA_SERVER_NOFILE cannot be overriden with env var in container

- chromadb/api/configuration.py
- chromadb/db/mixins/sysdb.py
- chromadb/test/configurations/test_configurations.py
- chromadb/test/property/strategies.py
It doesn't really make sense to have a config where `hnsw:batch_size > hnsw:sync_threshold`, and although (I think) we don't depend on this invariant today we could accidentally depend on it in the future without enforcing it.
> [BUG] fix HNSW param defaults in new configuration logic & require batch_size < sync_threshold

- chromadb/segment/impl/vector/local_persistent_hnsw.py
Resolves issues like https://github.com/chroma-core/chroma/actions/runs/9952798975/job/27494936402 and https://github.com/chroma-core/chroma/actions/runs/9948297218/job/27482628460.
This bug has existed for a while, but was only discovered recently in our property tests because the `max_batch_size` and `max_sync_threshold` parameters were turned down to 10 in `chromadb/test/property/test_persist.py`.
> [BUG]: fix missing record in query result when many records were deleted and pending persist

- rust/worker/chroma_config.yaml
- rust/worker/src/blockstore/arrow/config.rs
- rust/worker/src/blockstore/arrow/provider.rs
- rust/worker/src/config.rs
- Refactored the configuration key `max_block_size_bytes` from `ArrowBlockfileProviderConfig` to `BlockManagerConfig`.
- ...
> [CLN] Move max_block_size_bytes to block_manager_config

- .github/workflows/_javascript-client-tests.yml
- bin/ts-integration-test.sh
- clients/js/package.json
- clients/js/pnpm-lock.yaml
- clients/js/src/embeddings/GoogleGeminiEmbeddingFunction.ts
- clients/js/src/embeddings/OpenAIEmbeddingFunction.ts
- adds a couple required dependencies for running the JS Tests
- switches to using pnpm when running the JS client tests
- adds the .sh extension to the test script
- suppresses a couple of type errors
- N/A
> [TST] Get ts-integration-test.sh script working locally

- chromadb/segment/impl/vector/local_persistent_hnsw.py
@HammadB and I discussed this. Makes it much easier to model the WAL behavior in tests while also simplifying the logic.
> [ENH] simplify logic for when to persist index changes

- chromadb/segment/impl/vector/local_persistent_hnsw.py
Reverts chroma-core/chroma#2539. Appears that this introduced a bug that can occur after client restart. Will add a (currently) failing test and fix in next PR.
> Revert "[ENH] simplify logic for when to persist index changes"

- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/blockstore/arrow/concurrency_test.rs
- This PR enables cache eviction for the concurrency test. 
- ...
> [TST] Enable cache eviction for shuttle concurrency test

- go/pkg/log/repository/log.go
- Traces the error msg in honeycomb/jaeger
None
> [ENH] Add error trace in log service for GetAllCollectionInfoToCompact

- .github/workflows/_python-tests.yml
- bin/get-logs.sh
- Previously, we were not uploading artifacts per python version. Because of this we only retained the logs of the last python version that ran per test.
None
> [BLD] log artifacts per python version

- docs/cip/CIP-07102024_Write_Ahead_Log_Pruning_Vacuuming.md
See https://github.com/chroma-core/chroma/issues/2288.
> [ENH] CIP: Write-Ahead Log Pruning & Vacuuming

- chromadb/server/fastapi/__init__.py
- chromadb/types.py
Closes #2503
Closes #2137
- Support for pydantic 1.x in FastAPI server.
N/A
> [BUG]: Pydantic 1.9+ compatibility

- rust/worker/src/index/hnsw.rs
- If the metadata specifies SOME hsnw params but not all, we should default.
- None
Added a test
None
> [BUG] HNSW Rust params should have defaults

- chromadb/api/base_http_client.py
- chromadb/api/segment.py
- chromadb/errors.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/conftest.py
- chromadb/test/test_api.py
Returns a new `chroma-trace-id` header for both successful and errored responses.
> [ENH] return `chroma-trace-id` header, include trace ID in thrown errors

- chromadb/db/impl/sqlite_pool.py
- chromadb/test/property/invariants.py
- chromadb/test/test_multithreaded.py
- requirements_dev.txt
Closes #1379
- Using weakrefs in pools' `connections` set.
N/A
- https://peps.python.org/pep-0567/
> [ENH] Connection pool FD leak v2

- .github/workflows/_python-tests.yml
- chromadb/db/base.py
- chromadb/db/mixins/embeddings_queue.py
- chromadb/ingest/__init__.py
- chromadb/ingest/impl/utils.py
- chromadb/logservice/logservice.py
- chromadb/segment/impl/metadata/sqlite.py
- chromadb/segment/impl/vector/local_hnsw.py
- chromadb/segment/impl/vector/local_persistent_hnsw.py
- chromadb/test/conftest.py
- chromadb/test/property/invariants.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_clean_log.py
- chromadb/test/property/test_cross_version_persist.py
- clients/python/integration-test.sh
Depends on https://github.com/chroma-core/chroma/pull/2545.
Changes:
- Adds a `clean_log()` method to producers (not called automatically in this PR).
- The existing table `max_seq_id` is now used to track the maximum seen sequence ID for both metadata and vector segments (formerly only used by metadata segments).
- Segments are expected to update the `max_seq_id` table themselves.
- Vector segments will automatically migrate the `max_seq_id` field from the old pickled metadata file source into the database upon init.
In this PR, log entries are deleted on a per-collection basis. The next PR in this stack deletes entries globally.
> [ENH] add `.clean_log()` to Producers

- chromadb/types.py
Reproduction:
```bash
pip install chromadb pydantic==1.10.17
```
```python
import uuid
local_client = chromadb.PersistentClient(path="metadata_casting")
collection = local_client.get_or_create_collection(f"{uuid.uuid4()}",metadata={"string":"string","int":1,"float":1.0,"bool":True})
print(collection.metadata)
```
- Pydantic 1.x uses left_to_right union mode and thus converting all metadata values to str. This PR makes the model attr be a `Dict[str,Any]` to prevent that from happening. The __init__ still uses Metadata type
> [BUG]: Pydantic 1.x Union Types

- rust/worker/src/execution/orchestration/common.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/orchestration/metadata.rs
Propagates nested error messages for get segment errors to make debugging easier.
- see above
n/a
n/a
> [ENH] propogate nested error message

- go/pkg/metastore/db/dao/segment.go
Fixes a nil dereference bug during error handling. Seen under high concurrent load, root cause of the error is unknown but this should help us debug. Also handles query construction/execution errors as recommended by gorm.
- see above
n/a
n/a
> [BUG] fix nil dereference during error log

- rust/worker/src/blockstore/arrow/blockfile.rs
- rust/worker/src/blockstore/arrow/provider.rs
- rust/worker/src/blockstore/arrow/sparse_index.rs
- rust/worker/src/blockstore/types.rs
- rust/worker/src/execution/operators/merge_knn_results.rs
- rust/worker/src/execution/operators/merge_metadata_results.rs
- rust/worker/src/segment/record_segment.rs
- Implement prefetch() API at the blockfile level for a set of blocks and use it to prefetch record segment indexes
None
> [ENH] prefetch APIs for Record segment and blockfile

- rust/worker/src/execution/dispatcher.rs
- rust/worker/src/execution/operator.rs
- rust/worker/src/execution/operators/record_segment_prefetch.rs
- Only prefetch operator is tagged as IO currently. All others are tagged by default as "Other". Chose "other" instead of CPU as the tag name because  these operators do both cpu and io today although we do want to eventually move IO off them.
- Dispatcher spawns IO tasks on the main tokio runtime.
Modified existing rust test
None
> [ENH] Tag operators as IO or other + dispatcher schedules IO tasks on the main runtime

- rust/storage/src/s3.rs
- rust/worker/chroma_config.yaml
We observed that using multipart upload for every object put causes enough overhead to cause test failures in CI with existing timeouts, so this PR will bypass multipart upload if the object size is below the part size.
This also bumps the part size to 512MB, as blocks will never be more than 8MB anyways.
covered by existing tests, confirmed that both code paths are tested
n/a
> [ENH]: only use multipart upload if object size > part size

- .github/workflows/nightly-tests.yml
Jobs here were failing because the get-logs.sh script was changed but usage was not updated here.
n/a
n/a
> [BUG]: fix nightly test workflow

- chromadb/cli/cli.py
- chromadb/db/mixins/embeddings_queue.py
- chromadb/ingest/__init__.py
- chromadb/logservice/logservice.py
- chromadb/test/db/test_log_purge.py
- chromadb/test/property/invariants.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/test_cli.py
Fixes a bug where if any collection had dangling logs, any logs created after those by other collections would not get purged.
Also fixes a small, somewhat related bug with `chroma utils vacuum` (see PR comment below).
Added a new regression test that was formerly failing.
n/a
> [BUG] fix multi collection log purge

- rust/worker/src/execution/operators/pull_log.rs
- Move the pulled record count to a structured field so its queryable
- None
this is a non-functional change. I verified that it shows up in jaeger as expected locally.
None
> [CHORE] Move pull log trace record count to structured field

- rust/worker/src/execution/dispatcher.rs
- rust/worker/src/execution/operator.rs
- rust/worker/src/execution/operators/pull_log.rs
- rust/worker/src/execution/operators/record_segment_prefetch.rs
- This moves pull logs to use the IO operator functionality introduced in #2603 
- Renamed IoOperator to IO since its a bit redundant. 
- None
Existing tests cover this change
None
> [PERF] Make pull logs an I/O operator so it runs on main runtime

- k8s/distributed-chroma/templates/compaction-service.yaml
- k8s/distributed-chroma/values.yaml
Allows Helm chart consumers to configure replica count of compaction service.
n/a
n/a
> [ENH]: allow configuring replica count of compaction service

- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/execution/dispatcher.rs
- rust/worker/src/execution/operators/flush_s3.rs
- rust/worker/src/execution/operators/write_segments.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/system/scheduler.rs
Fixes traces for the compaction service so that each scheduled compaction is a root span, rather than everything being in the same span.
Also adds some additional tracing to functions called by the compactor.
Tested locally with Jaeger:
n/a
> [ENH]: fix compactor traces, add additional info to trace

- chromadb/logservice/logservice.py
Adds the record count to the LogService.submit_embeddings span. Useful when debugging.
n/a
> [ENH]: add record count to span when submitting embeddings

- chromadb/api/segment.py
Previous to this change, we emitted 2 spans per embedding for every `/add`, `/upsert`, etc call. This pollutes the traces and contributes to our burst usage on our observability provider during load testing.
Now, one span is emitted per request for embedding validation.
Happy to revise this if there's a better solution.
n/a
> [ENH] fix embedding validation span pollution

- chromadb/db/impl/grpc/client.py
- chromadb/logservice/logservice.py
- chromadb/proto/utils.py
- chromadb/segment/impl/metadata/grpc_segment.py
- chromadb/segment/impl/vector/grpc_segment.py
- chromadb/test/proto/test_utils.py
Adds a gRPC interceptor for retrying requests instead of relying on gRPC's internal retry mechanism. This gives us much better visibility into retries, and also showed that the previous approach was not performing retries for some reason.
Example trace (tested by making this handler on the Go server randomly fail 50% of the time):
Added a new test that starts a flaky server, records requests, and asserts that the request was retried correctly. The new test also confirmed that the previous retry configuration wasn't working.
n/a
> [ENH]: lift frontend gRPC retry to application & trace

- rust/blockstore/src/arrow/blockfile.rs
- rust/worker/src/segment/record_segment.rs
- Uses the id_to_user_id for count instead of id_to_data, since this is likely to be smaller
- Changes load_blocks to take a slice so callers don't transfer ownership
- Adds some documentation
- None
Existing tests should cover this change as its non-functional / not a new behavior. 
None
> [ENH] Fetch blocks in parallel and make load_blocks take a slice instead

- rust/distance/src/lib.rs
- Cleanup some warnings by only building distance modules when required features are enabled
- None
None
> [CLN] Only use distance avx/neon/sse if enabled

- rust/index/bindings.cpp
- rust/index/build.rs
- rust/index/src/hnsw.rs
- rust/index/src/types.rs
- rust/worker/src/execution/operators/hnsw_knn.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
- rust/worker/src/segment/record_segment.rs
- Introduces a mechanism to propagate errors from C++ into rust by catching errors in the bindings and then populating a thread_local variable.
- Build the c++ code automatically on change
- Propagate new errors up through the codebase
- Coalesce shared functionality in rust hnsw tests
- the c++ bindings were creating errors, but not throwing them, this path is purely defensive so it was never excercised, this fixes that. 
- None
Added a new test to test add() errors
None
> [ENH] Make Rust/C++ FFI error handling robust

- k8s/distributed-chroma/Chart.yaml
- k8s/distributed-chroma/templates/compaction-service.yaml
- k8s/distributed-chroma/templates/frontend-service.yaml
- k8s/distributed-chroma/templates/query-service.yaml
We want to bind pods to nodes, instead of disallowing other pods from being scheduled on specific nodes.
Tested locally with Tilt.
n/a
> [ENH]: allow using node selectors for pods instead of tolerations

- chromadb/migrations/metadb/00004-metadata-indices.sqlite.sql
Add indexes to sqlite metadata value columns.
This greatly improves the performance of queries that filter based on equality or comparison to metadata fields:
Note that the index only improves performance when the filter is highly selective. If there are large numbers of records that match the filter, processing is still slow (as they must all realized in memory and passed to the vector search.)
Creating the indexes on a database of ~40,000 embeddings with ~600,000 metadata rows takes less than ten seconds. It will seamlessly be applied to existing databases the first time they are loaded.
The change should be both forward and backward compatible. The only effect of the presence or absence of indices should be on the underlying sqlite query plan: result set semantics should be invariant …
> [ENH] [PERF] add indices to metadata columns

- Cargo.lock
Fix Rust build bug in CI (not sure why this only just started happening).
See here: https://github.com/time-rs/time/issues/681.
CI build should pass.
n/a
> [BLD]: bump `time` dependency

- Tiltfile
- rust/worker/src/execution/operators/merge_knn_results.rs
- rust/worker/src/execution/orchestration/hnsw.rs
Consolidates brute force results into a HashMap keyed by the query vector index instead of several separate HashMaps. This allows us to easily skip brute force search when possible.
Covered by existing tests. Manually confirmed that the brute force operator is no longer executed when collection is completely compacted.
n/a
> [ENH]: skip brute force search when log is empty

- k8s/distributed-chroma/Chart.yaml
- k8s/distributed-chroma/templates/logservice.yaml
- k8s/distributed-chroma/values.yaml
Allows configuring repliaCount and nodeSelector on the logservice, in line with other services.
Tested locally with Tilt.
n/a
> [ENH]: allow configuring replicaCount and nodeSelector on log service

- Cargo.lock
- rust/storage/Cargo.toml
- rust/storage/src/admissioncontrolleds3.rs
- rust/storage/src/lib.rs
- rust/storage/src/network_admission_control.rs
- rust/storage/src/s3.rs
- Introduces Network Admission Control that gates all network IOs leaving the system.
- Downstream users can submit get requests to NAC. NAC returns a future that they can await on.
- It performs request coalescing by tracking outstanding remote calls and their respective futures in a hashmap and deduplicating requests for the same key. The future stored in the hashmap is a shared future for this purpose to ensure that duplicate users await the same future.
None
> [ENH] Network Admission Control APIs

- rust/blockstore/src/arrow/provider.rs
- rust/index/src/hnsw_provider.rs
- rust/storage/src/admissioncontrolleds3.rs
- rust/storage/src/s3.rs
- Blockfile Manager and HNSW Index Provider uses the NAC when doing get() calls.
- NAC returns a future that they can await on. Once they have the bytes, they can perform specific operations such as deserializing to block, writing to local disk, etc. These operations need to be made thread safe.
None
> [ENH] Block manager and HNSW provider consume Network Admission Control

- rust/storage/src/admissioncontrolleds3.rs
- rust/storage/src/config.rs
- rust/storage/src/s3.rs
- rust/worker/chroma_config.yaml
- rust/worker/src/config.rs
- Introduced count based rate limiting policy where a maximum of X number of outstanding are permitted. X is configurable.
None
> [ENH] NAC rate limits requests

- chromadb/api/models/AsyncCollection.py
- chromadb/api/models/Collection.py
- chromadb/api/models/CollectionCommon.py
- chromadb/api/types.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/test_api.py
- Refactored functions to adhere to SRP to reduce the level of abstractions. 
- when a user uses add and upsert on an collection, they are no longer required to pass in an array of IDs. They will be automatically generated if not given. 
> [ENH] Generate IDs when not given in upsert and add

- rust/index/src/hnsw_provider.rs
- rust/storage/src/admissioncontrolleds3.rs
- rust/storage/src/config.rs
- rust/storage/src/lib.rs
- rust/storage/src/s3.rs
- rust/worker/chroma_config.yaml
- rust/worker/src/config.rs
- Introduces a parallel fetch API that splits up gets into 8 MB parallel downloads
- This passes through Admission control so it is rate limited and deduped
- HNSW provider consumes this API
Added rust test
None
> [PERF] Multipart s3 downloads passing through NAC

- rust/index/src/hnsw_provider.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
It was seen that query nodes OOM in load tests. One area where we could optimize the memory footprint is the HNSW index cache. This PR restricts the cache to keep one entry per collection. Ideally, we would like the index version of this entry to be of the latest but there is no guarantee with this PR. Once the versioning changes land, we could improve this. For e.g. one bad case could be:
For the same collection:
1. get index version v1
2. get index version v2 (> v1)
3. get index version v1 (can happen due to an inflight query that started before compaction of v2 occured) -- this will evict v2 even though it is more recent and will be used again in future
None
> [ENH] Evict other versions of hnsw index of the collection when another version is fetched

- clients/js/src/CloudClient.ts
Adds the `tenant` parameter to the JS CloudClient.
Confirmed that the CloudClient now works with staging.
n/a
> [ENH]: update JS CloudClient to accept `tenant` parameter

- rust/index/src/fulltext/tokenizer.rs
- rust/index/src/fulltext/types.rs
- rust/worker/src/segment/metadata_segment.rs
Saves around 1,300ms when ingesting 15k documents (averaging 1000 chars each).
We spend 1.5x the tokenization time just cloning the tokens, which should be avoidable but is not included in this PR because the lifetimes get hairy and the % that tokenization takes in the total compaction time is currently fairly low.
- removes the mutex from the tokenizer, reducing overhead
- simplifies types by removing a `Box` wrapper
Covered by existing tests.
n/a
> [PERF]: remove mutex around tokenizer

- rust/blockstore/src/arrow/provider.rs
- rust/blockstore/src/memory/provider.rs
- rust/blockstore/src/memory/storage.rs
- rust/blockstore/src/provider.rs
- rust/cache/src/cache.rs
- rust/worker/src/compactor/compaction_manager.rs
After a successful compaction, the blocks in the cache are obsolete. This purges the cache of old blocks which helps to clarify memory usage patterns (memory usage should no longer grow over time).
Tested by profiling memory usage and confirming that usage did not grow after subsequent compactions.
n/a
> [ENH]: purge block cache after compaction

- rust/worker/src/execution/operators/flush_s3.rs
- rust/worker/src/execution/orchestration/compact.rs
- write_to_blockfiles is an intense operation, there should be no reason to hog the main runtime. Moved it to a worker thread as part of flush operation. I am hesitant to create a new operator exclusively for this as all of this seems temporary and eventually we want the blockfile to support read then write semantics
None
> [PERF] Move write to blockfiles off main runtime

- chromadb/test/distributed/test_sanity.py
- chromadb/test/property/invariants.py
We now test that the results are approximately what we expect rather than an exact match as distributed uses ANN.
By making this test recall-based, it should no longer flake in CI. 
n/a
> [ENH]: make test_sanity recall based

- rust/blockstore/src/arrow/sparse_index.rs
Fixes `get_target_block_id()` to run in `O(log n)` instead of `O(n)`. Shaves around 2.6s off total compaction time for 26k documents.
[get-target-block-id.trace.zip](https://github.com/user-attachments/files/16808322/get-target-block-id.trace.zip)
Covered by existing tests.
n/a
> [PERF]: speed up `get_target_block_id()`

- chromadb/test/property/invariants.py
- rust/worker/src/execution/operator.rs
- rust/worker/src/execution/operators/metadata_filtering.rs
- rust/worker/src/execution/orchestration/count.rs
- rust/worker/src/execution/orchestration/metadata.rs
- rust/worker/src/execution/orchestration/mod.rs
Skips querying the `MetadataSegmentReader` when there's no where clause which should result in a performance bump.
Also splits the `CountQueryOrchestrator` into a new file.
Covered by existing tests. Confirmed that the reader was not queried for a `.get()` call missing where clauses.
n/a
> [ENH]: skip querying `MetadataSegmentReader` for empty where clause

- Cargo.toml
Allows us to use external tooling to debug prod workloads.
Compaction binary size on macOS:
- before: 32MB
- after: 36MB
n/a
> [BLD]: add debug info to Rust release binaries

- Cargo.lock
- rust/blockstore/src/arrow/block/types.rs
- rust/blockstore/src/arrow/sparse_index.rs
- rust/cache/Cargo.toml
- rust/cache/src/cache.rs
- rust/cache/src/config.rs
- rust/cache/src/lib.rs
- rust/index/src/hnsw.rs
- rust/index/src/hnsw_provider.rs
- rust/types/src/types.rs
- rust/worker/chroma_config.yaml
- rust/worker/src/config.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
- Made HNSW cache weighted LRU where the weight is the size of the value.
- Changed the config to have capacity in terms of bytes and not counts
None
> [ENH] Weighted LRU for HNSW provider cache

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/src/bin/compaction_service.rs
This should fix unbounded memory growth when running inside a container. 
Background:
- we continue to observe OOM errors on the compaction service in production
- unbounded memory growth cannot be reproduced when running the binary natively under macOS
- unbounded memory growth *can* be reproduced when running the built container under macOS
- according to both Instruments.app and heaptrack (running inside the built container) there is no memory leak
It seems like glibc's malloc was not marking freed memory as free to the OS for some reason. When periodically running `malloc_trim()`, memory usage stayed within expected bounds.
Switching to jemalloc appears to resolve the issue.
1. Load [SciDocs](https://github.com/allenai/scidocs) dataset.
2. Insert first 15k documents into a new …
> [ENH]: use jemalloc for compactor service

- chromadb/logservice/logservice.py
- chromadb/test/property/test_add.py
- Reduce the batch size on logservice to be more conservative in order to prevent grpc payload limits from being hit.
- None
None
> [BUG] Smaller batch size

- .github/workflows/_python-tests.yml
- .github/workflows/_python-vulnerability-scan.yml
- .github/workflows/nightly-tests.yml
- clients/js/test/startChromaContainer.ts
Checks started failing today because v2 is too old.
GitHub CI.
n/a
> [BLD]: bump version of upload-artifact actions

- rust/worker/Dockerfile
Uses Docker cache mounts to cache Rust artifacts instead of layer caching. A cache mount persists across `docker build`s and is not stored as a layer in the image. Using a cache mount is better because:
- if a dependency changes, it does not require all dependencies to be rebuilt
- only changed Chroma code will be rebuilt
I tested the savings by performing an incremental build (with target `compaction_service`) after touching a file in the worker crate.
**Before**:
- `debug`: 35s
- `release`: 1m8s
**After**:
- `debug`: 14s
- `release`: 58s
It doesn't seem to speed up release builds as much as I was hoping, but a 2x reduction in debug build time is a nice win. Also makes the Dockerfile easier to read. Savings may be more pronounced when running multiple builds concurrently (e.g. the query …
> [BLD]: use cache mount in Rust Dockerfile

- chromadb/api/async_client.py
- chromadb/api/client.py
- chromadb/db/base.py
- chromadb/db/impl/grpc/client.py
- chromadb/db/mixins/sysdb.py
- chromadb/errors.py
- chromadb/test/api/test_get_database.py
- chromadb/test/db/test_system.py
When a database is not found, a 404 HTTP status code is now returned instead of a 500.
Added a new test. It doesn't strictly test the status code (difficult if we want to keep the more friendly error message), but exercises the code path.
n/a
> [ENH]: GET /databases should return 404 instead of 500 for not found

- rust/blockstore/src/arrow/block/delta/delta.rs
- rust/blockstore/src/arrow/block/types.rs
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/provider.rs
- rust/blockstore/src/arrow/sparse_index.rs
- rust/blockstore/src/key.rs
- rust/blockstore/src/memory/reader_writer.rs
- rust/blockstore/src/memory/storage.rs
- rust/blockstore/src/provider.rs
- rust/blockstore/src/types.rs
- rust/index/src/hnsw_provider.rs
- rust/index/src/metadata/mod.rs
- rust/index/src/metadata/types.rs
- rust/worker/src/compactor/scheduler.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/log/log.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/sysdb/test_sysdb.rs
- rust/worker/src/system/executor.rs
- rust/worker/src/system/scheduler.rs
- rust/worker/src/system/system.rs
- These errors were not properly propagated before
- None
This PR also contains stacked PRs as part of mereg
#2780 
#2793 
Non functional changes. Existing tests. We should add tests for these cases
None
> [CLN] Propagate errors for block get/fork

- clients/js/src/index.ts
- docs/docs.trychroma.com/tsconfig.json
the nextjs build was failing and so new docs were not releasing. this makes nextjs happy 
`yarn build` now works
none needed
> [DOC] fix docs build

- chromadb/api/models/Collection.py
Updated missing description for "query_uris" parameter on user-facing query method under Collection API.
Docstring for user-facing API updated. No documentation changes required in the docs repository.
> [DOC] Add description for query_uris parameter in collection query method

- docs/docs.trychroma.com/pages/getting-started.md
It should be `pnpm add <pkg>` instead of `pnpm install <pkg>`.
`pnpm install` is used to install all dependencies for a project while `pnpm add <pkg>` is used to install a package and any packages that it depends on.
More info (official source):
- https://pnpm.io/cli/add
- https://pnpm.io/cli/install
---
`pnpm install <pkg>` does the same as `pnpm add <pkg>` today, but it might stop functioning that way in future versions since the official docs clarify the difference between the two. It might be that `pnpm install <pkg>` was used in past versions, and the PNPM team didn't want to remove support for it right away after introducing `pnpm add <pkg>`.
> [DOC]: use `pnpm add <pkg>` instead of `pnpm install <pkg>`

- docs/docs.trychroma.com/pages/integrations/langchain.md
- Removed the code example from the Langchain integration documentation as per @jeffchuber's request.
- n/a
- The example in the docs has been updated. There are no other documentation changes required.
> [DOC]: Update Langchain integration example and fix broken link

- docs/docs.trychroma.com/components/layout/TopNav.tsx
- docs/docs.trychroma.com/tailwind.config.js
Tailwind dark-mode did not respond to changes properly since `next-themes` uses `data-theme="dark"` to apply dark mode styling to elements in this project. 
This made it hard to develop dark mode styling for custom components on the docs site. 
Visually tested with `npm run dev`. Notice that in production the "sun" doesn't change to a "moon" when applying dark mode (this _should_ happen on the tailwind styling).
Not needed.
> [BUG] - Fix tailwind themes in docs

- chromadb/api/types.py
- chromadb/test/ef/test_multimodal_ef.py
- clients/python/requirements.txt
- pyproject.toml
- requirements.txt
- Supports numpy 2.0 now that onnxruntime supports it by removing our limit of <2.0
- Change usage of `float_` to `float64`. These are supported in both < and >= 2.0. However `float_` is only supported by < 2.0. In < 2.0 the _ types are shorthand for the 64bit wide datatypes. I verified this. This makes the changes cleaner than #2776. 
- None
Existing tests
None
> [CLN] Support numpy >=2.0

- chromadb/segment/impl/vector/local_persistent_hnsw.py
- chromadb/test/property/invariants.py
- chromadb/test/property/test_persist.py
- rust/worker/src/execution/operators/merge_knn_results.rs
-  Discovered that there is an issue with `PersistentLocalHnswSegment` where `query_vectors` can return results with lengths different than `n_results`. This PR implements a test both displays and catches this issue.  
- Fixes off by one issue in hnsw/BF merge logic in both single node and distributed
- Added a test for the breaking case that fails on main, fix shows test passes
> [BUG] Test that query result shapes are correct in invariants

- chromadb/test/property/test_cross_version_persist.py
- Fix CVP tests which broke in #2811 by reimporting numpy
- None
None
> [BUG] Fix CVP tests by forcing numpy reimport

- rust/blockstore/src/arrow/block/value/int32array_value.rs
- In #2729 we changed to UInt32Array but some old data may be Int32Array. This is a rather ugly hack to preserve that behavior.
- None
We are scoping cross-version tests, which are needed in general.
None
> [BUG] Fix I32Array BW compat

- chromadb/telemetry/product/__init__.py
- docs/docs.trychroma.com/pages/telemetry.md
Update Posthog telemetry to indicate which events are associated with Chroma Cloud interactions by clients.
> [ENH] Update client telemetry for developer cloud

- chromadb/__init__.py
0.5.6 Release in #2817 got botched due to a _suspected_  (need to confirm) race on the tag, skipping and releasing 0.5.7.
> [RELEASE] 0.5.7

- chromadb/segment/impl/metadata/sqlite.py
- chromadb/test/api/test_limit_offset.py
- chromadb/test/property/test_filtering.py
- docs/docs.trychroma.com/pages/deployment/migration.md
- Updates `test_filtering.py`. The new implementation sorts the result by internal `offset_id` instead of user provided `id`, thus the unit tests need to be updated accordingly.
- In addition, a simple unit test is added to test `get()` with only `offset` and `limit`
Run the existing and new tests locally
Add documentation to explain the order of results return by `get()`
> [ENH] Update and implement new unit test for limit/offset

- chromadb/test/property/test_cross_version_persist.py
This test was previously failing after 0.5.7 was released because auto prune is enabled by default in 0.5.7.
Test passes locally.
n/a
> [BUG]: fix cross_version_persist assertion for >= 0.5.7

- .github/workflows/release-javascript-client.yml
The `db:run` script no longer exists and should not be necessary as the test fixture automatically creates and starts a container.
🤷
n/a
> [BUG]: fix JS publish workflow

- pyproject.toml
Added a regex filter on tags for setuptools, so we only consider release number tags.
Made sure we get dev and numbered versions, and that "js_release" tags are ignored.
Updating release guide.
> [BUG] Add release version regex to setuptools

- chromadb/api/__init__.py
- chromadb/api/async_api.py
- chromadb/db/impl/grpc/server.py
- chromadb/db/mixins/sysdb.py
- chromadb/test/db/test_system.py
- chromadb/test/property/test_collections.py
- chromadb/test/test_api.py
- docs/docs.trychroma.com/pages/reference/py-client.md
- go/pkg/metastore/coordinator/table_catalog.go
`get_or_create` collection was overriding metadata on the "get" path when the collection already exists. This PR removes this behavior to make the API consistent with its name. Users can utilize `Collection.modify` to change a collection's metadata.
One idea for `get_or_create` was to rename arguments prefix arguments with `create_`, to make it clear that they only apply to the `create` path. We decided to remove the overriding behavior on the `get` path without renaming the arguments to minimize breakage.
Another idea for future consideration is to add a `Client.modify_collection` API. This would make it clear at a quick glance that a separate modifying API is available. A caveat is that we already have a `Collection.modify` API.
Documentation updated to reflect this change.
> [ENH] - Fix `get_or_create_collection` semantic inconsistencies

- chromadb/proto/convert.py
- chromadb/types.py
- clients/js/test/collection.client.test.ts
- This PR simply hydrates the python representation of the collection with the log position that comes from the proto. Following the convention for version, this is 0 and unused in single node.
- None
None
> [ENH] Add log position to FE

- chromadb/proto/convert.py
- chromadb/segment/impl/metadata/grpc_segment.py
- chromadb/segment/impl/vector/grpc_segment.py
- rust/error/src/lib.rs
- rust/worker/src/execution/operators/merge_knn_results.rs
- rust/worker/src/execution/orchestration/count.rs
- rust/worker/src/execution/orchestration/get_vectors.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/orchestration/metadata.rs
- rust/worker/src/server.rs
- Pass the request_version_context into the protobufs and to the rust code. In the rust orchestrators, we error on mismatches and propagate this error up to python.
- None
None
> [ENH] Propagate version through system

- Cargo.lock
- rust/error/Cargo.toml
- rust/error/src/lib.rs
- rust/worker/src/server.rs
- Send error codes back to calling services from `Box<dyn ChromaError>`s
- None
> [ENH] Propagate error codes through rust services

- chromadb/api/segment.py
- chromadb/errors.py
- chromadb/segment/impl/metadata/grpc_segment.py
- chromadb/segment/impl/vector/grpc_segment.py
- chromadb/test/distributed/test_version_mismatch.py
- Adds version mismatch error in python and retries on it from the FE.  
- None
Added tests for version mismatches post a compaction wait, if the version matches the request should succeed. If we set it to an erroneous value, we expect a `VersionMismatchError`.
None
> [ENH] Add retry on mismatch

- rust/blockstore/src/arrow/block/delta/data_record.rs
- rust/blockstore/src/arrow/block/delta/delta.rs
- rust/blockstore/src/arrow/block/delta/mod.rs
- rust/blockstore/src/arrow/block/delta/single_column_size_tracker.rs
- rust/blockstore/src/arrow/block/delta/single_column_storage.rs
- rust/blockstore/src/arrow/block/delta/storage.rs
- rust/blockstore/src/arrow/block/types.rs
- rust/blockstore/src/arrow/block/value/data_record_value.rs
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/flusher.rs
- rust/blockstore/src/arrow/provider.rs
- rust/blockstore/src/arrow/sparse_index.rs
- rust/blockstore/src/key.rs
- rust/blockstore/src/memory/provider.rs
- rust/blockstore/src/memory/reader_writer.rs
- rust/blockstore/src/memory/storage.rs
- rust/blockstore/src/provider.rs
- rust/blockstore/src/types.rs
- rust/index/src/fulltext/types.rs
- rust/types/src/data_chunk.rs
- rust/types/src/data_record.rs
- rust/types/src/metadata.rs
- rust/types/src/operation.rs
- rust/types/src/record.rs
- rust/types/src/scalar_encoding.rs
- rust/types/src/segment.rs
- rust/types/src/segment_scope.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- Clean up warnings under rust/types.
- `cargo clippy --all-targets`
> [CHORE] Cleanup clippy warnings in rust/blockstore

- rust/blockstore/src/arrow/block/delta/storage.rs
- rust/blockstore/src/arrow/sparse_index.rs
- rust/blockstore/src/provider.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/record_segment.rs
- This switches to `debug_struct` over `f.write` as per @rescrv's suggestion.
- Fixes a spurious warning about an unused struct field
- None
We do not test the debug behavior.
None
> [CHORE] Switch to debug_struct over f.write

- rust/index/src/fulltext/types.rs
- rust/types/src/data_chunk.rs
- rust/types/src/data_record.rs
- rust/types/src/metadata.rs
- rust/types/src/operation.rs
- rust/types/src/record.rs
- rust/types/src/scalar_encoding.rs
- rust/types/src/segment.rs
- rust/types/src/segment_scope.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- Clean up warnings under rust/types.
- `cargo clippy --all-targets`
> [CHORE] Cleanup some clippy errors and all warnings for rust/types

- rust/index/src/hnsw_provider.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/execution/orchestration/compact.rs
- Compaction doesn't need to use the cache.pop.  We know exactly which compactions we trigger.
- This will unblock upgrading foyer within chroma.
> [CHORE] Remove the need to pop from the disk cache during compaction

- rust/blockstore/src/key.rs
- rust/blockstore/src/memory/provider.rs
- rust/blockstore/src/memory/reader_writer.rs
- rust/blockstore/src/provider.rs
- rust/blockstore/src/types.rs
- rust/index/src/hnsw_provider.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/execution/orchestration/compact.rs
- Fixes from another PR that I merged too fast.
> [CHORE]  Make a ChromaError type for RuntimeTypeError

- Cargo.lock
- rust/types/Cargo.toml
- rust/types/src/metadata.rs
- Updates `MetadataValue` so that the floating type is `f64` and the integer type is `i64`, which is consistent with proto definitions.
- Updates `WhereComparison` so that it can be handled with less code (in the subsequent PRs).
- Convert `DirectWhereDocumentComparison` as a variant of `Where` enum. This unifies the `Where` and `WhereDocument`, which facilitates a shared evaluation pipeline (in the subsequent PRs).
- Introduce `SignedRoaringBitmap` which captures the idea of performing conjunction and disjunction on bitmaps without the knowledge of the whole domain. This is useful because in our case the domain is decided by the entries in the database that is not yet deleted, and currently it is …
> [ENH] Implement `SignedRoaringBitmap` and update where/where_document AST

- rust/worker/src/execution/operators/metadata_filtering.rs
- Refactors the `MetadataFilteringOperator`. Now it should produce the exact set of offset ids that should be contained in the result, so that the next operator can only focus on hydrating the offset ids.
- Implement the `MetadataProvider` enum, which represents an universal interface for metadata access. Currently it can be constructed either from materialized logs or a `MetadataSegmentReader`.
- Introduce the `RoaringMetadataFilter` trait, which helps to evaluate a `Where` clause given a `MetadataProvider`. `$ne` and `$nin` are supported as part of this process
This is guaranteed to break existing tests. Only the last PR in the stack addresses the breaking changes, and …
> [ENH] Implement `MetadataProvider`, `RoaringMetadataFilter`, and refactor `MetadataFilteringOperator`

- .github/workflows/_rust-tests.yml
- rust/benchmark-datasets/src/datasets/ms_marco_queries.rs
- rust/benchmark-datasets/src/datasets/scidocs.rs
- rust/chroma/src/lib.rs
- rust/chroma/src/main.rs
- rust/distance/src/distance_avx.rs
- rust/distance/src/distance_sse.rs
- rust/distance/src/types.rs
- rust/storage/src/s3.rs
- rust/worker/src/system/scheduler.rs
- rust/worker/src/system/types.rs
This removes use of a deprecated error type and refactors some mutexes held across await points to be held prior to the await point.
- Clippy errors be gone
*cargo test locally && ci globally
> [CHORE] Finish clippy work.  Enable it.  Make docs not warn too.

- Cargo.lock
- Cargo.toml
- rust/benchmark-datasets/Cargo.toml
- rust/blockstore/Cargo.toml
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/sparse_index.rs
- rust/blockstore/src/key.rs
- Implements the serde traits for the sparse index
- Refactors out the forward/reverse mapping into one lock protected struct we serde from
- Clean up imports on the benchmark crate, since that uses bincode.
- None
Notes
- I chose to implement this with the default serde impls because then we get zero-copy into the in memory struct. Since the serde is used for on-disk caching, that is preferable. A potential alternative would be to serialize to/from bytes and implement our own Serializer/Deserializer. 
- I forwarded the pattern of exposing the "forward" of the SparseIndex. This is a bad abstraction and I'll clean it up in a subsequent PR, preferring to keep it as is for now.
*How are these changes …
> [ENH] Implement serde for SparseIndex

- chromadb/segment/impl/metadata/sqlite.py
- chromadb/test/property/test_filtering.py
- chromadb/test/segment/test_metadata.py
- Updates the semantics of `$ne`, `$nin`, and `$not_contains` to be the exact opposite of `$eq`, `$in`, and `not_contains`. Previously, `$ne` and `$nin` only returns records with the specified key in the metadata, while `$not_contains` only returns records with documents. Now `$ne` and `$nin` returns all records excluding those matching `$eq` and `$in`, and `$not_contains` returns all records excluding those matching `$contains`. 
- N/A
This is a breaking change that should be documented on the migration …
> [ENH] Change the semantics of `$ne`, `$nin`, and `$not_contains` for local Chroma

- .github/workflows/_rust-tests.yml
- .github/workflows/pr.yml
- Moves clippy into its own job so that we don't block tests. It is good to be able to run these separately. 
- Unifies the rust lint jobs into the lint action, where `cargo fmt` was already running.
- None
None
> [TST] Move clippy into the lint job

- chromadb/server/fastapi/__init__.py
- chromadb/telemetry/opentelemetry/__init__.py
The frontend will add the collection, tenant, and database IDs to traces on incoming requests when available.
n/a
> [ENH]: add tenant, database, and collection IDs to trace when available

- Cargo.lock
- rust/test/Cargo.toml
- rust/test/src/benchmark.rs
- rust/test/src/lib.rs
- rust/test/src/storage.rs
- Implement new functionalities to initialize blockfile provider for testing and benchmark
- N/A
N/A
> [TST] Implement utility functions to instantiate blockfile provider

- requirements_dev.txt
- Bound `hypothesis` package version to `6.112.2`, since changes in the next version breaks our python tests. We need to address the breaking changes and fix the tests in the future.
- N/A
N/A
> [TST] Bound hypothesis version for breaking changes

- .github/workflows/release-chromadb.yml
- RELEASE_PROCESS.md
Automatically set a released version as the latest on Github
We will make a new release and see.
Update the release process documentation
> [ENH] Automatically set version release as the latest release on Github

- chromadb/test/property/strategies.py
- Enable the tests for `$ne`, `$nin`, and `$not_contains` on distributed chroma.
- N/A
> [TST] Enable tests for $ne, $nin, and $not_contains for hosted Chroma

- chromadb/__init__.py
- docs/docs.trychroma.com/pages/deployment/migration.md
> [RELEASE] 0.5.12

- rust/blockstore/src/arrow/provider.rs
- rust/blockstore/src/provider.rs
- rust/cache/src/foyer.rs
- rust/cache/src/lib.rs
- rust/cache/src/nop.rs
- rust/cache/src/unbounded.rs
- rust/index/benches/full_text.rs
- rust/index/build.rs
- rust/index/src/hnsw_provider.rs
- rust/types/build.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/server.rs
End-to-end tests confirm that with this change foyer will initialize the disk path (assuming it's writable) and instantiate a disk.  A memory cache will also instantiate.
Note that the PersistentCache type means that the key and value implement StorageKey and StorageValue, so it's totally acceptable for every non-persistent cache to implement the trait.  This means that any place that takes a persistent cache will also take the non-persistent versions.  It's trait logic, not "is a".
- ...
- ...
> [ENH]  Make block and sparse index caches use persistent type.

- rust/blockstore/src/arrow/block/types.rs
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/memory/reader_writer.rs
- rust/blockstore/src/types.rs
- rust/index/src/fulltext/types.rs
- rust/index/src/metadata/types.rs
- Updates the binary search algorithm for arrow block to match the latest std impl
- The binary search now identifies the partition point instead of returning the value at the location
- New utility function to scan a range of values for the same prefix
- Now methods that yields a vector of records like `get_by_prefix` and `get_gt` returns `Vec<(K, V)>` instead of `Option<Vec<&str, K, V>>`. The empty vector is sufficient to indicate the absence of the specified `(prefix, key)`
- With all the refactoring above, now `get_gt/gte/lt/lte` finds the starting point of the scan using binary search. Previously, we scan the entire block.
*Are all docstrings for user-facing APIs …
> [ENH] Use binary search for gt/gte/lt/lte

- chromadb/api/__init__.py
- chromadb/api/async_api.py
- chromadb/api/async_client.py
- chromadb/api/async_fastapi.py
- chromadb/api/client.py
- chromadb/api/fastapi.py
- chromadb/api/segment.py
- chromadb/db/__init__.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/test_api.py
- clients/js/src/Collection.ts
The `Collection.delete` API seemingly returns None, but our internal implementation returns a list of the IDs that were deleted. This PR makes all `delete` implementations return `None` for consistency.
The documentation does not mention the API returning a list of deleted IDs, so it is consistent with the expected behavior.
> [CLN] Make delete return None

- chromadb/api/segment.py
- chromadb/ingest/impl/utils.py
- chromadb/segment/__init__.py
- chromadb/segment/impl/manager/distributed.py
- chromadb/segment/impl/manager/local.py
- chromadb/segment/impl/metadata/grpc_segment.py
- chromadb/segment/impl/metadata/sqlite.py
- chromadb/segment/impl/vector/grpc_segment.py
- chromadb/segment/impl/vector/local_hnsw.py
- chromadb/test/property/test_persist.py
- chromadb/test/property/test_segment_manager.py
- chromadb/test/segment/test_metadata.py
- chromadb/test/segment/test_vector.py
- Migrate away from `MetadataReader` and `VectorReader` interface
- N/A
> [ENH] Migrate away from MetadataReader and VectorReader

- chromadb/api/segment.py
- chromadb/ingest/impl/utils.py
- chromadb/segment/__init__.py
- chromadb/segment/impl/manager/distributed.py
- chromadb/segment/impl/manager/local.py
- chromadb/segment/impl/metadata/grpc_segment.py
- chromadb/segment/impl/metadata/sqlite.py
- chromadb/segment/impl/vector/grpc_segment.py
- chromadb/segment/impl/vector/local_hnsw.py
- chromadb/test/property/test_persist.py
- chromadb/test/property/test_segment_manager.py
- chromadb/test/segment/test_metadata.py
- chromadb/test/segment/test_vector.py
Reverts chroma-core/chroma#2942
The `MetadataReader` and `VectorReader` should be kept for better code readability. The plan is to remove `get_segment` abstract method from `SegmentManager` interface and have divergent implementation for `LocalSegmentManager` and `DistributedSegmentManager` respectively
> [BUG] Revert "[ENH] Migrate away from MetadataReader and VectorReader"

- chromadb/api/segment.py
- chromadb/execution/executor/distributed.py
- chromadb/execution/executor/local.py
- chromadb/segment/__init__.py
- chromadb/segment/impl/manager/distributed.py
- chromadb/segment/impl/manager/local.py
- Use executor interface in `SegmentAPI` to replace the direct usage of segment readers. This is a follow up of https://github.com/chroma-core/chroma/pull/2950
- N/A
> [ENH] Use executor in segment.py

- Cargo.lock
- rust/cache/Cargo.toml
- rust/cache/src/foyer.rs
- rust/cache/src/lib.rs
- rust/index/src/hnsw_provider.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/server.rs
- Anything that implements the hnsw provider will evict files from disk when evicted from cache.
> [ENH] Call purge_one when evicting from cache.

- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/root.rs
- Use the count index if it exists to speed up search.
- None
Existing count tests for BF hold
None
> [ENH] Use sparse index count in blockfile

- rust/blockstore/src/arrow/block/delta/delta.rs
- rust/blockstore/src/arrow/block/delta/single_column_storage.rs
- rust/blockstore/src/arrow/block/delta/storage.rs
- rust/blockstore/src/arrow/mod.rs
- rust/blockstore/src/arrow/provider.rs
- rust/blockstore/src/arrow/sparse_index.rs
- Introduces the ability to attach metadata to a block
- We use the RecordBatch ability to store a custom HashMap of metadata in its schema.
- The delta.finish() method is used to pass the metadata. So metadata is a one-time writeable piece of data.
- into_arrow returns the arrow fields, not the actual record batch, so that schema can be attached.
- /
Tests for this functionality are in a higher PR in the stack
> [ENH] Add metadata to block

- rust/blockstore/src/arrow/block/types.rs
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/config.rs
- rust/blockstore/src/arrow/flusher.rs
- rust/blockstore/src/arrow/mod.rs
- rust/blockstore/src/arrow/provider.rs
- rust/blockstore/src/arrow/root.rs
- rust/blockstore/src/arrow/sparse_index.rs
- rust/blockstore/src/provider.rs
- Introduces a root of the blockfile, which stores version, sparse index and id. 
- Add versioning to the metadata of the sparse index
- ...
Existing tests + 1 test for version backwards compat is introduced higher in the stack
None
> [ENH] Add blockfile root

- rust/blockstore/src/arrow/block/delta/storage.rs
- rust/blockstore/src/arrow/block/types.rs
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/concurrency_test.rs
- rust/blockstore/src/arrow/provider.rs
- rust/blockstore/src/arrow/root.rs
- rust/blockstore/src/arrow/sparse_index.rs
- rust/blockstore/src/types.rs
- rust/index/benches/full_text.rs
- rust/index/src/fulltext/types.rs
- rust/index/src/metadata/types.rs
- rust/test/src/segment.rs
- rust/worker/src/execution/operators/count_records.rs
- rust/worker/src/execution/operators/flush_s3.rs
- rust/worker/src/execution/operators/hydrate_metadata_results.rs
- rust/worker/src/execution/operators/metadata_filtering.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/segment/types.rs
- Adds a count index to sparse index. On the writer this is kept in its own dict so that we can set it ONLY at the end to avoid having to set another map in the hot path.
- Changes to raw arrow based serialization instead block-based for root since we need to have multiple columns. Once BF supports this we can move back. 
Added tests for old version migration and new functionality
A V1 RootWriter will not serialize counts. 
A V1 BlockfileWriter will ALWAYS upgrade to V1.1 and set all its counts at commit()
None
> [ENH] Add count index

- Cargo.lock
- rust/cache/Cargo.toml
- rust/cache/src/foyer.rs
- rust/worker/README.md
- Bump foyer version to 0.12.2
- FYI: foyer [CHANGELOG](https://github.com/foyer-rs/foyer/blob/main/CHANGELOG.md)
- Bump MSRV
- Add `tracing` feature for chroma-cache.
> [ENH] Bump foyer to 0.12

- chromadb/telemetry/product/posthog.py
Our telemetry is anonymous, so this will save money.
n/a
> [ENH]: disable Posthog profiles

- chromadb/test/client/test_http_client_v1_compatability.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/utils/cross_version.py
- Consolidate shared helpers that aid in installing and using previous versions of Chroma in order to test cross version compatibility.
> [TST] Consolidate shared package version helpers

- chromadb/api/models/AsyncCollection.py
- chromadb/api/models/Collection.py
- Adds tenant and database to server calls from Collection objects. Previously, they weren't being sent to the server objects and thus URLs were using the default tenant/database.
- Small bit of typing/named parameter cleanup.
> [ENH] Add tenant/database to Collection operations

- chromadb/api/segment.py
- Add `@rate_limit` decorator in front of all server-side operations for the HTTP API
> [ENH] Stand up @rate_limit in front of all operations

- k8s/distributed-chroma/values.yaml
- We are providing a "fast" storage path on our cloud instances at `/local` so this needs to be reflected in our Helm charts as the `hostPath` for our cache directory.
`tilt up` builds and updates the charts in the expected way. 
> [CHORE] Update host path for disk cache

- chromadb/api/client.py
- chromadb/api/models/AsyncCollection.py
- chromadb/server/fastapi/__init__.py
- After an audit of everywhere that uses an instance of `ServerAPI`, there were a few places where `tenant`/`database` were not being threaded all the way through. This PR fixes that.
> [BUG] Ensure tenant/database are threaded through everywhere

- chromadb/test/property/test_persist.py
Updates `test_persist` to test persisting potentially multiple collections. This is to prevent introducing bugs like https://github.com/chroma-core/chroma/pull/2923 in the future.
I ran this new test against 0.5.12 and Hypothesis easily caught the bug.
n/a
Closes #2927
> [TST]: update test_persist to create 1+ collections

- rust/worker/src/tracing/opentelemetry_config.rs
* We only had tracing for the `worker` crate.  Enable it for all our crates at trace level and info level for non-chroma crates.
> [CHORE] enable tracing for our crates

- rust/worker/src/tracing/opentelemetry_config.rs
The RUST_LOG environment variable will allow the environment to override the specifics of which crates log at what level.  The format of RUST_LOG is:  default_level,crate_name1=some_level,crate_name2=some_other_level
- ...
- ...
> [ENH] Configure tracing via RUST_LOG.

- rust/worker/src/tracing/opentelemetry_config.rs
* Filter OTEL exporter to be traces over 1ms or non-foyer only
* Filter bunyan stdout exporter to be only the clear
*How are these changes tested?* Localhost with jaeger
> [ENH] In-process filtering of foyer traces under 1ms.

- rust/blockstore/src/arrow/flusher.rs
- The NAC doesn't limit write path, only read. Which was my misunderstanding of whats finished. This is a temporary workaround to limit concurrency.
- None
None
> [BUG] Buffer unordered to limit NAC

- chromadb/errors.py
- chromadb/server/fastapi/__init__.py
- clients/js/src/Errors.ts
- clients/js/test/get.collection.test.ts
- This will propagate value/type errors as invalid argument errors
- None
None
> [CLN] make ValueError and TypeError present as InvalidArgumentError

- Cargo.lock
- rust/cache/Cargo.toml
- rust/cache/src/foyer.rs
- rust/worker/src/tracing/opentelemetry_config.rs
* This wires up the cache to give us latency metrics for all operations.
I manually verified that the traces are exported if I change the otel_endpoint to otel-collector:4317 instead of jaeger:4317
- [ X] Tests pass locally with `pytest` for python, `yarn test` for js, `cargo test` for rust
> [ENH]  Latency histograms for get/insert/remove/clear of cache.

- chromadb/segment/impl/distributed/segment_directory.py
- chromadb/test/segment/distributed/test_rendezvous_hash.py
- chromadb/utils/rendezvous_hash.py
- /
- Adds support for multiple assignment in HWRH. This works by taking the top-K scores instead of the top 1
Added a test for uniformity
None
> [ENH] Rendezvous hashing support replication

- chromadb/execution/executor/distributed.py
- chromadb/execution/executor/local.py
- Restore the logic to skip the filter when the user does not specify any in the `query`
- ...
> [BUG] Remove unnecessary call to `get_metadata` for query

- rust/storage/src/admissioncontrolleds3.rs
- NAC would just get stuck if all tokens are exhausted by a single request in a low concurrency setting. There is a bug in the code that defers the release of all tokens for a request to the very end, this PR fixes that. Verified through a local repro.
None
> [BUG] Fix NAC getting stuck

- chromadb/api/__init__.py
- chromadb/api/async_api.py
- chromadb/api/async_client.py
- chromadb/api/async_fastapi.py
- chromadb/api/client.py
- chromadb/api/fastapi.py
- chromadb/api/models/CollectionCommon.py
- chromadb/api/segment.py
- chromadb/server/fastapi/__init__.py
- docs/docs.trychroma.com/pages/reference/py-client.md
- Removes id from the signature of `get_collection()`. Removes from the `__repr__()` of `Collection`.
- This is a patch for the bug of not being able to get a `Collection` by its id. It is the precursor to a much larger/breaking change where we are planning to completely scrub `collection_id` from client-facing code.
- Documentation is updated but this is a breaking changes so needs to be communicated in the next release.
> [ENH] Remove collection_id from get_collection

- chromadb/telemetry/opentelemetry/__init__.py
- chromadb/telemetry/opentelemetry/fastapi.py
- This change adds the ASGI http.disconnect tag to the root span so that we can filter out disconnects from errors
- ...
I manually ran a disconnect script and checked the events were tagged appropriately. I ensured requests with no disconnect were not tagged.
None
> [ENH] Add fastapi middleware for http.disconnect

- rust/blockstore/src/arrow/provider.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/segment/types.rs
Count of records materialized for metadata/record segments, blockfile IDs, and a typo fix.
> [CHORE] More details logged to understand compaction.

- chromadb/quota/__init__.py
- Removes `quota_rules` property from `QuotaProvider` as it is not implemented within OSS
> [CLN] Remove quota_rules from QuotaProvider

- chromadb/utils/embedding_functions/open_clip_embedding_function.py
OpenCLIP embeddings are failing type validation, as they return a `Tensor`. Converting to NuPy arrays to fix.
To discuss
> [BUG] Convert OpenCLIP embeddings to numpy arrays

- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/sparse_index.rs
Replaces specialized methods like `get_block_ids_gt` and `get_block_ids_lt` with a single `get_block_ids_range()` method that behaves similarly to the std `BTreeMap::range()` method. This reduces complexity/repetition and also enables queries that are bounded in both directions.
n/a
> [ENH]: replace `get_block_ids_*` with `get_block_ids_range()` in SparseIndex

- rust/blockstore/src/arrow/block/types.rs
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/types.rs
Replaces specialized methods like get_gt and get_lt with a single get_range() method that behaves similarly to the std BTreeMap::range() method. This reduces complexity/repetition and also enables queries that are bounded in both directions.
> [ENH]: replace `get_*` methods on Arrow blocks with `get_range()`

- rust/blockstore/src/memory/reader_writer.rs
- rust/blockstore/src/memory/storage.rs
- rust/blockstore/src/types.rs
Replaces specialized methods like get_gt and get_lt with a single get_range() method that behaves similarly to the std BTreeMap::range() method. This reduces complexity/repetition and also enables queries that are bounded in both directions.
> [ENH]: replace `get_*` methods on memory blockfile impl with `get_range()`

- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/blockfile_writer_test.rs
- rust/blockstore/src/types.rs
- rust/index/src/fulltext/types.rs
- rust/index/src/metadata/types.rs
Last PR in this stack. Propagates `.get_range()` API to the rest of the codebase.
n/a
> [ENH]: replace `.get_*` methods on blockfile API with `.get_range()`

- rust/blockstore/src/arrow/block/types.rs
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/provider.rs
- rust/blockstore/src/blockfile_writer_test.rs
- rust/blockstore/src/memory/reader_writer.rs
- rust/blockstore/src/provider.rs
- rust/blockstore/src/types.rs
- rust/index/src/fulltext/types.rs
- rust/index/src/metadata/types.rs
Enables a usecase from @Sicheng-Pan (scanning up to a given limit with an application filter) and makes some current operations slightly more efficient.
n/a
> [ENH]: make `get_range()` a lazy Stream

- chromadb/segment/impl/manager/local.py
In Python // is integer division, but sometimes people see it as a comment.  Add a note for anyone applying patches downstream so that they will have to re-evaluate their patch (and hopefully drop it).
> [ENH] Comment about integer division.

- chromadb/segment/impl/vector/batch.py
- chromadb/segment/impl/vector/local_hnsw.py
- chromadb/test/property/test_persist.py
- There was a bug where if the ID already existed the max seq id of the batch was not advanced. This results in storing more data than we need to on the log since the seq id is underreported. Not a huge issue, but breaks tests. This change removes `max_seq_id` from the batch entirely. `local_hnsw` will track it correctly in memory, and `local_persistent_hnsw` tracks it correctly on persist advances. For example, `add A` and then `add A` will result in the second add A to note advance the `batch` max_seq_id, by removing the needless redundant state we prevent the error.
- None
This is a test fix. I've included the hypothesis repro as a new test. I ran test_persist.py 15 …
> [BUG] Fix max seq ID incorrect bug by reducing state

- Cargo.toml
Increases full-text query performance (as measured by its benchmark) by 20-30% "for free". Does not seem to affect the limit/filter benchmarks.
Cold builds take the same amount of time with LTO enabled/disabled. Incremental builds take about 2x as long (25s -> 1m). (These changes only apply when building for the release profile.)
n/a
> [PERF]: enable thin LTO

- rust/worker/src/execution/operators/projection.rs
- Mark the `ProjectionOperator` as `Other` type, which implies it uses both compute and IO
- ...
N/A
> [PERF] Mark `ProjectionOperator` as a regular operator

- chromadb/api/segment.py
- chromadb/quota/__init__.py
- chromadb/quota/simple_quota_enforcer/__init__.py
- chromadb/server/fastapi/__init__.py
- Updates the signatures on `QuotaEnforcer` abstract class and `SimpleQuotaEnforcer` impl slightly to explicitly name the parameters on `enforce()`. Adds the `set_context()` method.
- Sets up the relevant context passing and quota enforcement within the API.
> [ENH] Set up QuotaEnforcer on API

- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/concurrency_test.rs
- rust/blockstore/src/arrow/ordered_blockfile_writer.rs
- rust/blockstore/src/arrow/provider.rs
- rust/blockstore/src/memory/provider.rs
- rust/blockstore/src/provider.rs
- rust/blockstore/tests/blockfile_writer_test.rs
- rust/index/benches/full_text.rs
- rust/index/src/fulltext/types.rs
- rust/index/src/metadata/types.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/record_segment.rs
Follow up from https://github.com/chroma-core/chroma/pull/2952. Renames `open()` on the blockfile provider to `read()` (semantically consistent with `write()`) and removes the deprecated `create()` & `fork()` methods.
n/a
> [CLN]: rename blockfile `open()` -> `read()` and remove `create()`/`fork()`

- Cargo.lock
- Cargo.toml
- rust/blockstore/tests/blockfile_writer_test.rs
Generates transitions on-demand instead of upfront. It seemed like generating transitions upfront was preventing proper shrinking for some reason. :(
My main motiviation was trying to convience proptest to catch a bug I knew about in another PR. It now catches the bug correctly.
I also changed the values being stored to `Vec<u32>` instead of Strings as they seem to be much faster to generate.
Execution time for this test went from 40s -> 16s for me and we're also running 4x as many cases now.
n/a
> [TST]: improve blockfile writer proptest

- rust/blockstore/src/arrow/block/delta/ordered_block_delta.rs
- rust/blockstore/src/arrow/block/value/uint32array_value.rs
- rust/blockstore/src/arrow/ordered_blockfile_writer.rs
Increases throughput by 11x for fresh blockfiles (and, I suspect, on forked blockfiles where the new set of data is mostly disjoint from the forked blocks). Does not result in a significant performance difference when mostly rewriting blocks on a forked blockfile.
Also increases throughput when writing to forked blockfiles by ~10% by avoiding clones and excess comparisons.
n/a
> [PERF]: improve OrderedBlockfileWriter writing performance

- chromadb/telemetry/opentelemetry/__init__.py
- chromadb/telemetry/opentelemetry/fastapi.py
This reverts commit fc54f702f3244d67283e241b614bbbd8d01c18d3. Which does not quite work the way I'd like because I can't disambiguate between a real disconnect and a fake one.
- None
- None
None
> Revert "[ENH] Add fastapi middleware for http.disconnect (#3038)"

- chromadb/test/property/strategies.py
This was previously generating f64 values, but we store these values internally in distributed Chroma as f32, leading to occasional flakes of test_filtering.
n/a
> [TST]: fix float generation for where clause filtering

- rust/blockstore/src/arrow/block/delta/unordered_block_delta.rs
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/ordered_blockfile_writer.rs
- rust/blockstore/src/arrow/provider.rs
- rust/worker/src/compactor/compaction_manager.rs
- The block manager now writes to the cache when compacting. This should reduce I/O time on subsequent compactions.
- Removes cache purging for blocks at the end of compaction, this is a hack and we should tune caches to not OOM instead.
- None
None
> [ENH] Enable write through cache while compacting. Disable cache clearing

- rust/blockstore/src/arrow/block/types.rs
- rust/cache/src/foyer.rs
- The cache code uses weighted capacity and specifies the capacity in MiB units. But we currently assume blocks are 1 MB.
- The underlying foyer cache is capacity and weight based. Fixing to MiB makes cache configuration indirect from the mechanics of the cache and results in it being cumbersome and potentially outright impossible to use. For example if I want to limit to 7000 items. I have to specify  a very small value as my capacity. This value may not be an integer but the configuration expects an integer capacity. Or alternatively, I can say that each item has some byte weight and choose a limit based on that. Rather than force these workarounds, it makes more sense for callers to think in whatever units they need …
> [CHORE] Make block cache weight 8. Make cache config unit based.

- rust/cache/src/foyer.rs
- https://github.com/chroma-core/chroma/pull/2697 Introduced a weighted cache. https://github.com/chroma-core/chroma/pull/2890/files#diff-2aee13d252376073188831aad803a50727d44fbf45f73e31106eab7e326de93dR348 Deleted it and smothered the setting, making "weighted_lru" not actually be weighted. (https://github.com/chroma-core/chroma/pull/2890/files#diff-6195692a271c580d5af2ce130f2b5a99b0e478a12271b1ba7bca2ed9572f7f3cR54) .
- This PR enables weighting by default. As we can set the weight to 1 for types we don't want weighting for. We don't have any types that we want the ability to support both for and we can add that trivially in the future if needed.
- None
None
> [BUG] Cache should use weight

- Cargo.lock
- rust/blockstore/src/arrow/provider.rs
- rust/storage/Cargo.toml
- rust/storage/src/admissioncontrolleds3.rs
- rust/storage/src/config.rs
- rust/storage/src/lib.rs
- rust/storage/src/local.rs
- rust/storage/src/object_store.rs
- rust/storage/src/s3.rs
The `object_store` crate implements a backend-agnostic version of object
storage that is capable of accessing gcp, azure, aws, local filesystem
and other implementations.
Tested against tilt.
> [ENH] Implement an object-store backend for storage.

- rust/storage/src/caching.rs
- rust/storage/src/config.rs
- rust/storage/src/lib.rs
- rust/storage/src/non_destructive.rs
- rust/storage/src/object_store.rs
This test wires up to make sure that every object store with a cache
that gets constructed is non-destructive, and also doesn't trip the
asserts for non-destructive behavior.
> [ENH]  End-to-end StorageConfig generating valid object stores.

- rust/storage/src/caching.rs
- rust/storage/src/config.rs
- rust/storage/src/evicting.rs
- rust/storage/src/lib.rs
- rust/storage/src/non_destructive.rs
- rust/storage/src/object_store.rs
We already wrap up the object store in an interface that doesn't expose
delete.  This allows us to wrap an object store in a non-destructive
interface that advertises when it is non-destructive.  The cache has
been updated to mandate that the cache be destructive and the backing
store be non-destructive.
> [ENH]  Safer object store interface.

- Cargo.lock
- rust/storage/Cargo.toml
- rust/storage/src/caching.rs
- rust/storage/src/config.rs
- rust/storage/src/evicting.rs
- rust/storage/src/latency.rs
- rust/storage/src/lib.rs
- rust/storage/src/non_destructive.rs
- rust/storage/src/object_store.rs
This object store tracks the size of the objects inserted to it and
deletes objects when the object store's size exceeds a configured
threshold.  Tests show that it will prune on startup as appropriate.
Before we ship this with a configuration language (a missing step that
enables us to use this code), I'd like to investigate ways to prevent an
evicting object storage from accidentally evicting 100% of an S3 bucket.
> [ENH]  Evicting object store.

- Cargo.lock
- rust/storage/Cargo.toml
- rust/storage/src/caching.rs
- rust/storage/src/config.rs
- rust/storage/src/evicting.rs
- rust/storage/src/latency.rs
- rust/storage/src/lib.rs
- rust/storage/src/non_destructive.rs
- rust/storage/src/object_store.rs
The object store takes two object stores, one as the canonical data
source and one as a cache.  It will then manage the cache to dedupe
traffic to the backend store for get_opts calls (whole files) only.
> [ENH]  First cut at a caching object store.

- go/pkg/memberlist_manager/memberlist_manager.go
- go/pkg/memberlist_manager/memberlist_manager_test.go
- go/pkg/memberlist_manager/memberlist_store.go
- go/pkg/memberlist_manager/node_watcher.go
- Removes unnecessary pointer indirection from MemberList, reducing indirection overhead
- Preallocates slices for MemberList to minimize memory allocations.
- Optimizes ready pod lookup during member listing, improving efficiency.
- None
Existing Test
- [ x] Tests pass locally with `pytest` for python, `yarn test` for js, `cargo test` for rust
> [PERF] Performance Optimizations for MemberList and Ready Pod Lookup (Go)

- rust/worker/chroma_config.yaml
- Send telemetry to otel_collector not jaeger. Fixing the left over in #3018 deemed out of scope by @codetheweb in https://github.com/chroma-core/chroma/pull/3018#issuecomment-2442919746
- None
None
> [CLN] Send rust telemetry to otel_collector by default

- rust/blockstore/src/arrow/block/delta/data_record.rs
- rust/blockstore/src/arrow/block/delta/data_record_size_tracker.rs
- rust/blockstore/src/arrow/block/delta/mod.rs
- rust/blockstore/src/arrow/block/delta/single_column_storage.rs
- rust/blockstore/src/arrow/block/delta/spann_posting_list_delta.rs
- rust/blockstore/src/arrow/block/delta/spann_posting_list_size_tracker.rs
- rust/blockstore/src/arrow/block/delta/storage.rs
- rust/blockstore/src/arrow/block/value/data_record_value.rs
- rust/blockstore/src/arrow/block/value/mod.rs
- rust/blockstore/src/arrow/block/value/roaring_bitmap_value.rs
- rust/blockstore/src/arrow/block/value/spann_posting_list_value.rs
- rust/blockstore/src/arrow/block/value/str_value.rs
- rust/blockstore/src/arrow/block/value/u32_value.rs
- rust/blockstore/src/arrow/block/value/uint32array_value.rs
- rust/blockstore/src/arrow/types.rs
- rust/blockstore/src/key.rs
- rust/blockstore/src/types/value.rs
- rust/types/src/lib.rs
- rust/types/src/spann_posting_list.rs
- Implements the ArrowWriteableValue and ArrowReadableValue traits
- Implements the delta and various sizing functions
None
> [ENH] Add new value type for spann posting lists

- rust/blockstore/src/arrow/block/delta/builder_storage.rs
- rust/blockstore/src/arrow/block/delta/data_record.rs
- rust/blockstore/src/arrow/block/delta/single_column_storage.rs
- rust/blockstore/src/arrow/block/delta/spann_posting_list_delta.rs
- rust/blockstore/src/arrow/block/value/data_record_value.rs
- rust/blockstore/src/arrow/block/value/roaring_bitmap_value.rs
- rust/blockstore/src/arrow/block/value/spann_posting_list_value.rs
- rust/blockstore/src/arrow/block/value/str_value.rs
- rust/blockstore/src/arrow/block/value/u32_value.rs
- rust/blockstore/src/arrow/block/value/uint32array_value.rs
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/types.rs
- Implemented `writer.get_clone()` that returns an owned value for the key
None
> [ENH] BF writer support reads

- chromadb/utils/embedding_functions/openai_embedding_function.py
Allow multiple openAI API keys #2979 
Removed direct assignment to global openai.api_key to prevent unintended side effects.
It seems that `cargo test` is failing due to a build issue. #2294 
Both `pytest` and `yarn test` succeed.
> [ENH] multiple api keys support

- rust/index/src/hnsw.rs
- rust/index/src/hnsw_provider.rs
- rust/index/src/types.rs
- rust/types/src/metadata.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
- Leaky abstraction. The Hnsw provider knew about segments and was parsing it to extract stuff like index params. The distributed hnsw segment writer and reader should instead be doing that and provider should not know about it.
None
> [CLN] Cleanup hnsw provider to not know about segments

- Cargo.lock
- Cargo.toml
- rust/worker/src/tracing/opentelemetry_config.rs
This bumps the version of tonic and prost, eliminating two copies of
tonic.  It then configures a service name for metrics emitted from Rust.
> [CHORE]  Configure service name for metrics.

- pyproject.toml
- Attempt to fix protobuf versioning incompatibility by removing the requirement from pyproject.toml
> [BUG] Remove protobuf from pyproject.toml

- rust/storage/src/admissioncontrolleds3.rs
Currently the NAC hangs when attempting to pull an empty file because of a bug in the futures crate. This adds a small check to work around the bug.
n/a
> [BUG]: fix NAC hang when pulling empty file

- rust/worker/src/tracing/opentelemetry_config.rs
Confirmed in tilt, not just by looking at code.
We see, e.g. the following metricsz:
default_get_latency_bucket{job="compaction-service",le="250"} 529
> [CHORE]  Set service.name correctly for metrics.

- rust/storage/src/s3.rs
Follow-up from https://github.com/chroma-core/chroma/pull/3143: I forgot that the same logic existed in the S3Storage struct.
n/a
> [BUG]: fix S3 hang when pulling empty file

- rust/worker/src/execution/operators/knn_hnsw.rs
- rust/worker/src/execution/orchestration/knn.rs
- rust/worker/src/execution/orchestration/mod.rs
- rust/worker/src/server.rs
- Previously a single `<collection>.query(...)` will spawn multiple `KnnOrchestrator` concurrently, leading to multiple instances of HNSW readers. Each HNSW reader will load the index data to the same locations in the file system, resulting in a high probability of concurrent read and write on the same index files. This PR moves the logic to create HNSW reader into `KnnFilterOrchestrator`, so all `KnnOrchestrator` will share the same HNSW reader.
- N/A
> [BUG] Share the same HNSW reader for KNNOrchestrator

- chromadb/api/segment.py
- chromadb/db/impl/grpc/client.py
- chromadb/db/impl/grpc/server.py
- chromadb/db/mixins/sysdb.py
- chromadb/db/system.py
- chromadb/test/db/test_system.py
- go/pkg/sysdb/coordinator/coordinator.go
- go/pkg/sysdb/coordinator/coordinator_test.go
- go/pkg/sysdb/coordinator/table_catalog.go
- go/pkg/sysdb/grpc/collection_service.go
- go/pkg/sysdb/metastore/db/dao/segment.go
- go/pkg/sysdb/metastore/db/dbmodel/segment.go
This PR only changes the backend GRPC/sysdb code.
- Improvements
- Removes the state where orphaned segments could be lying around.
N/A
> [ENH] Atomically delete Collection w segments

- chromadb/server/fastapi/__init__.py
- Update quota exception handler to return a `400` instead of a `429`
> [BUG] Update quota exception handler to 400

- rust/blockstore/src/arrow/blockfile.rs
- rust/index/src/hnsw_provider.rs
- Fixes a race on concurrent hnsw loads. The goal is to allow multiple different files to write at the same time. 
- None
None
> [BUG] Fix hnsw concurrent loads

- chromadb/execution/executor/distributed.py
- chromadb/execution/executor/local.py
- chromadb/segment/impl/distributed/segment_directory.py
- chromadb/segment/impl/manager/distributed.py
- rust/worker/src/execution/operators/fetch_segment.rs
- rust/worker/src/execution/operators/knn_projection.rs
- rust/worker/src/execution/orchestration/get_vectors.rs
- rust/worker/src/execution/orchestration/mod.rs
- rust/worker/src/server.rs
- rust/worker/src/utils/mod.rs
- Migrate the distributed executor in frontend to use new query plan interface in Grpc
- Update `server.rs` to use new query plan interface in Grpc
- ...
> [ENH] Migrate to Query Plan Interface

- rust/worker/src/server.rs
- #3145 suggests `<stream>.buffered` will hang infinitely if the stream is empty. Thus we should bail early if we receive no query embedding
- ...
N/A
> [BUG] Return early with empty query embeddings

- Cargo.lock
- rust/cache/Cargo.toml
- rust/cache/src/foyer.rs
- rust/worker/Cargo.toml
- rust/worker/src/tracing/opentelemetry_config.rs
- Upgrade otel stack from 0.26 to 0.27
> [ENH]: upgrade otel stack to 0.27

- chromadb/test/client/test_http_client_v1_compatability.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/utils/cross_version.py
- pyproject.toml
- requirements.txt
- Bounds tokenizers as in #3202 
- Includes a change to CVP test to install an old version of a dep in case of b/w incompat like this has. 
- None
None
> [BUG] Bound tokenizers, patch CVP test

- rust/blockstore/src/arrow/blockfile.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/segment/test.rs
- rust/worker/src/server.rs
- The record segment writer has a race condition if multiple threads are concurrently applying materialized logs to it. Specifically, the maximum offset id will not be set properly. This PR introduce tests on the Rust side to replicate this bug and then aims to fix the bug.
- N/A
N/A
> [BUG] Race condition when updating max offset id

- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/execution/operators/write_segments.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/segment/test.rs
- rust/worker/src/segment/types.rs
- Currently the materializer is initialized with an atomic integer representing current maximum offset, and increases it upon initialization so that it can be used to represent the next available offset id. If two materializers are sharing the same atomic integer, then the increment is duplicated upon initialization, leaving a hole in the offset id. This PR initializes the materializer directly with the next available offset id to resolve this scenario.
- N/A
N/A
> [BUG] Pass next offset id to log materializer

- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/count_records.rs
- rust/worker/src/execution/operators/filter.rs
- rust/worker/src/execution/operators/get_vectors_operator.rs
- rust/worker/src/execution/operators/hnsw_knn.rs
- rust/worker/src/execution/operators/knn_log.rs
- rust/worker/src/execution/operators/limit.rs
- rust/worker/src/execution/operators/prefetch_record.rs
- rust/worker/src/execution/operators/projection.rs
- rust/worker/src/execution/operators/write_segments.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/segment/test.rs
- rust/worker/src/segment/types.rs
Simplifies usage of log materialization logic & lifetimes in preparation for next PR in this stack. There are no actual logic changes.
n/a
> [CLN]: make materialization function rather than struct

- Cargo.lock
- rust/load/Cargo.toml
- rust/load/chroma_load.yaml
- rust/load/src/config.rs
- rust/load/src/lib.rs
- rust/load/src/rest.rs
- rust/load/src/workloads.rs
- rust/worker/src/config.rs
This mirrors the compactor and query services (and can even merge with
their configs if we so choose).
> [ENH]  Use figment configuration for chroma-load

- chromadb/api/async_fastapi.py
- Fixes bug where headers were not being added to async client requests. Also adds the verify argument.
- ...
> [BUG] Add headers to async client requests

- go/pkg/sysdb/coordinator/table_catalog.go
[BUG] Fix property failure for soft delete.
Renaming soft deleted collection at delete time
since modify and create can try to re-create
a collection with the same name.
- Fix property failure for soft delete.
n/a
> [BUG] Fix property failure for soft delete.

- rust/load/src/opentelemetry_config.rs
HTTP2 (gRPC) is not supported by whatever chroma-load is talking to for exporting tracing.  Use http
with the binary format instead.
> [CHORE]  Set tonic to http binary for chroma-load

- rust/index/src/spann.rs
- rust/index/src/spann/utils.rs
- Implement the full k-means with regularization and random sampling fully emulating the spann reference implementation
None
> [ENH] Implement K Means

- rust/index/src/spann/types.rs
- rust/worker/src/segment/spann_segment.rs
- Implements update and delete for the spann segment/index
None
> [ENH] SPANN: Implement update and delete

- rust/index/bindings.cpp
- rust/index/src/hnsw.rs
- rust/index/src/spann/types.rs
- rust/index/src/types.rs
- Full garbage collection in spann
None
> [ENH] Full garbage collection

- .github/workflows/copy-helm-chart.yml
- .github/workflows/release-helm-chart.yml
Does what it says on the tin. Automatically publishes to ECR upon chart version change or manual workflow run.
Tested in a sandbox repo & AWS account.
Requires https://github.com/chroma-core/hosted-chroma/pull/691.
n/a
> [BLD]: publish Helm chart to ECR

- rust/blockstore/src/memory/storage.rs
- rust/blockstore/src/types/value.rs
- rust/index/src/spann/types.rs
- rust/types/src/spann_posting_list.rs
- rust/worker/src/segment/spann_segment.rs
- Spann segment reader with from_segment impl
- ...
None
> [ENH] Introduce spann segment reader

- rust/index/src/spann/types.rs
- rust/index/src/spann/utils.rs
- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/execution/operators/spann_centers_search.rs
- rust/worker/src/segment/spann_segment.rs
- Operator for querying nearest heads for a query
- ...
None
> [ENH] rng_query_operator

- Cargo.lock
- Cargo.toml
- rust/load/Cargo.toml
- rust/load/src/opentelemetry_config.rs
Saying "with_http" isn't enough.  You need to then pass in a client.
> [BUG]  Instantiate http client for chroma-load tracing.

- rust/index/src/spann/types.rs
- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/execution/operators/spann_fetch_pl.rs
- rust/worker/src/segment/spann_segment.rs
- Operator for fetching the posting list for a given head. Currently clones the posting list. Can revisit in future if it ends up becoming a performance bottleneck.
- ...
None
> [ENH] Fetch posting list operator

- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/execution/operators/spann_bf_pl.rs
- None
-  Goes over the posting list, filters out the allowed set, sorts and returns the top k.
None
> [ENH] Brute force distances for a posting list operator

- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/execution/operators/spann_knn_merge.rs
- Implements merge amongst all the parallel posting lists and the log.
None
> [ENH] spann_merge_operator

- rust/worker/Dockerfile
Rust image builds are currently failing because an older, cached version of hnswlib is being used.
n/a
> [BLD]: invalidate the layer cache for git clone hnswlib when there's a new commit to the repo

- .github/workflows/release-chromadb.yml
Adds action to trigger deploy of Chroma Cloud after checks pass. After merging, our internal staging deployment of Distributed Chroma will be gated by our CI tests (Rust tests, Python tests, etc).
n/a
> [BLD] trigger hosted release workflow

- docs/docs.trychroma.com/components/markdoc/Heading.tsx
Vercel builds are failing, perhaps due to "JSX" deprecation.
N/A
N/A
> [DOC] Fix Vercel build failures

- .github/workflows/release-chromadb.yml
chromadb currently takes ~6m to build. Now that this build is blocking staging deploys, we should make it as fast as possible.
I'll add the var before merging.
n/a
n/a
> [BLD]: use Depot to build chromadb image

- rust/load/src/bin/chroma-load-start.rs
- rust/load/src/lib.rs
- rust/load/src/rest.rs
This PR introduces a "Throughput" type for configurable workload
oscillations.  By setting sinusoid or sawtooth throughputs, you can vary
the workload automatically as a function of its runtime.
> [ENH]  Sinusoid and sawtooth load patterns for chroma-load.

- rust/load/src/bit_difference.rs
- rust/load/src/config.rs
- rust/load/src/data_sets.rs
- rust/load/src/lib.rs
Serialize the running workloads to a JSON blob when the configuration
option `persistent_state_path` is set to a non-None value.
> [ENH] chroma-load can save and restore running workloads to survive restarts.

- rust/wal3/README.md
- rust/wal3/src/manifest.rs
- rust/wal3/src/manifest_manager.rs
Low volume writers would hang indefinitely, permanently.
Details in the comments above the change.
> [BUG]  Fix a bug in wal3 manifest snapshots.

- Tiltfile
- go/Dockerfile
- go/Dockerfile.migration
- go/cmd/logservice/main.go
- k8s/distributed-chroma/values.yaml
Currently, we build the log service from a `main.go` that lives in our private repository. This `main` package imports code from here in `./go`. Instead of having this weird split world, this syncs the few differences from the private repository (those from the `./go/Dockerfile` and using a "sharedOtel" import for the gRPC service) to here. There is also a change in the private repository to remove all the dead/duplicated code that we no longer need. This other change also updates the build to use this code entirely instead of the `main` package that was defined over there. 
- Manual `docker build` and `docker run`
- `tilt up`
- not needed
> [BLD] Sync internal log service changes to OSS

- rust/load/src/lib.rs
- rust/load/src/opentelemetry_config.rs
To fend off the possibility of overloading honeycomb budgets, I've
implemented metrics visibility.  Tracing relegated to ERROR and above
via open telemetry and INFO via stdout.
> [ENH]  Metrics-only support.

- go/shared/otel/main.go
This log line doesn't say much, and it causes lots of events to otel.
> [CHORE]  Remove a useless and expensive log line.

- docs/docs.trychroma.com/components/markdoc/Heading.tsx
> [DOC] Fix vercel build fail

- .github/workflows/apply-hotfix.yaml
- .github/workflows/pr.yml
- .github/workflows/trigger-deploy.yaml
Updates workflows for new deploy process. Depends on https://github.com/chroma-core/chroma/pull/3294.
Prototyped workflows in test repositories.
n/a
> [BLD]: update deploy workflows

- go/pkg/log/repository/log.go
- go/pkg/sysdb/grpc/collection_service.go
- go/pkg/sysdb/grpc/segment_service.go
- go/pkg/sysdb/grpc/tenant_database_service.go
- go/pkg/sysdb/metastore/db/dao/collection.go
- go/pkg/sysdb/metastore/db/dao/segment.go
- go/pkg/sysdb/metastore/db/dao/tenant.go
- rust/worker/src/log/log.rs
- Removes a few msgs that get logged in the happy path every 10 secs
None
> [ENH] Remove log messages in happy hot paths

- .github/workflows/trigger-deploy.yaml
Prevents distributed Chroma workflows from being triggered by release/$version_number.
Tested in private repo.
n/a
> [ENH]: stricter release/* & rc/* branch trigger

- rust/load/src/bin/chroma-load-start.rs
- rust/load/src/bin/chroma-load-stop-all.rs
- rust/load/src/lib.rs
Staring was failing with a 400 that was really a 404.  This PR changes
that case to a 404 instead of 400 and prints the body in the
chroma-load-start tool.  Also, a tool to stop all workloads.
> [ENH]  Make the error messages out of chroma-load decipherable.

- chromadb/proto/convert.py
- chromadb/proto/query_executor_pb2.py
- chromadb/proto/query_executor_pb2.pyi
- idl/chromadb/proto/query_executor.proto
- rust/types/src/segment.rs
- rust/worker/src/server.rs
- N/A
- Propagate full segment information from frontend to query node
N/A
> [ENH] Propagate segment information from frontend to query node

- clients/js/src/ChromaClient.ts
- clients/js/src/index.ts
- clients/js/src/types.ts
- clients/js/test/collection.client.test.ts
Users want to use "Collection" for type annotations, but it is not being exported from the js-client.
N/A
> [ENH] Export Collection type directly

- chromadb/server/fastapi/__init__.py
Closes #3309
- Removes body parameters from API routes, adds OpenAPI extras to preserve API docs
- Update the response classes for exceptions to use ORJSON instead of JSON response objects
N/A
> [PERF]: Fixing double deserialization issue - 30% performance improvement

- go/pkg/sysdb/grpc/collection_service.go
This one log line generates 2kiB of log for each get.  Probably not
worth keeping around right now.
> [CHORE]  Snip a log line that's happy-path and too verbose.

- rust/load/src/opentelemetry_config.rs
The sheer volume of output requires more CPU for a terminal to render
than chroma-load consumes (kiB written per query).  I'm betting it's a
good approximation for what's happening in production.
> [BUG]  Update chroma-load to only output errors to stdout.

- rust/blockstore/src/arrow/block/types.rs
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/memory/reader_writer.rs
- rust/blockstore/src/memory/storage.rs
- rust/blockstore/src/types/reader.rs
- rust/worker/src/execution/operators/limit.rs
- rust/worker/src/segment/record_segment.rs
- N/A
- Implement `rank(prefix, key)` method for blockfile, which calculates the number of elements in the blockfile that is strictly less than the given prefix-key pair. In otherword, the given prefix-key pair can be inserted at its rank without breaking the order of the blockfile.
- Use the `rank(prefix, key)` method to replace `get_at_index(index)` in `LimitOperator` and `RecordSegmentReader`.
> [ENH] Implement rank() for blockfile

- rust/blockstore/src/arrow/block/types.rs
- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/sparse_index.rs
- rust/blockstore/src/memory/reader_writer.rs
- rust/blockstore/src/memory/storage.rs
- rust/blockstore/src/types/reader.rs
- Deprecate blockfile `get_at_index` method
- N/A
> [CLN] Deprecate blockfile get_at_index()

- .gitignore
- These are generated at build time now
None
> [ENH] Ignore proto files generated by Go

- .github/workflows/_python-tests.yml
Increases wall time by about 2m for cluster tests, however they're still relatively fast. Say the average cluster test is 8m before this change and 10m after this change. With the minute multipler, the total # of minutes before was 64 and is now 20 (-3.2x).
n/a
n/a
> [BLD]: use lower core count for Python cluster tests

- rust/load/Cargo.toml
This updates the client to not contend within libssl.
> [ENH]  Bump to the latest chromadb-rs pr.
