chroma-core/chroma

- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/api/models/Collection.py
> Use `embedding_function` over `embedding_fn`

- chromadb/utils/embedding_functions.py
Added OpenAI as an embeddings function. Slots in easily.
> OpenAI Embeddings

- chromadb/utils/embedding_functions.py
Per OpenAI's get_embedding function here: https://github.com/openai/openai-python/blob/main/openai/embeddings_utils.py
> Remove newlines to improve performance

- .github/workflows/chroma-release.yml
For tagged releases, add the `latest` tag to the Docker image as well.
> Add `latest` tag to docker releases

- pyproject.toml
- requirements.txt
> Remove uuid since it is a part of the python std lib

- chromadb/api/models/Collection.py
- chromadb/api/types.py
- chromadb/test/test_api.py
many_to_one should check for ints as well as floats.
> Make sure to check for ints in many to one

- chromadb/utils/embedding_functions.py
This PR adds support for Cohere embeddings and supports all embedding models as per Cohere documentation (large, small, multi-lingual).
> Add support for cohere embeddings

- chromadb/db/clickhouse.py
- chromadb/db/index/hnswlib.py
- chromadb/test/test_api.py
Make sure the index is loaded before checking dimensionality
Cannot reproduce in tests which is why this is currently a draft PR
None
> Make sure the index is loaded before checking dimensionality

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/api/models/Collection.py
- chromadb/api/types.py
- chromadb/db/__init__.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/server/fastapi/__init__.py
- chromadb/server/fastapi/types.py
- chromadb/test/test_api.py
This PR adds support for includes field on get calls.
- Add validation for includes in query and get
- Refactor shared logic out
- Ability to pass includes flag to collection.get() calls to selectively return fields
Added tests for the new functionality
All docstrings are updated. Will update API documentation in a PR against docs!
> Add support for get includes

- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/server/fastapi/types.py
Addresses #160
- Update list type for older python
- None
No new tests required.
None needed.
> Update list type for older python

- examples/where_filtering.ipynb
- None
- Added an example for filtering
Running the notebook is test :) 
Yes!
> Add filtering example

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/db/__init__.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/server/fastapi/__init__.py
- chromadb/server/fastapi/types.py
- chromadb/test/test_api.py
- This PR is courtesy of @FanaHOVA (#120)!!! I am just cleaning up a few things and adding some additional testing
New tests were added to handle get_or_create with persistence and an embedding function as well as just get_or_create.
All docstrings are up to date.
Doc page changes are in this PR -> https://github.com/chroma-core/docs/pull/5
> get_or_create

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/local.py
- chromadb/db/__init__.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
A lot of our internal code is untyped, this take a step towards adressing that.
- Adds typing along core code paths
- None
Existing tests, this is just typing changes.
None required.
> Typing overhaul

- chromadb/server/fastapi/types.py
- clients/js/package.json
- clients/js/src/generated/models/create-collection.ts
- clients/js/src/generated/models/delete-embedding.ts
- clients/js/src/generated/models/get-embedding.ts
- clients/js/src/generated/models/query-embedding.ts
- clients/js/src/index.ts
- clients/js/test/client.test.ts
This PR includes some small improvements to our JS types
> small improvements to JS types

- chromadb/api/models/Collection.py
- chromadb/api/types.py
- chromadb/test/test_api.py
- Closes #185 - errors when ids are not strings. 
- None
Tests were added for the error-checking
None required.
> ID validation

- chromadb/db/index/hnswlib.py
Added the missing f to an f-string in a logging message
> Fixed F-string in logging message

- chromadb/__init__.py
- chromadb/api/local.py
- chromadb/api/types.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/test/test_api.py
- chromadb/utils/embedding_functions.py
- Unifies error messages across the project to make them more useful and consistent
- Improves the error message for invalid collection names
> Unified error messages

- chromadb/api/types.py
- chromadb/db/clickhouse.py
> fixed typos

- README.md
just taking a stab
before/after
- readability
- more code upfront, pple like code
- be more aggressive explainining Chroma api upfront
> [docs] Readme Refactor

- chromadb/utils/embedding_functions.py
I was using OpenAI's ada-002 before, and switched to instructor-xl after comparing both against my tweets and my emails. For my purposes, instructor-xl seems to be at least as good.
https://huggingface.co/hkunlp/instructor-xl
The huggingface benchmarks support my impression.
https://huggingface.co/spaces/mteb/leaderboard
> Added function for the Instructor models.

- clients/js/DEVELOP.md
programatically -> programmatically
> fix typo in DEVELOP.md

- .github/workflows/chroma-release.yml
- RELEASE_PROCESS.md
- chromadb/__init__.py
Bump version for release
- None
- None
Existing tests
None
> Release 0.3.13

- chromadb/__init__.py
- chromadb/db/duckdb.py
closes https://github.com/chroma-core/chroma/issues/241
> create persist dir if not exist, correct logging of persistence

- .gitignore
- examples/deployments/google-cloud-compute/README.md
- examples/deployments/google-cloud-compute/chroma.tf
- examples/deployments/google-cloud-compute/main.tf
- examples/deployments/google-cloud-compute/startup.sh
- examples/deployments/google-cloud-compute/variables.tf
- Google Cloud Compute Deployment with terraform example
> Google Cloud Compute deployment example

- chromadb/db/duckdb.py
Closes https://github.com/chroma-core/chroma/issues/242
thank you to @TadaoYamaoka for finding this!
> fixes the log for persist

- chromadb/db/index/hnswlib.py
- chromadb/test/test_api.py
Foolish inverted logic bug that wasn't covered by tests.
Added a unit test that inserts enough index data to provoke and index resize.
No documentation changes required.
> Fix index resize bug

- chromadb/__init__.py
> Bump version

- chromadb/__init__.py
> Version 0.3.17

- chromadb/__init__.py
> Release 0.3.18

- chromadb/__init__.py
Release 0.3.20 since 0.3.19 didn't release successfully, and cannot be re-released without special-casing the deployment code.
No changes to functionality.
No changes to documentation
> Increment version to 0.3.20

- .vscode/settings.json
- chromadb/__init__.py
- chromadb/api/models/Collection.py
- chromadb/api/types.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/db/index/hnswlib.py
- chromadb/server/fastapi/types.py
- chromadb/telemetry/__init__.py
- chromadb/test/test_api.py
- chromadb/utils/embedding_functions.py
- Adds the flake8 linter configured to run with black in vscode
- Fix the linter errors. It already caught one bug!
- None
Existing tests, no functional changes.
None needed.
> Add flake8 linter, address linter issues

- chromadb/__init__.py
Release 0.3.21
Existing tests
None
> Release 0.3.21

- chromadb/api/local.py
Allow capital letters in collection names 🤪 
Property tests.
None required, behavior now matches existing documentation.
> Allow capital letters in collection names

- bin/integration-test
Adds the current JS tests to CI
> add running js tests, currently all pass

- .vscode/settings.json
- chromadb/api/local.py
- chromadb/test/property/invariants.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_collections.py
- chromadb/test/property/test_update.py
This adds a basic, minimal ANN invariant to our Hypothesis test suite. 
I've tried to make these tests green with no modifications to Chroma itself. This exposes a bunch of implicit assumptions about the API, which is good because that's what we wanted these tests to do. 
I've marked those as #TODO - I would like to keep track of those somewhere, we can discuss where exactly here. 
@levand helped me figure out how to prevent Hypothesis from generating too much data. The current solution seems OK for the time being but we'll probably want to improve on it. 
Run the tests. 
N/A
> Minimal ANN Accuracy Invariant and Collection.add()

- README.md
[docs] add replit template to readme
- ...
- ...
> [docs] add replit template to readme

- .github/ISSUE_TEMPLATE/bug_report.yaml
this was copied form template and feels unnecessarily invasive
- ...
- ...
> remove contact question from github issue template

- chromadb/utils/embedding_functions.py
Make api_key parameter in  OpenAIEmbeddingFunction optional so that it fallbacks onto environment variable
None required
None required
> make api_key in OpenAIEmbeddingFunction optional

- chromadb/api/local.py
- chromadb/api/types.py
- chromadb/errors.py
- chromadb/test/configurations.py
- chromadb/test/property/invariants.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_collections.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/test_api.py
Tests for adding/deleting embeddings using a Hypothesis state machine
These are the tests
N/A
> State machine tests for embeddings in a collection

- chromadb/api/local.py
- chromadb/db/clickhouse.py
- chromadb/db/duckdb.py
- chromadb/test/configurations.py
- chromadb/test/property/invariants.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/property/test_persist.py
- Adds a state machine for persistence tests.
These are the tests.
None required. The existing documentation covers persist-on-exit behavior.
> Persist state machine

- .github/workflows/chroma-integration-test.yml
- chromadb/test/property/invariants.py
Seperate integration tests into their own github actions
No tests required. 
No documentation changes required.
> Seperate integration tests into their own github actions

- chromadb/test/configurations.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_filtering.py
Add property tests for `where`, `where_document` and `ids` in `get`.
Also makes generation slightly more efficient so hopefully will avoid `Unsatisfiable` errors we're seeing in CI on lukev/collection-contents-strategy.
These are the tests.
N/A
> Hypothesis-based tests for filter

- chromadb/test/configurations.py
- chromadb/test/property/conftest.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_collections.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/property/test_persist.py
Move fixtures to conftest.py so they are shared.
Existing tests pass!
None
> Combine fixtures

- chromadb/test/property/invariants.py
Check if the results in the ann invariant are sorted
These are tests!
None
> Ensure ann invariant results are sorted

- chromadb/api/models/Collection.py
- chromadb/test/property/invariants.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/property/test_filtering.py
- chromadb/test/property/test_persist.py
Our APIs support adding individual values for IDs, embeddings, metadatas and documents as well as lists of values.
This PR exercises this functionality in the context of the Hypothesis property tests
These are the tests
N/A
> Test unwrapped values

- .github/workflows/chroma-integration-test.yml
- .github/workflows/chroma-test.yml
- README.md
Current CI config had a bug causing a single runner to run all the tests, defeating the purpose of partitioning them.
These are the tests.
N/A
> Fix glob syntax in CI config

- .github/workflows/pr-review-checklist.yml
Adds a checklist
Manually in github.
None
> PR checklist

- chromadb/api/models/Collection.py
- fixes #407 
Checked with minimal example (see snippets in #407).
N/A
> check for none instead of truth for optional array arguments

- chromadb/__init__.py
> Upgrade to 0.3.22

- chromadb/db/index/hnswlib.py
Fixes types in hnswlib.py
Existing tests should catch any issues with non-working types. But this is only type changes and no logic changes to the surface area is minimal.
None required.
> Fix types in hnswlib.py

- DEVELOP.md
Update developer information to match user site.
> Add Python 3.10.0 note to DEVELOP.md

- examples/alternative_embeddings.ipynb
Add an example notebook to demonstrate using both openai & cohere embeddings with the 'getting started' example from docs
n/a
n/a
> Add example demonstrating using openai & cohere embeddings

- chromadb/__init__.py
- chromadb/api/__init__.py
- chromadb/errors.py
- chromadb/server/__init__.py
- chromadb/server/fastapi/__init__.py
- chromadb/server/fastapi/types.py
Fix types in fastapi server and related files
Existing tests
None required.
> Fix types in fastapi server and related files

- clients/js/package.json
Bump npm to 1.4.2 for release today
> bump to 1.4.2.

- chromadb/__init__.py
> Release 0.3.24

- chromadb/test/property/invariants.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/property/test_filtering.py
- chromadb/test/property/test_persist.py
Adds yet more types to our tests. Involves some refactorings and introduces some new types. 
These are the tests. 
N/A
> Yet more test types

- .pre-commit-config.yaml
- chromadb/test/property/invariants.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/property/test_embeddings.py
- chromadb/test/property/test_filtering.py
- chromadb/test/property/test_persist.py
Adding types to more tests. 
These are the tests 
N/A
> More types in tests

- requirements.txt
-  Removed double posthog from requirements.txt
-  Fixed https://github.com/chroma-core/chroma/issues/616
> Fixed #616

- chromadb/config.py
#629 was left unfinished, this completes the merge to support thin client error'ing.
Existing tests
None required.
> Finish merged TODO to merge in thin client

- clients/js/src/types.ts
- Fix incorrect types for `embeddings` and `distances` in `QueryResponse`
- closes: #660 
Tests ran and passed
None
> Fix incorrect types in QueryResponse

- chromadb/__init__.py
> Release 0.3.26

- chromadb/test/property/test_embeddings.py
The SQLite implementation does not emit an exception to the API when there are duplicate IDs on `add`. This updates the tests to reflect that. 
In future, we should instead consider making upsert and delete the only API operations. 
This is the test 
None, however we should update the documentation when this branch lands.
> Fix multi-add property test for SQLite

- requirements.txt
easy typo fix
- just remove a duplicate requirement
seems reasonable to me
N/A
> [easy] remove duplicate pypika from requirements.txt

- chromadb/utils/embedding_functions.py
Related issue: #594
- HuggingFaceEmbeddingFunction: fix wrong return type from List to List[List]
- GoogleVertexEmbeddingFunction: fix wrong return type of empty dict to empty List
> fix wrong return type

- clients/js/src/types.ts
> fix JS Where type, closes #718

- examples/deployments/google-cloud-compute/chroma.tf
- examples/deployments/google-cloud-compute/startup.sh
- Terraform definition was not correct, and Docker containers would not boot up
- Missing firewall definition to the outside world
Run
```angular2html
terraform apply -var="project_id=<your_project_id> -auto-approve"
```
> fix(gcp): fixed terraform definitions for gcp example

- clients/js/examples/browser/app.ts
- changes the client usage in example
> update client usage in example 

- clients/js/src/embeddings/CohereEmbeddingFunction.ts
- Fixes cohere embeddings not using the api key.
* I tested that cohere embeddings returned a result
* Without this change the result is undefined
no
> fix cohere api key

- clients/python/README.md
found b/c of this PR against docs https://github.com/chroma-core/docs/pull/91
> fix port str

- clients/js/package.json
> bump JS to fix cohere embedding function

- pyproject.toml
Pydantic and fastapi don't validate our types the same way in future versions, as a hotfix, hardpin to known good versions.
Existing tests.
None required.
> Hardpin pyproject.toml to fix #774

- chromadb/__init__.py
> Release 0.3.27

- chromadb/__init__.py
- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/segment.py
- chromadb/test/test_client.py
Adds clean clients based on #741 and as disccused in #714 
New tests based on #741 
We will need to add documentation for the shortcutted clients.
> Clean clients

- chromadb/api/__init__.py
- chromadb/api/fastapi.py
- chromadb/api/local.py
- Updated and cleaned up all the Docstrings on the API Abstract Base Class 
- Removed all the shadowing docstrings from the concrete API implementations 
N/A - No functional change
This is a documentation change.
> API ABC Docstrings

- chromadb/__init__.py
> Release 0.4.0

- bin/generate_cloudformation.py
Update the cloud formation template to run properly without clickhouse dependencies 
Manually ran the cloud formation generation script.
None
> Fix cloud formation template

- chromadb/__init__.py
> Release 0.4.1

- chromadb/__init__.py
> Release 0.4.2

- chromadb/__init__.py
> Bump to 0.4.3

- .github/workflows/chroma-client-integration-test.yml
- .github/workflows/chroma-integration-test.yml
- .github/workflows/chroma-test.yml
- bin/windows_upgrade_sqlite.py
- chromadb/db/impl/sqlite.py
- chromadb/test/property/test_cross_version_persist.py
- chromadb/test/property/test_persist.py
- chromadb/test/test_api.py
- chromadb/utils/delete_file.py
Addresses #887
- Adds windows to github test runners
- ...
These are tests.
None required.
> Add windows tests

- DEVELOP.md
> switch to new clients for DEVELOP.md

- chromadb/utils/embedding_functions.py
Fix the bug that causes functionality to be unavailable when using azure-openai due to missing api version parameter. 
openai examples: https://github.com/openai/openai-cookbook/blob/main/examples/azure/embeddings.ipynb
- ...
fix https://github.com/chroma-core/chroma/issues/698
> add azure openai api_version param

- chromadb/api/segment.py
- chromadb/segment/impl/vector/local_persistent_hnsw.py
- chromadb/test/conftest.py
- chromadb/test/property/invariants.py
- chromadb/test/property/test_embeddings.py
- Fixes #907 
Added tests to excercise get() in test_embeddings state machine. Add a unit test for get with nonexistent
None required
> Fix bug in get_vectors() by properly merging

- chromadb/__init__.py
> Release 0.4.4

- chromadb/__init__.py
> Release 0.4.5

- examples/basic_functionality/where_filtering.ipynb
- Added enhanced examples of how to use `where` filtering with logical operators based on community questions
Run the jupyter notebook `examples/basic_functionality/where_filtering.ipynb`
No document updates.
> Where filtering with logical operators - updated examples

- chromadb/api/models/Collection.py
- https://github.com/chroma-core/docs/pull/98 Landed documentation fixes to address this but modified documentation generated from the code. This PR amends the code to be correct so that subsequent generations are correct.
- N/A
Not needed.
In v0.4.6 we should regen API docs and release.
> [DOC] Fix where documentation

- chromadb/config.py
> better resetting error messaging

- chromadb/__init__.py
> Release 0.4.6

- README.md
- pull_request_template.md
- Add contributing guide to readme and a check if tests pass to PR template
- None
Addresses #968
These are documentation changes. No tests required.
These are documentation changes.
> [DOC] Add contributing guide to readme and check if tests pass to PR template

- chromadb/__init__.py
> Release 0.4.7

- bin/integration-test
- chromadb/config.py
- clients/js/package.json
- clients/js/src/ChromaClient.ts
- clients/js/src/auth.ts
- clients/js/test/auth.basic.test.ts
- clients/js/test/initClientWithAuth.ts
- docker-compose.test-auth.yml
Refs: #1026
- Auth abstractions
- Basic auth supported
Yes docs need to be updated to provide information how to configure auth with the JS client.
> [ENH]: JS Client Support for Auth

- chromadb/config.py
- clients/js/src/embeddings/OpenAIEmbeddingFunction.ts
- clients/js/test/add.collections.test.ts
Refs: #1038
- Added support for both v3 and v4 of the OpenAI node library
`yarn test` 
TBD
> [ENH]: OpenAI npm package v4 breaking changes

- chromadb/utils/distance_functions.py
- Reduced unnecessary complexity. Replaced lambdas to def.
tests run successfully. There should be no additional ut-s. Client/calling code for the changed names is not changed. 
* added docstring to module.
> [CLN] replaced lambdas with def

- docs/cip/CIP-1_Allow_Filtering_for_Collections.md
This diff adds CIP-1 Allow Filtering for Collections
- ...
- ...
> Add CIP-1 Allow Filtering for Collections

- .github/workflows/chroma-js-release.yml
- clients/js/DEVELOP.md
- clients/js/package.json
- Adds release automation for JS client. 
They will have to be tested after merging this PR
Update the js client Develop guide for how to use this automation.
> [BLD] Add release automation for JS client

- .github/workflows/chroma-js-release.yml
- Add working directory to npm run js
- ...
These must be tested after merge, this is an iteration on #1091 
None required.
> [BLD] Add working directory to npm run js

- .github/workflows/chroma-release-python-client.yml
- .github/workflows/chroma-release.yml
- Prevent python release from running on js tag pushes
Manually on main via triggering
None
> [BLD] Prevent python release from running on js tag pushes

- .github/workflows/chroma-js-release.yml
- Properly use github_env to pass env vars across steps 
- https://docs.github.com/en/github-ae@latest/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
Will be manually tested, this is an iteration on #1093 
None
> [BLD] Release env vars save to GITHUB_ENV

- .github/workflows/chroma-js-release.yml
Add install deps to JS release workflow
> [BLD] Add install deps to JS release workflow

- .github/workflows/chroma-js-release.yml
- Add npm run db:run to run docker-compose up
- ...
Will be tested manually. This is an iteration on #1095 .
None
> [BLD] Add npm run db:run to run docker-compose up

- clients/js/package.json
> [RELEASE] Release JS 1.5.7

- bin/build
closes https://github.com/chroma-core/chroma/issues/1003
> remove unused bin/build

- chromadb/__init__.py
> [RELEASE] Release 0.4.9

- .github/workflows/chroma-release.yml
- Pushes images to dockerhub
Will have to be tested on main as part of CI/CD
None required.
> [BLD] Add dockerhub support

- chromadb/segment/impl/metadata/sqlite.py
- Fixed an issue where list values for In/Nin that are not wrapped with pypika ParameterValue will result in floating point comparisons failure after a certain precision threshold.
N/A
> [BUG]: Issue where In/Nin list values

- examples/deployments/google-cloud-compute/README.md
- examples/deployments/google-cloud-compute/chroma.tf
- examples/deployments/google-cloud-compute/main.tf
- examples/deployments/google-cloud-compute/startup.sh
- examples/deployments/google-cloud-compute/variables.tf
- Added external volume for Chroma data
- Bumped to the latest version (0.4.9)
- Added auth by default
- Made the template more configurable via variables with sensible defaults
- Tested with terraform
The update contains README with docs.
> [ENH] Added auth and external volume support for GCP

- .github/actions/bandit-scan/Dockerfile
- .github/actions/bandit-scan/action.yaml
- .github/actions/bandit-scan/entrypoint.sh
- .github/workflows/python-vuln.yaml
- bandit.yaml
- Added bandit scanning for all pushes to repo
Manual testing of the workflow
N/A - unless we want to start a separate security section in the main docs repo.
> [SEC]: Bandit Scan

- chromadb/auth/providers.py
- chromadb/test/property/test_embeddings.py
- Improvements 
- simplified ut-s
- cleaned up a typing import
- [+] Tests passed successfully locally with `pytest` for python, `yarn test` for js
N/A
> simplified ut-s

- clients/js/package.json
Refs: #1104
- Removed transformers and web-ai peer dependencies.
N/A
> [BUG]: Fixing broken peer deps

- clients/js/package.json
> [RELEASE] JS 1.5.11

- chromadb/__init__.py
> Release 0.4.11

- chromadb/utils/read_write_lock.py
- Fixes #1198 about notifyAll deprecation
> [Bug]: Fix notifyAll deprecation

- examples/deployments/common/startup.sh
- examples/deployments/do-terraform/README.md
- examples/deployments/do-terraform/chroma.tf
- examples/deployments/do-terraform/variables.tf
- Full deployment of a Chroma on a DO droplet with attached volume
Manually tested.
Docs are in the deployment README.md
> [ENH]: DO deployment blueprint

- bin/integration-test
- An issue was introduced in the integration tests where Python testing with `pytest` was commented out (bug introduced with #1114)
N/A
> [BUG]: Emergency Fix Integration Tests

- chromadb/__init__.py
> [RELEASE] 0.4.14

- .gitattributes
- Edit .gitattributes to collapse generated files (https://thoughtbot.com/blog/github-diff-supression)
- ...
*Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the [docs repository](https://github.com/chroma-core/docs)?
None required*
> [CLN] Add gitattributes entry to mark generated files

- chromadb/__init__.py
> [RELEASE] 0.4.15

- chromadb/test/property/test_collections.py
- Fix minor bug in tenant state machine to be sure we always reference the model
- N/A
These are test changes
None required.
> [BUG][TST] Fix bug in tenant state machine test

- go/coordinator/internal/coordinator/coordinator.go
Use in-memory catalog so we can start integration testing things. We'll need to add flags to decide which catalog to use in the very near future.
- CI
> Use in-memory catalog

- chromadb/auth/fastapi.py
- We map attributes from AuthN's user identity to AuthzUser so that they can be passed to authz provider
N/A
> [ENH]: Added user attributes mapping from identity to AuthzUser

- chromadb/auth/__init__.py
- chromadb/auth/fastapi.py
- chromadb/auth/fastapi_utils.py
- chromadb/server/fastapi/__init__.py
- examples/basic_functionality/authz/authz.ipynb
- Added attribute injection hook to add database and tenant to authz resource attributes
N/A
> [ENH]: Authz tenant and DB resource attribute hook

- chromadb/server/fastapi/__init__.py
- Added a missing attribute extraction required for list_collections to properly be authorized
N/A
> [ENH]: Missing authz resource attribute extraction to `list_collections`

- clients/js/package.json
> 1.6.1 commit for JS release

- chromadb/api/segment.py
- chromadb/test/property/test_filtering.py
> [BUG] Fix bug in metadata join

- chromadb/telemetry/product/events.py
- Batch posthog requests much more aggressively. We really should do batches of ever-increasing size for a given collection but I want to get this fix out this week.
- ...
> More Posthog batching

- chromadb/api/client.py
- Add a better error message for HTTPClient connection errors during tenant/db validation on startup
- N/A
> [ENH] Add a better error message for HTTPClient connection errors

- chromadb/__init__.py
> [RELEASE] 0.4.16

- chromadb/__init__.py
> [RELEASE] 0.4.17

- chromadb/server/fastapi/__init__.py
- chromadb/telemetry/opentelemetry/fastapi.py
- pyproject.toml
- requirements.txt
- ...
- Added FastAPI OTEL instrumentation; this leads to much more consistent and cohesive traces (before, we had some disjoint traces as the context was not contiguous, from top to bottom)
N/A
> [ENH]: FastAPI Instrumentation for improved traceability

- chromadb/api/segment.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/auth/test_simple_rbac_authz.py
- Fixed an issue where get_collection in the segment was mapping returning the originally passed DB and tenant
N/A
> [BUG]: DB and tenant not properly mapped on get_collection

- chromadb/api/__init__.py
- Fixes #478 with better documentation for confusing behavior. This is the discussed solution for this for now.
- None
This is just a doc change
This is just a doc change
> [BUG] Fix #478

- chromadb/segment/impl/distributed/segment_directory.py
- chromadb/segment/impl/distributed/server.py
- Makes proxies route to the correct worker
- ...
> [ENH] Proxy assignment

- chromadb/utils/embedding_functions.py
- Fixes https://github.com/chroma-core/chroma/issues/1385
- ...
Got a Cohere API key and repro'd the issue locally. With this change, calling the embedding function no longer breaks.
> Pass input_type to cohere embedding models

- go/coordinator/internal/metastore/db/dbcore/core.go
> [BUG] Fix Postgres connection

- docs/CIP_2_Auth_Providers_Proposal.md
- docs/CIP_Chroma_Improvment_Proposals.md
> [BUG] Fix typos

- go/coordinator/Dockerfile
- Fix go build issue due to https://github.com/mattn/go-sqlite3/issues/1164#issuecomment-1848677118
- ...
> [BUG] Fix go build due to sqlite dependency

- go/coordinator/Dockerfile
- Install jq in coordinator docker image. This lets us escape DB passwords which is required per https://atlasgo.io/concepts/url#non-alphanumeric-characters
> Install jq in Coordinator docker image

- go/coordinator/Dockerfile
- Add `findutils` to Coordinator docker image. This gives us useful utilities to use to administer the coordinator and debug the production deployment.
> Add xargs to coordinator

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/src/config.rs
- rust/worker/src/lib.rs
Dupe of #1500, which I accidentally mistacked not onto main. This was approved so merging it here without approval. Refer to #1500 for PR description etc.
> [ENH] Add Rust Configuration

- .github/workflows/chroma-worker-test.yml
- rust/worker/Dockerfile
- /
- Adds a github action for rust CI
- Adds a basic dockerfile, in this pr it just runs cargo test by default.
None required.
> [CHORE] Add Rust CI & Basic Dockerfile

- chromadb/__init__.py
> Release 0.4.19

- chromadb/auth/fastapi.py
- Make sure `database` isn't `None` before reading its length.
- Overwrite the `name` field of `CreateTenant` and `CreateDatabase` objects. I'm not sure the correct long-term solution here; everything I can think of feels pretty hacky.
> [BUG] Bugfixes in auth overwrite

- clients/js/src/ChromaClient.ts
- clients/js/src/CloudClient.ts
- clients/js/src/index.ts
- clients/js/test/auth.token.test.ts
- clients/js/test/initClientWithAuth.ts
- Adds CloudClient convenience wrapper - similar to https://github.com/chroma-core/chroma/blob/3939974e811cbca1737c949f1136829a9d0b5c62/chromadb/__init__.py#L185
> CloudClient support

- clients/js/package.json
peer dependency @google/generative-ai
> JS Client: peer dependency @google/generative-ai

- clients/js/package.json
1.7.2 bump to release google optionalDep
> 1.7.2 bump

- go/coordinator/internal/metastore/db/dao/collection_test.go
- This fixes TestCollectionDb_GetCollections
- ...
> [BUG] Fix failing TestCollectionDb_GetCollections

- chromadb/api/models/Collection.py
- chromadb/test/test_api.py
> [BUG] Raise exception when attempting to change DF 

- go/coordinator/internal/coordinator/apis_test.go
- go/coordinator/internal/coordinator/meta_test.go
- go/coordinator/internal/grpccoordinator/collection_service_test.go
- go/coordinator/internal/metastore/coordinator/memory_catalog_test.go
- go/coordinator/internal/metastore/coordinator/table_catalog_test.go
- go/coordinator/internal/metastore/db/dbcore/core.go
> [BUG] Fix SysDB related CI tests failure

- go/coordinator/internal/memberlist_manager/node_watcher.go
- This fixes data race detected by make test and CI
- ...
> [BUG] Fix data race issue in memberlist

- chromadb/__init__.py
> Release 0.4.21

- .github/workflows/chroma-cluster-test.yml
- Run SysDB Tests in minikube cluster in CI. They were not previously running.
- None.
> [BUG] Run SysDB Tests in minikube cluster in CI

- clients/python/requirements_dev.txt
Reverts chroma-core/chroma#1561
Broke a lot of CI
> Revert "[BUG]: Fix for failing chromadb-client build"

- chromadb/utils/embedding_functions.py
Changes identity `is` to equality `==` check
> identity to equality check

- chromadb/__init__.py
> Release 0.4.22

- rust/worker/chroma_config.yaml
- rust/worker/src/ingest/ingest.rs
- rust/worker/src/lib.rs
- rust/worker/src/sysdb/mod.rs
- rust/worker/src/sysdb/sysdb.rs
- Fix a typo in ingest
- Adds the rust sysdb
Some cleanup is TODO - will address in this PR 
No tests were added. I will add an integration test for this.
None
> [ENH] Rust SysDB

- go/coordinator/internal/utils/pulsar_admin.go
- idl/chromadb/proto/chroma.proto
- k8s/deployment/segment-server.yaml
- k8s/test/coordinator_service.yaml
- k8s/test/minio.yaml
- k8s/test/pulsar_service.yaml
- k8s/test/segment_server_service.yml
- rust/worker/Dockerfile
- rust/worker/chroma_config.yaml
- rust/worker/src/config.rs
- rust/worker/src/ingest/ingest.rs
- rust/worker/src/lib.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
- rust/worker/src/segment/segment_manager.rs
- rust/worker/src/server.rs
- rust/worker/src/sysdb/sysdb.rs
- rust/worker/src/types/embedding_record.rs
- Adds the grpc connections for the worker
- /
> [ENH] Add rust grpc server

- examples/chat_with_your_documents/main.py
- examples/chat_with_your_documents/requirements.txt
- Update openai call to use the new api (#1640 )
Tested locally. 
```➜  chat_with_your_documents git:(nicolas/fix-bug-openai-deprecated-chat-api-example) ✗ pyenv exec python main.py
Do you want to use GPT-4? (y/n) (default is gpt-3.5-turbo): 
Query: What was said about the pandemic?
Thinking using gpt-3.5-turbo...
Based on the provided context, it is mentioned that the pandemic has been punishing and that there was progress made in fighting against the pandemic. The context also mentions that children were struggling before the pandemic with issues such as bullying, violence, trauma, and the harms of social media. It further states that COVID left its scars, including a spike in violent crime in 2020. Additionally, the pandemic disrupted global supply chains.
Therefore, based on the …
```
> [BUG] update openai api in example (#1640)

- chromadb/server/fastapi/__init__.py
- On shutdown event system.stop() is called to properly stop all components
N/A
> [ENH]: FastAPI Shutdown hook

- go/coordinator/internal/coordinator/meta.go
- The coordinator did not respect find by id queries if they were given without tenant and database, this breaks auth in the FE server when it tries to resolve a collections tenant and database.
- /
> [BUG] Coordinator - Find by id

- rust/worker/src/memberlist/memberlist_provider.rs
> Rust worker memberlist logs

- rust/worker/src/ingest/ingest.rs
> More rust logs

- .pre-commit-config.yaml
- mypy.ini
- pyproject.toml
- minor reducing the number of config files to maintain
N/A
> [CHORE]: Moved mypy config from .ini to pyproject.toml

- rust/worker/src/ingest/ingest.rs
> Add rust worker logs

- rust/worker/chroma_config.yaml
> [BUG] change rust tenant to default

- DEVELOP.md
- Tiltfile
- k8s/dev/coordinator.yaml
- k8s/dev/pulsar.yaml
- k8s/dev/server.yaml
- k8s/dev/setup.yaml
- k8s/dev/worker.yaml
Use tilt for local end to end dev. It is a v1 (Without debugging instruction, optimized docker image etc)
> Tilt setup for local dev

- chromadb/db/migrations.py
> FIPS Compliance

- chromadb/api/types.py
- chromadb/test/property/test_embeddings.py
- clients/js/test/add.collections.test.ts
Refs: #1698
- Added validation for 0-dimensional embeddings
N/A
> [BUG]: Disallowing 0-dimensional embeddings

- go/coordinator/Dockerfile
- Make dockerfile build faster for coordinator
With tilt, locally
> [ENH]: update coordinator docker for faster build

- chromadb/__init__.py
> [RELEASE] 0.4.23

- .github/workflows/check-pr-title.yml
- Add title checker to CI
- ...
> [ENH] Add PR title checker

- .github/workflows/check-pr-title.yml
- I think this fixes the PR title checker regex
> [BUG] Fix PR title regex

- .github/workflows/check-pr-title.yml
- Turn PR title checker back on. I accidentally disabled it by munging the regex
> [CLN] Turn PR title checker back on :/

- chromadb/auth/fastapi.py
- chromadb/auth/fastapi_utils.py
- chromadb/server/fastapi/__init__.py
- chromadb/test/client/create_http_client_with_basic_auth.py
- chromadb/test/client/test_create_http_client.py
- chromadb/utils/fastapi.py
- Fixes https://github.com/chroma-core/chroma/issues/1554 (again)
> [BUG] Fix circular import when initializing a client with basic auth

- chromadb/quota/__init__.py
- chromadb/server/fastapi/__init__.py
- Fixing a bug with quota error handling on the fast API server
> [BUG]: fix server quota error handling

- .github/workflows/check-pr-title.yml
- Add "release" to PR title chceker
> [BUG] Add "RELEASE" to PR title checker

- chromadb/__init__.py
> [RELEASE] 0.4.24

- pull_request_template.md
> [DOCS] Update pull_request_template.md

- chromadb/segment/impl/metadata/sqlite.py
- chromadb/test/segment/test_metadata.py
Refs: #1664
- Follow up on #1664 
N/A
> [BUG]: Deleting FTS entries upon deletion of individual records

- .github/workflows/release-helm-chart.yml
- Changes to OSS k8s will trigger hosted-chroma to update its k8s to stay in sync.
> [ENH] Helm CD to hosted

- k8s/distributed-chroma/templates/logservice.yaml
- k8s/distributed-chroma/values.yaml
connect log service in staging
> [ENH] log service staging

- rust/worker/src/system/executor.rs
- rust/worker/src/system/mod.rs
- rust/worker/src/system/scheduler.rs
- rust/worker/src/system/system.rs
- rust/worker/src/system/types.rs
- ...
- This PR adds the compatibility to allow components to schedule tasks
> [ENH] Add system scheduler to allow tasks to run with a schedule

- rust/worker/src/blockstore/arrow_blockfile/block/types.rs
- rust/worker/src/errors.rs
- /
- Adds a block builder for creating BlockData. Blocks hold BlockData in order to serve queries. 
Basic unit tests were added
None
> [ENH] Block builder

- rust/worker/README
- rust/worker/README.md
> [DOC] Update and rename README to README.md

- rust/worker/src/compactor/mod.rs
- rust/worker/src/compactor/scheduler.rs
- rust/worker/src/compactor/scheduler_policy.rs
- rust/worker/src/compactor/task.rs
- rust/worker/src/compactor/types.rs
- rust/worker/src/lib.rs
- rust/worker/src/log/log.rs
- rust/worker/src/system/types.rs
- rust/worker/src/types/collection.rs
- rust/worker/src/types/embedding_record.rs
- rust/worker/src/types/metadata.rs
- rust/worker/src/types/operation.rs
- rust/worker/src/types/scalar_encoding.rs
- rust/worker/src/types/segment.rs
- rust/worker/src/types/segment_scope.rs
- ...
- This PR adds compactor scheduler with system components and scheduler. 
> [ENH] Compactor scheduler with system

- rust/worker/src/blockstore/arrow_blockfile/mod.rs
- rust/worker/src/blockstore/arrow_blockfile/sparse_index.rs
- /
- Adds a sparse index for blockfiles
Basic unit tests for now
None
> [ENH] Sparse index

- chromadb/auth/fastapi.py
- Hosted auth is not working due to a missing import
> [BUG]: fix auth

- k8s/distributed-chroma/templates/sysdb-migration.yaml
- k8s/distributed-chroma/values.yaml
- Template out values in sysdb-migration.yaml so we can point it at databases besides localhost postgres.
> [ENH] Let us specify sysdbMigration target

- k8s/distributed-chroma/templates/sysdb-migration.yaml
- Call `atlas schema clean` before applying migrations.
> [ENH] Clean DB before applying (for now)

- rust/worker/chroma_config.yaml
- Add log service config to query service.
> [BUG] Add logservice config to query service

- rust/worker/src/config.rs
- Adds a basic test to ensure that the default config loads and parses
- None
This is a test
None
> [TST] Add test that the default config loads and parses

- rust/worker/src/execution/operators/pull_log.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/log/log.rs
- ...
- This PR implements the PullLog operator
> [ENH] Implement the PullLog operator

- rust/worker/src/distance/mod.rs
- rust/worker/src/distance/types.rs
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/execution/operators/normalize_vectors.rs
- rust/worker/src/index/hnsw.rs
- rust/worker/src/index/types.rs
- rust/worker/src/lib.rs
- /
- Adds a brute force operator type
Added tests comparing to hardcoded distance metrics
None
> [ENH] Add brute force operator

- go/pkg/coordinator/grpc/server.go
- go/pkg/memberlist_manager/memberlist_manager.go
- go/pkg/memberlist_manager/memberlist_store.go
- go/pkg/memberlist_manager/node_watcher.go
- Add some debugs for memberlist in go
- None
> [CHORE] Go Memberlist debug

- rust/worker/src/log/log.rs
- The error message here seems to have been copied from grpc sysdb and was mentioning segment which was confusing.
- None
None
> [CLN] Clean up log error message

- rust/worker/src/execution/orchestration/hnsw.rs
- #1927 accidentally reverted #1918 
- None
none
> [BUG] Fix as_nanos bad merge

- Tiltfile
- go/cmd/coordinator/cmd.go
- go/pkg/coordinator/grpc/server.go
- go/pkg/memberlist_manager/memberlist_manager.go
- k8s/distributed-chroma/templates/compaction-service-memberlist-cr.yaml
- ...
- This PR adds memberlist manager for compaction service.
> [ENH] Add compaction service memberlist propagation

- rust/worker/src/assignment/assignment_policy.rs
- rust/worker/src/blockstore/arrow_blockfile/block/types.rs
- rust/worker/src/blockstore/arrow_blockfile/sparse_index.rs
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/compactor/mod.rs
- rust/worker/src/distance/mod.rs
- rust/worker/src/execution/data/data_chunk.rs
- rust/worker/src/execution/dispatcher.rs
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/index/fulltext/mod.rs
- rust/worker/src/index/fulltext/tokenizer.rs
- rust/worker/src/index/fulltext/types.rs
- rust/worker/src/index/hnsw.rs
- rust/worker/src/index/metadata/types.rs
- rust/worker/src/index/mod.rs
- rust/worker/src/lib.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- rust/worker/src/server.rs
- rust/worker/src/storage/s3.rs
- rust/worker/src/sysdb/test_sysdb.rs
- rust/worker/src/system/scheduler.rs
- rust/worker/src/system/types.rs
- rust/worker/src/types/mod.rs
- rust/worker/src/types/record.rs
- rust/worker/src/types/segment.rs
- ...
- This PR cleans up unused import and addresses some warnings by cargo build and cargo test. 
- Unused variables are not touched. 
> [CLN] Clean up unused imports

- Cargo.lock
- rust/worker/Cargo.toml
- This PR removes unused dependency and move rayon to dev dependency.
- ...
> [CLN] Remove unused dependency and move rayon to dev dependency

- Tiltfile
- go/cmd/coordinator/cmd.go
- go/pkg/coordinator/grpc/server.go
- k8s/distributed-chroma/values.yaml
- This PR removes the pulsar related configuration for sysdb. 
- Also, removes dependency of pulsar for sysdb in Tiltfile.
- ...
> [CLN] Remove pulsar as a dependency to sysdb

- chromadb/segment/impl/manager/local.py
- Fixed a wrong decorator in local segment manager
- Added a few more tracing decorators
N/A
> [BUG]: Trace decorator fix - local segment manager

- go/pkg/memberlist_manager/node_watcher.go
- This PR adds proper locking to the ip to key map. 
- ...
> [BUG] Add proper locking before modifying the ip to key map

- go/database/log/atlas.hcl
- k8s/distributed-chroma/templates/log-migration.yaml
- k8s/distributed-chroma/values.yaml
- Use env variable for atlas migration
> [ENH]: use env variable for log database migration url

- rust/worker/src/lib.rs
- ...
- This PR adds graceful shutdown to query and compaction service. 
- Currently, it only handles sigterm as Kubernetes uses sigterm to kill a pod gracefully. Will add more signal handling in the future. 
> [ENH] Add graceful shutdown to query and compaction service

- go/pkg/memberlist_manager/memberlist_manager.go
- go/pkg/memberlist_manager/memberlist_manager_test.go
- go/pkg/memberlist_manager/node_watcher.go
- This PR uses pod lister to get the most up to date members in a deployment. It reduces the complexity of computing the new memberlist with events and it is more robust to errors and sysdb failures. 
- ...
> [ENH] Use lister to update the memberlist

- rust/worker/src/compactor/scheduler.rs
- This PR adds check for empty memberlist. 
- ...
> [BUG] Add check for empty memberlist for compactor scheduler

- go/pkg/memberlist_manager/memberlist_manager_test.go
- This PR reduces the re-sync period in unit test to reduce test flakyness. 
- ...
> [BUG] Fix memberlist manager flaky test

- rust/worker/src/compactor/scheduler.rs
- rust/worker/src/execution/operators/flush_sysdb.rs
- rust/worker/src/sysdb/test_sysdb.rs
- This PR makes TestSysDb thread safe and improves unit tests to take advantage of that. 
- ...
> [ENH] Make TestSysDb thread safe

- bin/ts-integration-test
- clients/js/src/ChromaClient.ts
- clients/js/test/auth.basic.test.ts
- clients/js/test/auth.token.test.ts
Fix regression that stopped running the JS client unit tests during CI.
Both regressions are from a large PR: #1970.
> [BUG] Fix JS client regression

- chromadb/server/fastapi/__init__.py
- Use only name to get collection
> [ENH]: use name/uuid to get collection

- rust/worker/src/config.rs
- This PR cleans up unused configuration in config parsing
- ...
> [CLN] Remove unused config

- chromadb/server/fastapi/__init__.py
- Fix the "overwrite tenant and/or database if they're `None` or `default_{tenant, database}` from auth" logic.
> [BUG] Fix auth overwrite

- go/Dockerfile.migration
- k8s/distributed-chroma/templates/log-migration.yaml
> [ENH]: simplify migration

- chromadb/db/impl/grpc/client.py
- chromadb/db/impl/grpc/server.py
- Fix issue with sysdb grpc client
> [ENH]: fix sysdb client grpc

- clients/js/src/types.ts
- clients/js/test/get.collection.test.ts
- clients/js/test/query.collection.test.ts
- Ran prettier to fix breakage lint rule breakge in #2044
- ...
Lint CI failed, this is a fix
> [CLN] Run prettier to make linter happy

- chromadb/segment/impl/metadata/grpc_segment.py
- This code case can never happen because the direct equality case is handled already.
this removes dead code and comments the logic
- ...
> [CLN] remove dead code in metadata proto conversion

- .github/workflows/chroma-cluster-test.yml
- .github/workflows/chroma-integration-test.yml
- .github/workflows/chroma-test.yml
- chromadb/test/distributed/README.md
- chromadb/test/distributed/test_sanity.py
- chromadb/test/test_logservice.py
- k8s/distributed-chroma/values.yaml
- Adds a basic sanity test for distributed
- None
This is a test
None
> [ENH] cluster sanity test

- clients/js/src/Errors.ts
- clients/js/test/delete.collection.test.ts
- clients/js/test/get.collection.test.ts
- clients/js/test/query.collection.test.ts
- run prettier to make the linter happy
- None
existing tests
None
> [CLN] run prettier to make the linter happy

- k8s/distributed-chroma/templates/compaction-service.yaml
- k8s/distributed-chroma/templates/query-service.yaml
- k8s/distributed-chroma/values.yaml
-Pass env into helm for query/compaction services
- None
None
> [ENH] Pass env into helm for query/compaction services

- k8s/distributed-chroma/templates/compaction-service.yaml
- k8s/distributed-chroma/templates/query-service.yaml
- Fixes the way env vars are handled here
- None
Manually
None
> [BUG] Helm chart for query/compactor config

- k8s/distributed-chroma/templates/compaction-service.yaml
- k8s/distributed-chroma/templates/query-service.yaml
- Use correct env for query/compact in helm
- None
> [BUG] Use correct env for query/compact in helm

- docs/docs.trychroma.com/components/layout/TopNav.tsx
Disable search until we have Algolia re-index. 
(also test to make sure tests dont run)
> [DOC] disable search for now

- k8s/distributed-chroma/templates/compaction-service.yaml
- k8s/distributed-chroma/templates/query-service.yaml
- rust/worker/src/storage/config.rs
- rust/worker/src/storage/s3.rs
- Storage from config debug
- None
None
> [CLN] Add debug for rust storage from config

- Tiltfile
- k8s/distributed-chroma/configuration/default.yaml
- k8s/distributed-chroma/templates/compaction-service.yaml
- k8s/distributed-chroma/values.yaml
- add config map based config file for rust worker
> [ENH]: add config map based config file for rust worker

- k8s/distributed-chroma/templates/log-migration.yaml
- k8s/distributed-chroma/templates/sysdb-migration.yaml
- Allow Helm chart consumers to specify annotations for the migration jobs.
> [ENH] annotations for migration jobs

- go/pkg/metastore/db/dao/collection.go
- This PR uses select for update to ensure no lost update even for isolation levels read committed or below. 
- ...
> [BUG] Use select for update to ensure no lost update

- go/pkg/memberlist_manager/memberlist_manager_test.go
- This PR reduces re-sync period for node watcher and reconcile interval to 1s for memberlist manager. 
- ...
> [BUG] Memberlist flaky test

- .github/workflows/release-chromadb.yml
(came out of a discussion with @HammadB)
> [BLD] Run all tests before release

- rust/worker/src/index/hnsw_provider.rs
- Fix a bug where the hnsw index is initalized incorrectly
- None
Adds a basic test for the bugfixed case
> [BUG] HNSW index initialized with wrong id

- rust/worker/src/index/hnsw_provider.rs
> [TST] Hnsw fork bug

- rust/worker/src/segment/distributed_hnsw_segment.rs
- Adds support for upsert/update/delete in the distributed hnsw segment
- None
Will add basic tests before merging
None
> [ENH] Distributed HNSW segment respects updates/upsert/deletes

- .github/workflows/release-chromadb.yml
- Added else condition with exit 1 on tag not matching - fixes https://github.com/chroma-core/chroma/actions/runs/8997234036
N/A
> [BLD]: Chroma release WF exit with error on tag not matching pattern

- docs/docs.trychroma.com/pages/_app.tsx
> [DOC] github edit link on pages

- rust/worker/bindings.cpp
- rust/worker/src/execution/operators/hnsw_knn.rs
- rust/worker/src/index/hnsw.rs
- rust/worker/src/index/types.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
- This PR pass in allowed_ids and disallowed_ids to HNSW bindings.
- ...
> [ENH] Add allowed_ids and disallowed_ids to HNSW bindings

- README.md
- chromadb/api/models/Collection.py
- chromadb/api/types.py
- chromadb/config.py
- chromadb/telemetry/opentelemetry/__init__.py
- clients/js/README.md
- docs/docs.trychroma.com/pages/deployment/auth.md
- docs/docs.trychroma.com/pages/deployment/migration.md
- rust/worker/src/distance/types.rs
Recent doc overhaul broke links. This PR fixes those
NA
NA
> [ENH] Update broken doc links

- rust/worker/src/blockstore/arrow/sparse_index.rs
- Fixes a bug with sparse index serialization
- ...
A test was added for to/from block
None
> [BUG] Sparse index key serialization

- .github/workflows/pr.yml
> [CLN] Lint rust in CI

- examples/deployments/systemd-service/systemd-service.md
- New example of a systemd script to start Chroma (with docker compose) upon system boot
Examples updated
Ref: https://discord.com/channels/1073293645303795742/1239966987593977909
> [CHORE]: SystemD script for starting Chroma at boot time

- chromadb/test/distributed/test_sanity.py
- rust/worker/src/execution/operators/merge_knn_results.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- None
- Support include=['embeddings']
> [ENH] Support include=['embeddings']

- rust/worker/src/execution/orchestration/hnsw.rs
- Query path pulling log should use the correct distance function from the metadata
- None
this serves to ungate test_add.py
None
> [CHORE] Pulling log should use distance function from the segment

- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/normalize_vectors.rs
- Normalize vectors for cosine distance, since its ip. We should probably SIMD this later.
- None
- [] Tests pass locally with `pytest` for python, `yarn test` for js, `cargo test` for rust
> [CHORE] normalize the cosine bf

- rust/worker/src/types/metadata.rs
- Handle the None case correctly.
- None
> [BUG] UpdateMetadataConversion should handle the none case

- rust/worker/src/compactor/compaction_manager.rs
- This PR changes to only schedule new compaction task when last compaction is finished. 
- ...
> [ENH] Only schedule new compaction task when last compaction is finished

- docs/docs.trychroma.com/components/layout/TopNav.tsx
Algolia has now reindexed the docs, so let's ship text search.
> [DOC] re-enable search

- chromadb/api/segment.py
Closes: #2207
- Updated the log message, as it appears to be missleading to users.
N/A
> [CLN]: Making log message clearer for `get_or_create_collection` (when collection exists)

- chromadb/cli/cli.py
- chromadb/server/fastapi/__init__.py
- chromadb/telemetry/product/events.py
- New telemetry event for server startevent that differentiates between normal and CLI runs
N/A
> [CHORE]: Server start telemetry event

- go/pkg/memberlist_manager/memberlist_store.go
- This PR handles the object conversion gracefully.
- ...
> [ENH] Handle K8s object conversion gracefully

- docs/docs.trychroma.com/pages/roadmap.md
> [DOC] update year

- docs/docs.trychroma.com/components/layout/TopNav.tsx
> [DOC] add algolia insights

- rust/worker/src/execution/orchestration/metadata.rs
- rust/worker/src/index/fulltext/tokenizer.rs
- rust/worker/src/index/fulltext/types.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/server.rs
- rust/worker/src/types/metadata.rs
- Metadata query orchestrator.
> [ENH] Metadata query orchestrator

- chromadb/__init__.py
- chromadb/telemetry/product/events.py
- docs/docs.trychroma.com/pages/telemetry.md
- Adds telemetry to detect if a client is launched in a colab env
- None
None
> [CHORE] In colab telemetry

- chromadb/test/property/test_collections_with_database_tenant.py
- chromadb/test/property/test_collections_with_database_tenant_overwrite.py
- This fixes a bug in test_collection_with_tenant_database_overwrite that was causing the test to fail. This change allows overrides of the TenantDatabaseCollectionStateMachine to overwrite the tenant/database on calls to create_tenant and create_database. This is a leaky abstraction, in that its narrow and only used by one overrider. But given this is just composition for testing, its fine. 
- The singleton client will always override the tenant/database since it should not allow creating new tenants/databases if we are using the singleton client.
- None
None
> [TST] fix enabled test_collection_with_tenant_database_overwrite test

- k8s/distributed-chroma/templates/compaction-service.yaml
- k8s/distributed-chroma/templates/query-service.yaml
- This PR adds rolling updates to compaction and query service. 
- ...
> [ENH] Add rolling update strategy to compaction and query service

- docs/docs.trychroma.com/pages/telemetry.md
- docs improvement
Update telemetry docs with another example
Fixes #2240
> [DOC] added PersistentClient example to telemetry docs

- .github/workflows/pr.yml
> [BLD] better name for required check

- chromadb/test/auth/test_simple_rbac_authz.py
- This test times out via hypothesis often. https://github.com/chroma-core/chroma/actions/runs/9473605352/job/26101620843. Mirroring other tests by setting deadline to None.
- None
None
> [TST] RBAC Test timeout

- .github/workflows/release-dev-javascript-client.yml
> [BLD]: Fix the JS dev release versioning

- README.md
- docs/docs.trychroma.com/pages/_app.tsx
- docs/docs.trychroma.com/pages/index.md
update cache on discord shields
> [DOC] change cachce on discord shields

- chromadb/api/models/Collection.py
Added brackets in the list of dictionaries.
- ...
- ...
> [CHORE]: Fix example of "where" in Collection.query()

- .github/workflows/release-dev-javascript-client.yml
> [BUG]: JS client dev release registry fix

- .github/workflows/release-dev-javascript-client.yml
> [BLD]: Adding org scope to package.json (GH release)

- .github/workflows/release-dev-javascript-client.yml
> [BLD]: Fixing working dir for package.json update

- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/compactor/scheduler.rs
- rust/worker/src/execution/operators/pull_log.rs
- rust/worker/src/execution/operators/register.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/execution/orchestration/metadata.rs
- rust/worker/src/log/log.rs
- rust/worker/src/log/mod.rs
- rust/worker/src/server.rs
- Same reasoning as #2350 
- None
existing
None
> [CLN] Make log use enum not dyn

- chromadb/__init__.py
> [RELEASE] 0.5.1

- chromadb/__init__.py
> [RELEASE] 0.5.2

- chromadb/auth/simple_rbac_authz/__init__.py
Closes https://github.com/chroma-core/chroma/issues/2367.
> [BUG] remove hypothesis from prod code path

- chromadb/__init__.py
> [RELEASE] 0.5.3

- rust/worker/chroma_config.yaml
- rust/worker/src/config.rs
- rust/worker/src/log/config.rs
- rust/worker/src/log/log.rs
> [ENH] Timeout log client

- rust/worker/chroma_config.yaml
- rust/worker/src/config.rs
- rust/worker/src/storage/config.rs
- rust/worker/src/storage/s3.rs
- Timeout for s3 storage
- None
None
> [ENH] Timeout for s3 storage

- rust/worker/chroma_config.yaml
- rust/worker/src/config.rs
- rust/worker/src/sysdb/config.rs
- rust/worker/src/sysdb/sysdb.rs
-  Add timeout for sysdb client. Also add interceptor
- None
> [ENH] Add timeout for sysdb client. Also add interceptor

- chromadb/test/property/strategies.py
- chromadb/test/property/test_add.py
- chromadb/test/property/test_filtering.py
> [TST] Fix test filtering and add recordset test tiers

- rust/worker/src/server.rs
> [BUG] debug proto not included in release

- .github/actions/rust/action.yaml
Extracted from https://github.com/chroma-core/chroma/pull/2393.
> [BLD] slight speed up by caching built Rust dependencies

- chromadb/api/__init__.py
- chromadb/api/types.py
- chromadb/cli/cli.py
- chromadb/server/fastapi/__init__.py
- chromadb/server/fastapi/types.py
- clients/js/src/ChromaClient.ts
- clients/js/src/generated/api.ts
- clients/js/src/generated/models.ts
this improves our OpenAPI types for FastAPI and then enables much better typescript codegen
> [ENH] openapi types for better codegen

- chromadb/server/fastapi/__init__.py
- clients/js/src/ChromaClient.ts
- clients/js/src/generated/models.ts
- clients/js/src/types.ts
- clients/js/test/collection.client.test.ts
> [ENH] updates to fastapi types and JS client

- chromadb/api/models/CollectionCommon.py
> [ENH] Add collection repr

- chromadb/api/async_fastapi.py
- chromadb/api/fastapi.py
Closes #2444
- Makes included optional in the response with a default to the original include parameter
N/A
> [BUG]: Compatibility for `included` for 0.5.0 and earlier

- rust/worker/src/segment/distributed_hnsw_segment.rs
- Read from the cache before we load from storage for hnsw index
- None
> [ENH] Read from hnsw cache

- rust/worker/src/storage/s3.rs
- Enables s3 retry by default
- None
None
> [ENH] S3 Retry

- docs/docs.trychroma.com/components/layout/TopNav.tsx
- docs/docs.trychroma.com/pages/_app.tsx
fixing search and analytics on docs.
> [BUG] debug docs search

- k8s/test/jaeger.yaml
- Fix broken OTEL by pinning until we root cause the issue 
None
> [BLD] Pin Jaeger version

- rust/worker/src/execution/orchestration/compact.rs
- Compactor should tolerate this set of errors, OR for dispatcher failures, it should panic
- None
None
> [CLN] Compactor should tolerate all errors or panic

- go/pkg/log/repository/log.go
- This just cleans up a confusing trace that logs an error where we have an expected case
- None
> [CLN] Don't trace expected error case

- .github/workflows/_python-tests.yml
- .github/workflows/nightly-tests.yml
- chromadb/test/conftest.py
Timings with slow settings in this PR:
> [BLD] run intensive distributed property tests nightly

- chromadb/test/conftest.py
- chromadb/test/property/test_embeddings.py
- rust/worker/src/execution/operators/brute_force_knn.rs
- rust/worker/src/execution/operators/get_vectors_operator.rs
- rust/worker/src/execution/operators/hnsw_knn.rs
- rust/worker/src/execution/operators/merge_metadata_results.rs
- rust/worker/src/execution/operators/metadata_filtering.rs
- rust/worker/src/segment/distributed_hnsw_segment.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/segment/types.rs
- rust/worker/src/types/operation.rs
- Materialize logs in get_vectors operator to take care of cases
None
> [BUG] Fix add -> wait for compaction -> delete -> add case

- chromadb/test/distributed/test_sanity.py
- Generates data with a seed and logs the seed to stdout
- Increases hnsw params so that search is more precise
None
> [ENH] Debuggable test_sanity

- rust/worker/src/segment/types.rs
- Materialization traces
- None
Existing tests
None
> [PERF] Materialization traces

- chromadb/test/property/test_embeddings.py
No longer need this due to #2449
> [TST] Remove N > 3 precondition

- chromadb/test/property/test_embeddings.py
> [ENH] Add collection id as log entry in test_embeddings

- chromadb/segment/impl/vector/local_persistent_hnsw.py
- chromadb/test/property/strategies.py
- chromadb/test/property/test_persist.py
See https://github.com/chroma-core/chroma/pull/2062 for a longer explanation.
> [BUG] fix issue when deleting->adding same ID before index is persisted

- rust/worker/src/index/hnsw_provider.rs
- This PR adds tracing for HNSW file copy to local and fixes the cache initialization from config. 
- ...
> [ENH] Use instrumented tracing for HNSW provider file read

- k8s/distributed-chroma/templates/compaction-service.yaml
- k8s/distributed-chroma/templates/query-service.yaml
- Allows passing tolerations to the query and compaction services
- None
None
> [BLD] Allow query/compactor to specify tolerations in k8s

- .github/workflows/nightly-tests.yml
- k8s/test/jaeger.yaml
`test_embeddings` passed [after this change](https://github.com/chroma-core/chroma/actions/runs/9997408719/job/27633895446?pr=2538), which I haven't seen green before.
> [BUG] debug nightly tests timing out

- k8s/distributed-chroma/templates/frontend-service.yaml
- Adds support for tolerations in the FE helm chart
- None
Existing tilt based tests ensure no regressions. This is not explicitly tested for. 
None
> [ENH] Add support for FE tolerations

- k8s/distributed-chroma/Chart.yaml
- k8s/distributed-chroma/templates/frontend-service.yaml
- k8s/distributed-chroma/values.yaml
- Add replica count in helm chart and bump version
- /
Existing tests ensure no functional regressions. This is not explicitly tested.
None
> [ENH] Support FE replica count

- chromadb/test/property/test_embeddings.py
> [TST] add hypothesis collection id to logs

- go/pkg/memberlist_manager/memberlist_store.go
-  Properly display memberlist in SysDB
- ...
> [ENH] Properly display memberlist in SysDB

- go/pkg/memberlist_manager/memberlist_store.go
- Add some additional debug for ml
- ...
> [CHORE] Add logs to memberlist

- go/pkg/memberlist_manager/memberlist_store.go
- Debug the fetched memberlist
- ...
> [CHORE] Add more debugs to memberlist

- chromadb/server/fastapi/__init__.py
- This traces calls to the auth system in the server so that we can measure its latency in a span
- None
Manually verified in jaeger
> [PERF] Trace auth requests

- k8s/distributed-chroma/Chart.yaml
- k8s/distributed-chroma/templates/sysdb-service.yaml
- k8s/distributed-chroma/values.yaml
- Adds sysdb cpu and memory requests and limits
- None
None
> [ENH] Add sysdb cpu/memory requests and limits to helm chart

- k8s/distributed-chroma/Chart.yaml
- k8s/distributed-chroma/templates/sysdb-service.yaml
> [BUG] Sysdb k8s resource typo

- go/go.mod
- go/go.sum
- go/pkg/metastore/db/dbcore/core.go
- go/shared/libs/db_utils.go
> [ENH] add tracing to gorm

- .github/workflows/release-dev-javascript-client.yml
Fixes error seen here: https://github.com/chroma-core/chroma/actions/runs/10221982481/job/28285683548.
Added test job is used by existing workflow.
n/a
> [BLD]: fix JS dev release workflow

- go/database/log/db/queries.sql.go
- go/database/log/queries/queries.sql
- go/pkg/log/repository/log.go
- go/pkg/log/repository/log_test.go
- go/pkg/log/server/property_test.go
- go/pkg/log/sysdb/mock_sysdb.go
- go/pkg/log/sysdb/sysdb.go
- This PR adds unit and property tests for log service gc.
- ...
> [ENH] Add unit and property tests for log service gc

- rust/worker/src/execution/dispatcher.rs
Fixes tracing for log service spans.
n/a
> [BUG]: fix tracing for IO tasks

- .github/workflows/nightly-tests.yml
Fixes log upload for nightly tests.
Will be tested tonight. ;)
Copied from working test workflow.
n/a
> [BLD]: fix nightly tests pod log upload

- chromadb/config.py
- chromadb/db/impl/grpc/client.py
- chromadb/logservice/logservice.py
- chromadb/segment/impl/metadata/grpc_segment.py
- chromadb/segment/impl/vector/grpc_segment.py
- Adds timeouts to config + all grpc related service calls
- None
Existing tests cover this, we don't explicitly test the grpc timeout
None
> [ENH] Add timeouts to FE grpc clients

- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/execution/orchestration/compact.rs
Split up compaction traces to have 1 trace for every scheduled batch and 1 separate trace for every collection being compacted. Collection-level traces have the collection ID and the "parent" span ID as attributes.
n/a
> [ENH]: improve compaction traces

- rust/worker/src/compactor/compaction_manager.rs
Sometimes we want to link a span with a parent span without making it part of the parent's tree. OpenTelemetry has a standard for this behavior. 
Tested locally with Jaeger. Remains to be seen if this works with Honeycomb, I didn't see any docs on it.
n/a
> [ENH]: use `follows_from()` standard instead of manually adding parent attribute

- go/shared/otel/main.go
Confirmed in Grafana that this works:
see above
n/a
> [BUG]: fix log service metrics service name

- rust/blockstore/src/arrow/block/types.rs
- Does what the title says. If you want more explanation, come to my desk. I am at 660 Alabama.
None
> [PERF] Binary search get_prefix() calls in blockfile

- rust/worker/chroma_config.yaml
- rust/worker/src/compactor/compaction_manager.rs
- rust/worker/src/compactor/config.rs
- rust/worker/src/config.rs
- rust/worker/src/execution/orchestration/compact.rs
This will allow us to better control max memory usage (thus avoiding OOMs).
Tested by setting the new fields to small values and observing that more compaction jobs/partitions are created.
n/a
> [ENH]: add config fields for max partition size & max compaction size in compactor

- docs/docs.trychroma.com/README.md
- docs/docs.trychroma.com/pages/_app.tsx
Fixed meta tags in docs
None needed
None needed
> [DOC] fix meta tags

- rust/blockstore/src/arrow/provider.rs
- rust/blockstore/src/arrow/sparse_index.rs
- rust/blockstore/src/provider.rs
- Adds error propagation for sparse index
- Noen
None
> [CLN] Add sparse index errors

- rust/blockstore/src/arrow/blockfile.rs
- rust/blockstore/src/arrow/provider.rs
- rust/blockstore/src/arrow/sparse_index.rs
- rust/blockstore/src/key.rs
- rust/blockstore/src/memory/reader_writer.rs
- rust/blockstore/src/memory/storage.rs
- rust/blockstore/src/provider.rs
- rust/blockstore/src/types.rs
- rust/index/src/hnsw_provider.rs
- rust/index/src/metadata/mod.rs
- rust/worker/src/compactor/scheduler.rs
- rust/worker/src/execution/orchestration/compact.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- rust/worker/src/log/log.rs
- rust/worker/src/memberlist/memberlist_provider.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/sysdb/test_sysdb.rs
- rust/worker/src/system/executor.rs
- rust/worker/src/system/scheduler.rs
- rust/worker/src/system/system.rs
> [CLN] Clean up misc todos

- docs/docs.trychroma.com/pages/index.md
Add Levand's clojure client to docs
@levand had made this change https://github.com/chroma-core/chroma/pull/2765 - but the PR got wacked. So this is the shortcut.
NA
NA
> [DOC] add levands clojure client to docs

- docs/docs.trychroma.com/pages/deployment/migration.md
> [DOC]: remove docs for reverted JS refactor

- chromadb/db/mixins/embeddings_queue.py
- chromadb/errors.py
- chromadb/test/ingest/test_producer_consumer.py
- Adds a non-500 code for batch size exceeded
- None
None
> [CLN] Add batch size errors

- chromadb/__init__.py
> [RELEASE] 0.5.6

- rust/worker/src/execution/operators/record_segment_prefetch.rs
- rust/worker/src/execution/orchestration/hnsw.rs
- Skip prefetch if there is no data to be prefetched
None
> [ENH] Skip prefetch if empty

- .github/workflows/release-chromadb.yml
- RELEASE_PROCESS.md
* Some updated information for the release guide.
* Added the `verbose` flag to PyPi actions.
* Removed the deprecated Publish to CloudFormation Github Action.
N/A
N/A
> [ENH] Release guide update

- idl/makefile
- requirements_dev.txt
- Pin `grpcio-tools` and `protobuf` versions in `requirements_dev.txt` to resolve dependency conflict
- Update `idl/makefile` so that it can search for go plugins in the environment
- New functionality: N/A
Tested with existing test cases
N/A
> [BUG] Resolve python dev requirement conflict

- docs/docs.trychroma.com/pages/deployment/migration.md
Finalizing migration guide for v0.6.0
N/A
This PR
> Update migration guide for 0.6.0 release

- chromadb/__init__.py
- docs/docs.trychroma.com/pages/deployment/migration.md
> [RELEASE] 0.5.9

- chromadb/__init__.py
- docs/docs.trychroma.com/pages/deployment/migration.md
> [RELEASE] 0.5.10

- chromadb/__init__.py
- docs/docs.trychroma.com/pages/deployment/migration.md
> [RELEASE] 0.5.11

- .gitignore
- Cargo.lock
- Cargo.toml
- rust/chroma/Cargo.toml
- rust/chroma/src/main.rs
> [ENH]  We own the `chroma` crate

- docs/docs.trychroma.com/pages/getting-started.md
> hosted in early access

- rust/index/src/fulltext/types.rs
- rust/index/src/hnsw.rs
- rust/index/src/metadata/types.rs
- rust/index/src/utils.rs
- rust/types/src/signed_rbm.rs
- rust/worker/src/execution/operators/hydrate_metadata_results.rs
- rust/worker/src/execution/operators/metadata_filtering.rs
- rust/worker/src/execution/orchestration/metadata.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/types.rs
- rust/worker/src/server.rs
> [CHORE]  Cleanup clippy warnings from merges pre-clippy.

- Cargo.lock
- Cargo.toml
- rust/test/Cargo.toml
- rust/test/src/benchmark.rs
- rust/test/src/lib.rs
- rust/test/src/log.rs
- rust/test/src/segment.rs
- rust/test/src/storage.rs
- rust/worker/Cargo.toml
- rust/worker/src/execution/mod.rs
- rust/worker/src/execution/operator.rs
- rust/worker/src/execution/operators/metadata_filtering.rs
- rust/worker/src/execution/operators/mod.rs
- rust/worker/src/execution/operators/register.rs
- rust/worker/src/lib.rs
- rust/worker/src/log/log.rs
- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/mod.rs
- rust/worker/src/segment/record_segment.rs
- rust/worker/src/segment/types.rs
- Change the visibility in the worker crate in order to run benchmark
- Implement utility functions to compact logs into segments for benchmark
N/A
> [TST] Implement utility functions to instantiate segment

- .github/workflows/_rust-tests.yml
- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/benches/metadata_filtering.rs
- rust/worker/src/server.rs
- N/A
- Benchmark metadata filtering operator
N/A
> [TST] Benchmark metadata filtering

- .github/workflows/pr.yml
- uses the existing action under `./.github/actions/python` with py312 for the lint job
N/A
> [BUG]: Lint job - python setup failure

- chromadb/db/mixins/embeddings_queue.py
- chromadb/test/db/test_log_purge.py
- chromadb/test/property/invariants.py
- docs/docs.trychroma.com/pages/deployment/migration.md
Closes #2922
Closes #2912
It might be related to #2905
- ...
- ...
> [BUG]: Log purge correctness

- .github/workflows/release-chromadb.yml
Fix to allow Github action to set a version release as the latest version
Make a release and verify
N/A
> [BUG] Fix Github release latest action

- chromadb/db/base.py
- chromadb/db/impl/grpc/client.py
- chromadb/db/mixins/sysdb.py
- chromadb/errors.py
- chromadb/test/db/test_system.py
- clients/js/src/ChromaFetch.ts
- clients/js/src/Errors.ts
- clients/js/test/admin.test.ts
- Returns 409 for uniqueconstrainterrors
- None
None
> [CLN] Return 409 for uniqueconstrainterrors

- rust/worker/src/execution/orchestration/compact.rs
Prior to this change, if something inside the compaction orchestrator panicked the panic would not be correctly caught and propagated. This resulted in behavior where compaction failed for a particular collection, and then, while the compaction process looked alive to outside observers, it refused to process any new compaction jobs.
Tested by manually inserting a random panic.
n/a
> [BUG]: gracefully handle compaction orchestrator errors

- chromadb/execution/executor/abstract.py
- chromadb/execution/executor/distributed.py
- chromadb/execution/executor/local.py
- chromadb/execution/expression/operator.py
- chromadb/execution/expression/plan.py
- N/A
- Defines the query operators and query plan, which is the first step towards query pushdown for distributed Chroma.
- Defines the executor abstract class, which should execute any variant of query plan. Also provides dummy implementation for both local and distributed chroma.
N/A
> [ENH] Layout Query Plan and Executor interface in frontend

- chromadb/api/segment.py
- chromadb/config.py
- chromadb/execution/executor/abstract.py
- chromadb/execution/executor/distributed.py
- chromadb/execution/executor/local.py
- k8s/distributed-chroma/templates/frontend-service.yaml
- k8s/distributed-chroma/values.yaml
- N/A
- Implements the local executor, which reuses the logic from `segment.py`
- Duplicate local executor for distributed as a temporary implementation
> [ENH] Implement local executor

- docs/docs.trychroma.com/pages/reference/py-client.md
Fix a small cosmetic bug.
- Minor cosmetic fix - code block not rendered correctly.
N/A - tested visually.
> [DOC] Update py-client.md - fix a minor cosmetic bug

- chromadb/test/ef/test_openai_ef.py
- chromadb/utils/embedding_functions/openai_embedding_function.py
- clients/js/src/embeddings/OpenAIEmbeddingFunction.ts
- clients/js/test/add.collections.test.ts
Closes #2576
- adding `dimensions` parameter to OpenAI EF as requested by a community user
TBD
> [ENH]: OpenAI embedding dimensions

- rust/worker/Dockerfile
- rust/worker/README.md
> [CHORE] Bump rust version and CI/CD to 1.81.0

- chromadb/__init__.py
> [RELEASE] 0.5.15

- rust/blockstore/src/arrow/root.rs
- Make v1 writer write strings
- Make v1.1 reader handle the migration for string -> binary
- None
The tests now read the old format and write the new
None
> [BUG] fix blockfile migration

- rust/blockstore/src/arrow/root.rs
Remove unused import.
Lint checks now pass
> [CHORE] Remove unused import

- chromadb/errors.py
- Adds a new ChromaError, QuotaError. Meant to be raised when a client exceeds given quotas.
> [CHORE] Add QuotaError as a ChromaError

- rust/worker/src/execution/orchestration/hnsw.rs
* This log line logs every record id in the candidate set, which is just a pain to read.  Instead, log the size of the set.
> [CHORE] cleanup spammy log line.

- rust/cache/src/foyer.rs
> [ENH] Enable tracing::instrument for foyer cache calls.

- rust/worker/src/segment/metadata_segment.rs
- rust/worker/src/segment/types.rs
> [CHORE] Cleanup clippy warnings for Rust 1.82

- rust/worker/src/tracing/opentelemetry_config.rs
> [CHORE] Set chroma-cache to error-level tracing.

- Cargo.lock
> [CHORE] upgrade rustls and h2 to avoid bugs

- rust/worker/src/tracing/opentelemetry_config.rs
* Fix that by removing chroma from list of traced crates.
> [CHORE]  having chroma=tracing enabled tracing for chroma-cache too.

- rust/blockstore/src/arrow/flusher.rs
- Flush all blocks in parallel using `FuturesUnordered` 
- MetadataSegment flushing can take very long for large collections, this should speed it up
- None
Existing tests, this is a nonfunctional change
None
> [PERF] Flush blocks in parallel

- Cargo.lock
- rust/worker/Cargo.toml
- rust/worker/src/tracing/opentelemetry_config.rs
I need a feature that's only present in the latest libraries.  Upgrade to get it.
* Should be a NOP until the next patch.
- [✅] Tests pass locally with `pytest` for python, `yarn test` for js, `cargo test` for rust
> [CHORE]  Upgrade tracing libraries to latest.

- examples/chat_with_your_documents/README.md
- examples/chat_with_your_documents/main.py
- examples/chat_with_your_documents/requirements.txt
Basic chat-with-your-docs-example
Proofread and follow manually
Included
> [CLN] Update chat-with-docs example

- docs/docs.trychroma.com/pages/deployment/index.md
Add production banner to deployments index page
N/A
N/A
> Docs update

- docs/docs.trychroma.com/pages/deployment/index.md
Add prod callout to deployments hub
N/A
N/A
> [CLN] Docs Tweaks

- k8s/distributed-chroma/templates/log-migration.yaml
- Cleans up the helm chart with an incorrect path
- None
I added some annotations under `logServiceMigration` and validated `helm template` generates what we expect. 
None required.
> [CLN] Clean up log service migration template

- deployments/azure/chroma.tfvars.tf
- deployments/azure/main.tf
- deployments/gcp/main.tf
- docs/docs.trychroma.com/pages/deployment/_sidenav.js
- docs/docs.trychroma.com/pages/deployment/azure.md
- docs/docs.trychroma.com/pages/deployment/gcp.md
- docs/docs.trychroma.com/pages/deployment/index.md
Added an Azure deployment guide
Followed the guide to ensure correctness.
This PR is a docs update.
> [ENH] Azure Deployment Guide

- chromadb/test/segment/distributed/test_rendezvous_hash.py
- One can view the assignment as a binomial distribution. We can take the std dev of the binomial to validate the null hypothesis - that our data is a binomial distribution. 
- As @Sicheng-Pan pointed out (https://github.com/chroma-core/chroma/pull/2969#discussion_r1821694613) the previous tolerance to the multi-assign test should have failed. It did not. Sometimes math disagrees with simulation. We were still in two sigma with a tolerance of 75, now the tolerance is 150.
- None
> [ENH] Sometimes simulation disagrees with math

- docs/docs.trychroma.com/pages/integrations/llamaindex.md
Some links in our integration docs were broken.
> [CLN] Fix broken links in LlamaIndex docs

- .github/actions/rust/action.yaml
- .github/workflows/_go-tests.yml
- .github/workflows/_javascript-client-tests.yml
- .github/workflows/_python-tests.yml
- .github/workflows/_python-vulnerability-scan.yml
- .github/workflows/_rust-tests.yml
- .github/workflows/nightly-tests.yml
- .github/workflows/pr.yml
- .github/workflows/release-chromadb.yml
- .github/workflows/release-dev-javascript-client.yml
- .github/workflows/release-javascript-client.yml
> [CHORE] Bump github actions/checkout to v4.

- chromadb/config.py
- chromadb/quota/__init__.py
- Remove the `QuotaProvider` abstract class as it is an implementation choice specific to `QuotaEnforcer` and does not need an exposed hook.
> [CLN] Remove QuotaProvider

- rust/index/src/hnsw_provider.rs
- rust/storage/src/admissioncontrolleds3.rs
- Adds visibility into time taken for acquiring the mutex and NAC dedup
None
> [PERF] Add tracing for cold HNSW get

- chromadb/api/segment.py
- The collection model was not being updated, leading to a write to sysdb per added record if the dimension field was none. This fixes that but updating the local model optimistically. 
- None
These are performance, not functional changes. Existing tests cover functionality regression. I have attached before/after jaeger traces for proof-or-performance.
None
**Before**
**After**
> [PERF] Update collection model with dimension during validation
