chroma-core/chroma

rust/worker/src/execution/orchestration/hnsw.rs
- Adding some debug
- None
None
=> [CHORE] Add more debug to hnsw query result

rust/blockstore/src/arrow/block/types.rs, rust/worker/src/execution/orchestration/hnsw.rs
- Added more reference to the binary search algorithm we implemented based on `std::slice::binary_search`
- ...
=> [DOC] Add more reference to code copied from std

rust/worker/src/tracing/opentelemetry_config.rs
1753 / 10k spans are the insert in one space that I looked.  This should
silence them without making us fly blind.
=> [CHORE]  Bump the threshold for foyer tracing to 20ms

rust/worker/src/server.rs
This PR enhances memory efficiency and error handling in worker endpoints for querying vectors and metadata.
- Memory Optimization: Preallocates vectors when sizes are known, reducing memory overhead and enhancing efficiency.
- Error Handling Refactor: Consolidates common validation logic and removes redundant checks, simplifying error handling.
- Enhanced Testing: Adds unit tests to ensure request validation and improve reliability.
- ...
Added unit tests for request validation. No new functionality was introduced, so existing tests cover other impacted areas
`cargo test` 
*Are all docstrings for user-facing APIs updated if required? Do we need to make documentation …
=> [PERF] Optimize memory usage and error handling in worker endpoints

chromadb/errors.py
- Change the `QuotaError` status code from 429 to 400.
=> [CLN] Change QutoaError to 400

rust/index/src/hnsw_provider.rs
- Add some debug to log weight and id of evicted data
- None
None
=> [CHORE] Debug hnsw index purge with weight

rust/index/src/hnsw_provider.rs, rust/worker/chroma_config.yaml
- Just to unify config on MiB
- none
None
=> [CHORE] Use MiB for hnsw cache

rust/index/src/hnsw_provider.rs
- Foyer wants non-zero weights https://github.com/foyer-rs/foyer/blob/2e4844b99759511b6dc3141c1eb8b263c31e457b/foyer-memory/src/handle.rs#L104
- None
None
=> [BUG] Do not allow zero weight

Cargo.lock, rust/storage/Cargo.toml, rust/storage/src/latency.rs, rust/storage/src/lib.rs
This object store injects exponentially distributed latency into an
object store.
=> [ENH]  Latency-simulating object store.

rust/worker/src/execution/operators/prefetch_record.rs
- Silence error when prefetching uninitialized record segment
- ...
=> [ENH] Silence error when prefetch uninitialized segments

chromadb/db/mixins/sysdb.py
Removing a line that will throw an error.
- Add logger import.
n/a
=> [BUG] Fix for a import bug introduced by last PR.

rust/blockstore/src/arrow/blockfile.rs, rust/blockstore/src/arrow/concurrency_test.rs, rust/blockstore/src/arrow/ordered_blockfile_writer.rs, rust/blockstore/src/memory/reader_writer.rs, rust/blockstore/src/types/reader.rs, rust/index/src/metadata/types.rs, rust/worker/src/execution/operators/count_records.rs, rust/worker/src/execution/operators/filter.rs, rust/worker/src/execution/operators/get_vectors_operator.rs, rust/worker/src/execution/operators/hnsw_knn.rs, rust/worker/src/execution/operators/merge_knn_results.rs, rust/worker/src/execution/operators/projection.rs, rust/worker/src/execution/operators/write_segments.rs, rust/worker/src/segment/metadata_segment.rs, rust/worker/src/segment/record_segment.rs, rust/worker/src/segment/types.rs
This way we can detect an error from NotFound.
=> [CHORE]  Make blockfile get return Result<Option<T>, _>.

chromadb/telemetry/opentelemetry/__init__.py
This reverts commit 5eb4da3999f54aa6dbaec4f3215700877a7a9243.
=> Revert "[ENH] Add Kubernetes pod name to traces (#3101)"

chromadb/telemetry/opentelemetry/__init__.py
- Add Kubernetes pod name to all spans
=> [ENH] Add pod_name to spans

k8s/distributed-chroma/templates/compaction-service.yaml, k8s/distributed-chroma/templates/frontend-service.yaml, k8s/distributed-chroma/templates/logservice.yaml, k8s/distributed-chroma/templates/query-service.yaml
- Add support for resource limits for all services. Off by default.
- None
None
=> [ENH] Add support for resource limits for all services

rust/cache/src/foyer.rs
Track cache hit and cache miss rates for Foyer caches.
=> [ENH]  Cache hit and miss rates for foyer.

chromadb/test/property/test_embeddings.py
The actual test flake shows that record segments were not found during
the test run.  I cannot reproduce locally, so submitting the extracted
test as an exemplar so that we test it in the future.
=> [TST]  Commit the manually reconstructed test flake.

go/cmd/coordinator/cmd.go, go/pkg/sysdb/grpc/segment_service.go
- Reverts chroma-core/chroma#3164 - Soft Delete.
n/a
=> [BUG] - Revert "[ENH] Enabling Soft-delete." #3164

chromadb/test/property/test_embeddings.py, go/pkg/sysdb/grpc/collection_service_test.go, rust/worker/src/execution/operators/write_segments.rs, rust/worker/src/execution/orchestration/compact.rs
=> [BUG] Compaction on deletion logs for unintialized collection

rust/worker/src/server.rs
- Ensure input parameters for projections are validated before applying `knn_filter` to avoid unnecessary processing
- Provide precise error message when scan operator inputs are invalid
- Add unit tests to verify KNN queries and error scenarios
- ...
Added new unit tests
=> [PERF] Validate KNN  Projection Input Parameters Before Applying knn_filter

Cargo.lock, Cargo.toml, rust/load/Cargo.toml, rust/load/src/bin/chroma-load.rs, rust/load/src/data_sets.rs, rust/load/src/lib.rs, rust/load/src/opentelemetry_config.rs, rust/load/src/rest.rs, rust/load/src/workloads.rs
This PR commits the chroma-load crate, which contains a program called
chroma-load.  chroma-load runs as a daemon and hosts pre-configured data
sets and workloads that can be mixed and matched at runtime.
See the README embedded in the REST endpoint for more.
=> [ENH] Chroma load - the load generation daemon.

Cargo.toml, rust/benchmark/Cargo.toml, rust/cache/Cargo.toml, rust/load/Cargo.toml, rust/worker/Cargo.toml
This PR moves to the workspace's Cargo.toml any package used by both
chroma_load and another package.  It also drops patch version for easier
upgrades.
=> [CHORE] To the workspace with shared deps.

k8s/distributed-chroma/templates/query-service.yaml, k8s/distributed-chroma/values.yaml
- K8s support for replicas on the query node
- None
None
=> [ENH] K8s support query replicas

k8s/distributed-chroma/Chart.yaml
- Helm chart version needs to be bumped after #3234 
- None
None
=> [CHORE] Bump helm chart version

rust/index/src/spann/types.rs, rust/index/src/spann/utils.rs
- Implements Append using Kmeans. NPA violation checks and reassign protocol
None
=> [ENH] Implement append

Cargo.lock, Cargo.toml, rust/load/src/opentelemetry_config.rs
Tonic won't export straight to honeycomb.  Change to http-proto.
=> [CHORE] switch chroma-load away from tonic

.github/workflows/release-helm-chart.yml
=> [BLD]: fix Helm package directory in workflow

rust/load/src/lib.rs
This PR brings more concurrency to chroma-load for high-request-rate
workloads.  It does so by spawning a tokio task for each in-flight
workload step.
=> [ENH]  Use tasks for concurrency.

go/pkg/utils/integration.go
fix function name in comment
No need
=> chore: fix function name in comment

rust/benchmark/src/datasets/gist.rs, rust/benchmark/src/datasets/mod.rs, rust/benchmark/src/datasets/ms_marco_queries.rs, rust/benchmark/src/datasets/scidocs.rs, rust/benchmark/src/datasets/types.rs, rust/benchmark/src/datasets/wikipedia.rs, rust/index/src/hnsw_provider.rs, rust/index/src/spann/types.rs, rust/index/src/spann/utils.rs, rust/worker/Cargo.toml, rust/worker/benches/spann.rs, rust/worker/src/execution/operators/mod.rs, rust/worker/src/execution/operators/spann_bf_pl.rs, rust/worker/src/execution/operators/spann_centers_search.rs, rust/worker/src/execution/operators/spann_knn_merge.rs
- Fixes spann bugs
- Adds a basic benchmark
None
=> [ENH] SPANN: Bug fixes and benchmark

.github/workflows/release-chromadb.yml
=> [BLD]: add Depot CLI setup step to fix build

.github/workflows/apply-hotfix.yaml
Uses bot token instead of provided GitHub token to create hotfix PR.
n/a
n/a
=> [BLD]: fix hotfix workflow

go/pkg/log/repository/log.go, go/pkg/sysdb/grpc/collection_service.go, go/pkg/sysdb/grpc/segment_service.go, go/pkg/sysdb/grpc/tenant_database_service.go, go/pkg/sysdb/metastore/db/dao/segment.go, go/pkg/sysdb/metastore/db/dao/tenant.go, rust/worker/src/log/log.rs
This PR cherry-picks the commit 4fe70188c0f8b6c48ed2642522769a1d9bddc87b onto rc/2024-12-13. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #3300 to rc/2024-12-13

Tiltfile, k8s/test/minio.yaml
Fix the console UI port, and add
a forwarding for it.
- Add a port forwarding to access minio console UI.
- ...
=> [CHORE] Port forward minio UI

rust/worker/src/tracing/opentelemetry_config.rs
This increases verbosity of non-chroma crates and decreases verbosity of
chroma.
=> [CHORE]  Make everything except chroma `INFO`.  Make chroma `DEBUG`.

.github/workflows/_python-tests.yml, chromadb/api/segment.py, chromadb/db/impl/grpc/client.py, chromadb/db/impl/grpc/server.py, chromadb/db/mixins/sysdb.py, chromadb/db/system.py, chromadb/execution/executor/distributed.py, chromadb/execution/expression/operator.py, chromadb/proto/convert.py, chromadb/segment/impl/manager/distributed.py, chromadb/segment/impl/manager/local.py, chromadb/test/db/test_system.py, chromadb/test/distributed/test_sanity.py, chromadb/test/property/test_sysdb.py, chromadb/test/segment/distributed/test_protobuf_translation.py, chromadb/test/segment/test_metadata.py, chromadb/test/segment/test_vector.py, chromadb/types.py
- N/A
- Use `GetCollectionWithSegments` endpoint for SysDB in `SegmentAPI`
=> [ENH] Use GetCollectionWithSegments endpoint in frontend

chromadb/test/client/test_http_client_v1_compatability.py, chromadb/test/property/test_cross_version_persist.py, pyproject.toml, requirements.txt
Let the version resolution pick the right version.
=> [CHORE]  Unpin tokenizers.

.github/actions/python/action.yaml
=> [BUG] Generate protos with a lower version for tests.

chromadb/__init__.py
=> [RELEASE] 0.6.0

docs/docs.trychroma.com/markdoc/content/docs/run-chroma/persistent-client.md
Typo fix in docs
Not applicable
=> Fix typo in persistent-client.md

.github/workflows/release-chromadb.yml
The load service is in the control plane.
n/a
=> [BLD]: release both planes instead of just data plane

clients/js/package.json
=> [RELEASE] JS 1.10.0

docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/openai.md
- Changed the parameter name from 'model' to 'openai_model' in the TypeScript OpenAIEmbeddingFunction implementation.
- This update aligns the code with the correct parameter name used in the OpenAI API for embeddings.
- Ensures consistency and correctness in the usage of the OpenAI embeddings API with TypeScript.
=> [DOC] Update TypeScript OpenAI Embedding Function Parameter Documentation

rust/index/bindings.cpp, rust/index/src/hnsw.rs
It does not seem to, comment out for now while we investigate.
=> [BUG] Does the integrity check work?

rust/load/Cargo.toml, rust/load/src/lib.rs
The client would open an unbounded number of connections.  Bound it so
that they will only open so many connections at once.
=> [BUG]  Update to async'ified, limited client.

docs/docs.trychroma.com/markdoc/content/reference/python/client.md
closes #3396
- Updated python client reference docs `list_collection` section
N/A
=> [DOC]: Update docs list_collections python client to match 0.6.0 semantics

deployments/azure/main.tf
- Quell error in main.tf for azure deployment
- N/A
I confirmed terraform init now works with the main.tf file
Doc changes aren't required, file is still good to go :)
=> [CLN] Change features = {} to features {} in deployments/azure/main.tf

chromadb/test/ef/test_ef.py, chromadb/utils/embedding_functions/voyageai_embedding_function.py, clients/js/package.json, clients/js/pnpm-lock.yaml, clients/js/src/embeddings/VoyageAIEmbeddingFunction.ts, clients/js/test/add.collections.test.ts, docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/voyageai.md
Resolving merge conflicts for: https://github.com/chroma-core/chroma/pull/3377
=> [ENH] Voyage Integration

docs/docs.trychroma.com/markdoc/content/docs/overview/roadmap.md
Blog link on roadmap page was broken
=> [DOC] Update broken blog link

clients/js/package.json
=> [RELEASE] JS-Client 10.1.2

.github/workflows/apply-hotfix.yaml
Fixes the apply-hotfix workflow with better filtering for the default branch name.
Tested here in this PR.
n/a
=> [BLD]: fix apply-hotfix workflow

rust/index/bindings.cpp, rust/index/src/hnsw.rs
This PR cherry-picks the commit 6c614ecdc9c88104e86cd0eec39173ee48d01f65 onto release/2025-01-03. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #3424 to release/2025-01-03

.github/workflows/apply-hotfix.yaml
Incorrect reference to PR's HTML URL.
=> [BLD] Fix reference to html url

rust/worker/src/segment/distributed_hnsw_segment.rs
This PR cherry-picks the commit 75aeb811a638e8b4b5d518955a9b701311817410 onto release/2025-01-03. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #3431 to release/2025-01-03

Cargo.lock, Cargo.toml, rust/garbage_collector/Cargo.toml, rust/garbage_collector/garbage_collector_config.yaml, rust/garbage_collector/src/bin/garbage_collector_service.rs, rust/garbage_collector/src/bin/garbage_collector_tool.rs, rust/garbage_collector/src/config.rs, rust/garbage_collector/src/lib.rs, rust/garbage_collector/src/opentelemetry_config.rs, rust/worker/src/tracing/opentelemetry_config.rs
- Parse config and setup tracing
None
None
=> [ENH] Setup GC tool and service

rust/blockstore/src/arrow/ordered_blockfile_writer.rs, rust/garbage_collector/src/config.rs, rust/index/src/hnsw_provider.rs, rust/worker/src/execution/operators/limit.rs, rust/worker/src/segment/types.rs
Do not log the buffer being read.  Instrument only once.
=> [CHORE]  Do not log hnsw provider twice.

docs/docs.trychroma.com/app/[...slug]/page.tsx, docs/docs.trychroma.com/app/layout.tsx, docs/docs.trychroma.com/components/header/cloud-signup.tsx, docs/docs.trychroma.com/components/sidebar/menu-item.tsx, docs/docs.trychroma.com/components/sidebar/sidebar.tsx, docs/docs.trychroma.com/components/ui/dialog.tsx, docs/docs.trychroma.com/context/app-context.tsx, docs/docs.trychroma.com/markdoc/content/docs/overview/roadmap.md, docs/docs.trychroma.com/markdoc/content/production/cloud-providers/aws.md, docs/docs.trychroma.com/markdoc/content/production/cloud-providers/azure.md, docs/docs.trychroma.com/markdoc/content/production/cloud-providers/gcp.md, docs/docs.trychroma.com/markdoc/content/production/containers/docker.md, docs/docs.trychroma.com/markdoc/content/production/deployment.md, docs/docs.trychroma.com/markdoc/content/sidebar-config.ts, docs/docs.trychroma.com/package.json, docs/docs.trychroma.com/public/chroma-icon.svg
To be merged when trychroma.com/signup goes live.
=> [DOC] Point cloud section to new signup form

docs/docs.trychroma.com/markdoc/content/production/cloud-providers/gcp.md
=> Fix minor typo gcp.md

rust/worker/chroma_config.yaml, rust/worker/src/compactor/compaction_manager.rs, rust/worker/src/compactor/config.rs, rust/worker/src/compactor/scheduler.rs, rust/worker/src/config.rs
This PR cherry-picks the commit a632f2b6cfcc04ca6cae1d0e0e169e1e5ce631c9 onto release/2025-01-10. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #3469 to release/2025-01-10

rust/index/bindings.cpp, rust/index/src/hnsw.rs
This PR cherry-picks the commit cf95ad92137bd6d951aa56fda5d7ee40a1861d6e onto release/2025-01-10. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #3479 to release/2025-01-10

chromadb/db/impl/grpc/client.py
- Increase max grpc stream for sysdb, which could be a bottleneck we found in staging
- N/A
=> [ENH] Increase Sysdb GRPC max concurrent stream

clients/js/package.json
Release Chroma JS-Client v1.10.3
=> [RELEASE] JS-Client 1.10.3

chromadb/execution/executor/distributed.py, chromadb/segment/distributed/__init__.py, chromadb/segment/impl/distributed/segment_directory.py, chromadb/test/segment/distributed/test_memberlist_provider.py, go/pkg/memberlist_manager/memberlist_manager.go, go/pkg/memberlist_manager/memberlist_manager_test.go, go/pkg/memberlist_manager/memberlist_store.go, go/pkg/memberlist_manager/node_watcher.go, k8s/distributed-chroma/Chart.yaml, k8s/distributed-chroma/crds/memberlist_crd.yaml
- Adds node name to the memberlist to allow for node-level routing
- None
Existing tests are modified
None
=> [ENH] Add node name to memberlist

rust/blockstore/src/arrow/provider.rs
The `cached()` method was always returning true (assumed that no error == block is cached). This is now fixed.
Added test was previously failing.
n/a
=> [BUG]: `BlockManager::cached()` should not always return true

chromadb/server/fastapi/__init__.py
Closes #3493
Intorduced with #3445 
- removed the importlib statement which causes `importlib.metadata.PackageNotFoundError: No package metadata was found for chromadb` error when trying to access /docs
N/A
=> [BUG] fix bad OpenAPI docs

rust/load/src/data_sets.rs
This will go through all the tiny stories data sets in turn.  This may turn out to be a bad idea or
be insufficient, but we shall see.
=> [ENH] RoundRobin across tiny-stories data sets.

clients/js/package.json
Release Chroma JS-Client v1.10.4
=> [RELEASE] JS-Client 1.10.4

k8s/distributed-chroma/Chart.yaml
- Bumps helm chart to release rust FE from #3549 
- None
None
=> [ENH] Bump helm chart for rust fe

chromadb/api/fastapi.py, rust/frontend/src/frontend.rs, rust/frontend/src/server.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
- ...
- New rust FE server implements get_database
None
=> [ENH] Get database e2e

clients/js/package.json, clients/js/pnpm-lock.yaml, clients/js/src/embeddings/OllamaEmbeddingFunction.ts
- moves the ollama import into a static method
=> [BUG] Fix failing JS CI due to ollama import

rust/frontend/src/config.rs, rust/sysdb/src/config.rs, rust/sysdb/src/sysdb.rs
- Balance gRPC channels for gRPC sysdb
- Add config for num endpoints
- None
None
=> [ENH] Balance gRPC channels

idl/chromadb/proto/chroma.proto, rust/types/src/metadata.rs, rust/worker/benches/filter.rs, rust/worker/benches/load.rs, rust/worker/src/execution/operators/filter.rs
- Refactor the deserialization logic for `Where` clause
- Implement the serialization logic for `Where` clause
=> [ENH] Serialize Where clause to protobuf

rust/types/src/collection.rs, rust/types/src/execution/error.rs, rust/types/src/execution/mod.rs, rust/types/src/execution/operator.rs, rust/types/src/execution/plan.rs, rust/types/src/metadata.rs, rust/types/src/segment.rs, rust/types/src/segment_scope.rs, rust/types/src/types.rs, rust/worker/src/execution/orchestration/get.rs, rust/worker/src/execution/orchestration/knn_filter.rs, rust/worker/src/server.rs
- N/A
- Serialize/Deserialize query plan to/from protobuf
=> [ENH] Serialize/Deserialize query plan to/from ProtoBuf

chromadb/api/segment.py, chromadb/segment/impl/manager/distributed.py
https://github.com/chroma-core/hosted-chroma/issues/814
- Clean up.
- ...
=> [BUG] Clean up delete_segments.

Cargo.lock, rust/frontend/Cargo.toml, rust/frontend/src/executor/distributed.rs, rust/frontend/src/executor/mod.rs, rust/frontend/src/frontend.rs, rust/frontend/src/lib.rs, rust/types/src/api_types.rs, rust/types/src/execution/operator.rs
- N/A
- Implement the distributed executor for Rust frontend
N/A
=> [ENH] Implement distributed executor for Rust frontend

rust/sysdb/src/sysdb.rs
- N/A
- Implement sysdb `get_collection_with_segments` endpoint
=> [ENH] Implement SysDB get_collection_with_segments endpoint

Cargo.lock, rust/frontend/src/executor/distributed.rs, rust/frontend/src/frontend.rs, rust/frontend/src/server.rs, rust/types/Cargo.toml, rust/types/src/api_types.rs, rust/types/src/execution/operator.rs, rust/types/src/metadata.rs
=> [ENH] Add query route

rust/memberlist/src/memberlist_provider.rs, rust/worker/src/compactor/compaction_manager.rs, rust/worker/src/compactor/scheduler.rs
- Add extra fields that we added to the memberlist to the rust memberlist struct
- None
Added a test to check contents of memberlist
None
=> [ENH] Update rust ml with extra fields

rust/frontend/src/ac.rs, rust/mdac/src/circuit_breaker.rs
This tracks the three core counters we should be tracking for the
circuit breaker.
=> [ENH]  Metrics for circuit breaker in mdac.

rust/frontend/src/errors.rs, rust/frontend/src/frontend.rs, rust/frontend/src/server.rs, rust/types/src/api_types.rs, rust/types/src/metadata.rs
- N/A
- Implement `count` and `get` endpoint for collection
=> [ENH] Implement read endpoints for collection

rust/frontend/src/frontend.rs, rust/frontend/src/server.rs, rust/frontend/src/types/errors.rs, rust/frontend/src/types/where_parsing.rs, rust/types/src/api_types.rs
Avoids duplication and removes custom payload parsing implementations (needed to parse where fields for /delete as well and figured I'd clean it up).
Tested locally with a simple script.
n/a
=> [CLN]: derive Deserialization for get and query payloads

Cargo.lock, Cargo.toml, rust/frontend/Cargo.toml, rust/frontend/src/executor/config.rs, rust/frontend/src/executor/distributed.rs, rust/types/src/execution/plan.rs
- Adds retries that load balance across the downstream nodes
- None
They are not currently
None
=> [ENH] FE<>Query retries load balance

rust/frontend/src/frontend.rs, rust/frontend/src/server.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs, rust/types/src/metadata.rs
See title.
Tested locally with simple script.
n/a
=> [ENH]: support collection updates on Rust frontend

rust/system/src/execution/config.rs
- Add a default to this config so we don't have to update yaml
- None
None
=> [BUG] Fix missing config default

Cargo.lock, Cargo.toml, rust/frontend/Cargo.toml, rust/frontend/src/frontend.rs, rust/frontend/src/lib.rs, rust/frontend/src/server.rs, rust/frontend/src/types/errors.rs, rust/frontend/src/utils.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
=> [ENH] Implement validators for Rust FE

.github/workflows/_python-tests.yml, .github/workflows/pr.yml, bin/cluster-test.sh, chromadb/api/async_fastapi.py, chromadb/api/fastapi.py, chromadb/test/conftest.py, rust/frontend/src/frontend.rs, rust/frontend/src/server.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
=> [ENH]: fixes for creating collections through the Rust frontend

docs/docs.trychroma.com/markdoc/content/docs/embeddings/embedding-functions.md
Update link for jina ai.
- ...
- ...
=> [DOC] Update embedding-functions.md

go/pkg/log/repository/log.go, rust/error/src/lib.rs, rust/frontend/frontend_config.yaml, rust/frontend/src/frontend.rs, rust/frontend/src/get_collection_with_segments_provider.rs, rust/log/src/types.rs, rust/types/src/api_types.rs
- Query fails with Pull log error, it is propagated all the way to FE. FE invalidates the cache and retries.
- ...
None
=> [ENH] Add cache invalidation

chromadb/test/property/strategies.py, chromadb/test/property/test_collections.py, rust/frontend/src/frontend.rs, rust/frontend/src/server.rs, rust/frontend/src/types/errors.rs, rust/frontend/src/utils.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs, rust/worker/src/compactor/scheduler.rs, rust/worker/src/execution/operators/register.rs, rust/worker/src/execution/orchestration/compact.rs
- Fix Rust FE behaviors
- N/A
N/A
=> [ENH] Misc cleanup for Rust FE

.github/workflows/_python-tests.yml, chromadb/proto/.gitignore, rust/frontend/src/frontend.rs
See https://github.com/chroma-core/chroma/pull/3646
=> [TST]: fix Rust frontend for test_logservice.py

rust/frontend/src/server.rs
- Client can also pass in None for offset so serde(default) won't work
- ...
None
=> [BUG] Fixes for test_filtering

rust/frontend/src/executor/client_manager.rs
- Bug that the old ml wasn't set
- None
None
=> [BUG] Set old ML in ml processor

rust/frontend/src/executor/client_manager.rs, rust/frontend/src/frontend.rs, rust/frontend/src/get_collection_with_segments_provider.rs, rust/frontend/src/server.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
- Refactored Rust FE error codes
- Pulled validation logic out of Rust FE
- N/A
=> [CLN] Cleanup Ruet FE error types

rust/frontend/src/executor/client_manager.rs, rust/memberlist/src/memberlist_provider.rs
- Fixes a hang in the ML on closed channels. I am assuming the underlying client closes the channel when it is disconnected entirely. Which leads to the send hanging. I have not had time to verify but we should. 
- None
Added tests
None
=> [BUG] Fix hang in ml

rust/frontend/src/frontend.rs, rust/frontend/src/server.rs, rust/types/src/api_types.rs
=> [ENH]: add/upsert/update Vecs should take optional elements

.github/workflows/_python-tests.yml, chromadb/test/property/invariants.py, chromadb/test/property/test_collections.py, chromadb/test/property/test_embeddings.py, chromadb/test/property/test_persist.py, rust/frontend/src/frontend.rs, rust/frontend/src/server.rs, rust/frontend/src/types/errors.rs, rust/types/src/api_types.rs
=> [TST]: fixes for test_add.py against Rust frontend

rust/blockstore/src/arrow/block/delta/single_column_storage.rs
There's a bug where keys are not seen in increasing order. We believe this is a concurrency bug somewhere.
Adding this panic will help us diagnose it if it happens again.
Separately, we should attempt to reproduce the bug with a `shuttle` test.
=> [ENH]: panic during splitting when keys are unordered

Cargo.lock, Cargo.toml, rust/segment/Cargo.toml, rust/segment/src/lib.rs, rust/segment/src/sqlite_metadata.rs, rust/sqlite/Cargo.toml, rust/sqlite/src/lib.rs, rust/sqlite/src/table.rs
- N/A
- Implement metadata segment reader in rust
=> [ENH] Implement sqlite metadata segment reader

rust/system/src/execution/operator.rs, rust/worker/src/execution/operators/prefetch_record.rs, rust/worker/src/execution/operators/prefetch_segment.rs
This PR cherry-picks the commit 68d8a4b7afa7fae618c3fd9a86a9e08ece49b486 onto release/2025-01-31. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #3664 to release/2025-01-31

chromadb/api/fastapi.py
This manifests as rejecting application/json from frontend.  Fix it.
=> [BUG]  If ssl is set, we overwrite headers.

Cargo.lock, rust/index/bindings.cpp, rust/index/src/hnsw.rs, rust/segment/Cargo.toml, rust/segment/src/lib.rs, rust/segment/src/local_hnsw.rs, rust/segment/src/local_segment_manager.rs
- FD pool with eviction that closes the FDs
- Local segment manager to create the hnsw segment reader and writer
- ...
None
=> [ENH] FD pool + Local segment manager

Cargo.lock, rust/python_bindings/Cargo.toml, rust/python_bindings/src/compaction_manager.rs, rust/python_bindings/src/lib.rs
- Compactor component in local
- ...
None
=> [ENH] Basic compaction manager scaffold

rust/load/src/opentelemetry_config.rs
The otel code for chroma-load doesn't set the x-honeycomb-dataset or
x-honeycomb-team headers.  Manually set these headers on the client.
=> [ENH]  The otel metrics for chroma-load (no longer)show up as unknown-dataset.

rust/segment/src/sqlite_metadata.rs, rust/sqlite/src/table.rs
- N/A
- Implement metadata segment writer
=> [ENH] Implement metadata segment writer

Cargo.lock, rust/index/src/hnsw.rs, rust/segment/src/local_hnsw.rs, rust/segment/src/local_segment_manager.rs, rust/segment/src/utils.rs
=> Enhanced reader + writer

Cargo.lock, rust/log/src/sqlite_log.rs, rust/python_bindings/src/bindings.rs, rust/sysdb/src/sqlite.rs
- Set up log in bindings
- None
None
=> [ENH] Setup log in bindings

rust/frontend/src/executor/local.rs, rust/python_bindings/src/bindings.rs, rust/segment/src/local_hnsw.rs, rust/segment/src/local_segment_manager.rs, rust/types/src/api_types.rs
- ...
- Implement `get_embeddings` for local hnsw segment reader
=> [ENH] Implement get embedding for local hnsw reader

rust/frontend/src/executor/local.rs, rust/frontend/src/local_compaction_manager.rs, rust/python_bindings/src/bindings.rs, rust/segment/src/local_hnsw.rs, rust/types/src/api_types.rs, rust/types/src/execution/operator.rs
- ...
- Implement query endpoint for local executor
=> [ENH] Implement query for local executor

Cargo.lock, rust/frontend/src/lib.rs, rust/log/Cargo.toml, rust/log/src/lib.rs, rust/log/src/local_compaction_manager.rs, rust/log/src/sqlite_log.rs, rust/python_bindings/src/bindings.rs, rust/system/src/types.rs
- Call compactor in the write path
- ...
None
=> [ENH] call compactor in the write path

rust/frontend/src/server.rs, rust/frontend/src/types/errors.rs, rust/frontend/src/types/mod.rs, rust/python_bindings/src/bindings.rs, rust/types/src/api_types.rs, rust/types/src/lib.rs, rust/types/src/where_parsing.rs
- This jank for testing. We need to clean it up
- None
None
=> [ENH] Rust bindings where clause parsing

Cargo.lock, rust/blockstore/src/provider.rs, rust/cache/src/foyer.rs, rust/error/Cargo.toml, rust/error/src/lib.rs, rust/error/src/sqlx.rs, rust/error/src/tonic.rs, rust/log/Cargo.toml, rust/log/src/sqlite_log.rs, rust/log/src/types.rs, rust/storage/src/object_store.rs, rust/sysdb/Cargo.toml, rust/types/Cargo.toml
Adds a `.boxed()` helper for `ChromaError` and a common sqlx error type.
=> [ENH]: error helpers & common WrappedSqlxError type

rust/sqlite/src/table.rs, rust/sysdb/src/sqlite.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs, rust/types/src/segment_scope.rs
=> [ENH]: add Rust sysdb impl for get_collection_with_segments()

rust/load/src/data_sets.rs, rust/load/src/lib.rs
I had to wire up get-by-key for the tiny stories data set to use it as a
reference.  Tested locally and against staging.
=> [ENH]  chroma-load runs load workloads.

rust/frontend/src/frontend.rs, rust/log/src/local_compaction_manager.rs, rust/log/src/sqlite_log.rs, rust/python_bindings/src/bindings.rs, rust/segment/src/sqlite_metadata.rs, rust/types/src/segment.rs
- Add local hnsw segment type
- Fix bug in compaction manager
- Encode document in metadata table
- N/A
=> [BUG] Misc bug fixes for local Rust impl

rust/sysdb/src/sqlite.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
=> [ENH]: add update_collection() SQLite impl for Rust frontend

rust/frontend/src/executor/local.rs, rust/frontend/src/frontend.rs, rust/log/src/sqlite_log.rs
- Add the filter bypass for local executor query
- N/A
=> [PERF] Rust local impl query filter bypass

chromadb/api/rust.py, rust/frontend/src/executor/local.rs, rust/python_bindings/rust_bindings.pyi, rust/python_bindings/src/bindings.rs, rust/segment/src/local_hnsw.rs, rust/types/src/api_types.rs, rust/types/src/metadata.rs
- wire up query
- wire up update
- @Sicheng-Pan bug fix for query path
- misc
- none
None
=> [ENH] wire up query

rust/frontend/src/executor/local.rs, rust/segment/src/sqlite_metadata.rs, rust/sysdb/src/sqlite.rs
- Collection dimension initialized to Null instead of zero
- Query should return the same number of result as the number of embeddings
- Filtering should handle Null values properly
- Convert empty metadata to None in get query
- N/A
=> [BUG] Misc bug fix for Rust impl

Cargo.lock, chromadb/api/rust.py, chromadb/db/mixins/embeddings_queue.py, chromadb/test/property/test_add.py, rust/frontend/Cargo.toml, rust/frontend/src/executor/local.rs, rust/frontend/src/frontend.rs, rust/frontend/src/types/errors.rs, rust/log/src/log.rs, rust/log/src/sqlite_log.rs, rust/python_bindings/src/bindings.rs, rust/segment/src/sqlite_metadata.rs, rust/segment/src/test.rs
- Pop document out of metadata
- Normalize query embedding if using cosine distance function
- Set and verify max batch size
- ...
=> [BUG] Misc bug fixes for Rust impl

chromadb/api/rust.py, rust/log/src/sqlite_log.rs, rust/python_bindings/rust_bindings.pyi, rust/python_bindings/src/bindings.rs, rust/sqlite/src/helpers.rs, rust/sysdb/src/sqlite.rs, rust/types/src/api_types.rs
=> [ENH]: use Rust SQLite impl for collection methods in bindings

Cargo.lock, chromadb/api/rust.py, rust/error/src/tonic.rs, rust/frontend/src/executor/local.rs, rust/frontend/src/executor/mod.rs, rust/frontend/src/frontend.rs, rust/python_bindings/rust_bindings.pyi, rust/python_bindings/src/bindings.rs, rust/segment/src/local_segment_manager.rs, rust/sqlite/Cargo.toml, rust/sqlite/src/config.rs, rust/sqlite/src/db.rs, rust/sysdb/src/sqlite.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
=> [ENH]: connect reset() to Rust bindings

chromadb/api/rust.py
=> [ENH]: impl component start/stop for Rust bindings

chromadb/api/rust.py, rust/python_bindings/rust_bindings.pyi, rust/python_bindings/src/bindings.rs, rust/sysdb/src/sqlite.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
=> [ENH]: hook up collection.modify() to Rust bindings

chromadb/api/rust.py, chromadb/test/property/test_persist.py, chromadb/test/test_api.py, rust/frontend/src/get_collection_with_segments_provider.rs, rust/log/src/local_compaction_manager.rs, rust/log/src/sqlite_log.rs, rust/python_bindings/rust_bindings.pyi, rust/python_bindings/src/bindings.rs, rust/sysdb/src/sqlite.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
- Switch to rust impl in `rust.py`
- ...
=> [TST] Test local rust impl

rust/python_bindings/src/bindings.rs, rust/segment/src/sqlite_metadata.rs, rust/segment/src/test.rs, rust/types/src/strategies.rs
- Implement proptest for where/where_document filter
- N/A
=> [TST] Implement prop test for where

chromadb/test/api/test_numpy_list_inputs.py
- Add tests for numpy types of various combinations
- None
None
=> [TST] Add tests for numpy input types

rust/tracing/Cargo.toml
=> [CHORE]  Tonic should always be enabled.

Cargo.lock, Cargo.toml, chromadb/server/fastapi/__init__.py, rust/frontend/src/auth/mod.rs, rust/frontend/src/bin/frontend_service.rs, rust/frontend/src/lib.rs, rust/frontend/src/server.rs, rust/frontend/src/types/errors.rs
This currently only supplies a NOP/() implementation.  Will implement
the other server-side providers as required.
=> [ENH]  Add frontend auth support to rust frontend.

chromadb/__init__.py, chromadb/api/rust.py, rust/index/src/hnsw.rs, rust/index/src/hnsw_provider.rs, rust/log/src/sqlite_log.rs, rust/python_bindings/src/bindings.rs, rust/segment/src/distributed_hnsw.rs, rust/segment/src/local_hnsw.rs, rust/segment/src/local_segment_manager.rs, rust/sqlite/src/config.rs, rust/sqlite/src/db.rs
- Use full file path instead of parent directory for sqlite
- Implement ephemeral hnsw index
- Implement ephemeral hnsw reader / writer
- Implement ephemeral sqlite
- [TODO] Implement ephemeral Rust client
=> [ENH] Implement ephemeral Rust Client

rust/cli/src/main.rs, rust/frontend/src/bin/frontend_service.rs, rust/frontend/src/lib.rs, rust/frontend/src/quota/mod.rs, rust/frontend/src/server.rs
- Adds a quota enforcer trait
- Enforces at various APIs
- ...
None
=> [ENH] Integrate quota

rust/frontend/src/quota/mod.rs
- Some fields made public
- Explicit lifetime annotation
- ...
None
=> [ENH] Revised quota enforcer trait

rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
=> [ENH] Implement GetCollectionSize in rust sysdb client

rust/frontend/src/frontend.rs
This adds a counter for each retryable path.
=> [ENH]  Per-request-type retry counters.

chromadb/server/fastapi/__init__.py, rust/frontend/src/auth/mod.rs, rust/frontend/src/server.rs
There were several missed routes.  The miss came because I followed one set of function calls, but neglected the async variants.
=> [BUG]  serveral routes were missed in the original auth code.

rust/index/src/fulltext/types.rs
This PR cherry-picks the commit d8a20eb01b6abef6003c678c076a50aa262b824a onto release/2025-02-07. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #3790 to release/2025-02-07

rust/cache/src/foyer.rs
=> [CLN] Remove spurious foyer traces

chromadb/api/types.py
- Fix a small type in the exception message: `Embedings` --> `Embeddings`
None.
=> [ENH] Fix type in exception message

docs/docs.trychroma.com/markdoc/content/reference/python/collection.md
- N/A
- N/A
N/A
Fixes a typo in two places.
=> [DOC] Fix minor typos

clients/python/pyproject.toml, docs/docs.trychroma.com/markdoc/content/docs/overview/about.md
=> [ENH] update docs

go/pkg/sysdb/metastore/db/dao/collection.go, go/pkg/sysdb/metastore/db/dao/collection_test.go, go/pkg/sysdb/metastore/db/dao/test_utils.go
- Subquery to get collection_metadata instead of issuing one query per collection for metadata
- Add go side tests for count collections
- Improve existing get collections test by also testing for order by
- ...
None
=> [ENH] Optimize GetCollections

.github/workflows/_python-tests.yml, bin/rust-integration-test.sh, bin/rust_single_node_integration_test_config.yaml, chromadb/api/rust.py, rust/frontend/single_node_frontend_config.yaml, rust/sqlite/src/config.rs, rust/sqlite/src/db.rs, rust/sqlite/src/migrations.rs
- Enable windows tests for rust impls
- ...
=> [TST] Enable windows tests for rust impl

rust/cache/src/foyer.rs
- Verify with test that the in memory cache can close file descriptor on eviction
- N/A
=> [TST] Test foyer cache can close file descriptor

docs/docs.trychroma.com/components/sidebar/menu-item.tsx, docs/docs.trychroma.com/lib/content.ts, docs/docs.trychroma.com/markdoc/content/cloud/getting-started.md, docs/docs.trychroma.com/markdoc/content/sidebar-config.ts
=> [DOC] Add cloud docs placeholder

docs/docs.trychroma.com/markdoc/content/integrations/chroma-integrations.md, docs/docs.trychroma.com/markdoc/content/integrations/frameworks/deepeval.md, docs/docs.trychroma.com/middleware.ts
- ...
- DeepEval integration docs.
*Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the [docs repository](https://github.com/chroma-core/docs)?* No.
=> [DOC] DeepEval Integration

Cargo.lock, Cargo.toml, rust/frontend/Cargo.toml, rust/frontend/src/quota/mod.rs
- Return rule, action, usage and limit in the QuotaExceeded error
- ...
None
=> [ENH] More legible quota message

pyproject.toml
- Protos were not included in sdist. This should fix it.
- ...
=> [BUG] Update [tool.maturin] section to add include protos.

.github/workflows/release-chromadb.yml
This PR cherry-picks the commit 4a28dfc1281f547b020611baf348adbc24a4db41 onto rc/2025-02-21. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #3832 to rc/2025-02-21

pyproject.toml
This PR cherry-picks the commit 35a2b0fc70d13b7688f1df0ba7b48c3cc15bb704 onto rc/2025-02-21. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #3833 to rc/2025-02-21

go/pkg/sysdb/coordinator/coordinator_test.go, go/pkg/sysdb/grpc/collection_service.go, go/pkg/sysdb/grpc/collection_service_test.go, rust/index/src/fulltext/util.rs
Changing from previous code denoting internal error.
Fixes - https://github.com/chroma-core/hosted-chroma/issues/1375
- ...
- ...
=> [ENH] Return NOT FOUND grpc err code for non-existent db in create coll.

docs/docs.trychroma.com/markdoc/content/docs/overview/introduction.md
Add a C++ client for ChromaDB to docs
=> [DOC] Add cpp client

Tiltfile, k8s/distributed-chroma/values.dev.yaml
Set flags for SysDb for Tilt only. Not for production.
- ...
- ...
=> [ENH] Enable version file for Tilt only.

chromadb/test/property/strategies.py
Before this change, it was possible for Hypothesis to generate where filters in which a float was used for `$eq`, `$ne`, `$in`, and `$nin`. Floats should not be used for these operators as float accuracy errors can give unexpected results.
Should fix a bad filter generation observed in this test run: https://github.com/chroma-core/chroma/actions/runs/13578627433/job/37960408763?pr=3868
Covered by existing tests.
=> [TST]: fix Hypothesis filter generation for floats

.github/workflows/_build_release_container.yml, .github/workflows/release-chromadb.yml
Allows us to manually release the container image with a specific tag.
yolo
=> [BLD]: allow manual release of container image

clients/python/pyproject.toml, pyproject.toml
- #3859 missed this
- None
Existing tests
None
=> [BUG] Json schema missing from deps

Cargo.lock, chromadb/__init__.py, rust/frontend/Cargo.toml, rust/frontend/src/server.rs
Releasing 1.0.0b0 (https://pythonpackaging.info/07-Package-Release.html#Versioning-your-code)
=> [RELEASE] 1.0.0b0

docs/docs.trychroma.com/markdoc/content/updates/migration.md
See title. Came up in Discord server.
=> [DOC]: add note to migration guide about container data directory change

chromadb/test/db/test_system.py, go/cmd/coordinator/cmd.go, go/pkg/sysdb/coordinator/coordinator_test.go, go/pkg/sysdb/coordinator/table_catalog.go, go/pkg/sysdb/grpc/cleanup.go, go/pkg/sysdb/grpc/server.go, go/pkg/sysdb/metastore/db/dao/collection.go, k8s/distributed-chroma/values.dev.yaml
=> [CHORE] Set soft delete flag to true by default.

rust/index/src/hnsw_provider.rs
- Adds debug traces for issue seen in prod - "Failed to remove temporary files..."
- ...
None
=> [ENH] Add traces to debug compactor issue

clients/js/src/embeddings/OllamaEmbeddingFunction.ts
=> [BUG] revert ollama import

rust/storage/src/admissioncontrolleds3.rs, rust/storage/src/lib.rs, rust/storage/src/s3.rs
This extends the s3 interface with a get_e_tag method, and extends the
put interface to take a PutOptions.
=> [ENH]  Support if-not-exists and if-match for putting objects to S3.

Cargo.lock, Cargo.toml, rust/wal3/Cargo.toml, rust/wal3/src/backoff.rs, rust/wal3/src/lib.rs
No writer, reader, snapshotter, or anything.  Just the scaffold types.
=> [ENH] Basic types for wal3 with documentation.

k8s/distributed-chroma/Chart.yaml, k8s/distributed-chroma/templates/rust-frontend-service.yaml
- Rust frontend service service account so we can attach roles to it in eks in hosted chroma
- None
They are not!
None
=> [ENH] Service account for rust frontend service

k8s/distributed-chroma/Chart.yaml, k8s/distributed-chroma/templates/rust-frontend-service.yaml
- Bind SA from last pr to RFE (#3924)
- None
None
=> [ENH] Bind service account to RFE

k8s/distributed-chroma/Chart.yaml, k8s/distributed-chroma/templates/query-service-memberlist-cr.yaml, k8s/distributed-chroma/templates/rust-frontend-service.yaml
- #3922 broke the ability of the RFE to list access the ML
- None
None
=> [BUG] Need podwatcher role on rust-fe

rust/frontend/src/server.rs
The Rust HTTP server now defaults the content-type header to application/json if not provided. This means that Python clients prior to 1.0.0b are now compatible with the Rust server.
Added test was previously failing.
n/a
=> [ENH]: default content-type to application/json if not provided

clients/js/package.json, clients/js/packages/chromadb-client/package.json, clients/js/packages/chromadb-core/package.json, clients/js/packages/chromadb/package.json
=> [ENH] Bump js package version to test deploys

rust/index/src/spann/types.rs
- Resize HNSW taking deletes into account (I am stupid for missing this)
- ...
None
=> [ENH] SPANN: Resize Hnsw appropriately

rust/frontend/src/quota/mod.rs
- ...
- Updates `QuotaEnforcerError` to support billing error
- Adds `NumDatabases` quota rule default
=> [ENH] Add BillingLimitExceeded error and NumDatabases quota rule

rust/frontend/src/quota/mod.rs
=> [ENH] Generic quota error

.github/workflows/pr.yml
to save time on PR CIs, don't run all tests unless core change specific, and run tests on specific changes if necessary
=> [CHORE] improve CI tests to run subset when only js or go changes are made

Cargo.lock, rust/storage/src/admissioncontrolleds3.rs, rust/storage/src/lib.rs, rust/storage/src/local.rs, rust/storage/src/object_store.rs, rust/storage/src/s3.rs, rust/wal3/src/lib.rs, rust/wal3/src/manifest.rs
This skeleton shows these types and where the storage crate will plug in.
=> [ENH]  Add manifest and snapshot types.

rust/index/src/hnsw_provider.rs
In production, we frequently see the error "Failed to remove temporary files for ******. No such file or directory (os error 2)". Although unlikely, there's a possible race condition that would cause this: the index is evicted from the cache while another task is inside the `purge_by_id()` method.
Changing the not found error to a warning for now to reduce pages.
n/a
=> [BUG]: supress not found error on temporary HNSW file removal

Cargo.lock, idl/chromadb/proto/query_executor.proto, rust/frontend/src/executor/distributed.rs, rust/frontend/src/executor/local.rs, rust/frontend/src/frontend.rs, rust/segment/src/sqlite_metadata.rs, rust/segment/src/test.rs, rust/types/src/api_types.rs, rust/types/src/execution/operator.rs, rust/types/src/record.rs, rust/worker/benches/get.rs, rust/worker/src/execution/orchestration/count.rs, rust/worker/src/execution/orchestration/get.rs, rust/worker/src/execution/orchestration/knn_filter.rs, rust/worker/src/server.rs, rust/worker/src/utils/convert.rs
- N/A
- Added the size of pulled log on the read endpoint results
=> [ENH] Add log bytes pulled as part of query result

rust/index/src/hnsw_provider.rs
This PR cherry-picks the commit c47769fa9e07732d850dd3b9e9e72ec5aa21bf0f onto release/2025-03-07. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #3969 to release/2025-03-07

rust/wal3/README.md, rust/wal3/src/lib.rs, rust/wal3/src/manifest.rs, rust/wal3/src/reader.rs, rust/wal3/src/writer.rs
This introduces a bare-bones reader for wal3 files that does not cache the fragments or snapshots.
=> [ENH]  Non-caching reader for wal3.

rust/wal3/examples/wal3-bench.rs, rust/wal3/src/manifest.rs, rust/wal3/src/manifest_manager.rs, rust/wal3/src/writer.rs
This PR threads through the debug-oriented writer field and adds a test that the manifest manager works as intended.
=> [TST] A test for the manager in wal3.

rust/sysdb/src/sysdb.rs, rust/sysdb/src/test_sysdb.rs
- ...
- Adds a `list_databases` method to the `TestSysDB`
=> [ENH] Add list_databases to TestSysDB

.github/actions/tilt/action.yaml, .github/workflows/_go-tests.yml, .github/workflows/_python-tests.yml, .github/workflows/_rust-tests.yml, Tiltfile, k8s/distributed-chroma/values.yaml, k8s/test/postgres.yaml
- Use depot builds for ci, greatly speeding up some parts of ci
- ...
=> [ENH] Use depot build in tilt ci

go/Dockerfile.migration, k8s/distributed-chroma/Chart.yaml, k8s/distributed-chroma/templates/sysdb-migration.yaml
=> [ENH] Unify images

rust/types/src/api_types.rs
Some endpoints were not serializing, resulting in null entries in the OpenAPI schema.
=> [ENH] Update OpenAPI spec for new endpoints

Cargo.lock, rust/frontend/src/lib.rs, rust/sysdb/Cargo.toml, rust/tracing/Cargo.toml, rust/tracing/src/init_tracer.rs, rust/worker/Cargo.toml
- Pretty print the trace in stdout. This gives us better readability of logs in Tilt
- N/A
=> [ENH] Pretty print trace in stdout

rust/garbage_collector/src/operators/compute_versions_to_delete.rs, rust/garbage_collector/src/operators/fetch_sparse_index_files.rs, rust/system/src/execution/dispatcher.rs, rust/system/src/scheduler.rs, rust/system/src/system.rs, rust/worker/src/execution/operators/count_records.rs, rust/worker/src/execution/orchestration/compact.rs
- Cleans up some prints
- None
None
=> [CLN] Cleanup some prints

rust/index/src/spann/types.rs
- When GCing a head, if it is empty then delete it
- ...
None
=> [ENH] Handle empty PL during GC

docs/docs.trychroma.com/app/globals.css, docs/docs.trychroma.com/app/layout.tsx, docs/docs.trychroma.com/components/header/header-nav.tsx, docs/docs.trychroma.com/components/header/header.tsx, docs/docs.trychroma.com/components/header/updates-link.tsx, docs/docs.trychroma.com/components/header/x-link.tsx, docs/docs.trychroma.com/components/markdoc/ask-ai.tsx, docs/docs.trychroma.com/components/markdoc/code-block-header.tsx, docs/docs.trychroma.com/components/markdoc/markdoc-page.tsx, docs/docs.trychroma.com/components/markdoc/markdoc-renderer.tsx, docs/docs.trychroma.com/components/markdoc/tabs.tsx, docs/docs.trychroma.com/components/posthog/posthog-pageview.tsx, docs/docs.trychroma.com/components/sidebar/menu-item.tsx, docs/docs.trychroma.com/components/sidebar/page-index.tsx, docs/docs.trychroma.com/components/sidebar/page-link.tsx, docs/docs.trychroma.com/components/sidebar/scrollable-content.tsx, docs/docs.trychroma.com/components/sidebar/sidebar.tsx, docs/docs.trychroma.com/components/table-of-contents.tsx, docs/docs.trychroma.com/context/app-context.tsx, docs/docs.trychroma.com/markdoc/content/sidebar-config.ts, docs/docs.trychroma.com/next-env.d.ts
ship a visual lift to the docs
=> [ENH] docs visual improvements

docs/docs.trychroma.com/components/posthog/posthog-pageview.tsx, docs/docs.trychroma.com/components/sidebar/page-link.tsx, docs/docs.trychroma.com/components/sidebar/scrollable-content.tsx, docs/docs.trychroma.com/context/app-context.tsx, docs/docs.trychroma.com/markdoc/content/sidebar-config.ts
next build succeeds locally but not on vercel. 
debugging
=> [BUG] bump to make vercel build run

rust/worker/src/execution/operators/fetch_log.rs, rust/worker/src/execution/operators/filter.rs, rust/worker/src/execution/operators/knn_projection.rs
=> [CLN] Some large traces

chromadb/test/utils/test_embedding_function_schemas.py
mocks all ef's in tests to stop flaky tests
=> [TST] mock all embedding functions in prop tests

.github/workflows/_rust-tests.yml, rust/worker/src/compactor/compaction_manager.rs
- Run bench in CI. Previously we only check that the bench can build
- N/A
=> [TST] Run benchmark in CI

rust/garbage_collector/src/garbage_collector_component.rs, rust/log/src/local_compaction_manager.rs, rust/memberlist/src/memberlist_provider.rs, rust/system/src/execution/dispatcher.rs, rust/system/src/execution/operator.rs, rust/system/src/execution/orchestrator.rs, rust/system/src/execution/worker_thread.rs, rust/system/src/executor.rs, rust/system/src/scheduler.rs, rust/system/src/types.rs, rust/worker/src/compactor/compaction_manager.rs
- Renames the component method for better interpretability
- N/A
=> [CLN] Revise component method naming

rust/log/src/log.rs, rust/segment/src/blockfile_record.rs, rust/segment/src/types.rs, rust/sysdb/src/sysdb.rs, rust/sysdb/src/test_sysdb.rs, rust/types/src/metadata.rs, rust/worker/src/compactor/compaction_manager.rs, rust/worker/src/compactor/scheduler.rs, rust/worker/src/compactor/scheduler_policy.rs, rust/worker/src/compactor/types.rs, rust/worker/src/execution/operators/materialize_logs.rs, rust/worker/src/execution/operators/register.rs, rust/worker/src/execution/orchestration/compact.rs
- N/A
- Calculate delta in logical size during materialization
=> [ENH] Propagate collection logical size to SysDB

go/pkg/sysdb/coordinator/model/collection.go, go/pkg/sysdb/coordinator/table_catalog.go, go/pkg/sysdb/grpc/collection_service.go, go/pkg/sysdb/metastore/db/dao/collection.go, go/pkg/sysdb/metastore/db/dao/collection_test.go, go/pkg/sysdb/metastore/db/dbmodel/collection.go, go/pkg/sysdb/metastore/db/dbmodel/mocks/ICollectionDb.go, idl/chromadb/proto/coordinator.proto, rust/log/src/log.rs, rust/segment/src/blockfile_record.rs, rust/segment/src/types.rs, rust/sysdb/src/sysdb.rs, rust/sysdb/src/test_sysdb.rs, rust/types/src/metadata.rs, rust/worker/src/compactor/compaction_manager.rs, rust/worker/src/compactor/scheduler.rs, rust/worker/src/compactor/scheduler_policy.rs, rust/worker/src/compactor/types.rs, rust/worker/src/execution/operators/materialize_logs.rs, rust/worker/src/execution/operators/register.rs, rust/worker/src/execution/orchestration/compact.rs
Reverts chroma-core/chroma#4019
=> Revert "[ENH] Calculate and update collection logical size during compaction"

go/pkg/sysdb/coordinator/model/collection.go, go/pkg/sysdb/coordinator/table_catalog.go, go/pkg/sysdb/grpc/collection_service.go, go/pkg/sysdb/metastore/db/dao/collection.go, go/pkg/sysdb/metastore/db/dao/collection_test.go, go/pkg/sysdb/metastore/db/dbmodel/collection.go, go/pkg/sysdb/metastore/db/dbmodel/mocks/ICollectionDb.go, idl/chromadb/proto/coordinator.proto, rust/log/src/log.rs, rust/segment/src/blockfile_record.rs, rust/segment/src/types.rs, rust/sysdb/src/sysdb.rs, rust/sysdb/src/test_sysdb.rs, rust/types/src/metadata.rs, rust/worker/src/compactor/compaction_manager.rs, rust/worker/src/compactor/scheduler.rs, rust/worker/src/compactor/scheduler_policy.rs, rust/worker/src/compactor/types.rs, rust/worker/src/execution/operators/materialize_logs.rs, rust/worker/src/execution/operators/register.rs, rust/worker/src/execution/orchestration/compact.rs
Fixes issues in https://github.com/chroma-core/chroma/pull/4019
=> [ENH] Calculate and update collection logical size during compaction

rust/frontend/src/server.rs
- Handle request to root in RFE. This caused async python client to fail
- ...
=> [BUG] Handle request to root in RFE server

chromadb/api/async_client.py, chromadb/api/client.py, chromadb/api/collection_configuration.py, chromadb/api/models/CollectionCommon.py, chromadb/api/rust.py, chromadb/api/segment.py, chromadb/api/types.py, chromadb/test/configurations/test_collection_configuration.py, chromadb/test/property/test_sysdb.py, chromadb/test/segment/distributed/test_protobuf_translation.py, chromadb/utils/embedding_functions/__init__.py, chromadb/utils/embedding_functions/cohere_embedding_function.py, chromadb/utils/embedding_functions/google_embedding_function.py, chromadb/utils/embedding_functions/huggingface_embedding_function.py, chromadb/utils/embedding_functions/instructor_embedding_function.py, chromadb/utils/embedding_functions/jina_embedding_function.py, chromadb/utils/embedding_functions/ollama_embedding_function.py, chromadb/utils/embedding_functions/onnx_mini_lm_l6_v2.py, chromadb/utils/embedding_functions/open_clip_embedding_function.py, chromadb/utils/embedding_functions/openai_embedding_function.py, chromadb/utils/embedding_functions/roboflow_embedding_function.py, chromadb/utils/embedding_functions/sentence_transformer_embedding_function.py, chromadb/utils/embedding_functions/text2vec_embedding_function.py, chromadb/utils/embedding_functions/voyageai_embedding_function.py
=> [CHORE] Allow generic embedding function for type safety, make Space literal

rust/frontend/src/server.rs
This PR cherry-picks the commit ${cherryCommit} onto origin/release/2025-03-21. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4091 to release/2025-03-21

Cargo.lock, Cargo.toml, chromadb/test/utils/wait_for_version_increase.py, rust/storage/Cargo.toml, rust/wal3/src/batch_manager.rs, rust/wal3/src/lib.rs, rust/wal3/src/manifest.rs, rust/wal3/src/manifest_manager.rs, rust/wal3/src/reader.rs, rust/wal3/src/writer.rs, rust/wal3/tests/common.rs, rust/wal3/tests/test_k8s_integration_00_empty_and_initialize.rs, rust/wal3/tests/test_k8s_integration_01_empty_and_open.rs, rust/wal3/tests/test_k8s_integration_02_initialized_init_again.rs, rust/wal3/tests/test_k8s_integration_03_initialized_append_succeeds.rs, rust/wal3/tests/test_k8s_integration_04_initialized_append_until_snapshot.rs, rust/wal3/tests/test_k8s_integration_05_crash_safety_initialize_fails.rs
This gets the basics of starting from nothing or an initialized
manifest right.  This also recovers from a manifest failing to write.
This tests every crash safety scenario.  I considered property tests, but these tests guarantee each position in the state space gets hit.
=>  [TST]  Start of tests for wal3.

Cargo.lock, rust/log-service/src/lib.rs, rust/storage/src/s3.rs, rust/wal3/Cargo.toml, rust/wal3/README.md, rust/wal3/examples/wal3-bench.rs, rust/wal3/src/bin/wal3-scrub.rs, rust/wal3/src/lib.rs, rust/wal3/src/manifest.rs, rust/wal3/src/manifest_manager.rs, rust/wal3/src/reader.rs, rust/wal3/src/writer.rs, rust/wal3/tests/common.rs, rust/wal3/tests/test_k8s_integration_01_empty_and_open.rs, rust/wal3/tests/test_k8s_integration_03_initialized_append_succeeds.rs, rust/wal3/tests/test_k8s_integration_04_initialized_append_until_snapshot.rs, rust/wal3/tests/test_k8s_integration_05_crash_safety_initialize_fails.rs, rust/wal3/tests/test_k8s_integration_99_load_and_scrub.rs
Currently hard-coded to dev environment, but verified over multiple gigabytes of logs, the setsums scrub properly.
Also includes a bugfix.
=> [ENH] Wal3 scrub tool and feature.

k8s/distributed-chroma/Chart.yaml, k8s/distributed-chroma/templates/rust-log-service.yaml
- Adds the service account for rust log service so we can IRSA for the s3 perms for it
- ...
None
=> [CHORE] Add service account for rust log service

rust/index/src/config.rs, rust/index/src/spann/types.rs, rust/segment/src/distributed_spann.rs, rust/worker/tests/config_from_default_path.rs, rust/worker/tests/config_from_specific_path.rs, rust/worker/tests/config_missing_default_field.rs
- Resize only once in the beginning for HNSW GC
- Automatically GC HNSW based on delete percentage
- Specify #[source] for error types so as to not drop errors in the middle
- ...
None
=> [ENH] Spann miscellanous fixes

rust/garbage_collector/src/operators/delete_versions_at_sysdb.rs
Does what it says on the tin.
Addresses the comment here: https://github.com/chroma-core/chroma/pull/4068#discussion_r2019120596
Added a test to cover the change.
n/a
=> [ENH]: `DeleteVersionsAtSysDbOperator` should only delete files marked for deletion

rust/index/src/spann/types.rs, rust/worker/src/execution/operators/spann_fetch_pl.rs
- To debug query performance
- ...
None
=> [ENH] Add tracing instrumentation to spann fetch PL operator

go/pkg/log/purging/main.go
- Run log purge at boot
- None
They are not
None
=> [ENH] Run log purge at boot

go/pkg/log/repository/log.go
- Add some light logging to purge loop
- ...
None
=> [ENH] Add logging to purge

idl/chromadb/proto/compactor.proto, rust/segment/src/test.rs, rust/worker/src/compactor/compaction_client.rs, rust/worker/src/compactor/compaction_manager.rs, rust/worker/src/compactor/compaction_server.rs, rust/worker/src/compactor/scheduler.rs, rust/worker/src/compactor/scheduler_policy.rs, rust/worker/src/compactor/types.rs, rust/worker/src/execution/operators/fetch_log.rs, rust/worker/src/execution/operators/projection.rs, rust/worker/src/execution/orchestration/compact.rs, rust/worker/src/server.rs, rust/worker/src/utils/convert.rs
- Updates compaction job definition
- Add the rebuild endpoint for compaction server
=> [ENH] Implement rebuild endpoint for compaction server

sample_apps/listing.json
Adding `sample_apps/listing.json` for sample apps definitions.
N/A
N/A
=> [ENH] Adding listing for sample apps

sample_apps/generative_benchmarking/README.md, sample_apps/generative_benchmarking/config.json, sample_apps/listings.json
Add `config.json` for generative benchmarking sample app
N/A
N/A
=> [ENH] Add gen benchmarking config

sample_apps/generative_benchmarking/config.json, sample_apps/listing.json
Update generative-benchmarking config
N/A
N/A
=> [ENH] Update gen-benchmarking config

rust/cli/src/lib.rs
Hide unannounced CLI commands from release
=> [BUG] Hide unannounced commands

docs/docs.trychroma.com/markdoc/content/sidebar-config.ts
=> [DOC] Update CLI main page

docs/docs.trychroma.com/markdoc/content/cli/install.md
=> [DOC] Update CLI install

rust/cli/install/install.ps1
Update CLI Windows installation script
=> [BUG] Update version in windows CLI installation script

docs/docs.trychroma.com/markdoc/content/cli/install.md
=> [DOC] Nit in docs

bin/windows_upgrade_sqlite.py
The script that upgrades SQLite on Windows during CI broke.
=> [BLD]: fix Windows SQLite upgrade script for CI

rust/frontend/sample_configs/tilt_config.yaml, rust/worker/tilt_config.yaml
=> [BUG] disable wal3 because it fails on main

rust/garbage_collector/src/helper.rs
#4226 disabled for everything except gc.  This completes that.
=> [BUG]  Fix build by changing gc logservice channel.

docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/baseten.md
Fix render issue causing 500 when loading Baseten docs page
Ran markdoc server locally to verify
This is a docs change
=> [DOC] Fix rendering issue in Baseten doc

go/pkg/log/server/server.go
This PR cherry-picks the commit 9b0dc21055a5b3ff7ecd59e221936ecda57a2687 onto origin/release/2025-04-04. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4237 to origin/release/2025-04-04

rust/frontend/sample_configs/tilt_config.yaml, rust/garbage_collector/src/helper.rs, rust/log-service/src/lib.rs, rust/log/src/grpc_log.rs, rust/worker/tilt_config.yaml
This will make the 50052 port and go service go untested, at the benefit of testing the new service.
To make tests pass, I had to up the fetch_logs_batch_size in testing.  This will not affect staging or prod.
Also bundled:  Tracing changes.
=> [ENH] Reenable wal3

rust/error/src/lib.rs, rust/error/src/tonic.rs, rust/frontend/src/quota/mod.rs
- Updates the QuotaExceededError HTTP status code from 429 to 422. Also implements a more readable error message.
- ...
=> [ENH] Update QuotaExceededError status code and message

rust/wal3/src/batch_manager.rs, rust/wal3/src/writer.rs
=> [ENH]  Add some tracing spans to wal3.

docs/docs.trychroma.com/markdoc/content/cli/sample-apps.md
clarify which version of the CLI you need to use the install command
=> [ENH] clarify CLI version req for install command

rust/frontend/sample_configs/tilt_config.yaml, rust/frontend/src/server.rs, rust/frontend/src/types/errors.rs
This will enable the scorecard in code because we didn't actually do anything with the result of
scorecard.
None
=> [BUG]  Return a rate limit error when scorecard trips.

.github/actions/go/action.yaml, .github/actions/python/action.yaml, .github/actions/rust/action.yaml, .github/actions/tilt/action.yaml, .github/workflows/_build_js_bindings.yml, .github/workflows/_build_release_container.yml, .github/workflows/_build_release_pypi.yml, .github/workflows/_go-tests.yml, .github/workflows/_javascript-client-tests.yml, .github/workflows/_python-tests.yml, .github/workflows/_python-vulnerability-scan.yml, .github/workflows/_rust-tests.yml, .github/workflows/apply-hotfix.yaml, .github/workflows/nightly-tests.yml, .github/workflows/pr-review-checklist.yml, .github/workflows/pr.yml, .github/workflows/release-chromadb.yml, .github/workflows/release-cli.yml, .github/workflows/release-dev-javascript-client.yml, .github/workflows/release-helm-chart.yml, .github/workflows/release-javascript-client.yml, .github/workflows/trigger-deploy.yaml, Tiltfile
- This builds on #4312 but adds conditionality for windows runners on GH
- None
None
=> [BLD] Switch to blacksmith runners 

docs/docs.trychroma.com/markdoc/content/integrations/frameworks/deepeval.md
Update links due to domain name changes.
NA
Yes
=> [DOC] Update DeepEval Links

go/pkg/sysdb/coordinator/coordinator_test.go, go/pkg/sysdb/coordinator/model/collection.go, go/pkg/sysdb/coordinator/model_db_convert.go, go/pkg/sysdb/coordinator/table_catalog.go, go/pkg/sysdb/coordinator/table_catalog_test.go, go/pkg/sysdb/grpc/collection_service.go, go/pkg/sysdb/metastore/db/dao/collection.go, go/pkg/sysdb/metastore/db/dbmodel/collection.go, go/pkg/sysdb/metastore/db/dbmodel/mocks/ICollectionDb.go, go/pkg/sysdb/metastore/s3/impl.go
- N/A
- Implement collection forking in SysDB
=> [ENH] Implement collection forking in SysDB

go/pkg/common/errors.go, go/pkg/log/repository/log.go
- Fixes a typo in log fork impl that led to wrong enumeration offset for the new collection
- Replaces updates with insert when populating the offsets for the new collection
- ...
=> [BUG] Fix log fork bugs

rust/frontend/src/server.rs
- Enables quota for fork in order to gate access
- None
None
=> [CLN] Enable quota for fork

docs/docs.trychroma.com/markdoc/content/docs/overview/contributing.md
This is just closing the loop on #4130 , which seems to have gotten out of sync with my local branch, so the revision requests I was responding to weren't getting pushed up, so I'll just close that one. Also, I noticed that in the meantime @jeffchuber already merged a PR #4286 with my changes, the only difference being that this adds a link to the channel. 🤷 
So this is a really trivial PR, just making it so that I can close out the other one and maybe you like this minuscule enhancement.
@jairad26
=> [CHORE]: Discord - link to channel

go/pkg/sysdb/coordinator/table_catalog.go, go/pkg/sysdb/metastore/db/dao/collection.go, go/pkg/sysdb/metastore/s3/impl.go, rust/frontend/src/server.rs
- Fix lineage file path
- Fix root collection tracing during fork
- ...
=> [BUG] Fix lineage file path and root collection tracing

.github/workflows/_python-tests.yml, chromadb/test/property/test_fork.py
- N/A
- Add prop test for collection forking
=> [TST] Add property test for collection forking

docs/docs.trychroma.com/markdoc/content/docs/collections/configure.md
=> [DOC]: Fix wrong cohere import in collection config docs

rust/frontend/src/impls/service_based_frontend.rs, rust/tracing/src/meter_event.rs
- N/A
- Track collection fork in meter event
=> [ENH] Track collection forking events

rust/garbage_collector/src/operators/compute_unused_files.rs
This operator was previously swallowing error details.
=> [ENH]: better errors in `ComputeUnusedFilesOperator`

rust/garbage_collector/src/garbage_collector_component.rs, rust/garbage_collector/src/garbage_collector_orchestrator.rs, rust/garbage_collector/src/helper.rs, rust/garbage_collector/src/operators/compute_unused_files.rs, rust/garbage_collector/src/operators/fetch_sparse_index_files.rs
This PR cherry-picks the commit 12a633c95e70413c02246af525250d0b58f694c0 onto release/2025-04-25. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4401 to release/2025-04-25

clients/js/packages/chromadb/package.json, rust/cli/install/install.ps1, rust/cli/install/install.sh, rust/cli/src/client/collection.rs, rust/cli/src/commands/copy.rs, rust/frontend/src/server.rs, rust/js_bindings/npm/darwin-arm64/package.json, rust/js_bindings/npm/darwin-x64/package.json, rust/js_bindings/npm/linux-arm64-gnu/package.json, rust/js_bindings/npm/linux-x64-gnu/package.json, rust/js_bindings/npm/win32-arm64-msvc/package.json, rust/js_bindings/npm/win32-x64-msvc/package.json
Update version for JS bindings and version for standalone installation scripts.
N/A
=> [RELEASE] Release CLI 1.1.0

clients/js/package.json, clients/js/packages/chromadb-client/package.json, clients/js/packages/chromadb-core/package.json, clients/js/packages/chromadb/package.json
Release JS client 2.4.0 with new CLI.
N/A
=> [RELEASE] JS release 2.4.0

clients/js/package.json, clients/js/packages/chromadb-client/package.json, clients/js/packages/chromadb-core/package.json, clients/js/packages/chromadb/package.json
=> [RELEASE] Release JS client 2.4.1

clients/js/package.json, clients/js/packages/chromadb-client/package.json, clients/js/packages/chromadb-core/package.json, clients/js/packages/chromadb/package.json
Release JS client with updated bindings for CLI
=> [RELEASE] JS Client 2.4.2

.github/workflows/_python-tests.yml, chromadb/test/test_cli.py, rust/cli/src/commands/vacuum.rs
This PR cherry-picks the commit 4e8df93a0bd0aa6f9c2ecd4b0f86e5c3ff6a38ac onto rc/2025-05-02. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4453 to rc/2025-05-02

.github/workflows/_python-tests.yml, rust/index/src/fulltext/types.rs, rust/index/src/fulltext/util.rs
This PR cherry-picks the commit db280e9e20baa5463843aee21c4aa3f975d640fc onto rc/2025-05-02. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4422 to rc/2025-05-02

.github/workflows/_build_js_bindings.yml, clients/js/packages/chromadb/package.json, rust/js_bindings/npm/darwin-arm64/package.json, rust/js_bindings/npm/darwin-x64/package.json, rust/js_bindings/npm/linux-arm64-gnu/package.json, rust/js_bindings/npm/linux-x64-gnu/package.json, rust/js_bindings/npm/win32-arm64-msvc/package.json, rust/js_bindings/npm/win32-x64-msvc/package.json
Update JS bindings CI with more debugging
=> [CHORE] Update JS bindings CI

go/pkg/log/repository/log.go, go/pkg/log/repository/log_test.go, rust/frontend/src/impls/service_based_frontend.rs, rust/log/src/grpc_log.rs
This PR cherry-picks the commit 048583dcfb0353b25cdd231b8d521ebda1bf5f98 onto rc/2025-05-02. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4457 to rc/2025-05-02

rust/frontend/src/quota/mod.rs
- Introduces this usage type with a default of 0
- ...
None
=> [ENH]: Introduce NUM_REGEX_PREDICATES

rust/js_bindings/Cargo.toml
It is a NOP block that's removed.
C/I.
N/A.
=> [CLN]  Cleanup a warning in js_bindings/Cargo.toml.

Cargo.lock, clients/js/packages/chromadb/src/cli.ts, rust/cli/Cargo.toml, rust/cli/src/commands/install.rs, rust/cli/src/commands/update.rs
* Add struct to properly parse Github endpoint API
* Fix wrong version check for installing sample apps
N/A
=> [BUG] Fix CLI update command

rust/wal3/src/manifest_manager.rs
There were two tests in manifest-manager that got disabled during a
refactor.  Re-enable the one, and delete the other as it's no longer
relevant because there is no background thread that can be disabled.
N/A
=> [BUG]  Restore commented-out test.

go/pkg/log/repository/log.go
- Can get unique constraint violation even when two writes contend to collection table. Return AlreadyExists so that FE can retry
- ...
None
=> [ENH]: Unique constraint violation when two writes contend for collection table on log

Cargo.lock, clients/js/packages/chromadb/package.json, rust/cli/Cargo.toml, rust/cli/install/install.ps1, rust/cli/install/install.sh, rust/js_bindings/npm/darwin-arm64/package.json, rust/js_bindings/npm/darwin-x64/package.json, rust/js_bindings/npm/linux-arm64-gnu/package.json, rust/js_bindings/npm/linux-x64-gnu/package.json, rust/js_bindings/npm/win32-arm64-msvc/package.json, rust/js_bindings/npm/win32-x64-msvc/package.json
Releasing CLI 1.1.1
* Fix Github release fetch bug affecting `install` and `update
=> [RELEASE] CLI 1.1.1

chromadb/__init__.py
=> [RELEASE] 1.0.9

rust/log-service/src/lib.rs
Questions for review:
- Should we name this metric differently?
- How/if should we tag it to differentiate from go?
N/A
=> [ENH]  Emit log_uncompacted_record_count from rust log service.

rust/worker/src/execution/operators/filter.rs, rust/worker/src/execution/operators/projection.rs
This PR cherry-picks the commit 1880120afbdb791dbc70d6d41b58c840b452e853 onto release/2025-05-09. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4548 to release/2025-05-09

rust/segment/src/sqlite_metadata.rs
previously on FTS operations, the left join + filter meant all rows were accumulated before applying the where clause to limit the results. Now, we introduced a subquery approach, similar to metadata so that the subquery can resolve first, and removed the left join. Since we are now using in on the subquery, and embedding<>metadata are 1:1 (unlike embedding<>metadata which is 1:many meaning we must do the left join). the left join on the fts table gets optimized away by sqlite anyways, so this is a code clarity update to remove the lj.
before:
after:
=> [ENH] use subqueries for fts locally

clients/js/package.json, clients/js/packages/chromadb-client/package.json, clients/js/packages/chromadb-core/package.json
Includes : https://github.com/chroma-core/chroma/pull/4569
=> [ENH] bump JS client to v2.4.5

rust/index/src/fulltext/types.rs, rust/types/src/regex/literal_expr.rs, rust/worker/src/execution/operators/filter.rs, rust/worker/src/execution/operators/limit.rs
This PR cherry-picks the commit ef112aefc7fea3104dd18eb930cfbd2aceddd739 onto rc/2025-05-16. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4562 to rc/2025-05-16

go/pkg/sysdb/coordinator/coordinator.go, go/pkg/sysdb/coordinator/coordinator_test.go, go/pkg/sysdb/coordinator/model/collection.go, go/pkg/sysdb/coordinator/model_db_convert.go, go/pkg/sysdb/coordinator/model_db_convert_test.go, go/pkg/sysdb/coordinator/table_catalog.go, go/pkg/sysdb/coordinator/table_catalog_test.go, go/pkg/sysdb/grpc/tenant_database_service_test.go, go/pkg/sysdb/metastore/db/dao/collection.go
This PR cherry-picks the commit 464c2e5919b8f46fd949c9059181d54a34c2f9a8 onto rc/2025-05-16. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4552 to rc/2025-05-16

.github/actions/tilt/action.yaml
Retry kind setup. DNS appears to occasionally flake: https://github.com/chroma-core/chroma/actions/runs/15145093152/job/42578809842
=> [BLD] retry kind setup

rust/types/src/regex/literal_expr.rs, rust/types/src/regex/mod.rs, rust/types/src/where_parsing.rs, rust/worker/src/execution/operators/filter.rs
This PR cherry-picks the commit 713978e2c1abc87f031fea97d5ee8f185e8d7232 onto release/2025-05-16. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4582 to release/2025-05-16

.github/workflows/release-chromadb.yml, .github/workflows/trigger-deploy.yaml
This PR cherry-picks the commit 87561f7932208f28c335a15e3856156b4da2c14f onto release/2025-05-16. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4561 to release/2025-05-16

.github/workflows/_python-tests.yml, chromadb/test/distributed/test_log_failover.py, idl/chromadb/proto/logservice.proto, idl/makefile, rust/log-service/src/lib.rs, rust/log/tests/log-offsets.rs, rust/wal3/src/cursors.rs
Adds a test.  The test will add 100 records, failover, add 100 more records, and then read all 200 records.
I will run the test I've added.
N/A
=> [ENH] Test log failover

chromadb/test/distributed/test_log_failover.py, go/pkg/sysdb/coordinator/table_catalog.go, rust/log-service/src/lib.rs
Description of how it happens in the tests.
CI + local testing of the new test.
N/A
=> [BUG] Cache + Log = Missing data on read.

clients/js/package.json, clients/js/packages/chromadb-client/package.json, clients/js/packages/chromadb-core/package.json, clients/js/packages/chromadb/package.json, rust/js_bindings/npm/darwin-arm64/package.json, rust/js_bindings/npm/darwin-x64/package.json, rust/js_bindings/npm/linux-arm64-gnu/package.json, rust/js_bindings/npm/linux-x64-gnu/package.json, rust/js_bindings/npm/win32-arm64-msvc/package.json, rust/js_bindings/npm/win32-x64-msvc/package.json
=> [RELEASE] JS client 2.4.7

chromadb/test/distributed/test_log_failover.py
I'm adding a test.
CI; new test passes locally.
N/A
=> [TST]  Add another test for log failover.

Cargo.lock, Cargo.toml, rust/python_bindings/Cargo.toml
This PR fixes open dependabot problems in the Rust codebase.
CI
N/A
=> [CHORE] Clean up dependabot alerts for Rust.

rust/types/src/api_types.rs
This PR cherry-picks the commit aaea8f752f8ce8618a233f387c1e171d1f4823ec onto release/2025-05-16. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4646 to release/2025-05-16

go/pkg/sysdb/metastore/db/dao/collection.go
This PR cherry-picks the commit a6f30a387fb27cb91823a8c61f78fab9d9861841 onto release/2025-05-23. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4663 to release/2025-05-23

.github/workflows/_python-tests.yml
=> [BLD]: fix typo so that test durations are reported properly

go/pkg/sysdb/coordinator/table_catalog.go, rust/log-service/src/lib.rs
Smoke test is failing on fork.  Add debug to see what's what.
Log lines should "just work".
N/A
=> [ENH]  Add logging statements to figure out why forking is failing in staging.

rust/garbage_collector/src/garbage_collector_component.rs, rust/garbage_collector/src/types.rs
This PR cherry-picks the commit 2d50100d9da6f333092fc04ffef27aaebdbe4de7 onto rc/2025-05-30. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4681 to rc/2025-05-30

go/pkg/sysdb/coordinator/table_catalog.go, rust/log-service/src/lib.rs
Smoke test is failing on fork.  Add debug to see what's what.
Log lines should "just work".
`cargo test` for rust
N/A
=> [ENH]  Add logging statements to figure out why forking is failing in staging. (#4679)

rust/log-service/src/lib.rs
- Fixes the off by one error during collection forking in rust log service
- N/A
_Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the [docs
section](https://github.com/chroma-core/chroma/tree/main/docs/docs.trychroma.com)?_
- ...
- ...
=> [BUG] Rust log service fork offsets off by one (#4689)

rust/log-service/src/lib.rs
Add tracing spans to see individual calls to get cursors and manifests.
=> [CHORE]  Instrumentation of dirty log rollup

rust/log-service/src/lib.rs, rust/wal3/src/reader.rs
Claude and I wrote some tests that focus on overflow cases and potential
boundary conditions.
Also embeds 4710:
Here's the scenario: A client is writing in batches to the log. The
batches come in groups, and wal3 does de-amplification of batches.
Imagine running a pull logs. Prior to this change, the pull logs can
only knows which files to fetch based upon the number of files or number
of bytes.
By pruning to number of records, we allow for the case where there's one
fragment that has BatchSize records, and so we only need to fetch one
fragment to read its records.
cargo test -p chroma-log-service --lib
`cargo test` for rust
N/A
=> [HOTFIX] PullLogs efficiency win for Rust Log Service

docs/docs.trychroma.com/markdoc/content/integrations/frameworks/llamaindex.md
=> [DOC] - Fixes broken URLs

rust/wal3/src/reader.rs
The setup:
- Fragments with LogPosition ranges [1, 101), [101, 201).
- Query for 75 records at offset 50 should fetch both fragments.
- Prior to this change only the first fragment was fetched.
N/A
=> [BUG] Fix a bug in the wal3 records-based pruning.

go/pkg/log/repository/log.go
Reverts chroma-core/chroma#4734
=> Revert "[ENH]  Simplify forking logic in go log"

rust/tracing/src/init_tracer.rs
Adds tracing for continuous_verification crate.
Tested locally via tilt.
N/A
=> [CHORE] Add tracing for continuous verification

.github/actions/tilt-setup-prebuild/action.yaml
Added comment explaining why this is needed.
=> [BLD]: specify working directory in reusable Tilt setup action

.github/actions/go/action.yaml, .github/actions/python/action.yaml, .github/actions/rust/action.yaml, .github/workflows/_build_js_bindings.yml, .github/workflows/_build_release_pypi.yml, .github/workflows/pr.yml, .github/workflows/release-chromadb.yml, .github/workflows/release-dev-javascript-client.yml, .github/workflows/release-javascript-client.yml
Blacksmith now supports transparent caching.
Workflows pass in this PR.
=> [BLD]: remove usage of forked Blacksmith actions

.github/workflows/release-chromadb.yml
https://github.com/chroma-core/chroma/actions/runs/15645712796
Broke after https://github.com/chroma-core/chroma/pull/4792.
=> [BLD]: fix missing option in release-chromadb.yml workflow

rust/garbage_collector/src/operators/list_files_at_version.rs
- S3 get call was previously orphaned because the span context was not automatically passed through when using `JoinSet::spawn()`
- limits concurrency of `get_all_block_ids()` tasks to 32
Verified in Jaeger that orphaned span is fixed.
n/a
=> [ENH]: limit concurrent get_all_block_ids() and fix orphaned span

DEVELOP.md
Updating DEVELOP.md with information on setting up Tilt and debugging within local dev environments.
- N/A
- N/A
- [ v] Tests pass locally with `pytest` for python, `yarn test` for js, `cargo test` for rust
=> [DOC] Update DEVELOP.md with details on Tilt setup and debugging

Cargo.lock, Cargo.toml, k8s/distributed-chroma/Chart.yaml, k8s/distributed-chroma/templates/garbage-collector.yaml, k8s/distributed-chroma/values.dev.yaml, rust/garbage_collector/Cargo.toml, rust/garbage_collector/src/bin/garbage_collector_service.rs, rust/garbage_collector/src/config.rs, rust/garbage_collector/src/garbage_collector_component.rs, rust/garbage_collector/src/lib.rs, rust/index/Cargo.toml, rust/jemalloc-pprof-server/Cargo.toml, rust/jemalloc-pprof-server/src/lib.rs, rust/worker/Cargo.toml
This PR cherry-picks the commit 13df08f11730fbee1e5daa633b3d066f1f9319a8 onto origin/release/2025-06-13. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4845 to release/2025-06-13

chromadb/telemetry/product/events.py
Increases posthog batch sizes to decrease cost
=> [CHORE] increase posthog batch size

rust/log/src/grpc_log.rs
It's possible for a log to be on one service, migrate, and be on
another.  This leaves garbage on one dirty log.  The protocol is for a
compactor to call PurgeDirtyMarker to clear the dirty marker, but it
could be misrouted.
CI
n/a
=> [ENH]  Make compactors purge the dirty markers from all log services

rust/garbage_collector/src/construct_version_graph_orchestrator.rs, rust/garbage_collector/src/garbage_collector_orchestrator.rs, rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs, rust/garbage_collector/src/operators/compute_unused_files.rs, rust/garbage_collector/src/operators/compute_versions_to_delete.rs, rust/garbage_collector/src/operators/delete_versions_at_sysdb.rs, rust/garbage_collector/src/operators/fetch_version_file.rs, rust/garbage_collector/src/operators/list_files_at_version.rs, rust/garbage_collector/src/operators/mark_versions_at_sysdb.rs
This PR cherry-picks the commit 6e5ec8f883a0885104d88e3bc69cb0945b75f18e onto release/2025-06-13. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4867 to release/2025-06-13

rust/log/src/grpc_log.rs
I suspect that purge dirty for collection is causing a thundering herd against the rust log service.
It's the last call that happens before things get slow.
CI
N/A
=> [ENH] Put a limiter on the purge_dirty_for_collection call.

clients/new-js/packages/chromadb/package.json
=> [RELEASE] JS 3.0.4

go/pkg/sysdb/grpc/collection_service.go
This PR cherry-picks the commit c3c23f33fadcfe022531e6061d5029ace39e69cf onto rc/2025-06-20. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4899 to rc/2025-06-20

rust/wal3/src/manifest.rs, rust/wal3/tests/test_k8s_integration_0_properties.rs
I noticed this is still not being set right.  Add a unit test and update
the prop tests to be more thorough.
N/A
=> [BUG]  Manifest-initial-offset was not set under gc conditions.

rust/wal3/src/gc.rs, rust/wal3/src/writer.rs
This PR cherry-picks the commit 26b8c1635898502a547f902374f7888db44eecc3 onto rc/2025-06-20. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4904 to rc/2025-06-20

rust/wal3/src/manifest.rs, rust/wal3/tests/test_k8s_integration_0_properties.rs
This PR cherry-picks the commit c4d0c934fc693ff0a953e6d8d80768b2c0989fe1 onto rc/2025-06-20. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4903 to rc/2025-06-20

rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
This PR cherry-picks the commit c7c257fda9cad5e0fc8f00ba6742cdc791bcfa37 onto rc/2025-06-20. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4929 to rc/2025-06-20

rust/wal3/src/batch_manager.rs, rust/wal3/src/manifest_manager.rs, rust/wal3/src/writer.rs
This PR cherry-picks the commit f92849ed3f65330a378bc87574d522d9f7672908 onto release/2025-06-20. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4964 to release/2025-06-20

docs/docs.trychroma.com/public/robots.txt
=> [ENH] Add robots.txt to allow all web crawlers on docs.trychroma.com

rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs, rust/garbage_collector/src/operators/delete_unused_logs.rs
- We would like to skip log gc in dry run mode
- N/A
=> [ENH] Skip log GC in dry run mode

rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs, rust/garbage_collector/src/operators/delete_unused_logs.rs
This PR cherry-picks the commit 70840a1f3bda911277e851653b89f78b803bc246 onto rc/2025-06-27. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4977 to rc/2025-06-27

rust/wal3/src/manifest_manager.rs, rust/wal3/src/writer.rs
This PR cherry-picks the commit 656ea74a259fd669a6ce8b210f783052754e275a onto rc/2025-06-27. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4972 to rc/2025-06-27

rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs, rust/garbage_collector/src/operators/delete_unused_logs.rs
This PR cherry-picks the commit 70840a1f3bda911277e851653b89f78b803bc246 onto release/2025-06-20. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4977 to release/2025-06-20

rust/garbage_collector/src/config.rs, rust/garbage_collector/src/garbage_collector_component.rs, rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs, rust/garbage_collector/src/operators/delete_unused_logs.rs, rust/garbage_collector/tests/proptest_helpers/garbage_collector_under_test.rs
This PR cherry-picks the commit f495f34e956bc2165418800e16b0d70a405b14d9 onto rc/2025-06-27. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5002 to rc/2025-06-27

Cargo.lock, rust/blockstore/src/arrow/block/types.rs, rust/cache/Cargo.toml, rust/cache/src/foyer.rs
- Ports changes in https://github.com/chroma-core/chroma/pull/4473 
- ...
None
=> [ENH]: Upgrade foyer to 0.17.3

rust/frontend/src/server.rs, rust/frontend/src/types/errors.rs
This PR cherry-picks the PR #5033 onto release/2025-06-27. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5033 to release/2025-06-27

Dockerfile, go/Dockerfile, rust/Dockerfile, rust/cli/Dockerfile, rust/garbage_collector/Dockerfile, rust/log-service/Dockerfile, rust/worker/Dockerfile
- Pins the protoc version and architecture across different dockerfiles
- N/A
=> [BUG] Sync protoc arch and version in dockerfile

rust/worker/src/execution/orchestration/get.rs, rust/worker/src/execution/orchestration/knn_filter.rs, rust/worker/src/execution/orchestration/spann_knn.rs
This PR cherry-picks the commit 80f3783418a01a2d3c743f747204fc204d97314c onto release/2025-06-27. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5053 to release/2025-06-27

rust/worker/src/execution/orchestration/get.rs, rust/worker/src/execution/orchestration/knn_filter.rs, rust/worker/src/execution/orchestration/spann_knn.rs
This PR cherry-picks the commit 80f3783418a01a2d3c743f747204fc204d97314c onto rc/2025-07-04. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5053 to rc/2025-07-04

clients/new-js/packages/chromadb/src/chroma-fetch.ts
Add billing error to JS client
=> [BUG] Add billing errors to JS client

clients/new-js/packages/chromadb/package.json
Release JS client 3.0.8:
* Includes better error messages for billing
=> [RELEASE] JS 3.0.8

pull_request_template.md
Update PR template for migration and observability
=> [DOC] Update PR template for migration and observability

go/pkg/log/server/server.go, idl/chromadb/proto/logservice.proto, rust/log-service/src/bin/chroma-log-service-purge-cache-entry.rs, rust/log-service/src/lib.rs
This PR cherry-picks the commit 6f8db1295b112b386b382587b0fba3505de585a9 onto rc/2025-07-11. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5085 to rc/2025-07-11

k8s/distributed-chroma/Chart.yaml, k8s/distributed-chroma/templates/compaction-service.yaml, k8s/distributed-chroma/templates/query-service.yaml, k8s/distributed-chroma/values.dev.yaml, rust/worker/src/compactor/compaction_server.rs, rust/worker/src/config.rs, rust/worker/src/lib.rs, rust/worker/tests/config_from_default_path.rs, rust/worker/tests/config_from_specific_path.rs, rust/worker/tests/config_with_env_override.rs, rust/worker/tests/config_without_cache_directive.rs
This PR cherry-picks the commit 6b40d2c73d8713954ec55d618f6c7f42490bc3a8 onto rc/2025-07-11. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5092 to rc/2025-07-11

rust/frontend/src/quota/mod.rs, rust/frontend/src/server.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
This PR cherry-picks the commit a4f208b7836e4e781ebd25cb220347bd44dfab92 onto release/2025-07-04. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4942 to release/2025-07-04

rust/frontend/src/quota/mod.rs, rust/frontend/src/server.rs, rust/sysdb/src/sysdb.rs, rust/types/src/api_types.rs
This PR cherry-picks the commit a4f208b7836e4e781ebd25cb220347bd44dfab92 onto rc/2025-07-11. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #4942 to rc/2025-07-11

docs/docs.trychroma.com/markdoc/content/integrations/chroma-integrations.md, docs/docs.trychroma.com/markdoc/content/integrations/frameworks/voltagent.md
I added Voltagent integration guide to the docs.
=> [DOC] Add VoltAgent integration documentation

rust/storage/src/admissioncontrolleds3.rs, rust/storage/src/s3.rs, rust/tracing/src/init_tracer.rs
This PR cherry-picks the commit c3f7bfd6ea9d6876b1577788ed10742ef29090e3 onto release/2025-07-11. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5086 to release/2025-07-11

rust/wal3/src/manifest.rs
- Add sanity check in the `apply_garbage` method of the log manifest. It checks the manifest contains the first log to keep and inherits the same next log position.
- N/A
=> [ENH] Add sanity check for log manifest gc

rust/garbage_collector/src/operators/delete_unused_files.rs, rust/storage/src/s3.rs
Hotfixes 2 PRs to the last release for better S3 metrics & a larger batch size during GC file deletion.
=> [HOTFIX]: apply PRs #5114 and #5116 to release/2025-07-11

docs/docs.trychroma.com/markdoc/content/docs/overview/introduction.md
- Add new java client to support Chroma 1.0.0+ and API V2.
-  No tests needed
- Add another line for java client in docs
=> [DOC] Add Java Client which support API V2

clients/new-js/packages/chromadb/package.json
Release JS client 3.0.10. Client allowing users to set a `null` EF
=> [RELEASE] JS 3.0.10

README.md, clients/new-js/packages/chromadb/README.md
Updating READMEs to include Chroma Cloud information on Pypi and NPM
=> [ENH] Update READMEs with Chroma Cloud

docs/docs.trychroma.com/markdoc/content/reference/python/client.md
This PR updates python client docs with the correct error message for get and delete collection
fixes https://github.com/chroma-core/chroma/issues/5098
=> [DOC] Update error value in get and delete collection for python

rust/blockstore/src/arrow/provider.rs, rust/storage/Cargo.toml, rust/storage/src/admissioncontrolleds3.rs, rust/storage/src/lib.rs
This PR cherry-picks the commit e3227a39a0fd60791a52844e2da91e4bfad691c1 onto rc/2025-07-25. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5158 to rc/2025-07-25

rust/garbage_collector/src/operators/delete_unused_logs.rs
This reverts commit 33cd7b0c8ed63acaa18a93cbcec6dbe4abd2221b.
CI
N/A
N/A
N/A
=> Revert "[ENH]  Thread collection ID through the GC::Wal3 error."

chromadb/chromadb_rust_bindings.pyi, clients/js/packages/chromadb-core/src/ChromaFetch.ts, clients/js/packages/chromadb-core/src/generated/models.ts, clients/new-js/packages/chromadb/src/api/types.gen.ts, rust/frontend/src/impls/in_memory_frontend.rs, rust/frontend/src/impls/service_based_frontend.rs, rust/frontend/src/server.rs, rust/frontend/tests/proptest_helpers/arbitrary.rs, rust/python_bindings/src/bindings.rs, rust/types/src/api_types.rs
This PR cherry-picks the commit 7f1f1087465ef8fad44e3cae31baa8238e228975 onto release/2025-07-25. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5160 to release/2025-07-25

chromadb/test/distributed/test_repair_collection_log_offset.py
The recent change to the rust log service and compactor added the
ability to repair automatically when the log is behind sysdb.  The test
flaked on landing, so this patch is to make it not flake.
Check that it rolls back the offset and give more time to repair.
Flaked on landing.  Have run ten in a row locally without flake.
CI.
N/A
N/A
N/A
=> [ENH]  Beef up recent test against flakes.

rust/frontend/src/impls/service_based_frontend.rs, rust/metering-macros/tests/tests.rs
This PR cherry-picks the commit 3df61ff460eafc8a4a842ce19134fcbbfb210d0a onto release/2025-08-01. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5195 to release/2025-08-01

docs/docs.trychroma.com/components/posthog/posthog-provider.tsx, docs/docs.trychroma.com/vercel.json
Updates Posthog configuration for docs.trychroma.com
=> [ENH] update posthog configuration on docs

rust/wal3/src/writer.rs
Today I fixed one setsum mismatch.  Another popped on staging.  This PR adds a debug line to dump
the manifest and garbage.
It's a trace, so I checked that things compile.
N/A
Watch staging
N/A
=> [ENH]  Add debug logging so we can figure out what's going on that makes a setsum mismatch.

rust/wal3/src/gc.rs, rust/wal3/src/manifest.rs, rust/wal3/tests/common.rs, rust/wal3/tests/test_k8s_integration_04_initialized_append_until_snapshot.rs, rust/wal3/tests/test_k8s_integration_87_gc.rs, rust/wal3/tests/test_k8s_integration_AB_stringy_setsum_mismatch.rs
This PR cherry-picks the commit fc3b02c905720272d3f0ed8cf2c3db1127768db7 onto release/2025-08-01. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5191 to release/2025-08-01

rust/index/src/spann/types.rs, rust/index/src/spann/utils.rs, rust/worker/tilt_config.yaml
This PR cherry-picks the commit 815c3ac561b207bad30bdf374ad9291e1bf5b0d1 onto release/2025-08-01. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5203 to release/2025-08-01

rust/blockstore/src/arrow/block/types.rs, rust/cache/src/foyer.rs, rust/cache/src/lib.rs
This PR cherry-picks the commit 04aeb2213989878260efd7d53063c7e664c202ca onto release/2025-08-01. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5201 to release/2025-08-01

rust/index/src/spann/types.rs
- Increased from 16 to 24 since CV tests are still failing with 16
- ...
None
Observe CV tests in staging
None
=> [ENH]: Increase nprobe for smaller collections

rust/system/src/execution/dispatcher.rs
Will help us debug when the dispatcher queue is overloaded.
Tested in Tilt by setting dispatcher limits very low and observing that the metric was correctly recorded.
=> [ENH]: add metric for # of aborted tasks in dispatcher

README.md
Reverts chroma-core/chroma#5215
=> Revert "[DOC] Made light/dark mode for Chroma logo"

rust/sysdb/src/sysdb.rs, rust/system/src/execution/operator.rs, rust/worker/src/execution/operators/register.rs
This PR cherry-picks the commit 11559550b52eba579cda6b2dab19a838e626417c onto rc/2025-08-08. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5228 to rc/2025-08-08

rust/blockstore/src/arrow/flusher.rs
=> [ENH]: Reduce peak memory usage of compactor

rust/system/src/execution/dispatcher.rs, rust/system/src/executor.rs
This PR cherry-picks the commit f178c3574f70873c32c13eb89ccc4e9af55818c8 onto release/2025-08-08. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5261 to release/2025-08-08

rust/blockstore/benches/blockfile_writer.rs, rust/blockstore/src/arrow/block/delta/unordered_block_delta.rs, rust/blockstore/src/arrow/blockfile.rs, rust/blockstore/src/arrow/concurrency_test.rs, rust/blockstore/src/arrow/config.rs, rust/blockstore/src/arrow/flusher.rs, rust/blockstore/src/arrow/ordered_blockfile_writer.rs, rust/blockstore/src/arrow/provider.rs, rust/blockstore/src/lib.rs, rust/blockstore/src/provider.rs, rust/blockstore/tests/blockfile_writer_test.rs, rust/garbage_collector/src/operators/compute_unused_between_versions.rs, rust/index/benches/full_text.rs, rust/index/benches/literal.rs, rust/index/src/fulltext/types.rs, rust/index/src/spann/types.rs, rust/segment/src/blockfile_metadata.rs, rust/segment/src/distributed_spann.rs, rust/segment/src/types.rs, rust/worker/benches/spann.rs, rust/worker/src/compactor/compaction_manager.rs, rust/worker/src/execution/operators/filter.rs, rust/worker/tests/config_from_default_path.rs, rust/worker/tests/config_from_specific_path.rs, rust/worker/tilt_config.yaml
This PR cherry-picks the commit 12b313ac7aac75124dfae02d16129be6248e212f onto release/2025-08-08. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5252 to release/2025-08-08

.github/actions/rust/action.yaml, rust/system/src/execution/orchestrator.rs
This PR cherry-picks the commit 4018509329902d39b7f7b59ef5d2047c1af14925 onto release/2025-08-08. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5249 to release/2025-08-08

DEVELOP.md
=> [DOC] Clean up DEVELOP.md

go/pkg/sysdb/metastore/db/dao/collection.go
An earlier [change](https://github.com/chroma-core/chroma/commit/9a54b8bb1ca576afd3367f22a81171c4a4a563ab) attempted to optimize the sysdb query in the case where the primary key for databases was fully specified. This was incomplete as it created a filtered subquery with a LIMIT + OFFSET inside the subquery. This would prevent the filter from being pushed down into the subquery during optimization. This change also sets the GUC `random_page_cost=1.1` for that query to be more in line with practices of SSD-based database instances. We conservatively only touch that GUC for this GetCollections change but we should look into assessing doing this database-wide.
- ...
- ...
Locally benchmarked this on a database …
=> [ENH]: Further optimize query on getCollections when databases pkey is fully specified

rust/garbage_collector/src/config.rs, rust/garbage_collector/src/garbage_collector_component.rs
This PR cherry-picks the commit e8ed50fef0585b6b403aedf6f53fd453bc53e809 onto release/2025-08-08. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5275 to release/2025-08-08

rust/segment/src/blockfile_record.rs, rust/worker/src/execution/orchestration/compact.rs
Somehow I missed this path for soft deletes.
Unfortunately, observability plan.
N/A
See the errors go away or not.
N/A
=> [BUG] CompactionError did not proxy should_trace_error

rust/blockstore/src/arrow/provider.rs, rust/storage/src/admissioncontrolleds3.rs, rust/storage/src/s3.rs
We're blind on S3 uploads/puts.  Change that.
CI
N/A
I watch honeycomb.
N/A
=> [ENH]  Complete the NAC metrics for the write half.

rust/segment/src/blockfile_record.rs, rust/worker/src/execution/orchestration/compact.rs
This PR cherry-picks the commit 896523292e2eadd85e54ef8cb9c4b6181af066f6 onto release/2025-08-08. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5282 to release/2025-08-08

rust/garbage_collector/src/garbage_collector_orchestrator.rs, rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs, rust/garbage_collector/src/operators/delete_versions_at_sysdb.rs
This PR cherry-picks the commit 5224b940981d99af8cc608d7613d56f696bce5a4 onto release/2025-08-15. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5318 to release/2025-08-15

chromadb/api/__init__.py, chromadb/api/async_api.py, chromadb/api/async_client.py, chromadb/api/async_fastapi.py, chromadb/api/client.py, chromadb/api/fastapi.py, chromadb/api/rust.py, chromadb/api/segment.py, chromadb/chromadb_rust_bindings.pyi
Reverts chroma-core/chroma#5310
=> Revert "[ENH] Add update_tenant and get_collection_by_crn to Python client"

k8s/distributed-chroma/Chart.yaml, k8s/distributed-chroma/templates/sysdb-service.yaml
Similar pattern to `k8s/distributed-chroma/templates/sysdb-migration.yaml`. This will allow us to add Argo CD annotations.
=> [ENH]: allow adding annotations to SysDb deployment in Helm chart

rust/frontend/src/auth/mod.rs, rust/frontend/src/server.rs
This PR cherry-picks the commit 23af0968b606026bb4528065892a44c67d70ce0f onto release/2025-08-15. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5305 to release/2025-08-15

Cargo.lock, rust/jemalloc-pprof-server/Cargo.toml
This PR cherry-picks the commit a0bd1f4ea0207fb8e4c844db45324531985096e2 onto rc/2025-08-22. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5340 to rc/2025-08-22

docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/google-gemini.md
Fix typo in Google EF docs page
=> [DOC] Fix Google Gemini EF typo

.github/actions/tilt/action.yaml, .github/workflows/_python-tests.yml
This PR is for fixing the failure of CI with INTERNALERROR.
CI
N/A
N/A
N/A
=> [CHORE]  CI failed with INTERNALERROR

docs/docs.trychroma.com/public/llms-guides-build-building-with-ai.txt
=> Fix typo in user role description

rust/blockstore/src/arrow/blockfile.rs, rust/blockstore/src/arrow/provider.rs, rust/index/src/spann/types.rs, rust/segment/src/blockfile_metadata.rs, rust/segment/src/blockfile_record.rs, rust/segment/src/types.rs, rust/tracing/src/util.rs, rust/worker/src/execution/operators/filter.rs, rust/worker/src/execution/operators/knn_projection.rs, rust/worker/src/execution/operators/limit.rs, rust/worker/src/execution/operators/projection.rs, rust/worker/src/execution/operators/spann_fetch_pl.rs, rust/worker/src/execution/orchestration/spann_knn.rs
Hotfix https://github.com/chroma-core/chroma/pull/5398
Tests pass locally with pytest for python, yarn test for js, cargo test for rust
N/A
Ensure dashboards remain unaffected.
N/A
=> [HOTFIX] Remove spans + add tracing for slow operations

docs/docs.trychroma.com/markdoc/content/cloud/quotas-limits.md
=> [DOC] Update quota limit

go/pkg/log/server/server.go
This PR cherry-picks the commit c290d79d41b20e9e700b4cde9399842caff2fb55 onto rc/2025-09-05. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5422 to rc/2025-09-05

rust/frontend/src/auth/mod.rs, rust/frontend/src/server.rs, rust/metering/src/core.rs
- Update search API auth
- Update meter event type
- N/A
=> [ENH] Update search API auth & meter event type

docs/docs.trychroma.com/markdoc/content/docs/overview/getting-started.md
=> [DOC] - Adds typescript basics video

rust/worker/src/config.rs, rust/worker/src/execution/orchestration/sparse_knn.rs, rust/worker/src/server.rs
This PR cherry-picks the commit 1efb3859a3053ac057941e4292ab47b62e85fb24 onto release/2025-09-12. If there are unresolved conflicts, please resolve them manually.
=> [HOTFIX] applying PR #5483 to release/2025-09-12

rust/frontend/src/traced_json.rs
parse_json was spotted taking in excess of 200ms.  Log the number of bytes parsed in JSON.
Manual inspection.
N/A
si
N/A
=> [ENH]  Log the number of bytes in the parse_json span.

chromadb/__init__.py, chromadb/execution/expression/operator.py
- Fix the type annotation and implementation for `Key.__eq__` override
- Re-export `Rrf` to top level for easier use
- N/A
=> [BUG] Fix equality override for search key

.github/actions/tilt/action.yaml, .github/workflows/_python-tests.yml
Reverts chroma-core/chroma#5535
=> Revert "Revert "[CHORE]  CI failed with INTERNALERROR""

Cargo.lock, Cargo.toml, rust/s3heap/Cargo.toml, rust/s3heap/src/internal.rs, rust/s3heap/src/lib.rs, rust/s3heap/tests/common.rs, rust/s3heap/tests/test_k8s_integration_01_empty_heap.rs, rust/s3heap/tests/test_k8s_integration_02_basic_push.rs, rust/s3heap/tests/test_k8s_integration_03_merge_buckets.rs, rust/s3heap/tests/test_k8s_integration_04_prune_completed.rs, rust/s3heap/tests/test_k8s_integration_05_peek_filtering.rs, rust/s3heap/tests/test_k8s_integration_06_retry_logic.rs, rust/s3heap/tests/test_k8s_integration_07_bucket_computation.rs, rust/s3heap/tests/test_k8s_integration_08_concurrent_operations.rs, rust/s3heap/tests/test_unit_tests.rs
This is the s3heap.  The implementation was done by hand, but then had tests and docs written for it with Claude.
CI
N/A
I'll add metrics in a follow-up PR.
N/A
=> [ENH]  s3heap:  A way to schedule tasks via S3-backed queues.

rust/index/src/hnsw_provider.rs, rust/storage/src/admissioncontrolleds3.rs, rust/storage/src/lib.rs
- Ensures that we only take the partitioned mutex to create hnsw files if we are not in `use_direct_hnsw` mode. This allows us to perf test the gains from directly loading hnsw from memory.
- Ensures that we also don't write to disk in `HnswIndexProvider::create` if `use_direct_hnsw` is enabled.
- N/A
_Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the_ [_docs section](https://github.com/chroma-core/chroma/tree/main/docs/docs.trychroma.com)?_
=> [ENH]: Gate hnsw file creation mutex under use_direct_hnsw flag

rust/index/src/hnsw_provider.rs
- The callback given to `fetch_batch` needs to be attached to its parent. This change fixes that.
- ...
_Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the_ [_docs section](https://github.com/chroma-core/chroma/tree/main/docs/docs.trychroma.com)?_
=> [ENH]: Attach fetch_batch callback to its parent

clients/new-js/packages/chromadb/src/collection.ts, clients/new-js/packages/chromadb/src/execution/expression/common.ts, clients/new-js/packages/chromadb/src/execution/expression/index.ts, clients/new-js/packages/chromadb/src/execution/expression/key.ts, clients/new-js/packages/chromadb/src/execution/expression/limit.ts, clients/new-js/packages/chromadb/src/execution/expression/rank.ts, clients/new-js/packages/chromadb/src/execution/expression/search.ts, clients/new-js/packages/chromadb/src/execution/expression/searchResult.ts, clients/new-js/packages/chromadb/src/execution/expression/select.ts, clients/new-js/packages/chromadb/src/execution/expression/where.ts, clients/new-js/packages/chromadb/src/execution/index.ts, clients/new-js/packages/chromadb/src/index.ts, clients/new-js/packages/chromadb/test/search.expression.test.ts
This PR adds support for search expressions and the search api via the javascript client, following 1:1 with the python search expression implementation
- ...
- ...
=> [ENH] Add search API DSL to JS
