rust/worker/src/tracing/opentelemetry_config.rs

Reverts chroma-core/chroma#3317. Spans under compaction job traces are now orphaned.

[CHORE] REVERT:  Make everything except chroma `INFO`.  Make chroma `DEBUG`."

---

Cargo.lock
rust/load/Cargo.toml

The chromadb-rs client called to the server to hit sysdb for each time a
collection is instantiated.  Add a collection cache.

[ENH] Bump chroma-load to version that caches get_collection

---

rust/index/bindings.cpp
rust/index/src/hnsw.rs

- N/A
- We would like to verify HNSW index integrity on load. An additional call to `checkIntegrity()` method is added to the `load()` method in the binding.
This should not break any existing test cases
N/A

[ENH] Validate HNSW index integrity on load

---

.github/actions/export-tilt-logs/action.yaml
.github/actions/tilt/action.yaml
.github/workflows/_go-tests.yml
.github/workflows/_python-tests.yml
.github/workflows/_rust-tests.yml
.github/workflows/nightly-tests.yml
bin/get-logs.sh

Exports traces from Jaeger and saves to CI artifact so that people can inspect traces produced during a CI test run.
Downloaded an artifact and imported traces for a service into Jaeger.
n/a

[BLD]: save OTEL traces in artifact during CI

---

chromadb/segment/impl/manager/cache/cache.py
chromadb/test/cache/test_cache.py

Closes #3334
- Fixes the lack of thread-safety of Basic and LRU segment caches by adding RLocks.
- Add tests to verify the thread-safety
- Implement simple state-machine property test to verify the LRU cache implementation

[BUG]: Add Segment Caches thread-safety

---

chromadb/utils/embedding_functions/open_clip_embedding_function.py

Currently, attempting to use OpenCLIP embeddings on a metal performance shader (MPS) device results in the following error:
```
RuntimeError: slow_conv2d_forward_mps: input(device='cpu') and weight(device=mps:0')  must be on the same device in add.
```
These changes fix this error by explicitly moving input tensors to the model device in `OpenCLIPEmbeddingFunction` embedding methods. This provides a significant speedup (~2x on my M1 MacBook Pro) compared to running on CPU.
It's quite difficult to perform CI testing on real macOS machines, so these changes don't include any tests for MPS devices specifically. However, these changes have been tested successfully on an M1 device, both with `device="cpu"` (the default) and `device="mps"`.
No user-facing APIs are updated. Now `device="mps"` …

[ENH] ✨ Support MPS accelerated OpenCLIP embeddings

---

chromadb/api/models/Collection.py
chromadb/test/client/test_database_tenant_auth.py
chromadb/test/property/test_embeddings.py

Bug found by a user. Before this fix, the resource object passed to auth providers would always have the default tenant and default database for calls made via the chromadb Python HTTP client.
Added test was failing before I updated `Collection.py`.
n/a

[BUG]: `upsert()` always uses default tenant/database

---

rust/worker/src/compactor/compaction_manager.rs
rust/worker/src/execution/operators/materialize_logs.rs
rust/worker/src/execution/operators/mod.rs
rust/worker/src/execution/operators/write_segments.rs
rust/worker/src/execution/orchestration/compact.rs

Log materialization is now in its own operator. Having materialization in its own operator unlocks two main benefits:
- allows us to pipeline log applications across segment types (currently unrealized)
- we can easily bail for any partition with an empty set of materialized records before constructing writers
Tested locally with SciDocs as well.

[ENH]: move materialization into operator

---

Cargo.lock
rust/load/Cargo.toml
rust/load/src/lib.rs

It won't report 429's to stderr, and logs just once per error.

[ENH]  Clean up the errors reported by chroma-load.

---

rust/worker/src/execution/operators/limit.rs
rust/worker/src/execution/orchestration/compact.rs
rust/worker/src/segment/record_segment.rs
rust/worker/src/segment/types.rs

Small cleanup to clarify usage of offset ID on reader.
n/a

[CLN]: remove offset ID atomic from record segment reader

---

docs/docs.trychroma.com/context/app-context.tsx

Closes #3395
- The app context responsible of redirecting pages to either the JS docs or python docs was stripping out the hash (anchor) if you're navigating to a documentation page with an anchor such as [https://docs.trychroma.com/reference/python/client#deletecollection](https://docs.trychroma.com/reference/python/client#deletecollection).
- This PR fixes this issue by appending the hash to the URL being redirected to if it's valid to append the hash.
- Also cleaning up a bit by removing a not used import of react `useContext`.
N/A
N/A

[DOC]: Fix anchors in links to docs.trychroma.com

---

rust/index/bindings.cpp
rust/index/src/hnsw.rs

We were seeing errors in compaction that looked like:
```
WriteSegments(ApplyMaterializatedLogsError(HnswIndex(FFIException(\"The number of elements exceeds the specified limit\"))))
```
This is because the resize logic uses `len` which removes deleted elements which then causes the conditional for resizing to be skipped. This adds a new method `len_with_deleted` to return the length of the index including the elements that have been deleted so that the resize is not skipped. See: https://github.com/chroma-core/chroma/blob/27564afa0e82d184a0fa853a7384d00861d8e9dc/rust/worker/src/segment/distributed_hnsw_segment.rs#L212-L222
A test was added. It will fail when using the existing `len` method, but passes when using the newly added `len_with_deleted` method.
N/A
Thanks to @sanketkedia for …

[BUG] Fix HNSW resize conditions to exclude deleted items

---

.gitignore
go/Makefile
go/README.md

These are all improvements to the local development environment, specifically for our Golang code. 
We recently removed generated protobuf files from the repository (see #3222). This resulted in needing to build these for my IDE to be happy. I eventually fixed what was a painful experience getting all this set up, so I added some details about getting it set up in the `README.md` and tweaked one thing in the `Makefile` for consistency with the other dependencies.
Note: there is some noise in the `README.md` diff that is from my linter.
We also weren't ignoring generated files, so I added them to `.gitignore` so they don't get re-added accidentally. 
Run `make build`

[BLD] Update Golang README and Makefile for generating protobuf dependencies

---

.github/workflows/apply-hotfix.yaml

When applying a hotfix, a PR gets generated. This PR is currently only in the output of the action, or can be found in the list of PRs. This adds a heading and a link to the PR in the action summary so that the developer can find it more easily.
I manually linted the action code to make sure I didn't break anything obvious. I may still want to tweak the output that gets generated, but at this point, the PR link will be much more easy to spot.

[BLD] Add link to hotfix PR in action summary

---

rust/worker/src/segment/distributed_hnsw_segment.rs

This is a follow-up from #3424 - where I had added code to fix the bug in compaction but then forgot to replace the method at the actual callsite with the new method 🤦🏼 . 
This updates the problem code to use `len_with_deleted` instead of just `len` so that the resize actually gets triggered. 
Some additional context: we decided not to change the behavior of the existing `len` method in case other callers were depending on existing behavior. In other words, we didn't want to introduce accidentally introduce bugs that were relying on the "buggy" code.

[BUG] Use len_with_deleted instead of len

---

chromadb/cli/cli.py
chromadb/db/impl/sqlite.py

Change a single warning to correctly state the version where vacuum was introduced.
No test needed this is only a string in a warning that is not tested.
Docstring updated, no change needed in other docs.

[Bug]: fix(vacuum): correctly state that vacuum was released in 0.5.6 not 0.6 (fixes #2956)

---

chromadb/execution/executor/distributed.py
chromadb/segment/distributed/__init__.py
chromadb/segment/impl/distributed/segment_directory.py
chromadb/segment/impl/manager/distributed.py
chromadb/test/distributed/test_reroute.py
chromadb/test/segment/distributed/test_memberlist_provider.py
go/pkg/memberlist_manager/memberlist_manager.go
go/pkg/memberlist_manager/memberlist_manager_test.go
go/pkg/memberlist_manager/memberlist_store.go
go/pkg/memberlist_manager/node_watcher.go
k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/crds/memberlist_crd.yaml

- The memberlist uses k8s dns based routing for the stateful set. However, this can result in delays when the routing updates. This propagates the ip in the memberlist which is much faster.
- This change is backwards compatible
- CRDs fields are optional by default, so not setting the ip is fine if CRD is updated
- CRD fields can be set in the code without the CRD being updated
- The python frontend will use the ip if present, otherwise it falls back to the id
- The go code will read the ip to "" anywhere it expects it to be set if the old version of the CR is used
- ...
Added a test which adds data to a collection, kills the query service pods and waits for them to be …

[BUG] Make memberlist use ips for routing

---

chromadb/errors.py
chromadb/test/api/test_collection.py

`UniqueConstraintError` was not included as the possible `ChromaError` types causing it to appear as a generic error.
Closes #2569 
N/A

[BUG] `UniqueConstraintError` not included as a `ChromaError`

---

clients/js/src/utils.ts

Allows the utility `toArrayOfArrays` to support other input iterables that can be returned from embedding functions, as well as handle empty edge case.
Closes #2724 
N/A

[BUG] Support all iterables in toArrayOfArrays

---

chromadb/server/fastapi/__init__.py

PR https://github.com/chroma-core/chroma/pull/3310 broke the OpenAPI spec by generating a snippet for a request body that included:
```json
"include": {
"default": [
"metadatas",
"documents",
"distances"
],
"items": {
"$ref": "#/$defs/IncludeEnum"
},
"title": "Include",
"type": "array"
}
```
This `$ref` is invalid because the corresponding `$def` was placed as a sibling to this fragment, rather than at the top level of the document (`$ref`s are always absolute). A thread where others ran into the same issue: https://community.sanicframework.org/t/problem-with-generated-openapi-schema-via-pydantic/1223
The `genapi` JS script now runs successfully.
*Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the …

[BUG]: fix bad OpenAPI generation

---

.github/workflows/nightly-tests.yml

We often see failures in this workflow that look like:
```
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
I linted the action, but will need to test it live to see that artifacts are getting generated appropriately. Expect that many of the failure conditions we are currently seeing go away.

[BLD] Make artifact names unique for the job being run

---

go/cmd/coordinator/cmd.go
go/pkg/grpcutils/config.go
go/pkg/grpcutils/service.go

By default, most grpc implementations allow up to 100 concurrent
streams.  We have 200 concurrent requests, basically guaranteeing
queueing.  Expose the two gRPC options in Go that will allow us to tune.

[ENH]  Add flags to the go binary for concurrency and stream processing.

---

rust/blockstore/src/arrow/ordered_blockfile_writer.rs
rust/garbage_collector/src/config.rs
rust/worker/src/execution/operators/limit.rs
rust/worker/src/segment/types.rs

[CHORE]  Update to Rust 1.84.

---

go/Dockerfile

Significantly decreases incremental build time of Go images. See https://github.com/chroma-core/hosted-chroma/issues/981 for context.
Container builds.
n/a

[ENH]: fix Go Dockerfile build time regression

---

idl/chromadb/proto/coordinator.proto

Proto definitions and GRPC defs for supporting Versioned Collections.
Part of GC work.
- ...
- Adds protobufs for Versioned Collections.
n/a

[ENH] Proto defs for collection version file. #950

---

rust/worker/chroma_config.yaml
rust/worker/src/compactor/compaction_manager.rs
rust/worker/src/compactor/config.rs
rust/worker/src/compactor/scheduler.rs
rust/worker/src/config.rs

- Can specify a list of collection ids that needs to disabled and compactor will respect that.
- In runtime, can set the env `CHROMA_COMPACTION_SERVICE__COMPACTOR__DISABLED_COLLECTIONS=[list of collection ids]` or  `CHROMA_COMPACTION_SERVICE.COMPACTOR.DISABLED_COLLECTIONS=[list of collection ids]` and the changes will take effect without restarting the pod
None

[ENH] Config to disable compactor on collections

---

rust/index/bindings.cpp
rust/index/src/hnsw.rs

- If you load an empty hnsw index, the index capacity is set to 0. Fixes this
None

[BUG] Fix hnsw malloc of 0 bytes

---

chromadb/api/__init__.py
chromadb/api/async_api.py
chromadb/api/async_client.py
chromadb/api/async_fastapi.py
chromadb/api/client.py
chromadb/api/fastapi.py
chromadb/api/segment.py
chromadb/auth/__init__.py
chromadb/db/impl/grpc/client.py
chromadb/db/mixins/sysdb.py
chromadb/db/system.py
chromadb/server/fastapi/__init__.py
chromadb/test/api/test_delete_database.py
clients/js/src/AdminClient.ts
clients/js/src/generated/api.ts
clients/js/src/generated/models.ts
clients/js/test/admin.test.ts
docs/docs.trychroma.com/markdoc/content/reference/python/client.md

Adds a method to delete a database.
Yes.

[ENH]: add method to delete database (single-node)

---

chromadb/db/impl/grpc/client.py
chromadb/test/api/test_delete_database.py
go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/model/database.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/grpc/tenant_database_service.go
go/pkg/sysdb/grpc/tenant_database_service_test.go
go/pkg/sysdb/metastore/db/dao/database.go
go/pkg/sysdb/metastore/db/dbmodel/database.go
idl/chromadb/proto/coordinator.proto

Adds implementation for database deletion API to distributed Chroma.
Added a new Go test. Mostly tested with existing Python tests.
n/a

[ENH] add distributed implementation for database deletion

---

DEVELOP.md
clients/python/README.md
docs/docs.trychroma.com/markdoc/content/docs/guides/multimodal-guide.md

[DOC] Fix typos

---

chromadb/config.py
docs/docs.trychroma.com/markdoc/content/production/administration/migration.md

- ...
- ...
Ref: https://discord.com/channels/1073293645303795742/1074711446589542552/1327201360319479818

[DOC]: Fix discord invite links

---

chromadb/server/fastapi/__init__.py

The auth methods were both sync, which led to latency on the async
thread pool.  Fix that.

[BUG]  Make auth requests in async context async.

---

chromadb/api/segment.py
chromadb/config.py
chromadb/rate_limit/__init__.py
chromadb/rate_limit/simple_rate_limit/__init__.py
chromadb/server/fastapi/__init__.py

This adds a rate limiter at the level of the fast api async code.  The
reason for doing this is that by the time stuff gets to the pool,
there's a queue.  We want to try and make the rate limiter async so that
we can avoid said queue.

[ENH]  Add a simple rate limiter for async.

---

chromadb/execution/executor/distributed.py

Auth is no longer a bottleneck.  This PR fixes two problems:
- Max concurrent streams is 100 by default and we need it to be higher.
- I'm unfamiliar with Python threading, but I don't think a dictionary
add is atomic in that putting into a dictionary is a release and
reading from a dictionary an acquire.  Add a mutex for safety.

[ENH]  Improve the grpc used to contact knn.

---

chromadb/test/property/test_filtering.py
rust/worker/src/execution/operators/limit.rs

This has been materializing as a flaky test, but is an actual correctness bug. Reproduced in a Python test and tracked down to this operator.
Added test was previously failing.
n/a

[BUG]: fix binary search impl of `LimitOperator`

---

go/cmd/coordinator/cmd.go
go/pkg/sysdb/metastore/db/dbcore/core.go

- Adds `ReadAddress` to `DBConfig` for `SysDB` Go coordinator
- None

[ENH] Update DBConfig to take read address

---

chromadb/quota/__init__.py
chromadb/quota/simple_quota_enforcer/__init__.py

- Updates `QuotaEnforcer.enforce` abstract class to receive a `collection_id` UUID

[ENH] Add collection_id param to QuotaEnforcer enforce func

---

clients/python/pyproject.toml

Ref: https://discord.com/channels/1073293645303795742/1329146423786213521/1329156629781942413
- Turns out we've forgot to remove the numpy pinning in python client
N/A

[BUG]: Removing numpy pinning from python client

---

go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/coordinator_test.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/coordinator/table_catalog_test.go
go/pkg/sysdb/grpc/cleaup_test.go
go/pkg/sysdb/grpc/collection_service.go
go/pkg/sysdb/grpc/collection_service_test.go
go/pkg/sysdb/grpc/server.go
go/pkg/sysdb/grpc/tenant_database_service_test.go
go/pkg/sysdb/metastore/db/dao/collection.go
go/pkg/sysdb/metastore/db/dao/collection_test.go
go/pkg/sysdb/metastore/db/dao/common.go
go/pkg/sysdb/metastore/db/dao/segment_test.go
go/pkg/sysdb/metastore/db/dao/tenant_test.go
go/pkg/sysdb/metastore/db/dao/test_utils.go
go/pkg/sysdb/metastore/db/dbcore/core.go
go/pkg/sysdb/metastore/db/dbmodel/collection.go
go/pkg/sysdb/metastore/db/dbmodel/mocks/ICollectionDb.go
idl/chromadb/proto/coordinator.proto

- None
- Hooks up `SysDB` Go coordinator to a DB read replica
- Adds a new RPC, `GetCollectionSize`, to return the total records in a collection, pulling from the reader DB

[ENH] GetCollectionSize on SysDB read replica

---

chromadb/db/impl/grpc/client.py
chromadb/db/impl/grpc/server.py
chromadb/db/mixins/sysdb.py
chromadb/db/system.py
chromadb/test/db/test_system.py

- None
- Exposes `get_collection_size()` on `SysDB`

[ENH] Update Python SysDB to support get_collection_size

---

docs/docs.trychroma.com/markdoc/content/docs/overview/getting-started.md

This pull request addresses an issue in the Getting Started documentation, where the incorrect yarn install command was provided for installing packages. The correct command, `yarn add <package-name>`
**Issue:**

[DOC] Fix install command in Getting Started doc: Replace 'yarn/pnpm install' with 'yarn/pnpm add'

---

chromadb/test/ef/test_ollama_ef.py
chromadb/utils/embedding_functions/ollama_embedding_function.py
docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/ollama.md

Closes #3473
- Ollama EF now uses the official ollama python client
- Improved tests
- Updated docs
- The EF now uses Chroma's default EF (all-minilm-l6-v2) as a default
Python integration example updated

[ENH]: Switching to official Ollama python client

---

Cargo.lock
go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/model/collection.go
go/pkg/sysdb/coordinator/model_db_convert.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/grpc/collection_service.go
go/pkg/sysdb/metastore/db/dao/collection.go
go/pkg/sysdb/metastore/db/dbmodel/collection.go
go/pkg/sysdb/metastore/db/dbmodel/mocks/ICollectionDb.go
go/pkg/sysdb/metastore/db/dbmodel/mocks/IDatabaseDb.go
idl/chromadb/proto/coordinator.proto
rust/garbage_collector/src/garbage_collector_component.rs
rust/sysdb/Cargo.toml
rust/sysdb/src/sysdb.rs

- Adds an rpc on Go side that is dumb and gets all collections
- Adds this rpc to the rust sysdb client + uses this rpc from rust client in gc
None

[ENH] Implement Get collections to GC + add to rust sysdb client

---

idl/chromadb/proto/compactor.proto
rust/types/build.rs
rust/worker/src/compactor/compaction_manager.rs
rust/worker/src/compactor/compaction_server.rs
rust/worker/src/compactor/mod.rs
rust/worker/src/compactor/types.rs
rust/worker/src/lib.rs
rust/worker/src/utils/convert.rs

- N/A
- We would like to manually start a compaction on certain collections. This PR is the first in the stack to implement this feature. Specifically, it:
- Introduces the grpc interface for compactor. Currently there is only a single variant of request that allows the user to specify an optional list of collection ids for compaction.
- Implements the `CompactionServer` struct in rust that implements this interface. It receives the request and send it to the running `CompactionManager`
- The next PRs will handle the request in `CompactionManager`.
*Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the [docs …

[ENH] Implement compactor server interface

---

rust/worker/src/compactor/compaction_manager.rs
rust/worker/src/compactor/scheduler.rs
rust/worker/src/compactor/types.rs

- N/A
- Following [the previous PR](https://github.com/chroma-core/chroma/pull/3375), this PR implements the logic to handle one-off compaction message in the compaction manager. It adds the collection ids to the scheduler, which will whitelist the collections for the next compaction run only.

[ENH] Handle one-off compaction message in compaction manager

---

Cargo.lock
rust/worker/Cargo.toml
rust/worker/src/bin/compaction_client.rs
rust/worker/src/compactor/compaction_client.rs
rust/worker/src/compactor/compaction_server.rs
rust/worker/src/compactor/mod.rs
rust/worker/src/lib.rs

- N/A
- Implements the compaction client, which is a CLI tool that can be used to remotely control a compaction service.
- For now it only allows for triggering an one-off compaction on selected collections (or all of available collections)

[ENH] Implement compaction client

---

k8s/test/otel-collector.yaml

Before (note generic "component received message" and "task execution" spans):
After:
Looks correct in Jaeger.
n/a

[ENH]: fix dynamic span names in Jaeger

---

chromadb/api/segment.py

- None
- Update calls to `quota_enforcer.enforce` to include `collection_id` for `ADD` and `UPSERT`

[ENH] Add collection_id to quota_enforcer calls

---

docs/docs.trychroma.com/markdoc/content/production/containers/docker.md

- Moving to `git clone https://...` instead of the current `git clone git@...`, the latter requires users to have a GH account with SSH key added
N/A

[DOC] Making git clone command more accessible in Docker container instructions

---

clients/js/src/embeddings/OllamaEmbeddingFunction.ts
clients/js/test/add.collections.test.ts
clients/js/test/embeddings/ollama.test.ts
clients/js/test/embeddings/startOllamaContainer.ts
clients/js/test/testEnvSetup.ts
docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/ollama.md

- Switching to ollama js client - https://www.npmjs.com/package/ollama
- Default model is all-mini
- Default URL is ollam's localhost url and port
- Using test containers to test the EF
- Conditional tests when ollama package is installed
- Moved tests to test/embeddings/ollama.test.ts
Updated integration example (simplified)

[ENH]: Switching Ollama JS EF to ollama js client

---

chromadb/test/property/test_embeddings.py

- Adds test coverage for deleting all records, waiting for a compaction and then continuing to add records, delete them and add them back. This previously broke our hnsw resizing logic. This was fixed in https://github.com/chroma-core/chroma/pull/3479
- None
None

[TST] Add test coverage for compaction that deletes everything

---

Cargo.lock
Cargo.toml
Tiltfile
k8s/distributed-chroma/templates/rust-frontend-service.yaml
k8s/distributed-chroma/values.yaml
rust/frontend/Cargo.toml
rust/frontend/Dockerfile
rust/frontend/src/bin/frontend_service.rs
rust/frontend/src/lib.rs
rust/frontend/src/server.rs
rust/load/Cargo.toml

- /
- Adds a rust-based frontend stub
- Adds the frontend to the k8s tiltfile
Confirmed I can tilt up and curl the service at `:3000`
None required.

[ENH] Add rust frontend stub

---

rust/system/src/execution/dispatcher.rs

When a task is dispatched and there's no available worker thread the task is put into a queue. We weren't holding the current span at time of task creation in the queue, leading to mysteriously missing span trees. This was especially apparent under high concurrent load or when the configuration specified a low number of worker threads.
Verified that formerly missing spans now show up in Jaeger, especially when `num_worker_threads` is 1.
n/a

[BUG]: keep track of current span if task must be queued

---

chromadb/server/fastapi/__init__.py

Closes #3521
- Fixes and issue where v1 and v2 operations were overlapping so when executed from Swagger UI v2 operations were hitting v1 api

[BUG]: FastAPI operations id are now unique

---

rust/system/src/execution/dispatcher.rs

It was lifo.  It is now fifo thanks to VecDeque

[ENH]  LIFO->FIFO for the dispatcher.

---

Cargo.lock
rust/frontend/Cargo.toml
rust/frontend/src/errors.rs
rust/frontend/src/lib.rs
rust/frontend/src/server.rs

Route handlers can now use `?` on methods that return `Result<_, E> where E: ChromaError`.
Tested by calling a route that threw.
n/a

[ENH]: better error handlilng for Axum routes

---

Cargo.lock
rust/cache/src/foyer.rs
rust/frontend/Cargo.toml
rust/frontend/frontend_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/frontend.rs

- ...
- FE has in-memory foyer cache
None

[ENH] Add cache for FE with no invalidation

---

rust/log/src/grpc_log.rs
rust/log/src/log.rs
rust/log/src/types.rs
rust/types/src/record.rs

Does what it says on the tin.
n/a

[ENH]: add `push_logs()` to log interface

---

Cargo.lock
rust/frontend/Cargo.toml
rust/frontend/Dockerfile
rust/frontend/frontend_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/frontend.rs
rust/frontend/src/server.rs
rust/types/src/api_types.rs
rust/types/src/metadata.rs

Adds write path to Rust frontend.
Tested with a small script that added records and then queried them.
n/a

[ENH]: add `/add` route to Rust frontend

---

Cargo.lock
rust/cache/src/foyer.rs
rust/cache/src/lib.rs
rust/cache/src/nop.rs
rust/cache/src/unbounded.rs
rust/config/src/assignment/assignment_policy.rs
rust/config/src/assignment/config.rs
rust/config/src/assignment/rendezvous_hash.rs
rust/frontend/Cargo.toml
rust/frontend/frontend_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/executor/client_manager.rs
rust/frontend/src/executor/config.rs
rust/frontend/src/executor/distributed.rs
rust/frontend/src/executor/mod.rs
rust/frontend/src/frontend.rs
rust/frontend/src/lib.rs
rust/log/src/config.rs
rust/memberlist/src/config.rs
rust/memberlist/src/memberlist_provider.rs
rust/sysdb/src/config.rs
rust/types/Cargo.toml
rust/types/src/api_types.rs
rust/worker/src/compactor/scheduler.rs
rust/worker/src/lib.rs

- Add clone to a bunch of config structs since we need it
- Adds a ClientManager to respond to the memberlist changes and update nodes
- Introduces config for the executor num_connections, and timeouts
- Performs top-k HWRH for assignment to query nodes and randomly load balances between them
- Add assign many behavior into assignment policy
Not well. Will add in future PR. Manually verified the connection pooling to query nodes
None

[ENH] Plumb ML into fe

---

chromadb/server/fastapi/__init__.py

Closes #3498
- Fixes a recursion in `auth_and_get_tenant_and_database_for_request` to correctly call `sync_auth_and_get_tenant_and_database_for_request` in `run_sync` context
N/A

[BUG] Fix recursion in auth_and_get_tenant_and_database_for_request

---

rust/config/src/assignment/config.rs
rust/frontend/frontend_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/executor/config.rs
rust/frontend/src/frontend.rs
rust/frontend/src/lib.rs
rust/frontend/src/server.rs
rust/log/src/config.rs
rust/mdac/src/scorecard.rs
rust/memberlist/src/config.rs
rust/sysdb/src/config.rs

By default we limit to 100 of each op per collection, but we could do
something more.

[ENH]  Wire up config to scorecard with default rules

---

rust/frontend/src/types/where_parsing.rs

Adds some basic tests for where document and where clause parsing.
n/a

[TST]: add basic tests for where parsing

---

rust/cache/src/async_partitioned_mutex.rs
rust/frontend/frontend_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/frontend.rs
rust/frontend/src/get_collection_with_segments_provider.rs
rust/frontend/src/lib.rs

- Uses partitioned mutex to avoid thundering herd on the sysdb
- ...
None

[ENH] Dedup get_collections_with_segments sysdb rpc

---

rust/frontend/src/frontend.rs
rust/frontend/src/server.rs
rust/sysdb/src/sysdb.rs
rust/types/src/api_types.rs

- N/A
- More routes for Rust FE

[ENH] More routes in rust FE

---

rust/frontend/src/frontend.rs
rust/frontend/src/server.rs
rust/types/src/api_types.rs
rust/types/src/operation.rs
rust/types/src/record.rs

Adds support for collection updates & upserts to Rust frontend.
Tested locally with a simple script.
n/a

[ENH]: add /upsert & /update to Rust frontend

---

rust/frontend/frontend_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/executor/client_manager.rs
rust/frontend/src/executor/distributed.rs

- Turning off FE cache until we have cache invalidation
-  Memberlist access is synchronized by a r/w lock instead of a mutex
- ...
None

[ENH] Nop cache for FE + Rwlock for memberlist

---

rust/frontend/src/frontend.rs
rust/frontend/src/server.rs
rust/types/src/api_types.rs

Adds support for deleting collection records to the Rust frontend.
Tested locally with a simple script.
n/a

[ENH]: add /delete to Rust frontend

---

.github/workflows/_rust-tests.yml

I've noticed that the tests will build everything and then recompile many things with nexttest
(presumably rustc config).  This seems unnecessary.  Running the tests should be enough.

[BUG]  Building and running tests builds twice.

---

rust/frontend/frontend_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/frontend.rs
rust/frontend/src/server.rs
rust/sysdb/src/sysdb.rs
rust/types/src/api_types.rs

[ENH]: hook up /reset for Rust frontend

---

.github/workflows/_python-tests.yml
.github/workflows/pr.yml
bin/cluster-test.sh
chromadb/api/async_fastapi.py
chromadb/api/fastapi.py
chromadb/test/conftest.py
rust/frontend/src/frontend.rs
rust/frontend/src/server.rs
rust/types/src/api_types.rs

Runs the Rust frontend tests when a PR is tagged with `rust-frontend`.
n/a

[TST]: run tests against Rust frontend

---

rust/frontend/src/frontend.rs

- The dimension is write-once. So we can cache it with abandon.
- None
None
None

[PERF] Use dimension cache in rust front

---

Cargo.lock
rust/load/Cargo.toml
rust/load/src/lib.rs

The client no longer bounds the number of outstanding requests.  Up to a higher-level primitive to do so.

[ENH] Bump chroma-load dep on client to avoid connection pooling and be open loop

---

rust/frontend/src/frontend.rs
rust/frontend/src/get_collection_with_segments_provider.rs

- Invalidates the frontend cache whenever the collection is updated. This could happen when dimension is set, when collection is updated by user, when collection is deleted by user.
- ...
None

[ENH] Invalidate collection cache appropriately

---

.github/actions/tilt/action.yaml
rust/frontend/src/frontend.rs
rust/frontend/src/server.rs
rust/types/src/api_types.rs
rust/types/src/execution/plan.rs

Fixes the Rust frontend so that `chromadb/test/distributed/test_sanity.py` passes.
n/a

[TST]: Rust frontend fixes for test_sanity

---

.github/workflows/_python-tests.yml
chromadb/proto/.gitignore
rust/frontend/src/frontend.rs

Previously, records were reversed before being pushed to the log.
`test_logservice.py` now passes.
n/a

[TST]: fix Rust frontend for test_logservice.py

---

rust/frontend/src/server.rs
rust/frontend/src/types/errors.rs

- Serialize the Rust error to match Python client errors
- N/A

[BUG] Match Rust FE error types with python client

---

k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/rust-frontend-service.yaml
rust/frontend/src/executor/client_manager.rs
rust/frontend/src/executor/distributed.rs
rust/frontend/src/executor/mod.rs
rust/frontend/src/frontend.rs
rust/frontend/src/server.rs
rust/types/src/api_types.rs

The memberlist (used by the query executor) may not be available immediately upon startup.
Tilt displays the container in green even when the probe is failing, but the docs imply that `tilt ci` will properly wait for k8s probe checks:
n/a

[ENH]: add ready probe to Rust frontend

---

rust/system/src/execution/operator.rs
rust/worker/src/execution/operators/prefetch_record.rs
rust/worker/src/execution/operators/prefetch_segment.rs

Prefetch operators are "fire and forget"; we don't care if the sender is no longer available to receive the result of the prefetch.
Tested by adding a sleep to a prefetch operator and observing that the logged event was at the debug level, not error level.
n/a

[ENH]: suppress prefetch errors when the sender no longer exists

---

clients/js/src/index.ts

Closes #3661
Closes #3551
- Turns out that in CJS projects, the use of `export type` erases runtime info, which causes failure in user projects when importing our types
N/A

[BUG] Using `export` instead of `export type` for CommonJS compat

---

.github/workflows/_python-tests.yml
.github/workflows/pr.yml

Rust frontend tests are now green, so we can enable them to run against all PRs without being gated by a label.

[BLD]: always run Rust frontend tests

---

Cargo.lock
Cargo.toml
rust/types/Cargo.toml
rust/types/src/lib.rs
rust/types/src/metadata.rs
rust/types/src/strategies.rs

Adds an Arbitrary impl for OperationRecord and UpdateMetadata. Used in the next PR upstack.
Spent a lot of time testing shrinking to ensure failures shrink fast.

[TST]: add proptest Arbitrary impl for OperationRecord and UpdateMetadata

---

rust/load/src/bit_difference.rs
rust/load/src/data_sets.rs
rust/load/src/lib.rs

A reference workload uses two collections.  It references one to get doc
ids and it writes/reads the other with queries, gets, and upserts.
This may sound strange, but it's because we need a canonical way of
knowing what data we're writing and can query so that we can verify
ground truth.
Options considered:
- Load the hugging face data sets to a volume.  Operationally tricky.
- Load the hugging face data sets to a different DB.  Operationally
tricky.
- Use a reference chroma collection (this).

[ENH]  Allow reference work loads.

---

rust/log/src/test.rs
rust/segment/Cargo.toml
rust/segment/src/blockfile_record.rs
rust/segment/src/sqlite_metadata.rs
rust/segment/src/test.rs
rust/types/src/collection.rs
rust/worker/benches/filter.rs
rust/worker/benches/get.rs
rust/worker/benches/limit.rs
rust/worker/benches/load.rs
rust/worker/benches/query.rs
rust/worker/src/execution/operators/filter.rs
rust/worker/src/execution/operators/knn_log.rs
rust/worker/src/execution/operators/knn_projection.rs
rust/worker/src/execution/operators/limit.rs
rust/worker/src/execution/operators/projection.rs
rust/worker/src/server.rs

- Proptest count endpoint
- Implement a reference segment that can be used in prop tests

[ENH] Implement reference segment

---

Cargo.lock
rust/log/src/local_compaction_manager.rs
rust/segment/src/sqlite_metadata.rs
rust/sqlite/Cargo.toml
rust/sqlite/src/helpers.rs
rust/sqlite/src/lib.rs
rust/sqlite/src/table.rs

Extracts metadata update logic into shared helpers in `chroma-sqlite` crate so that the logic can be shared with the sysdb.

[ENH]: put metadata update logic in shared helpers

---

Cargo.lock
rust/load/src/data_sets.rs

I envision a new engineer coming into the company tasked with
benchmarkign some aspect of the system.  They create a workload
description for it and commit that code.  Then they come to the code
this PR touches and add an entry for their collection that references
one of the three reference collections.

[ENH]  Add support to chroma-load for custom data sets.

---

rust/segment/src/sqlite_metadata.rs
rust/segment/src/test.rs
rust/types/src/execution/operator.rs
rust/types/src/strategies.rs

- Implement the logic to generate a vector of records for a collection
- Fixed a bug in sqlite metadata impl that leads to wrong result order
- N/A

[TST] Proptest for get and count

---

rust/frontend/src/executor/local.rs
rust/log/src/local_compaction_manager.rs
rust/log/src/sqlite_log.rs
rust/python_bindings/src/bindings.rs
rust/segment/src/local_hnsw.rs
rust/segment/src/local_segment_manager.rs
rust/segment/src/sqlite_metadata.rs
rust/sqlite/src/db.rs
rust/types/src/api_types.rs

- Adds the backfill logic in get() and query() path
- executor keeps an in-memory hash map of backfill status for optimization
- if need to backfill it sends a request to compaction manager to backfill
- compaction manager backfills by fetching logs and max seq ids for both the segments
- ...
None

[ENH] Backfill segments from log

---

rust/load/src/bit_difference.rs
rust/load/src/lib.rs

To construct a Zipf requires N pow operations.  For cardinality 1e6,
this is where chroma-load spends its time now and it's limiting
throughput.  Rather than refactor every type to have a a serde type and
a hydrated type, I did this.

[ENH][HACK]  Add a cache for zipf distributions to chroma load.

---

rust/load/src/bit_difference.rs
rust/load/src/lib.rs

To construct a Zipf requires N pow operations.  For cardinality 1e6,
this is where chroma-load spends its time now and it's limiting
throughput.  Rather than refactor every type to have a a serde type and
a hydrated type, I did this.

[ENH][HACK]  Add a cache for zipf distributions to chroma load. (#3721)

---

chromadb/api/rust.py
chromadb/api/segment.py
chromadb/db/mixins/sysdb.py
chromadb/errors.py
chromadb/test/api/test_delete_database.py
chromadb/test/test_api.py
rust/python_bindings/rust_bindings.pyi
rust/python_bindings/src/bindings.rs
rust/sysdb/src/sqlite.rs
rust/types/src/api_types.rs

Plumbs through database and tenant methods to Rust SQLite Python bindings. Removes the `InvalidCollectionException` Python exception and replaces with `NotFound` since we can't map to it from a Rust error code.

[ENH]: hook up database and tenant methods to Rust bindings

---

rust/log/src/local_compaction_manager.rs
rust/log/src/log.rs
rust/log/src/sqlite_log.rs

- On push logs, log service sends an async msg to compactor to purge logs
- compactor queries the max seq id of the segments
- It then sends a purge request to the log with the min of the two seq ids
- ...
None

[ENH] Log gc

---

k8s/distributed-chroma/values.yaml
rust/frontend/frontend_config.yaml
rust/log/src/local_compaction_manager.rs
rust/python_bindings/src/bindings.rs
rust/segment/src/sqlite_metadata.rs

- Numerical where filter should check both int and float value
- ...

[BUG] Check both int and float value for numerical filter

---

clients/js/test/add.collections.test.ts
clients/js/test/delete.collection.test.ts
clients/js/test/get.collection.test.ts
clients/js/test/peek.collection.test.ts
clients/js/test/query.collection.test.ts
clients/js/test/update.collection.test.ts
clients/js/test/upsert.collections.test.ts

- The new Rust FE replaces the InvalidCollectionError with the more generic ChromaNotFound error. The JS tests need to be updated for this.
- ...

[BUG] Fix JS tests

---

Cargo.lock
Cargo.toml
rust/benchmark/src/datasets/types.rs

Tantivy 0.21.1 transitively depends on zstd 2.0.10, which has symbol
errors on OS X at least.  Bump the dep so we can build hosted chroma.

[CHORE]  Update tantivy so hosted-chroma doesn't have conflicting zstd versions.

---

chromadb/api/segment.py
chromadb/segment/__init__.py
chromadb/segment/impl/manager/local.py
chromadb/test/property/invariants.py
chromadb/test/property/test_collections.py

Closes #3296
The delete collection logic slightly changes to accomodate the fix without breaking the transactional integrity of `self._sysdb.delete_collection`. The `chromadb.segment.SegmentManager.delete_segments` had to change to accept the list of segments to delete instead of `collection_id`.
- Fixes the resource leak when deleting a collection
N/A

[BUG]: Delete collection resource leak (single-node Chroma)

---

Cargo.lock
Cargo.toml
rust/cli/Cargo.toml
rust/cli/src/main.rs

[ENH] Adding initial Rust CLI

---

docs/docs.trychroma.com/markdoc/content/docs/overview/introduction.md

@schochastics and I have written a ChromaDB client for R that covers all endpoints in the API.
- It can be downloaded from GitHub: https://github.com/cynkra/rchroma 
- It has a documentation website as well (linked in the PR): https://cynkra.github.io/rchroma/
We will bring it to CRAN in the next few days.
- Adds a new line to the table in the documentation
- No tests needed
- This is a pure documentation change

[DOC] Add client for R to the documentation

---

chromadb/db/base.py
chromadb/db/mixins/embeddings_queue.py
chromadb/migrations/metadb/00005-max-seq-id-int.sqlite.sql
chromadb/segment/impl/metadata/sqlite.py
chromadb/segment/impl/vector/local_persistent_hnsw.py

This migration was added to the Rust local implementation, but not the Python local implementation.

[ENH]: add seq ID migration to Python

---

rust/frontend/src/auth/mod.rs

In a fit of not-thinking I wrote `+ Sync` next to the `+ Send`.  This is not correct for futures.

[BUG]  Don't add + Sync to futures.  Bad habit.

---

.github/workflows/release-cli.yml
rust/cli/install/install.ps1
rust/cli/install/install.sh

* Adding a GHA to make a CLI release and install scripts for it (unix and power shell).
* Chose /usr/local/bin and ~/.local/bin as these are often included in the PATH by default.
* Currently GHA is dispatch-able for testing purposes.
* Will test GHA for release and install scripts on Mac and Windows.
TBA

[ENH] Add GHA for CLI release and install scripts

---

go/pkg/log/configuration/config.go
go/shared/libs/db_utils.go

This enables us to configure the connection pool size for every go
service.  It reads the MAX_CONNS environment variable and applies that
if and only if it parses as an integer.  I opted to fall back to a
reasonable default rather than error.

[ENH]  Plumb MAX_CONNS in from the environment for go pgxpool.

---

.github/actions/rust/action.yaml
.github/workflows/_rust-tests.yml
rust/blockstore/src/arrow/block/delta/ordered_block_delta.rs
rust/blockstore/src/arrow/ordered_blockfile_writer.rs
rust/index/src/fulltext/types.rs

Adds invariant assertions for the ordered blockfile writer that are checked in debug mode.
Since `#[cfg(debug_assertions)]` can break release builds when improperly used, I added a CI check for `cargo build --release`.

[TST]: add invaariant assertions for ordered blockfile writing

---

docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/cohere.md
docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/voyageai.md

Documentation for some embedding function integrations refer to `texts` which throws an error. should refer to them as `input`

[DOC] update embedding function doc referencing texts -> input

---

rust/frontend/src/frontend.rs
rust/frontend/src/server.rs
rust/frontend/src/types/errors.rs
rust/python_bindings/src/bindings.rs
rust/types/src/api_types.rs

Centralizes logic for validating embedding dimension and updating collection dimension size. Needed when calling frontend methods directly.

[ENH]: push down `validate_embeddings()` into Frontend

---

docs/docs.trychroma.com/markdoc/content/production/administration/auth.md

fix inconsistent variable names for the Python HttpClient example on the Auth docs page
- Edited typo in documentation that had a variable name for the Chroma Python HttpClient first named `client` but when calling the `heartbeat()` method on it, was called as `chroma_client`.
I changed the initially named `client` to `chroma_client` for full consistency/functionality if tested by a user.
[Auth page to change](https://docs.trychroma.com/production/administration/auth)

[DOC] fix inconsistent variable names for the Python HttpClient

---

Cargo.lock
rust/cache/Cargo.toml
rust/cache/src/foyer.rs
rust/worker/chroma_config.yaml

- Foyer internally uses AHash for hashing, which the default constructor of randomizes itself internally so each new process has essentially different hash function. https://github.com/tkaitchuck/aHash/issues/132
This provides an option to pin the keys AHash uses. 
- /
Added a test that validates persistence by creating a new cache is able to read the old key. Without the config, this is expected to fail. 
I also debugged into foyer and confirmed we are hitting disk

[ENH] Make rust cache hash deterministic by default

---

chromadb/api/rust.py

- Add product telemetry client to `RustBindingsAPI`
- ...

[ENH] Use legacy posthog impl for rust client

---

go/cmd/coordinator/cmd.go
rust/garbage_collector/src/garbage_collector_orchestrator.rs

- https://github.com/chroma-core/chroma/pull/3749 turns version files on which breaks all users of CreateCollectionWithSegment
- This manifests as 
```
chromadb.errors.InternalError: Tonic error: status: Internal, message: "RequestError: send request failed\ncaused by: Put \"http://minio:9000/chroma-storage/***/collections/29b88c30-7764-4e9e-ad0f-f63f0a12d5fc/versionfiles/0\": dial tcp: lookup minio on 172.20.0.10:53: no such host", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }
```
Being thrown on sysdbs in non tilt enviornments.
- NOTE - I intentionally did not opt to turn off this setting in users because this feature is NOT production ready and SHOULD NOT be on by default. 
- New …

[ENH] Go version file config should not be enabled

---

rust/cli/install/install.ps1
rust/cli/install/install.sh

The CLI install script would fail if "which chroma" returns something, not allowing for proxy CLI in our python package.

[BUG] Remove auto fail from CLI install script

---

bin/rust_single_node_integration_test_config.yaml
rust/cli/src/main.rs
rust/config/src/lib.rs
rust/frontend/frontend_config.yaml
rust/frontend/single_node_frontend_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/frontend.rs
rust/frontend/src/lib.rs
rust/frontend/src/server.rs
rust/python_bindings/src/bindings.rs
rust/sqlite/src/config.rs

Adds a new Rust server config and moves relevant fields from the main frontend config into it.
There is one breaking change: OTEL parameters have been moved under a top-level `open_telemetry` field. Config files/env var overrides will have to be updated.
n/a

[ENH]: add config for Rust HTTP server

---

bin/rust_single_node_integration_test_config.yaml
rust/frontend/single_node_frontend_config.yaml
rust/frontend/src/lib.rs
rust/frontend/src/server.rs
rust/worker/src/execution/operators/knn_merge.rs
rust/worker/src/execution/operators/spann_knn_merge.rs
rust/worker/src/execution/orchestration/knn.rs
rust/worker/src/execution/orchestration/knn_filter.rs
rust/worker/src/execution/orchestration/spann_knn.rs

- We expected the knn merge operators to be infallible, but the task (as a wrapper of the operator) could still fail. This PR gracefully handle the task error.
- Misc cleanups
- Refactor the signature of frontend `run` method
- Update single node configs to persist hnsw by default and use in-memory mode in test
- N/A

[BUG] Gracefully handle merge operator task error

---

rust/frontend/single_node_frontend_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/lib.rs

- N/A
- Add the `persist_path` optional field in rust frontend server config. If provided it will fill the sqlite path and hnsw root folder for single node, unless explicitly overridden in corresponding configs.

[ENH] Unify persist path config

---

rust/load/src/lib.rs

In the full text search code, we use guacamole and rely upon the zipf
distribution to be within range.  This must be broken in guacamole and I
want to hack around it rather than debug statistics.

[BUG]  chroma-load has an oob access

---

.github/workflows/_python-tests.yml
Tiltfile
bin/rust-integration-test.sh
bin/rust_single_node_integration_test_config.yaml
k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/rust-frontend-service.yaml
rust/blockstore/src/config.rs
rust/config/src/assignment/config.rs
rust/frontend/frontend_config.yaml
rust/frontend/single_node_frontend_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/executor/config.rs
rust/frontend/src/get_collection_with_segments_provider.rs
rust/frontend/src/lib.rs
rust/log/src/config.rs
rust/memberlist/src/config.rs
rust/segment/src/local_segment_manager.rs
rust/sqlite/src/config.rs
rust/storage/src/config.rs
rust/sysdb/src/config.rs
rust/worker/chroma_config.yaml
rust/worker/tests/config_from_default_path.rs
rust/worker/tests/config_from_specific_path.rs
rust/worker/tests/config_missing_default_field.rs
rust/worker/tests/config_with_env_override.rs
rust/worker/tests/config_without_cache_directive.rs

- Adds default impls for most config fields necessary for single node.
- Changes config enums to use snake case for consistent field casing.
- Adds debug impls on config structs.
These changes are mainly in service of making it easier for users to understand and write config.
**Breaking change**: some config fields are now snake case.
n/a

[ENH]: consistent config field casing, add default and debug impls

---

docs/docs.trychroma.com/components/ui/tabs.tsx

The docs app would not build with `npm run dev` until I made this change.

[BUG]: fix docs build issue

---

rust/blockstore/src/config.rs
rust/config/src/assignment/config.rs
rust/frontend/src/executor/config.rs
rust/log/src/config.rs
rust/memberlist/src/config.rs
rust/storage/src/config.rs
rust/sysdb/src/config.rs

Config fields that were renamed in https://github.com/chroma-core/chroma/pull/3838 are now aliased instead so that either casing can be provided. After merge, I'll create a task to switch back to `rename_all = "snake_case"` in a few weeks.

[ENH]: make config field renames backwards compatible

---

rust/cli/Dockerfile

Noticed that SIGTERM was not correctly handled (results in commands like `docker stop` taking at least 10s before the engine sends a `SIGKILL`).
Verified that `docker stop` now immediately stops the container.

[ENH]: fix container signal handling & use Debian in published image

---

rust/frontend/src/frontend.rs

- Log only on retries and not on first attempt
- ...
None

[ENH] Remove retry log line in RFE

---

.github/actions/tilt/action.yaml
.github/workflows/_python-tests.yml

I accidentally changed the port in https://github.com/chroma-core/chroma/pull/3838. Port 3000 is the Rust frontend, port 8000 is the Python frontend.

[TST]: Rust cluster tests were using wrong port

---

bin/rust_python_compat_test.py
chromadb/test/property/test_cross_version_persist.py

- N/A
- Test rust client backward compatibility with python clients across legacy versions

[TST] Test rust client backward compatibility

---

Cargo.lock
Cargo.toml
chromadb/api/rust.py
rust/frontend/sample_configs/single_node.yaml
rust/frontend/src/config.rs
rust/python_bindings/src/bindings.rs
rust/segment/Cargo.toml
rust/segment/src/local_hnsw.rs

- Uses rayon to write in batches to hnsw, mirror'ing python
- misc cleanup
- disable otel in config for logspam, we should eventually turn it on
- ...
Existing tests and manually
None

[ENH] Add in parallel to local hsnw

---

pyproject.toml
requirements.txt

https://github.com/encode/starlette/pull/2812 (transitively updated to in fastapi 0.115.10) caused large portions of our test suite to fail. We're pinning fastapi (and thus starlette) for now to the last working version since we're deprecating the Python server anyways.
n/a

[BUG]: pin fastapi version

---

rust/frontend/src/frontend.rs
rust/log/src/log.rs
rust/log/src/sqlite_log.rs

Consumes the embeddings queue config (used to determine whether log purging should be enabled) on the Rust side.
Covered by `chromadb/test/db/test_log_purge.py`.

[ENH]: consume and populate the embeddings_queue_config from Rust log impl

---

rust/segment/src/local_hnsw.rs

`serde_pickle` makes many, many small write calls with our usage. Putting a buffered writer in front of syscalls improves throughput by ~20%.
n/a

[PERF]: improve insert throughput by ~20% via BufWriter

---

chromadb/telemetry/opentelemetry/grpc.py
rust/sysdb/src/sysdb.rs
rust/tracing/src/grpc_tower.rs

- Modify the python grpc otel layer to match the rust side
- Intercept the grpc response status code in the grpc tower layer

[ENH] Intercept GRPC status code

---

clients/js/package.json
clients/js/src/embeddings/DefaultEmbeddingFunction.ts

`v2.14.0` of `chromadb-default-embed` now includes a `dist/` folder.

[ENH] In JS frontends, fall back to hosted chroma package instead of third-party package

---

clients/js/src/embeddings/CohereEmbeddingFunction.ts
clients/js/src/embeddings/DefaultEmbeddingFunction.ts
clients/js/src/embeddings/GoogleGeminiEmbeddingFunction.ts
clients/js/src/embeddings/HuggingFaceEmbeddingServerFunction.ts
clients/js/src/embeddings/IEmbeddingFunction.ts
clients/js/src/embeddings/JinaEmbeddingFunction.ts
clients/js/src/embeddings/OllamaEmbeddingFunction.ts
clients/js/src/embeddings/OpenAIEmbeddingFunction.ts
clients/js/src/embeddings/TransformersEmbeddingFunction.ts
clients/js/src/embeddings/VoyageAIEmbeddingFunction.ts
clients/js/src/embeddings/all.ts
clients/js/src/embeddings/registry.ts
clients/js/src/index.ts
clients/js/test/add.collections.test.ts

Updates JS EFs to conform to similar interface as Python. Remaining tasks to do in follow-up PRs:
- add config validation using JSON schemas
- add tests, ideally covering config cross-language
n/a

[ENH]: update JS EFs to conform to new interface

---

Cargo.lock
rust/frontend/src/frontend.rs
rust/frontend/src/lib.rs
rust/storage/src/lib.rs
rust/storage/src/local.rs
rust/tracing/Cargo.toml
rust/tracing/src/meter_event.rs

- Changed the meter event field names so that the represented value can be easily aggregated
- Replaced global event sender channel with custom receiver that implements `ReceiverForMessage<MeterEvent>`. This allows us to spawn a component in the system and set a global receiver for the meter event message, and additional logic to listen on the receiver is hidden from the meter module.
- N/A

[ENH] Replace global event sender channel with `ReceiverForMessage<MeterEvent>`

---

rust/cli/src/main.rs
rust/frontend/src/bin/frontend_service.rs
rust/frontend/src/lib.rs

- This allows passing the system and registry into the FE endpoint
- None
It is untested explicitly in this change, a proxying non functional change.
None

[ENH] Allow passing system and registry into FE entrypoint

---

k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/rust-frontend-service.yaml
rust/cli/Dockerfile
rust/frontend/src/executor/mod.rs
rust/frontend/src/lib.rs
rust/frontend/src/server.rs
rust/system/src/executor.rs
rust/system/src/types.rs

- Update rust frontend k8s template
- Adds a `graceful_shutdown` method for `Component` trait
- Handles `SIGTERM` in frontend axum server

[ENH] Implement graceful shutdown for component and axum server

---

k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/rust-frontend-service.yaml

In the helm chart for the rust frontend's environment config, it was inheriting the environment config from the python config which is not what we want. We should explicitly set these values separately for each service.

[CHORE] Remove frontend env config from rust frontend env config

---

rust/blockstore/src/arrow/provider.rs
rust/garbage_collector/src/operators/delete_unused_files.rs
rust/garbage_collector/src/operators/fetch_version_file.rs
rust/storage/Cargo.toml
rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/lib.rs
rust/storage/src/local.rs
rust/storage/src/object_store.rs
rust/storage/src/s3.rs

This makes the put_bytes call take a PutOptions so that atomic
operations like put-if-not-exist and put-if-match can be supported.

[ENH]  Make PutOptions part of the storage API.

---

Tiltfile
k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/namespace.yaml
k8s/distributed-chroma/templates/rust-frontend-service.yaml
k8s/distributed-chroma/values.dev.yaml
k8s/distributed-chroma/values.yaml
k8s/test/namespace.yaml
rust/cli/Dockerfile
rust/frontend/sample_configs/distributed.yaml

- The Dockerfile in rust/cli was incorrectly overwritten to use distributed config. This dockerfile should be for single node config only
- I moved our helm to a local command so that we can call `set-file` this also mirrors what we do in hosted chroma
- Removed the test namespace, as its duplicated with the one in the main chart
- Turned off reset by default, and used values.dev to override it
- Consolidate postgres into the same section of other test components in tiltfile for cleanliness
- Use configmap for rust-frontend-service config, mirror'ing what we do in other envs
- None
Manually tested tilt
*Are all docstrings for user-facing APIs updated if required? Do we …

[BUG] Fixes for dockerfile, tilt, config management

---

rust/frontend/src/quota/mod.rs

- Appends the quota overrage error struct in the error string
- ...
None

[ENH] Add quota overrage details in the error string

---

rust/frontend/src/config.rs
rust/frontend/src/executor/local.rs
rust/types/src/api_types.rs

Found this bug while working on https://github.com/chroma-core/chroma/pull/3814.
Added test was previously failing.
n/a

[BUG]: empty list of IDs on query should return nothing

---

.github/workflows/_python-tests.yml
rust/cli/Cargo.toml

The python test runners are configured with the Ubuntu 20 image, which is being deprecated on GHA.
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
N/A

[ENH] Update test runner to ubunto-latest and rename cli crate

---

.github/workflows/_python-tests.yml

Completing https://github.com/chroma-core/chroma/pull/3938
N/A

[ENH] Update runners for all python tests

---

rust/index/src/spann/types.rs

- Adds tests that writes and then scans to verify that all the data is present
- Different flavors of tests like inserting concurrently, writing->persisting->loading->writing_again and so on
- Fixes code issues surfaced by them
- ...
None

[ENH] SPANN: Add rust integrity tests

---

Tiltfile
k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/rust-log-service.yaml
k8s/distributed-chroma/values.yaml
rust/log/Cargo.toml
rust/log/Dockerfile
rust/log/src/bin/log.rs
rust/log/src/lib.rs
rust/log/src/server.rs

- /
- Adds a basic grpc stub for the log service
- Added a feature for the server because the signals are unix only and not needed by rust-bindings
None

[ENH] Rust Log Service Stub

---

chromadb/api/rust.py
chromadb/chromadb_rust_bindings.pyi
rust/types/src/api_types.rs

Rust bindings were not returning the actual `Tenant` class that downstream consumers expected.
n/a

[BUG]: return correct tenant class in Python from Rust bindings

---

rust/frontend/sample_configs/distributed.yaml
rust/frontend/src/config.rs
rust/frontend/src/frontend.rs
rust/frontend/src/server.rs
rust/frontend/src/types/errors.rs
rust/index/src/spann/types.rs
rust/index/src/spann/utils.rs
rust/segment/src/distributed_spann.rs
rust/segment/src/types.rs
rust/types/src/api_types.rs
rust/types/src/hnsw_parameters.rs
rust/worker/benches/spann.rs
rust/worker/src/execution/operators/spann_centers_search.rs
rust/worker/src/execution/orchestration/compact.rs
rust/worker/src/execution/orchestration/knn_filter.rs
rust/worker/src/execution/orchestration/mod.rs
rust/worker/src/execution/orchestration/spann_knn.rs
rust/worker/src/server.rs

- Plumbs config in the collection and segment metadata that identifies spann segment
- Uses this information to appropriately construct readers/writers wherever needed
- Note that it only does so for the rust frontend
- Fixes other issues in the write and read path
- Note: this feature is only available on Rust Frontend currently
- ...
None

[ENH] Spann works e2e on local tilt

---

.github/workflows/_python-tests.yml

This should speed up workflows while also being cheaper. 
Primary motivation: `test_add.py` against the Rust bindings tends to error with "disk is full" on longer runs (e.x. https://github.com/chroma-core/chroma/actions/runs/13791893549/job/38580005218). The disk size for GitHub's runner is 14GB, while Depot's is 100GB.

[TST]: use Depot runners in Python/Rust tests

---

rust/blockstore/src/arrow/provider.rs
rust/garbage_collector/src/operators/fetch_version_file.rs
rust/index/src/hnsw_provider.rs
rust/segment/src/test.rs
rust/storage/Cargo.toml
rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/lib.rs
rust/storage/src/local.rs
rust/storage/src/object_store.rs
rust/storage/src/s3.rs
rust/storage/src/stream.rs

This PR shreds the Storage crate's error handling to mimick
object_store.  The motivation for doing this was very specific:
Multiple levels of error enums (that change based upon the backend) made
robustly handling if-match conflicts tedious and error-prone.

[ENH]  Have one error type for Storage.

---

chromadb/test/utils/test_embedding_function_schemas.py

right now, the ef schema test pulls from hugging face for the minilm model for schema tests. instead, it should mock this functionality.

[BUG] fix test to mock sentence transformer to stop pull from huggingface

---

Cargo.lock
rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/lib.rs
rust/storage/src/local.rs
rust/storage/src/object_store.rs
rust/storage/src/s3.rs

This enables a storage pattern wherein a file upload returns exactly the
e_tag of the file as calculated by AWS.

[ENH] Return the ETag for a successful PUT.

---

rust/wal3/src/lib.rs
rust/wal3/src/manifest.rs
rust/wal3/src/writer.rs

This gives us a count of total number of bytes ingested through the log.

[ENH]  Add the number of bytes written to the log to the manifest.

---

Cargo.lock
rust/wal3/src/batch_manager.rs
rust/wal3/src/lib.rs
rust/wal3/src/writer.rs

The initial cut only had a single-append call.  This was not fundamental
and an oversight.  Fix the single-append call and make sure that
batching doesn't split atomic batches by adding a test that does just
that.

[ENH]  Support batching for wal3.

---

Cargo.lock
rust/wal3/src/batch_manager.rs
rust/wal3/src/lib.rs
rust/wal3/src/manifest.rs
rust/wal3/src/manifest_manager.rs
rust/wal3/src/writer.rs

The timestamp_us field was supposed to be helpful, but it leads to
ambiguity when providing offsets to scan.  Chiefly, what should be the
behavior when a LogPosition with a timestamp different from the one
assigned to that offset is used for scan.  This does away with the
ambiguity and reverts to just logging the timestamp of insertion, which
can drift and therefore won't be monotonic.

[ENH] Remove timestamp_us from wal3 LogPosition.

---

chromadb/types.py

Currently, the Python client throws an error if an unknown field is present in the HTTP response for a collection. This prevents us from adding new fields.
n/a

[ENH]: don't throw error in Python client for unknown field in collection response

---

chromadb/api/async_fastapi.py
chromadb/api/fastapi.py
clients/js/package.json
clients/js/packages/chromadb-core/src/ChromaClient.ts

Official Chroma clients now include their version in a request header, user-agent. JS currently sends `Chroma Javascript Client v2.0.1 (https://github.com/chroma-core/chroma)` and Python currently sends `Chroma Python Client v1.0.0 (https://github.com/chroma-core/chroma)`.
Validated by logging received headers.
n/a

[ENH]: add user-agent header to clients

---

Cargo.lock
rust/cache/Cargo.toml
rust/cache/src/foyer.rs

- Upgrades foyer to 0.14.1
- This newer version does not write to disk on insert, added that ability at our layer
-  Fixed a config issue where buffer_pool_size was being set to < max_entry_size * flushers. Ideally it should be >=. See https://github.com/foyer-rs/foyer/discussions/751
- Fixed another config issue where tracing options were configured only for cache.get() and not for other operations
- ...
An existing test `test_foyer_hybrid_cache_can_recover` implicitly tests the scenario.
None

[ENH] Upgrade Foyer + Foyer config fix

---

chromadb/execution/executor/distributed.py
rust/frontend/src/executor/client_manager.rs
rust/frontend/src/executor/config.rs
rust/frontend/src/executor/distributed.rs

Will prevent frontends from erroring on large responses. I added config parameter for the Rust frontend and hardcoded the limit to 32MB for the Python frontend since we're removing it soon.
Tested by creating 1k documents of 10kB and calling `.get(limit=1000)`. This threw an error on main and worked on this branch. I can check in this test if desired, but it's not super straightforward to do in a clean way since we don't have a good pattern for E2E Rust tests yet.
n/a

[ENH]: bump the max response payload size limit for query service clients

---

Cargo.lock
Cargo.toml
go/cmd/logservice/main.go
go/pkg/sysdb/grpc/server.go
k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/compaction-service.yaml
k8s/distributed-chroma/templates/logservice.yaml
k8s/distributed-chroma/templates/query-service.yaml
k8s/distributed-chroma/templates/rust-log-service.yaml
k8s/distributed-chroma/templates/sysdb-service.yaml
rust/log/Cargo.toml
rust/log/src/server.rs
rust/worker/Cargo.toml
rust/worker/src/compactor/compaction_manager.rs
rust/worker/src/compactor/compaction_server.rs
rust/worker/src/compactor/scheduler.rs
rust/worker/src/server.rs

Adds a readiness probe to all services.
Confirmed that the probe result showed up in `kubectl` and that all services in Tilt were green.
n/a

[ENH]: add readiness probes to all services

---

.github/workflows/_rust-tests.yml
rust/cache/src/lib.rs
rust/index/src/spann/types.rs
rust/index/src/spann/utils.rs
rust/types/src/hnsw_parameters.rs
rust/worker/src/execution/operators/spann_centers_search.rs
rust/worker/src/execution/operators/spann_knn_merge.rs

- Removes duplicates during merge
- Removes pruning when searching centers in hnsw
- ...
Added operator test for merge
None

[ENH] Spann: remove duplicates + not prune in query

---

rust/index/src/config.rs
rust/index/src/spann/types.rs
rust/segment/src/distributed_spann.rs
rust/segment/src/lib.rs
rust/segment/src/spann_provider.rs
rust/segment/src/types.rs
rust/worker/benches/spann.rs
rust/worker/chroma_config.yaml
rust/worker/src/compactor/compaction_manager.rs
rust/worker/src/config.rs
rust/worker/src/execution/operators/spann_centers_search.rs
rust/worker/src/execution/operators/spann_fetch_pl.rs
rust/worker/src/execution/orchestration/compact.rs
rust/worker/src/execution/orchestration/spann_knn.rs
rust/worker/src/server.rs
rust/worker/tests/config_from_default_path.rs
rust/worker/tests/config_from_specific_path.rs
rust/worker/tests/config_missing_default_field.rs

- Introduces spann provider similar to blockfile_provider and hnsw_provider
- Introduces config for Garbage collection for spann
- Plumbs config all the way to the writer. For readers it is none
- Implement random sample x% of data and GC policy
- ...
None

[ENH] Spann: config for GC policy + introduce spann provider + implement GC policy

---

Cargo.lock
Cargo.toml
rust/error/Cargo.toml
rust/error/src/lib.rs
rust/frontend/Cargo.toml
rust/frontend/src/lib.rs
rust/frontend/src/server.rs
rust/frontend/src/server_middleware.rs
rust/frontend/src/types/errors.rs

By default, axum returns some built-in errors (like invalid JSON) as a plaintext response. This adds middleware so that these errors are converted to JSON and don't break clients.
Added a test that fails on main.
n/a

[ENH]: better axum errors

---

chromadb/api/types.py
chromadb/utils/embedding_functions/cohere_embedding_function.py
chromadb/utils/embedding_functions/google_embedding_function.py
chromadb/utils/embedding_functions/huggingface_embedding_function.py
chromadb/utils/embedding_functions/instructor_embedding_function.py
chromadb/utils/embedding_functions/jina_embedding_function.py
chromadb/utils/embedding_functions/ollama_embedding_function.py
chromadb/utils/embedding_functions/onnx_mini_lm_l6_v2.py
chromadb/utils/embedding_functions/open_clip_embedding_function.py
chromadb/utils/embedding_functions/openai_embedding_function.py
chromadb/utils/embedding_functions/roboflow_embedding_function.py
chromadb/utils/embedding_functions/sentence_transformer_embedding_function.py
chromadb/utils/embedding_functions/text2vec_embedding_function.py
chromadb/utils/embedding_functions/voyageai_embedding_function.py
clients/js/packages/chromadb-core/src/embeddings/CohereEmbeddingFunction.ts
clients/js/packages/chromadb-core/src/embeddings/IEmbeddingFunction.ts

rename inner_product to IP and remove error raise on legacy embedding functions, instead returning NotImplemented to stop erroring out.

[CHORE] rename inner_product to IP & remove error raise on legacy embedding functions 

---

k8s/distributed-chroma/values.dev.yaml

Allows us to see the full backtrace of panics.
Manually added a panic to the compactor and observed that a full stack trace was printed.
n/a

[TST]: enable Rust backtraces in Tilt services

---

rust/load/chroma_load_config.yaml
rust/load/src/bit_difference.rs
rust/load/src/lib.rs

- Change the default listening port to 3001 to not conflict with RFE.
- Fix a bug in bit-difference where it would generate zero-sized clusters.
- Fix a bug in bit-difference where duplicate IDs would be generated.
- Change the default database to "default_database" for zero-auth connections.
- Set associativity to 1.0 for random_upsert.

[ENH] chroma-load potpourri

---

rust/cache/src/foyer.rs

Our usage of foyer (manually inserting to disk and memory cache at the same time) seems to uncover bugs in foyer, so we're going to instead follow the happy path of foyer and only insert to the in-memory cache for now (and deal with worse cache perf across rollouts).
Made a new issue tracking the bug: https://github.com/chroma-core/chroma/issues/4040.
n/a

[BUG] don't write to disk cache

---

.github/workflows/pr.yml

The normal preset no longer take significantly longer than our fast preset and tests twice the number of examples.
n/a

[TST]: enable "normal" property testing preset in PRs

---

docs/docs.trychroma.com/markdoc/content/production/containers/docker.md

Update the Docker run command to use the correct image repository (`chromadb/chroma`).   The previous image (`chroma-core/chroma`) may be outdated or incorrect.   This ensures users pull the proper image for the server.

Fix Docker image name in server startup command

---

rust/frontend/src/frontend.rs
rust/index/src/spann/types.rs
rust/segment/src/distributed_spann.rs
rust/types/src/hnsw_parameters.rs
rust/worker/benches/spann.rs
rust/worker/src/execution/orchestration/knn_filter.rs

Rename for consistency with https://github.com/chroma-core/chroma/pull/3961. Taken out of https://github.com/chroma-core/chroma/pull/3961 to slightly decrease diff.
n/a

[ENH]: rename DistributedSpannParameters -> SpannConfiguration

---

chromadb/test/conftest.py
chromadb/test/ef/test_openai_ef.py
chromadb/test/utils/test_embedding_function_schemas.py

there have been consistent issues with embedding function tests. the root cause was the test fixture used, which attempted to install and uninstall dependencies required for the tests, and at any point if some installation did not succeed, it only pushed a log out, before continuing the tests. therefore tests were guaranteed to fail on any issue with the installation. this is also slow to have to install & uninstall packages every time the test runs. 
This pr removes the test fixtures and simplifies the mocks used for the embedding functions

[TST] remove conftest installs and simplify ef tests

---

rust/types/Cargo.toml
rust/types/src/collection.rs
rust/worker/src/compactor/compaction_manager.rs
rust/worker/src/compactor/scheduler.rs
rust/worker/src/execution/operators/register.rs

Adds a default impl for Collection. Makes it much easier to construct `Collection`s in tests, helps document exactly what fields any given test cares about, and prevents us from needing to update every manual `Collection` construction when we add a new field.

[ENH]: add Default impl for Collection type

---

Cargo.lock
rust/frontend/Cargo.toml
rust/frontend/src/tower_tracing.rs

- We were setting the wrong traceid that gets printed by client on encountering error.
- ...
None

[BUG]: Correctly set trace id for debugging using honeycomb

---

rust/sqlite/src/config.rs

Increases the busy timeout of SQLite connections via Rust to the same value we used previously for Python. This should fix flakes of `chromadb/test/client/test_multiple_clients_concurrency.py`.

[ENH]: increase SQLite busy timeout

---

rust/index/src/spann/types.rs
rust/types/src/spann_configuration.rs

- Removes them since for tuning I am exploring some of these values. Will set to more sensible ones later
- ...
None

[ENH]: Remove spann min param validations

---

rust/blockstore/src/arrow/blockfile.rs
rust/blockstore/src/types/reader.rs
rust/segment/src/blockfile_record.rs

These changes were originally part of https://github.com/chroma-core/chroma/pull/3370 but decided to break them out as they're no longer needed for that PR.
Makes the interface slightly more flexible and puts the burden of owned data on the caller.
n/a

[ENH]: improve interface for `load_blocks_for_keys()`

---

docs/docs.trychroma.com/markdoc/content/production/containers/docker.md

- changed `chroma-core` to `chromadb` image name
- ...

[DOC] fixed image name typo

---

.config/nextest.toml
.github/workflows/_python-tests.yml
.github/workflows/_rust-tests.yml
.github/workflows/pr.yml
.github/workflows/release-chromadb.yml

Allows us to track flaky tests and easily see which tests are slow. Tests on Windows are not currently reported because of a bug with Datadog's setup action (filed an issue).

[BLD]: report test results to Datadog

---

Cargo.lock
k8s/distributed-chroma/values.yaml
rust/cache/Cargo.toml
rust/cache/src/foyer.rs
rust/tracing/Cargo.toml

Upgrades foyer to use the new write-to-disk-at-insert-time policy. Also fixes the host path bindings for the cache volumes so that separate foyer instances do not write to the same directory.
Test asserting that cache could be recovered from disk was previously failing and is now passing.
n/a

[ENH]: write to Foyer disk cache at insert time, fix host path binding for cache volumes in CI

---

.github/actions/rust/action.yaml
rust-toolchain.toml

The prior Rust setup action frequently flaked on Windows for unknown reasons.
This also improves DX by adding a `rust-toolchain.toml`, which ensures everyone's dev environments remain in sync (`cargo` commands will error if current version does not match).

[BLD]: add `rust-toolchain.toml`, call rustup directly in CI

---

Cargo.lock
chromadb/cli/cli.py
rust/cli/Cargo.toml
rust/cli/src/commands/mod.rs
rust/cli/src/commands/update.rs
rust/cli/src/lib.rs
rust/cli/src/utils.rs

Update the update command to agree with new CLI project structure. Python CLI entry point handles updating independently of the Rust CLI.
N/A

[ENH] CLI - Update command updated

---

Cargo.lock
Cargo.toml
rust/index/src/hnsw.rs
rust/index/src/hnsw_provider.rs
rust/index/src/spann/types.rs
rust/index/src/types.rs
rust/segment/src/distributed_hnsw.rs
rust/segment/src/distributed_spann.rs
rust/segment/src/local_hnsw.rs
rust/worker/benches/spann.rs

- After https://github.com/chroma-core/hnswlib/pull/31, need to update all callsites of hnsw.load() to pass in ef_search obtained from collection config
- ...
None

[BUG] Pass down ef_search from collection config to hnsw load

---

rust/log-service/src/lib.rs
rust/storage/src/s3.rs
rust/wal3/examples/wal3-bench.rs
rust/wal3/src/lib.rs
rust/wal3/src/writer.rs
rust/wal3/tests/test_k8s_integration_01_empty_and_open.rs
rust/wal3/tests/test_k8s_integration_03_initialized_append_succeeds.rs
rust/wal3/tests/test_k8s_integration_04_initialized_append_until_snapshot.rs
rust/wal3/tests/test_k8s_integration_05_crash_safety_initialize_fails.rs

Given a future, the dirty bit will be optimistically set, and definitely
flushed before writing the manifest.  This guarantees that any log
making progress is logging its progress on the side.

[ENH]  Every wal3 fragment can optionally mark itself dirty.

---

rust/wal3/README.md
rust/wal3/src/lib.rs
rust/wal3/tests/test_k8s_integration_03_initialized_append_succeeds.rs
rust/wal3/tests/test_k8s_integration_04_initialized_append_until_snapshot.rs
rust/wal3/tests/test_k8s_integration_05_crash_safety_initialize_fails.rs

The readme says bucket by 4096 using hex; I was doing dec 5000.
This PR changes the bucketing to be groups of 4096 and uses a padded hex for the digits.

[CLN]  wal3 doc<->code sync

---

rust/garbage_collector/tests/prop_test_local_files.rs
rust/system/src/execution/dispatcher.rs
rust/system/src/system.rs
rust/system/src/types.rs

The test `run_gc_test_ext` currently fails on `main` for me when running locally with the error "too many open files". This is because the worker threads that our system creates are never cleaned up.
This PR updates `ConsumableJoinHandle` to wrap thread handles, and updates the dispatcher to stop worker threads when the dispatcher component is stopped.
The test now passes for me locally.
n/a

[ENH]: stop/kill worker threads when dispatcher is stopped

---

k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/compaction-service.yaml
k8s/distributed-chroma/templates/query-service.yaml

This has been broken for a while. The rendered yaml does not apply, failing with error:
```
Error from server (BadRequest): error when creating "chart.yaml": StatefulSet
in version "v1" cannot be handled as a StatefulSet: strict decoding error:
unknown field "spec.template.spec.updateStrategy"
```
The `updateStrategy` fields are specified at the incorrect level, should be specified under the top level spec. Decided to just remove them, because rollingUpdate is the default anyway.
Render yaml from helm chart, apply directly using `kubectl`.

[BUG] Fix query/compaction sset definitions

---

chromadb/api/__init__.py
chromadb/api/async_api.py
chromadb/api/async_client.py
chromadb/api/client.py
chromadb/api/models/Collection.py
chromadb/api/rust.py
chromadb/test/client/test_database_tenant.py
chromadb/test/client/test_multiple_clients_concurrency.py
chromadb/test/property/invariants.py
chromadb/test/property/test_collections.py
chromadb/test/test_api.py
docs/docs.trychroma.com/markdoc/content/reference/python/client.md

due to no ef persistence, https://github.com/chroma-core/chroma/pull/3216/ returned collection names for list_collections. since we now have ef stored in the configuration, users can now list_collections and directly use them, and list collections can return collection objects.
- ...
- ...

[CHORE] Revert list collections to return collection object

---

docs/docs.trychroma.com/markdoc/content/docs/querying-collections/full-text-search.md

This PR adds a section describing full text search's support for logical operators, like $and and $or
- ...
- ...

[DOC] add logical operation section in fts docs

---

rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/garbage_collector/src/operators/delete_versions_at_sysdb.rs

-  Delete version files as part of GC. SysDb creates new version file at every compaction since version files are immutable. Clean up these extra version files.
- ...

[ENH] Delete version files in GC.

---

clients/js/package.json
clients/js/packages/chromadb-client/package.json
clients/js/packages/chromadb-core/package.json
clients/js/packages/chromadb/package.json
clients/js/packages/chromadb/tsup.config.ts

Closes #3762 
Bundling the OpenAI library via noExternal resulted in dynamic require errors due to Node-native dependencies like 'http' and 'util'. Marked 'openai' explicitly as external to prevent these issues.
* Removes embedding functions that use http from noExternal. They'll just be installed separately as a dependency from package.json instead of being bundled
* Bumps js client to v2.2.0
- Released a test package `@philipithomas/chromadb v2.3.3` to test changes.

[BUG] Fix import openai error caused by bundling Node-native modules in noExternal

---

rust/wal3/README.md
rust/wal3/src/cursors.rs
rust/wal3/src/lib.rs

- initialize new cursors which guarantees at most once initialization.
- load existing cursors in a way that allows for LLSC-style saving.
- save existing cursors in a way that guarantees consistency.

[ENH]  wal3 cursor store

---

rust/frontend/src/server.rs

The bucket is probably copy/pasted from version. This change adds a separate bucket for get_user_identity.
These changes are not tested.
* n/a

[BUG] Fix metrics counting for get_user_identity

---

chromadb/test/property/test_cross_version_persist.py

The cross version test uses a 1.0.0 custom embedding function to test cross version compatibility. This PR reverts that to a legacy embedding function to ensure we can test cross compatibility from old versions to 1.0.0
- ...
- ...

[TST] move cross compat test to legacy ef

---

Tiltfile

We've been seeing a lot of build pollution/flaky builds with Depot. This (temporarily) removes Depot and builds on runners without using a cache until we resolve the issue.
n/a

[BLD]: remove Depot from builds for Tilt

---

rust/log-service/src/lib.rs

The config says it has tracing for rust-log-service in staging.
The println for tracing says it's disabled.
Add printlns before the tracing is online to dump the config in its
entirety so we get ground truth.

[ENH]  Add debug logging to see the config at startup.

---

rust/log-service/src/lib.rs

The config says it has tracing for rust-log-service in staging.
The println for tracing says it's disabled.
Add printlns before the tracing is online to dump the config in its
entirety so we get ground truth.

[ENH]  Add debug logging to see the config at startup. (#4158)

---

chromadb/api/async_fastapi.py

Closes #4156
- The async client was serializing the config using the old _str method which results in an error in the server (it is strange that async tests are passing as this is pretty much 100% reproducible issue unless those have been disabled)

[BUG]: async get_or_create_collection breaking in 1.0.0 

---

go/pkg/grpcutils/response.go
go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/grpc/collection_service.go
go/pkg/sysdb/grpc/collection_service_test.go
go/pkg/sysdb/metastore/db/dao/collection.go
go/pkg/sysdb/metastore/db/dbmodel/collection.go
go/pkg/sysdb/metastore/db/dbmodel/mocks/ICollectionDb.go
idl/chromadb/proto/chroma.proto
idl/chromadb/proto/coordinator.proto

Prevent tracing:error calls for soft deleted collection in compaction.
This PR is a duplicate of https://github.com/chroma-core/chroma/pull/3965
This PR contains only the golang or sysdb side changes.
- Add new GRPC needed by compactor, and return desired error code from FlushCompaction and CreateCollection.
- ...

[ENH] Prevent tracing:error calls for soft deleted collection in compaction.

---

Cargo.lock
rust/cli/Cargo.toml
rust/cli/src/commands/login.rs
rust/cli/src/dashboard_client.rs

Stand up a proper web server in the login command that allows the dashboard to send session ID and update login status to the user more gracefully.
N/A

[ENH] Improve CLI login

---

rust/frontend/sample_configs/tilt_config.yaml
rust/worker/tilt_config.yaml

This leaves the code merged, but effectively reverts #4084 because it flaked in CI on hosted.

[BUG] Turn off wal3 dual-log write as it flaked in CI.

---

.config/nextest.toml
rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/garbage_collector/src/helper.rs
rust/garbage_collector/src/lib.rs
rust/garbage_collector/src/operators/compute_unused_files.rs
rust/garbage_collector/src/operators/compute_versions_to_delete.rs
rust/garbage_collector/tests/prop_test_local_files.rs

This adds two new tests, one that tests the delete mode of garbage collection and one that tests the soft-delete mode.
It also makes tests starting with `test_k8s_integration_` run serially in CI as it's difficult to write assertions about bucket contents otherwise.
n/a

[TST]: add E2E test for garbage collection in delete and soft-delete/rename modes

---

go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/coordinator/table_catalog_test.go
go/pkg/sysdb/metastore/db/dao/collection.go
go/pkg/sysdb/metastore/s3/impl.go

Adds the database ID to the prefix for collection files in S3 as it's a logical grouping layer.
Validated that path in Minio now includes the database ID:
n/a

[ENH]: add database ID to collection version file prefix

---

bin/python-integration-test
bin/rust-integration-test.sh
bin/test-remote
chromadb/api/async_fastapi.py
chromadb/api/collection_configuration.py
chromadb/api/fastapi.py
chromadb/test/api/test_types.py
chromadb/test/client/test_database_tenant_auth.py
chromadb/test/configurations/test_collection_configuration.py
chromadb/test/conftest.py
chromadb/test/ef/test_custom_ef.py
chromadb/test/ef/test_multimodal_ef.py
chromadb/test/property/test_add.py
chromadb/test/test_client.py
chromadb/utils/embedding_functions/__init__.py

For better dx when using custom embedding function, this allows users to add a decorator to custom embedding functions to register their embedding functions during get_collection. It also adds better error handling when the user does not register their embedding function ,and prompts them down the correct path. This PR also adds async fastapi tests
- ...
- ...

[ENH] register_embedding_function a decorator, error logs, async fastapi tests

---

rust/segment/src/blockfile_record.rs
rust/worker/src/execution/operators/mod.rs
rust/worker/src/execution/operators/source_record_segment.rs
rust/worker/src/execution/orchestration/compact.rs
rust/worker/src/execution/orchestration/mod.rs

- Update the compact orchestrator to use record segment instead of log service during rebuild
- Implement a `SourceRecordSegmentOperator` that generate materialized logs based on data from record segment

[ENH] Implement SourceRecordSegment operator

---

go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/grpc/collection_service.go
idl/chromadb/proto/coordinator.proto
rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/garbage_collector/src/helper.rs
rust/garbage_collector/src/operators/delete_unused_files.rs
rust/garbage_collector/src/types.rs
rust/garbage_collector/tests/prop_test_local_files.rs

- Renames garbage collection `ListOnly` mode to `DryRun` for better clarity.
- Does not delete versions in `DryRun` mode, only marks them for deletion.
These changes make it possible to transition from running `DryRun` mode to running `Rename` or `Delete` modes with no additional tooling.
Added a new E2E test for dry run mode.
n/a

[ENH]: rename GC `ListOnly` mode -> `DryRun`, do not delete versions in `DryRun` mode

---

go/pkg/sysdb/coordinator/model/collection.go
go/pkg/sysdb/coordinator/model_db_convert.go
go/pkg/sysdb/grpc/collection_service.go
go/pkg/sysdb/metastore/db/dao/collection.go
go/pkg/sysdb/metastore/db/dbmodel/collection.go
idl/chromadb/proto/coordinator.proto
rust/garbage_collector/garbage_collector_config.yaml
rust/garbage_collector/src/config.rs
rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/garbage_collector/src/helper.rs
rust/garbage_collector/src/operators/compute_versions_to_delete.rs
rust/garbage_collector/src/types.rs
rust/garbage_collector/tests/prop_test_local_files.rs
rust/sysdb/src/sysdb.rs

The main change here is allowing setting different garbage collection modes per tenant. This will allow us to enable delete mode for one tenant while testing and keep everyone else in dry run mode.
I added a new test, but for it to work I ended up needing to make some changes around how cutoff time is handled (was planning to make these changes, just in a later PR).
Added a new E2E test to validate tenant overrides.

[ENH]: allow overriding default garbage collection mode per tenant & clean up cutoff time parameters

---

Cargo.lock
rust/garbage_collector/Cargo.toml
rust/garbage_collector/src/garbage_collector_component.rs

Adds 3 metrics to the garbage collection service as a starting point:
- total jobs, segmented by success/failure
- job duration in milliseconds (histogram)
- total # of files deleted
- total # of versions deleted
Ran garbage collection and validated that the produced values in Granfana looked reasonable.
n/a

[ENH]: add metrics for garbage collection

---

.github/workflows/_go-tests.yml
go/cmd/coordinator/cmd.go
go/pkg/sysdb/grpc/cleaup_test.go
go/pkg/sysdb/grpc/collection_service_test.go
go/pkg/sysdb/grpc/server.go
go/pkg/sysdb/grpc/tenant_database_service_test.go
go/pkg/sysdb/metastore/s3/impl.go
k8s/distributed-chroma/values.dev.yaml

Updates sysdb S3 config flags to improve parity between local dev and deployed envs. Also adds parameters necessary for configuration in deployed env (bucket name) and verifies that bucket is accessible before continuing startup.
n/a

[ENH]: fix sysdb S3 config for parity between local dev & deployed env, add necessary params

---

go/Dockerfile

The sysdb container currently can't access S3 because it's missing root certificates.
Container builds and runs in `tilt`.

[BLD]: install ca-certificates in sysdb image

---

rust/frontend/src/server.rs

Record tenant, database, and collection_id (where appropriate) attributes for the various frontend endpoints. This will allow us to perform usage queries such as gets per tenant (as well as per database / collection).
These changes are not tested (yet). The plan is to merge into staging, then manually create some honeycomb dashboards / graphs to verify these attributes are being passed as expected.

[ENH] Add attributes for frontend metrics

---

rust/cli/src/commands/login.rs
rust/cli/src/dashboard_client.rs

Use server side authentication for CLI login. Instead of having the browser send session data to the CLI.

[ENH] Use server side token verification for cli login

---

go/cmd/coordinator/cmd.go
k8s/distributed-chroma/values.dev.yaml

Should fix flakes like
```
>         sysdb │ Apr  7 21:30:36.210661 FTL Failed to start the process error="unable to access bucket chroma-storage: NotFound: Not Found\n\tstatus code: 404, request id: 183426A2C3C55B5C, host id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8"
```
n/a

[TST]: sysdb should create S3 bucket if it doesn't exist when starting via Tilt

---

rust/frontend/sample_configs/tilt_config.yaml
rust/garbage_collector/src/helper.rs
rust/log-service/src/lib.rs
rust/python_bindings/src/lib.rs
rust/sysdb/src/lib.rs
rust/wal3/examples/wal3-bench.rs
rust/wal3/src/batch_manager.rs
rust/wal3/src/writer.rs
rust/worker/tilt_config.yaml

This adds some tracing, re-enables the wal3-backed log.

[ENH] Re-enable wal3 with values that work well in tilt even if tests run long.

---

rust/frontend/src/executor/local.rs
rust/log/src/local_compaction_manager.rs
rust/segment/src/local_hnsw.rs
rust/segment/src/local_segment_manager.rs
rust/types/src/api_types.rs

Helps with tracing errors similar to #4212
- Made backfil errors related to init in HNSW index bubble up and be visible in the rust bindings
Before:
```
InternalError: Error executing plan: Error sending backfill request to compactor
```
After:
```
InternalError: Error executing plan: Error sending backfill request to compactor: Error constructing hnsw segment reader: Error creating hnsw segment reader: Error deserializing pickle file: eval error at offset 1: unsupported opcode '\0'
```

[ENH]: Improving local executor backfill error propagation

---

.github/actions/rust/action.yaml

Depot runner images now ship with a new enough version of rustup for `rust-toolchain.toml` to work properly.

[BLD]: remove rustup self update in CI

---

chromadb/test/ef/test_ef.py
chromadb/utils/embedding_functions/__init__.py
chromadb/utils/embedding_functions/baseten_embedding_function.py
docs/docs.trychroma.com/markdoc/content/integrations/chroma-integrations.md
docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/baseten.md

This PR adds a Baseten integration for using Chroma with models deployed on Baseten
Tested locally with deployed model, output is identical to OpenAI integration.
Integration is documented in appropriate file.

[ENH] Add Baseten integration

---

go/pkg/sysdb/metastore/s3/impl.go

Minio and S3 treat leading in keys differently. Minio strips the leading slash, S3 does not. This means that attempting to look up the key `/foo` for `s3://sample-bucket/foo` fails, but succeeds when testing locally with Minio.
This materializes as the garbage collector being unable to fetch version files in staging.
I will update the `collections.version_file_name` column in staging after merge to manually remove the leading slash.
I connected to the Postgres sysdb in my local environment and verified that version file names are now saved without a slash prefix.

[BUG]: remove leading slash from version file name

---

go/pkg/log/server/server.go

- Adds a no-op impl so that we don't get errors on this call for deployments using the legacy path. 
- None
They are not automated test

[CHORE] Add purge logs no-op impl to go log service

---

.github/workflows/release-dev-javascript-client.yml

* Match dev release for JS-client to standard release workflow.
The JS-client now has optional dependencies for the different JS-bindings libraries, so we need to ignore strictness in the checked in lock file, since pnpm install will pick the binary that matches the runner's OS as opposed to the one chosen when developing locally.

[BUG] Fix JS-client dev release

---

Cargo.lock
Cargo.toml
go/pkg/sysdb/grpc/collection_service.go
idl/chromadb/proto/coordinator.proto
rust/garbage_collector/src/garbage_collector_component.rs
rust/sysdb/src/sysdb.rs

We currently send a relative cutoff time in seconds to the Sysdb when it expects an absolute cutoff time. This updates the garbage collection service to send an absolute cutoff time instead.
n/a

[BUG]: use absolute cutoff time when listing collections to garbage collect

---

.github/workflows/_python-tests.yml
chromadb/test/property/test_cross_version_persist.py
chromadb/test/property/test_persist.py
chromadb/test/utils/cross_version.py

Parallelizes Python property tests to run in a single job. Saves about 3m of wall time and is 2.6x cheaper in compute costs.
As an example, before this change a [sample run](https://github.com/chroma-core/chroma/actions/runs/14342162428/job/40203844517?pr=4211) took ~16m in wall time and consumed 8,266s of compute (after the multiplier for the instance size).
After this change, the property tests take [~13m in wall time](https://github.com/chroma-core/chroma/actions/runs/14345988691/job/40215763200?pr=4225) and consume 3,144s of compute (even though I doubled the instance size).
n/a

[TST]: parallelize Python property tests in a single job

---

rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/src/lib.rs

- We would like to wait until existing GC jobs to finish on shutdown. Thus we will call `system.stop()` to gracefully shutdown all components when SIGINT/SIGTERM is received. Notice that the system component will always be shutdown once the existing message has been handled, so we don't need to worry about partial progress in the GC job.
- N/A

[ENH] Gracefully shutdown GC system

---

rust/tracing/src/init_tracer.rs

`OTEL_EXPORTER_OTLP_METRICS_ENDPOINT` is a standard environment variable used by [OTLP SDKs](https://opentelemetry.io/docs/languages/sdk-configuration/otlp-exporter). This updates our metric exporter set up so that this value is properly consumed if set.
n/a

[ENH]: allow overriding metrics endpoint with standard `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT` if set

---

k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/garbage-collector.yaml

Allows specifying environment variables on the garbage collector service similar to other services.
Tested by adding a test `env:` block to `values.yaml` and observing that the new values were correctly built with `helm template .`.

[ENH]: allow specifying environment variables for garbage collector k8s template

---

rust/tracing/src/init_tracer.rs

Updates the stdout log filter to show GC logs.
Logs now show up in Tilt.

[ENH]: show garbage collector logs in stdout

---

bin/rust_single_node_integration_test_config.yaml
rust/cache/src/foyer.rs
rust/frontend/sample_configs/distributed.yaml
rust/frontend/sample_configs/tilt_config.yaml
rust/frontend/src/get_collection_with_segments_provider.rs
rust/python_bindings/src/bindings.rs

- Adds a configurable ttl to collection_and_segments cache on RFE
- ...
None

[ENH] Add ttl to sysdb cache on RFE

---

.github/workflows/_python-tests.yml

Hoping this helps debug test failures like this: https://github.com/chroma-core/chroma/actions/runs/14366566402/job/40280832204.

[TST]: enable Rust backtraces in Python binding tests

---

.github/workflows/_python-tests.yml

Logs durations of 10 slowest Python tests at end of run.

[TST]: log durations of 10 slowest Python tests

---

rust/tracing/src/init_tracer.rs

Metrics are not being exported in staging. This should help debug.
Changed `otel_endpoint` to a non-existent endpoint and observed that errors were logged to stdout.
n/a

[ENH]: log OpenTelemetry export errors

---

rust/wal3/src/manifest.rs
rust/wal3/src/manifest_manager.rs
rust/wal3/src/writer.rs

There was a write hole where recovery would fail to write the dirty bit.  Plug it.

[ENH] When recovering a wal3 manifest, mark it dirty.

---

rust/worker/src/execution/orchestration/compact.rs

The partitioned compaction code had a race wherein one partition could race through all work before
other partitions registered their work.  This fixes the race condition.

[BUG]  Fix race condition.

---

rust/frontend/src/impls/service_based_frontend.rs

- We would like to retry failed reads from transport errors. These error will manifest as `Unknown` error codes in frontend.
- Only trace on retried requests.
- N/A

[ENH] Retry query paths on transport errors

---

rust/blockstore/src/arrow/block/delta/unordered_block_delta.rs
rust/blockstore/src/arrow/blockfile.rs
rust/blockstore/src/arrow/migrations.rs
rust/blockstore/src/arrow/provider.rs
rust/garbage_collector/src/operators/delete_unused_files.rs
rust/garbage_collector/src/operators/fetch_sparse_index_files.rs
rust/garbage_collector/src/operators/fetch_version_file.rs
rust/index/src/hnsw_provider.rs
rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/config.rs
rust/storage/src/lib.rs
rust/storage/src/local.rs
rust/storage/src/object_store.rs
rust/storage/src/s3.rs
rust/sysdb/src/test_sysdb.rs
rust/wal3/src/cursors.rs
rust/wal3/src/manifest.rs
rust/wal3/src/reader.rs
rust/wal3/src/writer.rs
rust/wal3/tests/common.rs
rust/worker/chroma_config.yaml
rust/worker/tests/config_from_default_path.rs
rust/worker/tests/config_missing_default_field.rs
rust/worker/tilt_config.yaml

- ...
- Introduces a notion of tagging s3 requests with their priority
- NAC divides the total network bandwidth amongst these priority variants
- This allocation of bandwidth distribution is configurable
- Changes the blockfile layer to suitably tag priority of s3 requests. Currently, prefetching is low priority and everything else is high priority
- When executing a request, NAC successively checks for bandwidth availability from lower priority channels and if any of them have availability then it dispatches the request otherwise it blocks on the semaphore of its own priority channel
None

[ENH] Introduce request priority in storage layer

---

rust/blockstore/src/arrow/provider.rs
rust/segment/src/blockfile_metadata.rs
rust/segment/src/blockfile_record.rs
rust/segment/src/distributed_spann.rs
rust/types/src/segment.rs
rust/worker/src/execution/operators/prefetch_segment.rs
rust/worker/src/execution/orchestration/compact.rs
rust/worker/src/execution/orchestration/spann_knn.rs

- ...
- Prefetches Posting lists in the beginning of query and compaction. Also, tracks which sparse index ids were already prefetched so as to not do it again. This state is not persistent across restarts and has a ttl.
None

[ENH]: Prefetch posting list in query + compactor

---

.github/workflows/_python-tests.yml

This test frequently flakes when parallelized.

[TST]: run test_cross_version_persist tests sequentially

---

rust/garbage_collector/src/operators/delete_unused_files.rs
rust/garbage_collector/src/types.rs

- The delete list is no longer used during GC and should be removed
- ...

[CLN] Deprecate delete list file in GC

---

chromadb/api/models/CollectionCommon.py
chromadb/test/ef/test_ef.py
chromadb/test/ef/test_openai_ef.py

This PR adds tests for validation_context to ensure the errors raised match the ones given by the caller, in this case an embedding function. tests for https://github.com/chroma-core/chroma/pull/4235

[CHORE] Add test to validate embedding function error handling

---

go/pkg/log/repository/log.go
go/pkg/log/server/server.go
idl/chromadb/proto/logservice.proto
rust/log-service/src/lib.rs
rust/log/src/grpc_log.rs
rust/log/src/log.rs
rust/wal3/src/manifest.rs

Compaction assumes that enumeration position t_i means t_i was the last
record seen and therefore next reader should read from t_i + 1.
Log service was built and tested for t_i meaning t_i was the first
record to return.
Somehow it passed tests, so let's see if this one does.
Note:  I changed the go code, but only by moving a +1 out a layer.  The
inner version was inconsistent with convention, so I updated it.

[BUG] OBO between log service and compaction.

---

.github/workflows/release-javascript-client.yml

JS release fails because js bindings used in release. Talked to Itai, he said its safe to remove

[CHORE] Remove js bindings from release

---

rust/frontend/src/impls/service_based_frontend.rs
rust/log-service/src/lib.rs
rust/log/src/grpc_log.rs
rust/types/src/api_types.rs
rust/wal3/src/batch_manager.rs
rust/wal3/src/lib.rs
rust/wal3/src/writer.rs
rust/worker/tilt_config.yaml

This does multiple things:
- Adds a Backoff code to pushlogs and plumbs it upwards.
- Coalesces the two timeouts that were used in batch_manager and uses
them everywhere.
- Stops batching by record count.  Byte count only.
- Adds a backoff condition to the batch manager.  If the batch size and
then some is in the log, it'll set backoff mode to shed further
writes.
- Configures the writer in tilt config.
- Plumbs an error for exp backoff.

[ENH]  Improve backoff and throttling of wal3.

---

rust/frontend/src/impls/service_based_frontend.rs
rust/log-service/src/lib.rs
rust/log/src/grpc_log.rs
rust/types/src/api_types.rs
rust/wal3/src/batch_manager.rs
rust/wal3/src/lib.rs
rust/wal3/src/writer.rs
rust/worker/src/execution/operators/fetch_log.rs
rust/worker/tilt_config.yaml

This fixes a critical bug in the as-of-yet-unreleased log service in
which logs would pull incorrectly.  The flow of the bug is as follows:
1)  Fetch logs scans to get a Vec<Parquet>.
2)  Fetch all parquet files in parallel.
3)  Take the first batch_size records across all files regardless of
their start/limit.

[BUG]  Fix an ordering and windowing bug in new log service.

---

chromadb/utils/embedding_functions/jina_embedding_function.py
clients/js/packages/chromadb-core/src/embeddings/JinaEmbeddingFunction.ts
docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/jina-ai.md
examples/use_with/jina/late_chunking.ipynb
schemas/embedding_functions/jina.json

This PR updates the Jina embedding function in both python and typescript to make v3 the default embedding model, and adds support for all configuration attributes that Jina supports.
this includes: late_chunking, task, truncate, dimensions, embedding_type, and normalized

[ENH] Update Jina embedding function to support all models and configurations

---

go/pkg/sysdb/metastore/db/dao/collection.go

- Handle `Null` version file name in updates
- ...

[BUG] Handle null version file name in query

---

chromadb/db/impl/grpc/client.py
go/pkg/sysdb/coordinator/model/collection.go
go/pkg/sysdb/coordinator/model/collection_configuration.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/coordinator/table_catalog_test.go
go/pkg/sysdb/grpc/collection_service.go
idl/chromadb/proto/coordinator.proto
rust/sysdb/src/sysdb.rs

- ...
- add `configuration_json_str` to go grpc implementation and enable writing to grpc service from rust
- add logic to overwrite existing configuration attributes with the updated configuration attributes

[ENH] grpc changes for update collection config

---

chromadb/api/async_fastapi.py
chromadb/api/collection_configuration.py
chromadb/api/fastapi.py
chromadb/db/impl/grpc/client.py
chromadb/test/configurations/test_collection_configuration.py
chromadb/types.py
clients/js/packages/chromadb-core/src/generated/models.ts
go/pkg/sysdb/coordinator/model/collection.go
go/pkg/sysdb/coordinator/model/collection_configuration.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/coordinator/table_catalog_test.go
go/pkg/sysdb/grpc/collection_service.go
idl/chromadb/proto/coordinator.proto
rust/segment/src/distributed_spann.rs
rust/sysdb/src/sqlite.rs
rust/sysdb/src/sysdb.rs
rust/types/src/collection.rs
rust/types/src/collection_configuration.rs

- Removed `#[serde(skip_serializing)]` attribute from `config` field in `Collection` struct, allowing it to be serialized
- Added `ToSchema` derive macro to `VectorIndexConfiguration` enum, enabling OpenAPI schema generation
- Added `ToSchema` derive macro to `InternalCollectionConfiguration` struct for OpenAPI schema generation
- Added `ToSchema` derive macro to `InternalSpannConfiguration` struct for OpenAPI schema generation
No documentation changes required as these changes are related to internal serialization and schema generation capabilities.

[ENH] return configuration in server response

---

chromadb/types.py
clients/js/README.md
clients/js/package.json
clients/js/packages/chromadb-client/README.md
clients/js/packages/chromadb-client/package.json
clients/js/packages/chromadb-core/package.json
clients/js/packages/chromadb-core/src/ChromaClient.ts
clients/js/packages/chromadb-core/src/Collection.ts
clients/js/packages/chromadb-core/src/CollectionConfiguration.ts
clients/js/packages/chromadb-core/src/generated/models.ts
clients/js/packages/chromadb-core/src/types.ts
clients/js/packages/chromadb-core/src/utils.ts
clients/js/packages/chromadb-core/test/admin.test.ts
clients/js/packages/chromadb-core/test/auth.basic.test.ts
clients/js/packages/chromadb-core/test/auth.token.test.ts
clients/js/packages/chromadb-core/test/auth.xtoken.test.ts
clients/js/packages/chromadb-core/test/collection.client.test.ts
clients/js/packages/chromadb-core/test/collection.config.client.test.ts
clients/js/packages/chromadb-core/test/get.collection.test.ts
clients/js/packages/chromadb-core/test/query.collection.test.ts
clients/js/packages/chromadb-core/test/startChromaContainer.ts
clients/js/packages/chromadb-core/test/testEnvSetup.ts
clients/js/packages/chromadb-core/test/testEnvTeardown.ts
clients/js/packages/chromadb/package.json
clients/js/pnpm-lock.yaml
rust/types/src/collection.rs

This PR adds support for collection configuration in the javascript client. it updates tests, functionality, and introduces a breaking change involving how the rust server responds with include

[ENH] Add collection config to js client

---

docs/docs.trychroma.com/markdoc/content/docs/collections/configure.md

This PR adds documentation for how to configure collection configuration, settings hnsw parameters, and embedding functions

[DOC] Add collection config docs

---

chromadb/api/collection_configuration.py
chromadb/api/types.py
chromadb/test/configurations/test_collection_configuration.py
chromadb/types.py
clients/js/packages/chromadb-core/src/CollectionConfiguration.ts
clients/js/packages/chromadb-core/src/generated/models.ts
go/pkg/sysdb/coordinator/model/collection_configuration.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/coordinator/table_catalog_test.go
rust/frontend/sample_configs/distributed.yaml
rust/frontend/sample_configs/tilt_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/executor/distributed.rs
rust/frontend/src/executor/local.rs
rust/frontend/src/executor/mod.rs
rust/frontend/src/impls/in_memory_frontend.rs
rust/frontend/src/impls/service_based_frontend.rs
rust/frontend/src/server.rs
rust/frontend/src/types/errors.rs
rust/index/src/spann/types.rs
rust/python_bindings/src/bindings.rs
rust/segment/src/distributed_spann.rs
rust/types/src/api_types.rs
rust/types/src/collection_configuration.rs
rust/types/src/spann_configuration.rs
rust/worker/benches/spann.rs

Add SPANN configuration for collection config

[ENH] Add Spann configuration to collection config

---

rust/frontend/sample_configs/tilt_config.yaml
rust/garbage_collector/src/helper.rs
rust/worker/tilt_config.yaml

I don't know where it is or what the flake is, but I cannot rule out it
being this code without trying this minimal commit to disable
use_alt_host_for_everything in tilt.

[BUG] disable alt-host shunt

---

chromadb/test/conftest.py

This affects CI and makes it so we get some debug output from
Hypothesis.  For example, when it fails the test because the deadline
was exceeded and then met.

[CHORE] set verbosity for hypothesis to verbose.

---

rust/frontend/src/tower_tracing.rs

Adds user agent to rust frontend traces. Previously this was included in the legacy frontend traces, but we had not included it in the rust frontend traces (yet).
Tested locally with tilt environment, confirmed traces included user agent in jaeger.
n/a

[ENH] Add user agent to rust frontend traces

---

chromadb/api/collection_configuration.py
chromadb/types.py

This PR fixes a typing error when an empty configuration json is returned during get_configuration and removes validation on num_threads in python

[CHORE] Fix typing on empty configuration json returned, remove validation on num_threads in python

---

chromadb/api/collection_configuration.py
chromadb/test/configurations/test_collection_configuration.py
clients/js/packages/chromadb-core/src/CollectionConfiguration.ts
clients/js/packages/chromadb-core/src/generated/models.ts
clients/js/packages/chromadb-core/test/collection.config.client.test.ts
rust/sysdb/src/sqlite.rs
rust/types/src/hnsw_configuration.rs

This PR removes num_threads and batch_size on server response for collection configuration, and removes client side validation

[HOTFIX] Remove batch_size and num_threads on server response, remove client coll config validation

---

rust/segment/src/local_hnsw.rs

Fixes: #4275
- Fixes an issue a logical error in distance comparison when adding RecordDistance to heap. We're looking for minimal no maximal distance
- When traversing a index with less than 100 items and more than 20% of the data deleted

[BUG]: <100 items, >20% delete Wrong distance comparison in local HNSW

---

chromadb/api/__init__.py
chromadb/api/async_api.py

The docstrings for `where` and `where_document` indicated that they default to `{}`. This is inconsistent with the actual type definition, and additionally confusing because sending `None` is OK, but sending `{}` is not.
So, this is a small find-and-replace for these instances.
This also comes up with respect to the `headers` in the [Docs site](https://github.com/chroma-core/chroma/blob/069ca5fb5223a1e466244f3c6e858c8e183ce233/docs/docs.trychroma.com/markdoc/content/reference/python/client.md?plain=1#L66) regarding the HTTP Client. In this case, the docs are clearly inconsistent with the code right above it, but I wasn't sure if I should change it, because `None` gets converted to `{}` in sending the request. I'm still inclined to correct it to match the actual code.
*How are these …

[DOC]: Fix docstring defaults for query filters

---

rust/blockstore/src/arrow/provider.rs

This only affects a single log line that's quite spammy.

[CHORE] Demote "Block: <UUID> written to storage (<>B)" to debug

---

rust/log/src/local_compaction_manager.rs

- We also propagate errors from sqlite metadata reader - related to debugging of #4217

[CHORE]: Local compation manager error propagation for sqlite

---

rust/blockstore/src/arrow/blockfile.rs
rust/blockstore/src/arrow/concurrency_test.rs

- We extend the lifetime of a block reference that is present in the reader's `loaded_blocks` hashmap and hand out that reference for reads. However if get_block() is called concurrently by multiple actors then they can race and overwrite an existing entry of the hash map. This will invalidate all existing references to that block causing null pointer exceptions and/or segmentation faults
- ...
None

[BUG] Segmentation fault in get_block

---

.github/actions/rust/action.yaml
.github/workflows/_build_js_bindings.yml
.github/workflows/_build_release_pypi.yml

- After #4337 this job fails due to not calling the rust setup action to get correct rust version
- CLN: Standardize usage of 
- None
Will have to test on main

[BLD] Setup rust in pypi release, standardize protoc action

---

rust/sqlite/src/config.rs

#4332
- Default sqlx pool options close idle connections for in-memory DB after 10mins which clears the data in the DB causing subsequent client calls to fail with sqlite errors. This PR sets max_lifetime and idle_timeout for in-memmory DB to None which prevents connection from being reaped

[BUG]: Setting max_lifetime and max_timeout to None for in-memory DB

---

.github/workflows/_build_release_pypi.yml

- Use the correct arg name for `github-token` to prevent rate limits against GH api
- Setup-rust in another action missing it
- None
None

[BLD] Setup rust, correct var name for token

---

go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/model/collection.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/grpc/collection_service.go
idl/chromadb/proto/coordinator.proto

- N/A
- Defines the SysDB fork service request and response
- Wires up the request upto `table_catalog.go`

[ENH] Wire up proto defs for sysdb fork endpoint

---

.github/workflows/_python-tests.yml
Tiltfile
chromadb/test/conftest.py
chromadb/test/property/invariants.py
chromadb/test/property/test_embeddings.py
rust/frontend/sample_configs/tilt_config.yaml
rust/frontend/src/config.rs
rust/garbage_collector/src/helper.rs
rust/log-service/src/lib.rs
rust/wal3/src/reader.rs
rust/worker/src/config.rs
rust/worker/src/execution/operators/count_records.rs
rust/worker/src/lib.rs
rust/worker/tilt_config.yaml

- Change timeouts in tilt to 60s
- Change deadline for proptest to 90s.
- Reenable use_alt_host_for_everything in tilt.
- Template with the right file consistently.
N/A

[CHORE] Enable rust log service, set timeouts, change tilt.

---

rust/log/src/log.rs

- Increases the default max batch size to be much higher since the quota system will be responsible for this.
- TODO: We should deprecate the pre-flight-check here and prefer the server to just reject the request.
- None
None

[CHORE] Increase default max batch size

---

go/pkg/log/repository/log.go
go/pkg/log/server/server.go
go/pkg/log/store/db/queries.sql.go
go/pkg/log/store/queries/queries.sql
go/pkg/sysdb/coordinator/coordinator_test.go
go/pkg/sysdb/coordinator/table_catalog.go
idl/chromadb/proto/logservice.proto
rust/frontend/src/impls/service_based_frontend.rs
rust/log-service/src/lib.rs
rust/log/src/grpc_log.rs
rust/log/src/log.rs
rust/types/src/api_types.rs

- N/A
- Implement log forking. Currently it is only implemented for legacy log service, by naively cloning the log offsets and records.

[ENH] Implement log forking

---

.github/actions/rust/action.yaml

- Make rust action set version to installed verison to help with things like - https://github.com/chroma-core/chroma/actions/runs/14605047733/job/40973984539 that are harder to express with the toolchain. Runners come with their own default version of rust so if we override it makes sense to default to that
- None
None

[CHORE] Make rust action set version to installed version

---

rust/frontend/sample_configs/tilt_config.yaml
rust/garbage_collector/src/helper.rs
rust/worker/tilt_config.yaml

- Disable it, again.
Passed in PR CI.  Failed in main CI, so it's a revert.

[CHORE]  Disable rust log service because it flaked once landing.

---

rust/load/src/data_sets.rs
rust/load/src/lib.rs
rust/load/src/workloads.rs

Upsert sequentially from the reference data set. Verify data by getting from the subset of already-loaded keys and checking results against the reference data set.
1. Create reference dataset using loader script:
```
export CHROMA_TENANT_ID="abc"
export CHROMA_DATABASE="chroma-load"
export CHROMA_API_KEY="xyz"
pipenv run -- python script/import_dataset.py \
--tenant $CHROMA_TENANT_ID \
--database $CHROMA_DATABASE \
--collection reference-all-MiniLM-L6-v2 \
--dataset roneneldan/TinyStories \
--dataset-split train \
--sentence-transformer-model all-MiniLM-L6-v2 \
--max-rows 1000000 \
--max-rps 120 \
--sequential-keys
```
2. (manually) Create (or reset via delete+recreate) the test collection: `test-all-MiniLM-L6-v2`
3.  Start the chroma-load service:
```
export …
```

[ENH] Add VerifyingDataSet that verifies loaded data

---

go/pkg/common/errors.go
go/pkg/sysdb/coordinator/table_catalog.go
rust/frontend/src/server.rs

- Disable the quota system for collection fork. We rely on a properly configured scorecard for now to limit access to this feature.
- Limit the maximum number of entries in the lineage file. 
- N/A

[ENH] Disable quota and add limit for collection fork

---

rust/frontend/src/server.rs

- A previous PR enabled quota to prevent access to fork on prod. This PR disables the quota for testing on staging after deployment to prod
- N/A

[CFG] Disable quota for forking

---

go/pkg/log/store/db/queries.sql.go
go/pkg/log/store/queries/queries.sql

- The log service will error during fork if the source colletion is not initialized yet (i.e. no data is added yet), because the compaction and enumeration offset does not exist. This PR fixes this edge case.
- ...

[BUG] Fix failing fork on empty collection

---

docs/docs.trychroma.com/components/markdoc/markdoc-renderer.tsx
docs/docs.trychroma.com/components/markdoc/page-nav.tsx
docs/docs.trychroma.com/components/sidebar/page-index.tsx
docs/docs.trychroma.com/components/sidebar/page-link.tsx
docs/docs.trychroma.com/components/sidebar/sidebar.tsx
docs/docs.trychroma.com/lib/content.ts
docs/docs.trychroma.com/markdoc/content/production/chroma-server/client-server-mode.md
docs/docs.trychroma.com/markdoc/content/production/cloud-providers/aws.md
docs/docs.trychroma.com/markdoc/content/production/cloud-providers/azure.md
docs/docs.trychroma.com/markdoc/content/production/cloud-providers/gcp.md
docs/docs.trychroma.com/markdoc/content/production/containers/docker.md

Fixes #4215 
On certain pages, specifically those that had a top section with no subsection, the Next/Prev functionality was sometimes breaking. This was due to the way the links and the slugs were connected and from the configuration of the Sidebar and the its components.
It turns out that `path` can be computed from `slug` by just prepending a `/`, so I removed the `path` property and refactored it to add some small logic to convert slug to path, simplifying the component properties.
In addition, I found that some links to the python-thin-client were broken, due to using relative paths, so I just did a quick fix by using the absolute path instead. The only downside is that if you are working in an IDE, the absolute link won't work within the IDE. There are ways to patch this, or …

[DOC]: Fix broken Next/Prev link buttons

---

rust/blockstore/src/arrow/provider.rs
rust/cache/src/foyer.rs
rust/cache/src/lib.rs
rust/cache/src/nop.rs
rust/cache/src/unbounded.rs

- Removed the write_mutex that block manager had. It does not have any correctness bearings. It was simply there so that we don't reinsert the same entry to the cache again. Because we clone and handout the block (internally a block is an Arc<> so clone is cheap) it should be fine to overwrite the cache with the same value again.
-  foyer.obtain() deduplicates disk access to the same key so might be more performant under concurrency. The trade-off is that you have to clone the key which for us is a 16 byte uuid.
None

[ENH] Introduce + consume foyer.obtain()

---

rust/load/src/data_sets.rs
rust/load/src/lib.rs

This adds a hook for workload executors to initialize the data sets before starting the verification process. It resets the collection by deleting + recreating it.
Tested locally, using same process as in https://github.com/chroma-core/chroma/pull/4341, but without manual step to create the test collection, since it's no longer necessary.

[ENH] Add hook to initialize collection before running verification

---

rust/load/Dockerfile

This will be used to initialize new runs of the verification service, by executing the binary in the image.
Verify the built image contains the expected binary:
```
docker buildx build -f ./rust/load/Dockerfile --build-arg RELEASE_MODE=1 --target load_service -t load-service:local .
docker run --rm --entrypoint ./chroma-load-start load-service:local
```

[ENH] Build chroma-load-start binary and add it to chroma-load container

---

rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/index/src/hnsw_provider.rs
rust/index/src/lib.rs
rust/index/src/spann/types.rs
rust/segment/src/distributed_hnsw.rs
rust/segment/src/distributed_spann.rs
rust/system/src/execution/orchestrator.rs
rust/worker/benches/spann.rs
rust/worker/src/compactor/compaction_manager.rs
rust/worker/src/execution/orchestration/compact.rs
rust/worker/src/execution/orchestration/count.rs
rust/worker/src/execution/orchestration/get.rs
rust/worker/src/execution/orchestration/knn.rs
rust/worker/src/execution/orchestration/knn_filter.rs
rust/worker/src/execution/orchestration/spann_knn.rs

- If hnsw cache evicts and purger is called concurrently with provider.open() then there is a race and can cause deletion of files that is being loaded concurrently
- Fixes it by removing the purger and purging at the end of provider.open(). For provider.fork() or provider.create(), we purge at the end of compaction and also in case of failures
- ...
None

[BUG] Fix race between hnsw load and hnsw purge

---

clients/js/package.json
clients/js/packages/chromadb-client/package.json
clients/js/packages/chromadb-core/package.json
clients/js/packages/chromadb/package.json

Bumps JS client to v2.3.0
Code lists an unreleased 3.0.0 version. After talking with @jairad26 , we concluded that a major version release was no longer necessary because we updated the changes to be backwards-compatible. 
This release includes:
- Collection config
- Forking support

[RELEASE] js client v2.3.0 with collection config and forking

---

rust/load/src/bin/chroma-load-start.rs
rust/load/src/lib.rs
rust/load/src/rest.rs

This way, the same load service can be used to run workloads against multiple different environments. Also, there is no need to specify secrets when deploying the load-service.
Test by running locally, and configuring a workload with a remote connection.

[ENH] Make connection configurable per running load-service workload

---

rust/worker/chroma_config.yaml
rust/worker/src/execution/orchestration/spann_knn.rs
rust/worker/tilt_config.yaml

- Handles the case when no data in the segments but only on the log for spann
- Increase the max_block_size for local tilt to 8MB (consistent with staging/prod) since posting lists can be bigger than the size that's currently the max in local
- ...
None

[BUG] Handle uninitialized spann segment reader

---

chromadb/test/property/invariants.py
rust/frontend/sample_configs/distributed.yaml
rust/frontend/sample_configs/tilt_config.yaml
rust/frontend/src/impls/service_based_frontend.rs
rust/index/src/spann/types.rs

- This is a placeholder PR that enables spann by default. It is just for testing if CI is green after all fixes have gone in.
- ...
None

[ENH] Turn on spann by default

---

chromadb/test/ef/test_default_ef.py

https://github.com/chroma-core/chroma/actions/runs/14651962766/job/41119672498
In this run, hypothesis fails this test because too much has been filtered out. this is because the test fetches all providers, and then filters to the available ones. a better solution would be to directly access the available providers
- ...
- ...

[CHORE] Fix flaky default_ef test

---

rust/index/src/hnsw_provider.rs
rust/index/src/spann/types.rs
rust/segment/src/distributed_hnsw.rs

- Previously, the caller was expected to lock before calling hnsw_provider.open(). This is leaky. Moved it inside.
- Also, used the double checked locking pattern to avoid taking the partitioned mutex in the happy path when the index is cached
- ...
None

[CLN]: Move hnsw_provider.open() lock inside the call itself

---

clients/js/packages/chromadb-core/src/generated/models.ts
rust/frontend/sample_configs/distributed.yaml
rust/frontend/sample_configs/tilt_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/server.rs
rust/frontend/src/types/errors.rs
rust/index/src/hnsw_provider.rs
rust/segment/src/distributed_hnsw.rs
rust/types/src/collection_configuration.rs
rust/types/src/hnsw_configuration.rs
rust/types/src/spann_configuration.rs

This PR removes the ability to set collection configuration on distributed chroma. If the user sets any configuration other than space, it will error in distributed chroma
- ...
- ...

[CHORE] Move distributed to default collection configuration

---

chromadb/types.py
chromadb/utils/embedding_functions/onnx_mini_lm_l6_v2.py

This PR fixes the pydantic warning message emitted
Fixes: https://github.com/chroma-core/chroma/issues/4193
https://github.com/chroma-core/chroma/issues/4190

[CHORE] Fix type safety

---

chromadb/test/ef/test_ef.py
chromadb/utils/embedding_functions/__init__.py
chromadb/utils/embedding_functions/cloudflare_workers_ai_embedding_function.py
clients/js/packages/chromadb-core/src/embeddings/CloudflareWorkersAIEmbeddingFunction.ts
clients/js/packages/chromadb-core/src/schemas/schemaUtils.ts
docs/docs.trychroma.com/markdoc/content/docs/embeddings/embedding-functions.md
docs/docs.trychroma.com/markdoc/content/integrations/chroma-integrations.md
docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/cloudflare-workers-ai.md
schemas/embedding_functions/cloudflare_workers_ai.json

This PR adds support for cloudflare worker embedding function across both python and typescript, adds docs, and schema validation

[ENH] Add Cloudflare Worker AI Embedding Function

---

chromadb/test/ef/test_voyageai_ef.py
chromadb/utils/embedding_functions/voyageai_embedding_function.py

Closes #4378
- Voyage AI client API seems to have changed and now returns [EmbeddingsObject](https://github.com/voyage-ai/voyageai-python/blob/012d16bd708c797766beb26555e56b10db8d09fd/voyageai/object/embeddings.py#L5-L16)
- Added skippable Voyage AI EF basic test

[BUG]: Fix Voyage AI EF to match new API

---

Dockerfile
Dockerfile.windows
chromadb/test/utils/cross_version.py
pyproject.toml
requirements.txt
requirements_dev.txt

https://github.com/chroma-core/chroma/issues/4382#issue-3020402184
this PR removes hnsw-lib from core dependencies, removes it from the dockerfile, and moves it to dev dependencies in pyproject

[CHORE] remove hnsw-lib from core dependencies

---

rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/garbage_collector/src/helper.rs
rust/garbage_collector/src/operators/compute_unused_files.rs
rust/garbage_collector/src/operators/fetch_sparse_index_files.rs

Collections that use a HNSW index have a segment file path called `hnsw_index`. However, collections with a SPANN index have a segment file path called `hnsw_path`. Currently garbage collection logic treats `hnsw_index` as HNSW files but was treating `hnsw_path` as sparse indices because we never match on that file type name.
This PR fixes the logic so that both `hnsw_index` and `hnsw_path` file types are treated as HNSW files.
Added test fails on main.
n/a

[BUG]: don't try reading HNSW files as sparse indices when performing garbage collection on SPANN collections

---

rust/frontend/src/server.rs

Previously, the frontend was unconditionally attempting to unwrap the collection config, even if it was None. This wasn't caught before because all of the popular clients are actually passing in a collection config. However, it should be optional.
Not tested yet, will check in staging after it merges.
n/a

[BUG] Prevent unconditional unwrap of collection config

---

go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/metastore/db/dao/collection.go

Upon compaction flush for a collection, the Sysdb [creates a version file if one does not exist](https://github.com/chroma-core/chroma/pull/4284/files). To do this, it populates fields in the file using the `GetCollectionEntry` method.
However, before this PR, the `GetCollectionEntry` method **always returned an empty string for the tenant**. This led to the field missing in the version file and version files being saved under the wrong bucket prefix.
Validated that the tenant ID is now correctly populated by:
1. `tilt up` with version files disabled on Sysdb.
2. Created a collection and added data.
3. Enabled version files on Sydb.
4. Added more data to the collection.
5. Observed that the tenant ID was correctly populated in the created version files. …

[BUG]: fix missing tenant ID in version file

---

rust/storage/src/admissioncontrolleds3.rs
rust/worker/src/execution/operators/prefetch_record.rs

- Tags the prefetch record segment operator as IO
- Fixes a potential spinloop in the admission controller where .recv() returns None on sender drop. It is unclear why the sender could drop, and that needs to be investigated. But this change makes sense defensively at the function level. This could alternatively use `tokio::sync::Notify`
- /
None

[BUG] Tag prefetch record as IO, fix spinloop in admissionController

---

.config/nextest.toml
.github/workflows/_rust-tests.yml
rust/index/src/spann/types.rs

- Reenables the parallel spann tests in CI with bigger stack size.
- ...
None

[TST] Re-enable parallel spann tests with bigger stack size

---

Cargo.lock
Cargo.toml
chromadb/api/rust.py
chromadb/api/types.py
chromadb/base_types.py
idl/chromadb/proto/chroma.proto
rust/frontend/src/impls/in_memory_frontend.rs
rust/segment/Cargo.toml
rust/segment/src/sqlite_metadata.rs
rust/segment/src/test.rs
rust/types/src/metadata.rs
rust/types/src/strategies.rs
rust/types/src/where_parsing.rs
rust/worker/Cargo.toml
rust/worker/src/execution/operators/filter.rs
rust/worker/src/execution/orchestration/compact.rs

- N/A
- Introduce the regex filters for documents:
- `{"$matches": "<regex>"}`: Evaluates to true for documents matching the regex
- `{"$not_matches": "<regex>"}`: The exact opposite of `$matches`. (i.e. it will evaluate to true on records without documents)
- Propagates the regex filters from the client to the query node. Current the implementation is `todo!()` for local and distributed chroma, and the code will panic when reached. The `todo!`s will be replaced with actual implementations with future impls.
_Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the [docs …

[ENH] Wire up regex filter from client to query node

---

DEVELOP.md
chromadb/__init__.py
docs/docs.trychroma.com/markdoc/content/reference/python/client.md

- Refactored Port Parameter Handling: Changed the port parameter in the [HttpClient class](https://github.com/chroma-core/chroma/blob/479ce3312c18545f6d5d741b28f0b45b97ea391a/chromadb/__init__.py#L164) to accept an integer instead of a string. This applies to both the Python code and the related documentation.
- Before: port="8000" (string)
- After: port=8000 (integer)
- Docstring Updates: Updated the docstrings in __init__.py to reflect the new default port value as an integer (8000 instead of "8000").
- Documentation Fixes: Corrected the documentation in client.md to reflect the updated data type for the port parameter, ensuring consistency with the code changes.
*Motivation*
I was interested in your project and started reading through the source …

[CLN] Fix Port Parameter Inconsistency in HttpClient (String to Integer)

---

rust/log-service/src/lib.rs
rust/wal3/src/copy.rs
rust/wal3/src/lib.rs
rust/wal3/src/manifest.rs
rust/wal3/src/reader.rs
rust/wal3/src/writer.rs
rust/wal3/tests/test_k8s_integration_70_load_and_scrub.rs
rust/wal3/tests/test_k8s_integration_80_copy.rs
rust/wal3/tests/test_k8s_integration_81_copy_then_update_src.rs
rust/wal3/tests/test_k8s_integration_82_copy_then_update_dst.rs

This commit adds parity for copying the wal3 log.  This supports
forking.
Get test_fork to pass with this with wal3 enabled.
None for chroma.  wal3 interface not public.

[ENH]  Fork the wal3 log.

---

rust/frontend/sample_configs/tilt_config.yaml
rust/garbage_collector/src/helper.rs
rust/log-service/src/lib.rs
rust/log/src/grpc_log.rs
rust/wal3/src/copy.rs
rust/wal3/src/manifest.rs
rust/wal3/src/manifest_manager.rs
rust/worker/tilt_config.yaml

- use_alt_host_for_everything: true
- add tracing
N/A

[ENH]  Enable rust log service in CI and add some tracing.

---

rust/frontend/src/server.rs

- Auth was missing for forking. Can be enabled now after https://github.com/chroma-core/hosted-chroma/commit/f180572dc9d44e5a9d05a5b3a1f729ab55bfff86 
- ...
None

[ENH]: Enable auth for forking

---

rust/wal3/src/manifest.rs

In a prior PR I refactored the code to give a strongly-consistent S3 get.
I didn't use it.
Now tests are flaking, but this should fix it.
N/A

[BUG]  You must ask for strong consistency from S3 GET.

---

rust/load/src/data_sets.rs

I'm seeing the error, "invalid request: IDs lengths are different: got 9, expected 10".
I assume this is from the verifying data set as it's the only place this
string could be sprintf'd.
This de-dupes keys before fetch to avoid the service doing the deduping
and returning a short set.  I wasn't able to repro locally, but am in
staging, so this will pass tests and then get debugged in staging.
N/A

[BUG] Handle duplicates in chroma-load.

---

rust/load/src/data_sets.rs

It was turned to be sequential-only, but this breaks wal3 testing.
N/A

[ENH]  Restore chroma-load's random-upsert ability for Reference datasets.

---

rust/index/src/fulltext/types.rs
rust/index/src/fulltext/util.rs

The encoding/decoding method we use for packing a trigram into a u64 cannot handle null terminator bytes. E.x. `decode(encode(a\0b)) == a`. This resulted in index writers and the blockfile writer disagreeing on the ordering of mutations (index writers sorted with `a\0b`, the blockfile writer ordered with `a`).
To work around this, any trigrams containing null terminator bytes are now ignored. An (arguably cleaner) alternative would be to replace null terminator bytes with something like a space instead.
Added test currently fails on main.
Ran the `full_text` benchmark to confirm that no performance regression is introduced.
_Are all docstrings for user-facing APIs updated if required? Do we need to make documentation …

[BUG] ignore trigrams with null terminator byte when constructing full text index

---

rust/load/src/opentelemetry_config.rs

Remove sampling. Will leverage refinery for this instead.
These changes are untested. However, it is now using (mostly) the same setup code as the other chroma services (which are working). So, we can test in staging after this is merged.

[CLN] Use GRPC for chroma-load OTEL

---

chromadb/test/utils/test_result_df_transform.py
chromadb/utils/results.py
requirements_dev.txt

This PR adds support to convert both get and query results to pandas dataframes. As a byproduct, users can now get results in row format.

[ENH] Add support to convert Get/QueryResult to pandas dataframe

---

.github/workflows/release-javascript-client.yml

Since the JS client now uses optional dependencies that are platform specific, we can't use a checked-in lock file and `pnpm install --frozen-lockfile`, since the bindings platform-specific package installed by the test runners will not match the one generated on a dev's machine.
N/A

[CHORE] Fix JS release to support platform specific bindings

---

rust/worker/src/execution/orchestration/compact.rs

- There are valid cases for this log pull to fail, it is not an invariant violation as stated.
- If the log is failed to be updated with the latest compaction offset (Which is best-effort), but the sysdb was, the log may schedule a collection for compaction that has no records outstanding. This leads to hitting this case, which is valid. In the future we could repair the log.
- Forked collections will also run into this as the fork() call may copy the old log offset, but a compaction happens after, this leads to them disagreeing but progression is always forward, it manifests as the same issue above which is that the log is behind the sysdb.
- Keeping this as a `warn` because its worth monitoring this as it implies log …

[CLN] Warn on log pull failure instead of error

---

.github/workflows/_python-tests.yml
.github/workflows/pr.yml
chromadb/test/test_cli.py
rust/cli/src/commands/vacuum.rs

Speed up python CLI wrapper tests:
* Run tests directly instead of setting up the integration test environment.
* Previously, vacuum set its own timeout for SQLite connections, however now we have a default timeout of 1000 seconds (~17 minutes) on all connections. The last test in `test_cli` checks that we abort long standing vacuum operations (when the DB file is locked). To work around the 1000 timeout, added a `timeout` argument to the CLI command to override the default long timeout. The DB set up by the test would have been vacuumed in a matter of seconds.
N/A

[TST] Debug cli tests

---

rust/segment/src/sqlite_metadata.rs

replaces metadata group by and havign with distinct and where.
before:
after:

[ENH] replace group_by and having with distinct and where for local chroma

---

rust/worker/src/execution/orchestration/compact.rs

This PR cherry-picks the commit dd6d1768237e9be8b1d0916657a8008e5530a05d onto rc/2025-05-02. If there are unresolved conflicts, please resolve them manually.

[HOTFIX] applying PR #4435 to rc/2025-05-02

---

go/pkg/log/repository/log.go
go/pkg/log/repository/log_test.go
rust/frontend/src/impls/service_based_frontend.rs
rust/log/src/grpc_log.rs

- Adds exponential retry to coll.add(), coll.update() and coll.upsert() for duplicate key errors returned by postgres
- ...
None

[ENH]: Add retry for add, update and upsert

---

Tiltfile
k8s/test/load-service.yaml
rust/load/src/opentelemetry_config.rs

Make the trace exporter to export all INFO and above traces (not just ERROR).
Also, update load service tracing to use GRPC (to match our other services).
Ran locally via `tilt up`. Verified traces appear under `chroma-load` service in jaeger.
n/a

[ENH] Add load service to local dev tiltfile

---

rust/load/src/bin/chroma-load-start.rs
rust/load/src/lib.rs

This change updates chroma-load-start to read the APi key from the environment. It is a bit more secure than passing the API key via the process arguments, which is potentially readable by other processes on the system.
Tested locally via tilt.

[CLN] Pass Chroma API key via env var for chroma-load-start

---

go/pkg/log/server/server.go
idl/chromadb/proto/logservice.proto
rust/log-service/src/bin/chroma-inspect-dirty-log.rs
rust/log-service/src/lib.rs

To get ground truth on the dirty log, add a tool that can print it as it
gets interpreted in the 'get all to compact' call.
N/A

[ENH]  A route and tool to inspect the dirty log.

---

k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/rust-log-service.yaml

This PR changes the rust log service from a deployment to a stateful set
so that we can use the standard memberlist techniques with it.
tilt up works + CI
N/A

[ENH]  Change rust-log-service to a stateful set.

---

rust/wal3/src/manifest_manager.rs
rust/wal3/src/writer.rs
rust/wal3/tests/test_k8s_integration_99_ping_pong_contention.rs

If two wal3 instances try writing the same log, only one will succeed,
and the other will fail.  This can, under rare situtation, lead to a log
failing recovery due to contention, and thus failing to open.
Contention should be a transient thing and the log should handle it.
Included is a claude-written test that plays ping-pong between two log
writers in a coordinated fashion.
N/A

[BUG]  Catch a bug that causes wal3 to hang under contention.

---

rust/load/src/data_sets.rs

This change removes a misleading / incorrect event log message.
The cardinality value is actually computed by record_load, based on the largest contiguous chunk of records that have been loaded so far. We cannot assume the cardinality will increase by 100, just by loading in another chunk of size 100.
Untested

[BUG] Remove misleading log message

---

Cargo.lock
rust/log-service/Cargo.toml
rust/log-service/src/lib.rs
rust/wal3/src/manifest_manager.rs
rust/wal3/src/writer.rs
rust/wal3/tests/test_k8s_integration_99_ping_pong_contention.rs

Using foyer, add caching to the rust log service.  This caches parquet
fragments listed to be fetched to complete a call to pull_logs.
Caching isn't used for the dirty log or forking logs, just pull logs.
It gets populated by a key that is (collection_id, path), and then gets
immutably served from that point forward.
N/A

[ENH]  Add caching to rust log service.

---

chromadb/test/configurations/test_collection_configuration.py
rust/frontend/sample_configs/distributed.yaml
rust/frontend/sample_configs/tilt_config.yaml
rust/frontend/src/config.rs
rust/frontend/src/server.rs
rust/frontend/src/types/errors.rs
rust/types/src/collection_configuration.rs
rust/types/src/spann_configuration.rs

- Users can now set hnsw params without failing. This is to support migrations from local to cloud. Setting hnsw configuration when SPANN is enabled will only take the space config and use in the spann, others will be discarded in place of default spann configuration
- Even if they explicitly try to create hnsw index, we disallow it now
- Users can set spann configuration, validation on ranges already handled internally
- ...
None

[ENH]: When SPANN is enabled, route HNSW configuration to SPANN, remove enable_set_index_params

---

go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/coordinator_test.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/coordinator/table_catalog_test.go
go/pkg/sysdb/grpc/collection_service.go
go/pkg/sysdb/grpc/collection_service_test.go
idl/chromadb/proto/coordinator.proto
rust/sysdb/src/sysdb.rs
rust/types/src/api_types.rs

- N/A
- Adds a new RPC to the SysDB, `CountForks`, that returns the number of forks for a given collection.

[ENH] Add RPC on SysDB to get fork count for a collection

---

Cargo.lock
rust/load/Cargo.toml
rust/load/src/data_sets.rs

When the upsert operations are rate-limited, the "block" of 100 records in the operation is never inserted. Therefore, the cardinality of the test data set can never grow beyond the point of the failed (rate limited) upsert.
Also, when starting a new workload, we need to reset the cardinality and heap for the data set, so that it starts again from cardinality of 0.
Tested locally in tilt. Verified that the cardinality of the test data set continues to grow, even after hitting rate limit errors on previous upsert attempts. Also verified that the cardinality is reset to 0 when initializing a new workload.

[BUG] Retry chroma-load upserts when rate limited

---

rust/cli/src/commands/mod.rs
rust/cli/src/commands/webpage.rs
rust/cli/src/lib.rs
rust/cli/src/utils.rs

Refactor web browser commands (open docs and discord) to their own module.
N/A

[CLN] CLI - Refactor webbrowser commands

---

rust/load/src/bin/chroma-load-start.rs
rust/load/src/lib.rs

chroma-load-start checks the environment for an auth key.  Make it optional and push the optionality down.
CI
N/A

[ENH][chroma-load]  If no api key is present in env, do not auth.

---

k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/values.yaml

This adds defaults to values.yaml that make k8s instantiate the log with a cache dir mounted.
CI + eyes.
N/A

[ENH] Configure the cache to have a hostPath and mountPath for log service.

---

chromadb/api/async_client.py
chromadb/api/client.py
chromadb/test/configurations/test_collection_configuration.py
clients/js/packages/chromadb-core/src/ChromaClient.ts

We had previously decided that providing embedding functions would now be done via the config. This PR makes it so that embedding functions, even if provided via the existing embedding function parameter, would still be routed to the config in the case where the user does not specify an EF in the config. So priority would be
1. config provided EF
2. parameter level EF
- ...
- ...

[ENH] write embedding function to config if provided

---

rust/frontend/src/impls/utils.rs

This PR disallows setting an empty string for an ID
https://github.com/chroma-core/chroma/issues/4346
---
This PR adds validation to prevent empty string IDs during the record addition process. It modifies the Rust codebase to reject IDs with zero characters by adding a new error type and appropriate validation check, addressing issue #4346.
**Key Changes:**
• Added a new `EmptyId` error type to the `ToRecordsError` enum
• Added validation to check for empty IDs in the `to_records` function
• Added comprehensive test cases to verify the validation behavior …

[ENH] Disallow empty string ids during add

---

rust/wal3/tests/test_k8s_integration_99_ping_pong_contention.rs

This should make it impervious to flakes.  What I saw was 26 in 2 min.
Changing to 20 in 3 min as the failure.
N/A

[BUG]  Adjust the ping-pong test for wal3 to timeout longer and run less.

---

rust/frontend/src/impls/service_based_frontend.rs
rust/log/src/config.rs
rust/log/src/grpc_log.rs
rust/log/src/local_compaction_manager.rs
rust/log/src/log.rs
rust/worker/benches/load.rs
rust/worker/src/compactor/scheduler.rs
rust/worker/src/execution/operators/fetch_log.rs
rust/worker/src/execution/operators/register.rs
rust/worker/src/execution/orchestration/compact.rs
rust/worker/src/server.rs

This adds an additional shunt path where a tenant can be listed for
access to the alt log.  This should make it possible to move a smoke
test tenant to the log.
N/A

[ENH]  Allow collections to shunt to the alt log by tenant.

---

rust/frontend/src/impls/service_based_frontend.rs
rust/log-service/src/lib.rs
rust/log/src/config.rs
rust/log/src/grpc_log.rs
rust/log/src/local_compaction_manager.rs
rust/log/src/log.rs
rust/worker/benches/load.rs
rust/worker/src/compactor/scheduler.rs
rust/worker/src/execution/operators/fetch_log.rs
rust/worker/src/execution/operators/register.rs
rust/worker/src/execution/orchestration/compact.rs
rust/worker/src/server.rs

This allows us to construct a persistent cache.  The config would fail
to construct a cache otherwise.
N/A

[ENH][rust-log-service]  Use the persistent cache.

---

rust/frontend/src/quota/mod.rs
rust/frontend/src/server.rs
rust/sysdb/src/sysdb.rs
rust/sysdb/src/test_sysdb.rs

- ...
- Implements the `count_forks` method on `TestSysDb`
- Updates quotas to support a `UsageType::NumForks` `Action::ForkCollection`
- Updates `fork_collection` API to enforce quotas on `Action::ForkCollection`
---
This PR implements the `count_forks` method in the `TestSysDb` class and adds fork collection support to the quota system. The implementation returns a fixed value of 10 for testing purposes, and changes the return type from `u64` to `usize` for consistency. …

[CHORE] Support count_forks/num_forks in TestSysDB/Quotas

---

rust/log/src/log.rs

This will trace the return value of every log call when it takes an Err(_) variant.
N/A

[ENH]  Display errors for all log calls.

---

rust/frontend/src/quota/mod.rs

- Removed the num regex predicates
- Added the regex pattern length with a default of 0
- ...
None

[ENH]: Add quota on regex pattern length

---

Cargo.lock

I ran `cargo update PACKAGE` for each package in dependabot that's rust.
Lockfile changes only.
CI
N/A

[BUG]  Bump buggy deps to satisfy dependabot

---

chromadb/api/types.py
chromadb/base_types.py

This PRs allows setting metadata to None in the python client to allow deleting metadatas after creation.
- ...
- ...
---
This PR enhances the Python client by allowing metadata values to be set to None, which enables users to delete metadata after creation. The change modifies the metadata type definition and validation logic to accept None as a valid value type.
*This summary was automatically generated by @propel-code-bot*

[ENH] Make metadata optional to allow deleting metadata in python client

---

.github/actions/docker/action.yaml
.github/workflows/_build_release_container.yml
.github/workflows/_go-tests.yml
.github/workflows/_python-tests.yml
.github/workflows/_rust-tests.yml
.github/workflows/pr.yml
Tiltfile
docker-compose.yml
rust-toolchain.toml
rust/Dockerfile

This PR unifies the 5 separate Rust Dockerfiles into 1. This results in substantially faster builds as well as being cleaner and easier to maintain.
After this PR, the old Rust Dockerfiles are no longer used in this repo but I'm keeping them around until all downstream consumers are updated to use the new `rust/Dockerfile`.
I tested the difference in (local) speed with 3 scenarios. For each one, I measured the time from the start of the build to when all services in Tilt were green.
|                                                    | before | after | speedup |
|----------------------------------------------------|--------|-------|---------|
| cold `tilt up`                                     | 7m14s  | 3m55s | 1.8x    |
| new comment in `rust/types/src/api_types.rs`       | 2m2s   | …

[BLD]: unify Rust Dockerfiles for faster builds

---

rust/frontend/src/quota/mod.rs

Adds an optional `message` to `QuotaExceededError`. This feature allows the quota system to give clients more info about an error.
---
This PR enhances the QuotaExceededError struct by adding an optional 'message' field, allowing the quota system to provide more detailed information to clients when quota limits are exceeded. The implementation uses the Validate trait to ensure non-empty message strings and includes comprehensive test coverage.
**Key Changes:**
• Added an optional `message` field to QuotaExceededError struct
• Updated the Display implementation to include the message when present
• Added validation to ensure non-empty message strings
• Added comprehensive tests for the new functionality
**Affected Areas:**
• rust/frontend/src/quota/mod.rs
*This summary was automatically …

[ENH] QuotaExceededError can include an optional message

---

go/pkg/sysdb/coordinator/table_catalog.go
rust/frontend/src/quota/mod.rs
rust/frontend/src/server.rs

- Default hardcoded `NUM_FORKS` value 1000000 --> 10000
- Send fork collection name to quota enforcer
- Remove hardcoded fork tree check in SysDB
- N/A

[CLN] fork_collection quota cleanup

---

.github/workflows/release-chromadb.yml

https://github.com/chroma-core/chroma/pull/4479 added auth against DockerHub for higher rate limits when pulling, but I forgot to update the release workflow to properly propogate the secrets down.

[BLD]: fix secret usage for Go test reusable workflow

---

Cargo.lock
rust/types/Cargo.toml
rust/types/src/regex/literal_expr.rs

- N/A
- Implement the literal provider interface and default impls, which allows evaluation of literal expression to a set of documents.
---
This PR introduces a new NgramLiteralProvider trait and implementation that enables efficient evaluation of literal expressions against document collections. The implementation uses n-gram based matching to find documents containing specific literal patterns, with support for handling compound expressions (concatenation and …

[ENH] Implement literal provider

---

rust/blockstore/src/arrow/block/types.rs
rust/blockstore/src/arrow/blockfile.rs
rust/blockstore/src/memory/reader_writer.rs
rust/blockstore/src/types/reader.rs
rust/blockstore/tests/blockfile_writer_test.rs
rust/index/src/fulltext/types.rs
rust/index/src/metadata/types.rs
rust/index/src/spann/types.rs
rust/segment/src/blockfile_record.rs
rust/segment/src/distributed_spann.rs
rust/worker/Cargo.toml
rust/worker/benches/regex.rs
rust/worker/src/execution/operators/filter.rs
rust/worker/src/execution/operators/source_record_segment.rs

- Return prefix as part of `get_range` method
- Wire up regex evaluation process in filter operator
---
**Implementing Regex Matching in Filter Operator**
This PR implements regex evaluation within the filter operator, enabling document-level regex matching. It changes blockfile reader APIs to expose prefixes as part of query results and leverages full-text indexes for more efficient regex evaluation. The implementation includes optimizations for exact pattern matching that …

[ENH] Wireup regex in filter operator

---

go/pkg/log/server/server.go

Adds a log line.
Compiles locally.
`cargo test` for rust
N/A

[CHORE]  Add a log line to go server to see if its scout logs is called (#4514)

---

chromadb/api/types.py
chromadb/base_types.py
idl/chromadb/proto/chroma.proto
rust/index/src/fulltext/types.rs
rust/segment/src/sqlite_metadata.rs
rust/segment/src/test.rs
rust/types/src/metadata.rs
rust/types/src/regex/hir.rs
rust/types/src/regex/literal_expr.rs
rust/types/src/where_parsing.rs
rust/worker/benches/regex.rs
rust/worker/src/execution/operators/filter.rs

- Renames `$matches` and `$not_matches` to `$regex` and `$not_regex`
- N/A

[CLN] Rename $matches to $regex

---

rust/load/src/lib.rs

Remove the parent "workload" trace for the entire workload. It's too long-lasting, and contains too many sub-spans. Instead, generate a "step" root trace for each workload step. Events for each workload step will be associated with the step's root trace.
This will make spans easier to read, and debug.
Tested locally via tilt and jaeger.
N/A

[ENH] Reorganize load-service traces

---

rust/cache/src/foyer.rs
rust/cache/src/lib.rs

- /
- `contains` in foyer is an approximate contains operation (for the disk cache) and has better performance. Additionally, it does not affect lru bookeeping. Prefetching currently uses `get()` for its `cached()` check. This change introduces `may_contain` which is a potentially false-positive check on if a cache contains a key. 
Basic unit test of proxied functionality. 
None

[ENH] Expose may_contain for disk cache, use in prefetch

---

rust/index/src/fulltext/types.rs

The full-text reader had a bug where it used the positions of tokens to determine whether the tokens appeared sequentially, rather than using the byte offset of tokens. This was problematic because the index stores byte offsets. Since Unicode characters can be many bytes wide, we cannot guarantee that the stored byte offsets are strictly consecutive.
Added a test that fails on main.
n/a

[BUG]: use byte offset in full-text reader rather than token position

---

rust/cache/src/foyer.rs
rust/frontend/sample_configs/distributed.yaml
rust/frontend/sample_configs/tilt_config.yaml
rust/worker/chroma_config.yaml
rust/worker/tilt_config.yaml

- All the foyer caches are named as "foyer" currently. This clobbers the metrics since each metric is prefixed with "<name>_.*". Introduces name in the config and passes it down to the cache builder
- ...
None

[ENH]: Add name to various foyer caches

---

go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/coordinator_test.go
go/pkg/sysdb/coordinator/model/collection.go
go/pkg/sysdb/coordinator/model_db_convert.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/coordinator/table_catalog_test.go
go/pkg/sysdb/grpc/collection_service.go
go/pkg/sysdb/metastore/db/dao/collection.go
go/pkg/sysdb/metastore/db/dbmodel/collection.go
go/pkg/sysdb/metastore/db/dbmodel/mocks/ICollectionDb.go
idl/chromadb/proto/coordinator.proto
rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/sysdb/src/sysdb.rs

Includes several updates to the `ListCollectionsToGc` gRPC method:
- returns the lineage file path, if present
- only returns the root collection for fork trees
- accepts an optional tenant parameter for test isolation.
Because `ListCollectionsToGc` now returns collections that are part of fork trees, I also updated GC to skip collections with a populated `lineage_file_path` (i.e. the root collection in a fork tree).
Added tests covering the fork tree grouping and GC behavior on forked collections.
n/a

[ENH]: `ListCollectionsToGc` returns lineage file path, group by fork tree, accept optional tenant for filtering

---

go/cmd/logservice/main.go
go/pkg/grpcutils/service.go
go/pkg/sysdb/grpc/server.go

The max gRPC payload/response sizes were updated for the Rust log client, but were never updated for the log service. So the `PushLogs` method was still failing when the request was > 4MB.
n/a

[BUG]: increase max payload size of log service (Go)

---

rust/load/src/bit_difference.rs

If the bit-difference workload is used for pure-upsert workloads it will
violate quota.  This PR shrinks the batch size to just one cluster at a
time.  By construction clusters fit a batch.
N/A

[ENH]  Fix 422 Unprocessable Entity error in Chroma Load

---

rust/frontend/src/quota/mod.rs

- Reduce default NUM_FORKS quota from 10000 to 256
- ...

[CHORE] Reduce default NUM_FORKS quota rule value

---

go/cmd/logservice/main.go
go/pkg/grpcutils/service.go
go/pkg/sysdb/grpc/server.go

This reverts commit 3028a39384589393489ac7ece9dedf38a0eea663.
After we deployed this commit, we lost metrics for log-service, so we suspect it has something to do with it. I will re-enable the payload size fix one way or the other, but want to get back to working observability for the time being.

Revert "[BUG]: increase max payload size of log service (Go) (#4534)"

---

chromadb/test/distributed/test_sanity.py
chromadb/test/property/test_embeddings.py

It would add and delete items in such a way that it's theoretically
possible to have a version increase before checking the current version.
Waiting for "current", then, actually begs the question and waits for
itself.
N/A

[CHORE]  Fix test-embeddings.py and test_sanity

---

clients/js/package.json
clients/js/packages/chromadb-client/package.json
clients/js/packages/chromadb-core/package.json
clients/js/packages/chromadb-core/src/embeddings/DefaultEmbeddingFunction.ts
clients/js/packages/chromadb/package.json

The Default EF in javascript incorrectly sets the config name to model_name, when the schema requires model. This PR fixes that.

[BUG] Default embedding function in JS did not create the correct config dict

---

rust/worker/src/execution/operators/filter.rs
rust/worker/src/execution/operators/projection.rs

- Add temporary traces to log filter arguments. We suspect certain filters are not handled properly.
- Add projection error variant for clarity
- N/A

[DBG] Add temporary trace for filter argument

---

rust/load/src/bin/chroma-load-start.rs
rust/load/src/data_sets.rs
rust/load/src/lib.rs
rust/load/src/rest.rs

This exposes the already-existing ability to shove a data set into
chroma-load.  The `/start` endpoint now takes a json blob xor a data set
name.  If the `/start` endpoint is given just the name, it resorts to
the old behavior so as not to break anything.
If given a JSON blob, it will interpret that as the data set and try to
run it.  Right now the only supported workloads would be to pass a blob
that's pre-configured, or to pass a `References` struct serialized to a
data set.  The chroma-load-start command has been updated to facilitate
this.

[ENH]  Support custom data sets for chroma load.

---

go/cmd/logservice/main.go

This restores the core functionality we were hoping to add in #4534 which is increasing the gRPC payload size. Instead of using the methods from the `grpcutils` package, this just sets the option in the existing setup so that we hopefully don't break whatever voodoo is keeping metrics collection working.
- See #4534
- See #4534
I ran `make test` locally, the build succeeds, but our local tests are broken for some reason. Relying on CI so that I don't have to debug yet another orthogonal issue.

[BUG] Restore increase max payload size of log service (Go)

---

go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/coordinator_test.go
go/pkg/sysdb/coordinator/model/segment.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/grpc/collection_service.go
go/pkg/sysdb/grpc/proto_model_convert.go
go/pkg/sysdb/grpc/segment_service.go

Prior to this fix, `v0` in the version file for forked collections was missing the segment file paths from the source collection.
There was a similar bug where if segment file paths were provided during the creation of a new collection, those file paths would also be absent from `v0` in the version file (we currently never provide segment file paths upon creation, but seemed good to fix as well).
Updated existing Go integration tests to check the created version file.
n/a

[BUG]: v0 in version file for forked collection missing segment file paths from source collection

---

rust/index/src/fulltext/types.rs
rust/types/src/regex/literal_expr.rs
rust/worker/src/execution/operators/filter.rs
rust/worker/src/execution/operators/limit.rs

- A particular order of operations involving deletes on the log causes empty posting list for (token, doc) pairs of the deleted doc. Regex on a single trigram does not skip empty posting lists thereby returning documents that don't exist.
- Fixed regex search algorithm for this case.
- Fixed FTS algorithm to skip empty posting lists
- ...
Added unit test
None

[BUG]: Regex search returning documents that are deleted

---

rust/tracing/src/init_tracer.rs

- Adds `hosted-frontend` to stdout layer in tracing
- ...

[BUG] Add hosted-frontend to OTel stdout layer

---

go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/coordinator_test.go
go/pkg/sysdb/coordinator/model/collection.go
go/pkg/sysdb/coordinator/model_db_convert.go
go/pkg/sysdb/coordinator/model_db_convert_test.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/coordinator/table_catalog_test.go
go/pkg/sysdb/grpc/tenant_database_service_test.go
go/pkg/sysdb/metastore/db/dao/collection.go

- It can happen that compaction flushes to sysdb with empty file paths. This happens when there are no changes to the segments after applying the logs.
- The sysdb handles this by keeping the previous segment file paths
- However versioning missed handling this case in the version file. This led to creation of versions with empty file paths in the version file.
- Consequently, after GC deletes all old versions and only leaves this version with empty file paths, there is no data on S3.
- Added a local test with mock s3
None

[BUG]: Handle version file creation with empty file paths

---

rust/segment/src/sqlite_metadata.rs

Move FTS to subquery approach for improved performance, and use unions in the case of int and float metadata, and replace is true uses with is not null to utilize db indexes
before (0.6.3):
after:

[ENH] For local: use subquery for FTS, unions for int & float metadata expr, is true -> is not null

---

Cargo.lock
rust/log-service/Cargo.toml
rust/log-service/src/lib.rs

If a collection on the rust-based log has more than a
configuration-configurable number of records, shut it down hard no
matter what.  This happens when compaction gets backlogged.  By default,
no more than 1_000_000 can be on the log uncompacted.  This is just a
placeholder that we can change.
N/A

[ENH]  Add a safety cutoff to the rust log service.

---

clients/js/packages/chromadb-core/src/ChromaFetch.ts
clients/js/packages/chromadb-core/src/Errors.ts

- Handles the new quota errors (422 code and message starts with `Quota exceeded`) and returns a `ChromaQuotaExceededError`. The new error type includes the quota message where before this threw a generic Error without any quota specific messaging.
- None
None

[ENH] Add handling for ChromaQuotaExceededError

---

chromadb/utils/embedding_functions/instructor_embedding_function.py
chromadb/utils/embedding_functions/sentence_transformer_embedding_function.py
chromadb/utils/embedding_functions/text2vec_embedding_function.py

Some embedding functions allow the user to pass a path for their embedding function. We should not be validating that the user is trying to update the model path, as that could be too restrictive.

[CHORE] Remove validation on ef config update for model path

---

rust/wal3/examples/wal3-bootstrap-reasoner.rs

The space of cases I have to handle:
panic(BenignRace, AlreadyInitialized, Uninitialized) -> cannot double-initialize manifest
panic(BenignRace, AlreadyInitialized, Failure) -> cannot double-initialize manifest
panic(BenignRace, AlreadyInitialized, Success) -> cannot double-initialize manifest
panic(Success, AlreadyInitialized, Uninitialized) -> cannot double-initialize manifest
panic(Success, AlreadyInitialized, Failure) -> cannot double-initialize manifest
panic(Success, AlreadyInitialized, Success) -> cannot double-initialize manifest
panic(BenignRace, Uninitialized, Failure) -> failed to install recovered manifest
panic(BenignRace, Success, Failure) -> failed to install recovered manifest
panic(Success, Uninitialized, Failure) -> failed to install recovered manifest
panic(Success, …

[ENH]  Add a tool to reason through the state space of bootstrap.

---

rust/wal3/examples/wal3-bootstrap-reasoner.rs
rust/wal3/src/reader.rs
rust/wal3/src/writer.rs
rust/wal3/tests/test_k8s_integration_83_bootstrap.rs
rust/wal3/tests/test_k8s_integration_84_bootstrap_empty.rs

This adds a "bootstrap" call to wal3 that copies the data semi-atomically.  It is reasoned to be
safe to do concurrent with all other log operations, but may leave a FragmentSeqNo(1) lying around
in the event that a log is initialized at the same time it's bootstrapping.  This should never
happen in our system so thankfully we can just leave the hole.
See #4558 for the reasoning.
N/A

[ENH] Bootstrap a wal3 log from existing content.

---

.github/actions/python/action.yaml

Reduces Python setup time by >10x from 1-2m to 10s by replacing pip with uv (in pip compatibility mode) and removing an unnecessary apt step.
Workflows pass.
n/a

[BLD]: use uv in CI

---

rust/types/src/regex/literal_expr.rs
rust/types/src/regex/mod.rs
rust/types/src/where_parsing.rs
rust/worker/src/execution/operators/filter.rs

- Remove the regex requirement that it must contain at least three literals
- Short circuit on pattern that can match empty string
- N/A

[ENH] Remove custom regex validation

---

rust/frontend/src/auth/mod.rs
rust/frontend/src/impls/service_based_frontend.rs
rust/frontend/src/server.rs

- N/A
- Adds an auth path that allows for sending granular collection info

[ENH] Auth path with collection info

---

go/pkg/log/server/server.go
idl/chromadb/proto/logservice.proto
rust/log-service/src/lib.rs
rust/wal3/src/manifest.rs

This allows one scout-logs request to know everything that's on the log.
It's necessary for the range to be everything pull-logs can access.
N/A

[ENH]  Add a lower bound to the scout logs response.

---

go/pkg/log/server/server.go
idl/chromadb/proto/logservice.proto
rust/log-service/src/lib.rs

This updates the IDL for the log service to have two new methods:
SealLog and MigrateLog.  They each take a collection ID and trigger the
two phase transitions for the go-to-rust migration that's coming.
IDL includes comments.

[ENH]  Add RPC endpoints for sealing and migrating logs.

---

Cargo.lock
rust/log-service/src/lib.rs
rust/log/src/grpc_log.rs
rust/worker/tilt_config.yaml

Following the rollout ADR, this will encode table to go
classic->transitioning->transitioned.
|            | **inactive**  | **active**   |
|------------|---------------|--------------|
| **open**   | classic       | BUG          |
| **sealed** | transitioning | transitioned |
N/A

[ENH]  Add feature to the rust log service to proxy the go log service.

---

go/pkg/log/repository/log.go
go/pkg/log/server/server.go
go/pkg/log/store/db/queries.sql.go
go/pkg/log/store/queries/queries.sql
idl/chromadb/proto/logservice.proto
rust/log-service/src/bin/chroma-inspect-log-state.rs
rust/log-service/src/bin/chroma-migrate-log.rs
rust/log-service/src/bin/chroma-seal-go-log.rs
rust/log-service/src/bin/log.rs
rust/log-service/src/lib.rs
rust/log/src/grpc_log.rs

- Implement the `migrate_log` endpoint.
- Add tool for sealing the go log.
- Add tool for triggering the go->rust migration (if there is no write to trigger it)
Tested in tilt manually.  Working on a plan to test in depth.
N/A

[ENH]  Tools to manually seal and migrate the log.

---

idl/chromadb/proto/logservice.proto
rust/log-service/src/lib.rs
rust/log/tests/log-offsets.rs

The rust log service handles cursors slightly differently from the go
log service.  Add two tests that are nearly identical to sus out
divergences in behavior between the two systems.
Add test.  Run test.  Leave the rest to CI.
N/A

[BUG]  Add a test that irons out an OBO in the rust log/go log migration path.

---

.github/actions/docker/action.yaml
.github/actions/rust/action.yaml
.github/workflows/_build_release_pypi.yml
.github/workflows/_python-tests.yml
.github/workflows/_rust-tests.yml
rust-toolchain.toml

Cleans up our workflows by removing the unused Datadog integration, and substantially speeds up Rust-based workflows by using the `rust-cache` action instead of sccache & caching the Rust toolchain. Times below are total Rust setup & compile time:
|                                               | before | after | speedup |
|-----------------------------------------------|--------|-------|---------|
| `test-rust-bindings`                          | 1m57s  | 1m11s | 1.6x    |
| `test-rust-single-node-integration`           | 2m45s  | 1m8s  | 2.4x    |
| `test-rust-single-node-integration` (Windows) | 6m36s  | 58s   | 6.8x    |
| `test-rust-thin-client`                       | 2m43s  | 1m17s | 2.1x    |
| `test-rust-bindings-stress`                   | 1m42s  | 1m12s | 1.4x    |
| …

[BLD]: remove Datadog from CI, use blacksmith for Rust cache

---

Cargo.toml

This change significantly speeds up dev builds. Timings when adding a comment to a specific file and observing the incremental build time in `tilt`:
|                                            | before | after | speedup |
|--------------------------------------------|--------|-------|---------|
| `rust/sqlite/src/db.rs`                    | 41s    | 18s   | 2.3x    |
| `rust/log-service/src/state_hash_table.rs` | 15s    | 9s    | 1.7x    |
`split-debuginfo = unpacked` is the default on macOS, however because we build inside Docker the Linux default (off) is used instead.
_Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the [docs section](https://github.com/chroma-core/chroma/tree/main/docs/docs.trychr …

[BLD]: significantly speed up dev builds

---

rust/frontend/src/config.rs
rust/frontend/src/impls/service_based_frontend.rs
rust/log/src/grpc_log.rs
rust/log/src/log.rs
rust/python_bindings/src/bindings.rs

I want a way to make a tenant bound to the new log for all collections,
no matter when they are created.  One way to handle this would be to
make the log service tenant-aware and have it do the selection
intelligently on the fly.  This would require threading the tenant
information in the proto and trusting it all the way down.
The alternative taken in this PR is to deal with it entirely from the
frontend by sealing the collection on the critical path of collection
creation, opting to trace an error rather than fail the op entirely if
sealing the log fails.
CI
N/A

[ENH]  Add a way to seal a tenant's Go log immediately upon collection creation.

---

chromadb/test/distributed/test_log_failover.py
go/pkg/log/repository/log.go
go/pkg/log/store/db/queries.sql.go
go/pkg/log/store/queries/queries.sql

Because there would be no row in the DB, sealing the collection fails to
update is_sealed to true.   Add a fallback to insert a sealed row if the
update fails.  Add a test to capture that this works.
CI.  Ran the new test locally.
N/A

[BUG]  Sealing a collection right away fails.

---

rust/worker/src/compactor/scheduler.rs

This trace says, "Error", but is recoverable.  So warn instead.

[CHORE] Downgrade a trace to warn status and document.

---

Cargo.lock
Cargo.toml
rust/frontend/Cargo.toml
rust/frontend/src/lib.rs
rust/frontend/src/server.rs
rust/frontend/src/tower_tracing.rs
rust/frontend/src/traced_json.rs
rust/tracing/src/init_tracer.rs

- Adds a new TracedJson handler which can separately trace the request buffering time, as well as the json parse time.
- Unifies all tracing inside of handlers to be structured, I used the existing pattern of events, since some things cannot be known until we parse the body.
- None
I manually verified the body length error, its the same as before
I checked the traces in jaeger, they are as expected
None

[ENH] Add TracedJson handler, unify and add detail to request tracing

---

rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/system/src/execution/orchestrator.rs
rust/worker/src/execution/operators/spann_fetch_pl.rs
rust/worker/src/execution/orchestration/compact.rs
rust/worker/src/execution/orchestration/count.rs
rust/worker/src/execution/orchestration/get.rs
rust/worker/src/execution/orchestration/knn.rs
rust/worker/src/execution/orchestration/knn_filter.rs
rust/worker/src/execution/orchestration/spann_knn.rs

- Traces become very noisy when prefetch is a part of the request span. Removed it and made its own independent root
- Also, pipeline the spans of fetch posting list with bf posting list
- ...
None

[ENH]: Detach prefetch span from the rest of query

---

.github/actions/rust/action.yaml

The `build-sdist` release job [is failing](https://github.com/chroma-core/chroma/actions/runs/15193462410/job/42739524860) because it's using the version of Rust provided in the runner image (1.80) instead of the version we install with rustup (1.81). This change sets the global default to 1.81, from our `rust-toolchain.toml`, so it should resolve the build issue.

[BLD]: fix: set default channel of rust from rust-toolchain.toml

---

go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/coordinator_test.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/grpc/collection_service.go
go/pkg/sysdb/metastore/db/dao/collection.go
go/pkg/sysdb/metastore/db/dbmodel/collection.go
go/pkg/sysdb/metastore/db/dbmodel/mocks/ICollectionDb.go
idl/chromadb/proto/coordinator.proto
rust/sysdb/src/sysdb.rs
rust/sysdb/src/test_sysdb.rs
rust/types/src/api_types.rs

Needed when garbage collecting a collection in a fork tree, because we need to read the version files of all other nodes in the tree.
Added a test.
n/a

[ENH]: add batch get version file paths method to Sysdb

---

Cargo.lock
Cargo.toml
rust/garbage_collector/Cargo.toml
rust/garbage_collector/src/construct_version_graph_orchestrator.rs
rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/garbage_collector/src/lib.rs
rust/garbage_collector/src/operators/fetch_lineage_file.rs
rust/garbage_collector/src/operators/fetch_version_file.rs
rust/garbage_collector/src/operators/get_version_file_paths.rs
rust/garbage_collector/src/operators/mod.rs
rust/storage/src/lib.rs

Adds an orchestrator to construct the version graph for all collections in a fork tree to be used by garbage collection.
Added tests for new orchestrator.
n/a

[ENH]: add orchestrator to construct version graph for garbage collection

---

rust/log-service/src/lib.rs

The following sequence triggers the bug:
- Insert [1, 100] to the log.
- Begin compacting [1, 84].
- Compaction finishes and sets the compaction log offset to 84 in the
narrow window between the scout_logs call and the
update_collection_log_offset in effectuate_log_transfer.
- Effectuate log transfer finishes and tries to set it to 1.
CI; always, CI.
N/A

[BUG]  Synchronize the update_collection_log_offset call w.r.t.  effectuate_log_transfer.

---

rust/garbage_collector/src/operators/compute_versions_to_delete_from_graph.rs
rust/garbage_collector/src/operators/mod.rs

Adds an operator to compute which versions to garbage collect from a version graph. Intended to replace `rust/garbage_collector/src/operators/compute_versions_to_delete.rs`.
Added new tests for operator.
n/a

[ENH]: add operator to compute versions to garbage collect from version graph

---

rust/blockstore/src/arrow/provider.rs
rust/garbage_collector/src/operators/list_files_at_version.rs
rust/garbage_collector/src/operators/mod.rs

Does what the title says. Given a version file and a version, the operator constructs a complete list of files used by the collection version (including block files by traversing all sparse indices).
Tested in the next PR.
n/a

[ENH]: add operator for garbage collection to list all files used by collection version

---

rust/frontend/src/server.rs

Closes #4620
- Adds support for `cors_allow_origins: ["*"]` and prevents Chroma from panicking when users supply a wildcard 

[ENH]: Adds support for CORS wildcard origins

---

chromadb/api/models/AsyncCollection.py

- `tenant` and `database` were not being sent in `AsyncCollection.modify()`, resulting in auth issues (it was present as of https://github.com/chroma-core/chroma/pull/2982).
- ...

[BUG] Send tenant/database in AsyncCollection.modify()

---

Cargo.lock
chromadb/test/property/test_filtering.py
rust/segment/src/sqlite_metadata.rs
rust/sqlite/Cargo.toml
rust/sqlite/src/config.rs
rust/worker/benches/regex.rs

- N/A
- Support regex filtering for local chroma

[ENH] Support regex for local Chroma

---

chromadb/api/async_fastapi.py
chromadb/api/base_http_client.py
chromadb/api/fastapi.py

- By default Chroma Cloud allows keepalive (we use HAProxy and it is on by default) and uses the http-request timeout if the keepalive timeout is not set - which for us is 50s. This raises the keepalive timeout from default 5s to < the haproxy timeout. We choose to not make this configurable for now, since the bottleneck will be the downstream config. This at least allows reusing the connection in a larger window
- None
None

[PERF] Tune keepalive for chroma cloud

---

rust/garbage_collector/src/construct_version_graph_orchestrator.rs
rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs
rust/garbage_collector/tests/proptest_helpers/garbage_collector_reference.rs
rust/sysdb/src/test_sysdb.rs
rust/worker/src/execution/orchestration/compact.rs

Adds a defensive check that validates that the current version is v0 if there are no file paths.
Added a test.
n/a

[ENH]: add validation during garbage collection for empty file paths

---

go/pkg/sysdb/coordinator/table_catalog.go

Prior to this change, the `was_created` flag was not correctly propagated up to the caller of `createCollectionImpl()`. This resulted in two concurrent create collection requests with `get_or_create: true` creating duplicate segments.
Did not add a new test.
n/a

[BUG]: don't create duplicate segments for collection under concurrent get_or_create requests

---

k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/rust-log-service.yaml

This PR properly sets my_member_id for rust-log-service nodes.
I bumped to two replicas and observed the log of the second one say
this:
From the log:  my_member_id: rust-log-service-1
N/A

[BUG]  Use the right path for my_member_id in rust-log-service.

---

rust/log-service/src/lib.rs

This line is logged once per collection on the dirty log.
I removed a line, relying upon CI.
N/A

[ENH] Cleanup the single most spammy log line in rls.

---

rust/segment/src/blockfile_metadata.rs
rust/types/src/regex/hir.rs
rust/types/src/regex/literal_expr.rs
rust/types/src/strategies.rs

- Added a few unit tests for the literal expr impl
- Added a basic proptest for ascii regex patterns
- N/A

[TST] Regex testing

---

go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/grpc/collection_service.go
go/pkg/sysdb/grpc/tenant_database_service.go
go/pkg/sysdb/grpc/tenant_database_service_test.go
go/pkg/sysdb/metastore/db/dao/database.go
go/pkg/sysdb/metastore/db/dbmodel/database.go
idl/chromadb/proto/coordinator.proto
rust/sysdb/src/sysdb.rs
rust/types/src/api_types.rs

Databases are now always soft deleted instead of being hard deleted. Databases are hard deleted when the new `FinishDatabaseDeletion` method is called (the garbage collector calls this in the next PR).
Updated existing test to cover soft delete behavior.
n/a

[ENH]: soft delete databases, add `FinishDatabaseDeletion` gRPC method to hard delete databases

---

rust/log/src/grpc_log.rs

One path is timing out in staging.  Add tolerance for that and some
debugging.
Compiles

[ENH] Robustly handle errors on the compaction path of the log.

---

chromadb/api/collection_configuration.py
chromadb/api/models/CollectionCommon.py
chromadb/api/rust.py
chromadb/api/segment.py
chromadb/db/impl/grpc/server.py
chromadb/db/mixins/sysdb.py
chromadb/proto/convert.py
chromadb/test/configurations/test_collection_configuration.py
chromadb/test/property/invariants.py
chromadb/types.py
chromadb/utils/embedding_functions/baseten_embedding_function.py
chromadb/utils/embedding_functions/cloudflare_workers_ai_embedding_function.py
chromadb/utils/embedding_functions/cohere_embedding_function.py
chromadb/utils/embedding_functions/google_embedding_function.py
chromadb/utils/embedding_functions/huggingface_embedding_function.py
chromadb/utils/embedding_functions/jina_embedding_function.py
chromadb/utils/embedding_functions/openai_embedding_function.py
chromadb/utils/embedding_functions/roboflow_embedding_function.py
chromadb/utils/embedding_functions/together_ai_embedding_function.py
chromadb/utils/embedding_functions/voyageai_embedding_function.py

This PR fixes a bug where it warns users if the configuration is not deserializable rather than raising an error, giving the users an empty config. Now, it raises an error if the configuration is not deserializable. This will only happen when the client is ahead of the server, which we do not need to support.
EF's from the config are now lazily loaded. only when ._embed is invoked from the model is it tried to be built, and will take precedent over the provided ef.
This also fixes a bug with list_collections, where if the user tries to load collections without the proper embedding function parameters set up, like api key env var, etc it would throw an hnsw and spann not configured error, which is not the root cause. instead, it will now load only the configuration_json, and at embed time …

[BUG] Raise Error when can't deserialize configuration json from server, lazily load ef on CollectionModel, warn on api_key

---

rust/blockstore/src/arrow/blockfile.rs
rust/blockstore/src/arrow/sparse_index.rs
rust/blockstore/src/types/reader.rs

- N/A
- Implements blockfile prefetch by prefix

[ENH] Prefetch block by prefixes

---

chromadb/api/async_client.py
chromadb/api/client.py
chromadb/api/collection_configuration.py
chromadb/test/configurations/test_collection_configuration.py
clients/js/packages/chromadb-core/src/ChromaClient.ts
clients/js/packages/chromadb-core/src/CollectionConfiguration.ts

This PR adds validation on create, get, and get_or_create collection to ensure that if embedding functions are provided in both places, it raises an error for the user if they are incompatible

[ENH] Add validation when multiple embedding functions set on client

---

.github/workflows/_python-tests.yml

Decreases test time of cross_test_version_persist from 13m11s to 5m47s for a 2.3x speedup. We have tried this in the past and ended up having [strange non-deterministic behavior](https://github.com/chroma-core/chroma/issues/4263), but [I ran a stress test here of 30x runs in a row](https://github.com/chroma-core/chroma/actions/runs/15336971977/job/43156007261?pr=4675) and it no longer seems to happen.

[BLD]: parallelize cross version test

---

rust/index/src/fulltext/types.rs

If the old and new documents are identical, we can save compute by ignoring the update.
A customer on Chroma Cloud seems to have a workload with a lot of no-op updates, so this should improve compaction speed for their collections.
n/a

[PERF]: skip document mutation in full-text index writer if old and new documents are same

---

rust/log-service/src/lib.rs

The logging was done manually.  wrap_span_with_parent_context should attach services in Honeycomb.
CI

[ENH] Use tracing util to set root span on rust log service.

---

go/pkg/log/repository/log.go
rust/log-service/src/lib.rs
rust/log/src/grpc_log.rs
rust/log/tests/log-offsets.rs
rust/wal3/src/copy.rs
rust/wal3/src/manifest.rs
rust/wal3/src/manifest_manager.rs
rust/wal3/src/writer.rs
rust/worker/src/compactor/scheduler.rs

- Add Error enum with WAL3, JSON, and dirty log specific error types
- Refactor RollupPerCollection to be Copy + Clone with new observation methods
- Remove large static rollup method from DirtyMarker in favor of modular approach
- Add rolling_up mutex and need_to_compact HashMap to LogServer for async operations
- Clean up unused imports and simplify overall structure
This change prepares the foundation for implementing async dirty log rollup
functionality while maintaining core rollup logic in a more maintainable form.
Includes #4701 and #4702.
CI
Internal documentation updated.

[ENH] Refactor dirty log rollup for async implementation

---

go/pkg/sysdb/coordinator/coordinator_test.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/coordinator/table_catalog_test.go
go/pkg/sysdb/metastore/db/dao/collection.go
go/pkg/sysdb/metastore/db/dbmodel/collection.go
go/pkg/sysdb/metastore/db/dbmodel/mocks/ICollectionDb.go

This field was previously only updated during version deletion.
Updated test to add assertion for this column.
n/a

[BUG]: correctly update `collections.num_versions` upon compaction flush

---

rust/log-service/src/lib.rs
rust/wal3/src/reader.rs

Here's the scenario:  A client is writing in batches to the log.  The
batches come in groups, and wal3 does de-amplification of batches.
Imagine running a pull logs.  Prior to this change, the pull logs can
only knows which files to fetch based upon the number of files or number
of bytes.
By pruning to number of records, we allow for the case where there's one
fragment that has BatchSize records, and so we only need to fetch one
fragment to read its records.
N/A

[ENH] Limit the number of records pulled by pull logs

---

pyproject.toml
requirements.txt
requirements_dev.txt

Unpins fastapi and moves to dev dependency. only use of it is in python fastapi server.
https://github.com/chroma-core/chroma/issues/4243

[CHORE] unpin fastapi, move to dev dependency

---

chromadb/__init__.py

Adds support to pass pathlib.Path for persistence
https://github.com/chroma-core/chroma/issues/4704

[CHORE] Add pathlib support to path for persistence

---

rust/log-service/src/lib.rs
rust/wal3/src/reader.rs

Claude and I wrote some tests that focus on overflow cases and potential boundary conditions.
Also embeds 4710:
Here's the scenario: A client is writing in batches to the log. The
batches come in groups, and wal3 does de-amplification of batches.
Imagine running a pull logs. Prior to this change, the pull logs can
only knows which files to fetch based upon the number of files or number
of bytes.
By pruning to number of records, we allow for the case where there's one
fragment that has BatchSize records, and so we only need to fetch one
fragment to read its records.
cargo test -p chroma-log-service --lib
N/A

[TST]  More tests of the log service code.

---

clients/new-js/packages/chromadb/src/utils.ts

Fix bug in 'where' clause validation for the JS client. Previously, the validation function recursed on the array of `$and` or `$or`, instead of the array elements themselves.

[BUG] Fix where validation bug

---

rust/log-service/src/lib.rs

- Trace frag count in rust log service during scout log
- N/A

[CHORE] Log frag count during scout

---

docs/docs.trychroma.com/components/header/header-nav.tsx
docs/docs.trychroma.com/components/markdoc/table.tsx
docs/docs.trychroma.com/components/sidebar/menu-item.tsx
docs/docs.trychroma.com/components/ui/table.tsx

In darkmode, markdoc table borders did not have a dark mode color assignment.
Likewise, in dark mode, the hover state of the HeaderNav MenuItems had no darkmode assignment.
Finally, this adds overflow to the HeaderNav and prevents MenuItems from wrapping.

[DOC] - Fixes various css isssues

---

rust/log-service/src/lib.rs

Skip using the results of the manifest load to make things faster for rollup/enrich.
CI.
N/A

[ENH] Avoid loading the manifest and rely exclusively on dirty log for enrich logs

---

clients/new-js/packages/chromadb/src/chroma-client.ts
docs/docs.trychroma.com/markdoc/content/docs/collections/create-get-delete.md

Rename `collection` method to `getCollectionById` for clarity.

[ENH] Add getCollectionById to JS

---

rust/log-service/src/lib.rs
rust/wal3/src/reader.rs

If the manifest in cache doesn't completely contain the fragments to be
returned, then bail.
CI
N/A

[BUG] Make sure the cached manifest can satisfy a pull-logs request.

---

rust/blockstore/Cargo.toml
rust/blockstore/src/arrow/provider.rs
rust/blockstore/src/lib.rs
rust/garbage_collector/src/construct_version_graph_orchestrator.rs
rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs
rust/index/src/lib.rs
rust/segment/Cargo.toml
rust/segment/src/test.rs
rust/storage/src/lib.rs
rust/worker/benches/get.rs
rust/worker/benches/query.rs
rust/worker/src/execution/operators/filter.rs
rust/worker/src/execution/operators/knn_projection.rs
rust/worker/src/execution/operators/limit.rs
rust/worker/src/execution/operators/prefetch_segment.rs
rust/worker/src/execution/operators/projection.rs
rust/worker/src/server.rs

- Previously we use `TempDir` to create temp directory for test, but the direct is never cleaned up because we invoke `<temp_dir>.into_path()`. This PR keeps the `TempDir` obj around so that the temporary directory can be deleted once the test finishes.
- ...

[BUG] Keep TempDir obj for test

---

go/pkg/sysdb/coordinator/model_db_convert.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/coordinator/table_catalog_test.go
go/pkg/sysdb/grpc/collection_service.go
go/pkg/sysdb/grpc/proto_model_convert.go
go/pkg/sysdb/metastore/db/dao/collection.go
idl/chromadb/proto/chroma.proto
idl/chromadb/proto/coordinator.proto
rust/garbage_collector/src/config.rs
rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs
rust/garbage_collector/src/helper.rs
rust/garbage_collector/tests/proptest_helpers/garbage_collector_under_test.rs
rust/sysdb/src/sqlite.rs
rust/sysdb/src/sysdb.rs
rust/types/src/collection.rs

- Return collection `updated_at` timestamp from the SysDb.
- Added a new `collection_soft_delete_grace_period` config parameter, defaults to 1 day.
- GCv2 will now ignore soft-deleted collections that are newer than the grace period (instead of immediately hard deleting them).
Updated existing test to validate that collections are not deleted when inside grace period.
n/a

[ENH]: GCv2: add grace period for transitioning soft deleted collections -> hard deleted

---

.github/actions/docker/action.yaml
.github/workflows/_build_release_container.yml

Reverts chroma-core/chroma#4759.
The split build consistently fails and is blocking our release pipeline. Reverting until we have clarity from Blacksmith and a tested & working split build impl.

[BLD] [REVERT]: build arm64 image on arm runner instead of in QEMU

---

rust/wal3/src/reader.rs

The bug is in the range_overlap code.
This manifests as pull_logs failing to pull logs.
Unit tests updated, only tested wal3 units locally.  CI for rest.
N/A

[BUG] Fix an obo in the wal3 reader.

---

chromadb/test/property/test_filtering.py

https://github.com/chroma-core/chroma/pull/4402 caused `test_filtering.py` to start flaking because the test assertions around `_` handling were not updated.

[TST]: fix test filtering flake caused by wildcard handling change

---

rust/log/src/test.rs

This speeds up the filter benchmark by 2.3x (tested locally, 7m12s -> 3m9s).

[ENH]: speed up filter benchmark

---

clients/new-js/packages/chromadb/package.json
clients/new-js/packages/chromadb/src/chroma-client.ts

Fix condition for populating auth params for `ChromaClient`

[BUG] Populate client args from deprecated args

---

Cargo.lock
rust/frontend/Cargo.toml
rust/frontend/src/lib.rs
rust/frontend/src/server.rs

https://github.com/chroma-core/chroma/pull/4780 started running the Rust tests in parallel in CI, which resulted in a new type of flake. The `random-port` crate is not safe to use across processes without additional locking/retry logic as it does not actually bind to and lock the port. Because of this, tests occasionally flake with port conflict errors when run in parallel.
This change fixes the issue by acquiring a random port at bind time.

[TST]: fix flakes in Rust tests caused by port conflicts

---

.github/workflows/_python-tests.yml
chromadb/test/api/test_collection.py
chromadb/test/api/test_invalid_update.py
chromadb/test/conftest.py
chromadb/test/property/test_add.py

`test_add.py` against the cluster is now parallelized. This speeds up the test by ~6m and brings it under the 15m threshold.

[BLD]: speed up test_add.py against cluster

---

chromadb/utils/embedding_functions/onnx_mini_lm_l6_v2.py

Remove CoreMLExecutionProvider from providers if available, it performs worse than CPU in all scenarios, as it is not optimized for BERT transformers.

[ENH] Remove CoreML as a provider for default ef

---

.config/nextest.toml
.github/workflows/_rust-tests.yml

The wall time of Rust integration tests is now ~18m, down from ~22m.

[BLD]: move GC proptest into separate job

---

chromadb/db/impl/sqlite.py

This small PR resolves the annoying deprecation warnings of the `logger` library which you can also find in the [CI logs](https://github.com/chroma-core/chroma/actions/runs/15312492452):
```python
D:\a\chroma\chroma\chromadb\db\impl\sqlite.py:111: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
```

[CHORE] address logger deprecation warnings

---

rust/log-service/src/bin/chroma-inspect-log-contents.rs

Returns the keys that are on the log in order, and the type of log operation.
N/A

[ENH]  Tool to inspect the contents of the log.

---

rust/tracing/src/init_tracer.rs

- Implements elements of https://github.com/chroma-core/chroma/pull/4292 to fix tracing on some services
- 

[BUG] Clean up tracing

---

rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/lib.rs
rust/storage/src/local.rs
rust/storage/src/s3.rs

This API will use the serverside option to upload a file, meaning that
copying a file becomes a cheap operation, relatively speaking.  No
longer will it have to stream to the rust-log-service and back to S3.
I added a unit test.  CI for the rest.
N/A

[ENH]  Add Copy API to chroma storage.

---

.github/workflows/_build_release_pypi.yml

The release workflow [recently started failing](https://github.com/chroma-core/chroma/actions/runs/15547454682/job/43808309595) with errors like 
```
Version 3.x was not found in the local cache
Error: The version '3.x' with architecture 'x86_64' was not found for Ubuntu 22.04.
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
I wasn't able to find any relevant issues for the `actions/setup-python` action. Maybe something on Blacksmith's side changed?
In any case, hopeful that pinning the major/minor version will fix it since this action completes successfully in other workflows with a pinned version.

[BLD]: pin Python version for wheel build workflow

---

rust/log-service/src/lib.rs

- Implement proptest for seal logs and migrate logs that does the following
- push random number of logs to a collection
- update the compaction log offset to one half of the logs present
- seal the log for this collection and migrate it to RLS
- verify that the logs after compaction log offset can be correctly read
- push random number of logs to the collection
- verify that the logs after compaction log offset can be correctly read
- ...

[TST] Impl proptest for log seal and migrate

---

.github/workflows/_build_release_pypi.yml

This was added in https://github.com/chroma-core/chroma/pull/4806, but it seems like the default sccache config doesn't work with Blacksmith. Disabling while we debug.

[BLD]: disable sccache during maturin build

---

rust/tracing/src/init_tracer.rs

`trace` spans can log an unbounded amount of data, so this should help us avoid running into exporter payload size limits.
Looks good in Jaeger.
n/a

[ENH]: change default trace level of garbage collector from trace -> debug

---

k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/query-service.yaml
rust/worker/src/server.rs

- Query nodes now wait on the log memberlist in order to pass readiness checks
- None
None

[ENH] Query node log memberlist readiness

---

rust/garbage_collector/src/garbage_collector_component.rs

In production, `max_collections_to_gc` is 10k which means that up to 10k jobs can be running at the same time. This adds a limiter so that there are at most 100 jobs running concurrently.
n/a

[ENH]: limit garbage collection job concurrency

---

rust/system/src/execution/dispatcher.rs
rust/system/src/execution/worker_thread.rs
rust/system/src/executor.rs

Reduces span spam and necessary nesting in traces.
A consequence is that spans that run in worker threads are no longer tagged as such, but the task type is usually obvious when looking at the code. If this is undesired I can add a task type span.
Before:
After:
Verified in Jaeger.
n/a

[ENH]: remove "Dispatcher" spans from tracing

---

.github/actions/rust/action.yaml

Reverts chroma-core/chroma#4833.
This is not the correct solution to thrashing since jobs may compile Rust with different configs (e.g. dev vs release mode) but that config is not included in the cache key.
I'll ask Blacksmith to bump our cache limit instead.

[BLD] [REVERT]: avoid Rust cache thrashing

---

rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/garbage_collector/tests/proptest_helpers/garbage_collector_under_test.rs
rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/lib.rs
rust/storage/src/s3.rs

This adds support for a list_prefix operation that calls the V2
ListOBjects API in the AWS SDK.  I've included an integration test.
The intended consumer of this API is the wal3 garbage collector,
which needs to list cursors in the directory to find the lowest-version
cursor.
Integration test added.
N/A

[ENH]  Support list_prefix operations for S3 and AC/S3.

---

rust/log-service/src/lib.rs
rust/types/src/collection.rs

This creates a method on the CollectionUuid that says its prefix relative to the storage root.
CI
N/A

[ENH]  Make storage_prefix_for_log a property of the CollectionUuid.

---

rust/garbage_collector/src/operators/delete_unused_files.rs
rust/garbage_collector/src/operators/delete_versions_at_sysdb.rs
rust/garbage_collector/tests/proptest_helpers/garbage_collector_under_test.rs
rust/log-service/src/lib.rs
rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/lib.rs
rust/storage/src/s3.rs
rust/types/src/collection.rs
rust/wal3/src/gc.rs
rust/wal3/src/manifest.rs
rust/wal3/src/writer.rs

Race:
- First thread installs a garbage file.
- First thread deletes garabage, but not GARBAGE file.
- Second thread "resumes" garbage deletion, deletes garbage.
- Second thread deletes GARBAGE file.
- Second thread installs GARBAGE file pointing to garbage.
- First thread deletes the wrong garbage file.
Use delete-if-match for S3 to protect against this.
CI
N/A

[BUG]  Two racing garbage collectors could leave garbage uncollected.

---

.github/actions/docker/action.yaml
.github/workflows/_build_release_container.yml
.github/workflows/pr.yml
rust/Dockerfile

This PR re-adds split builders for image releases so that ARM images can be built on native platforms. The issue before was that we ran `useblacksmith/build-push-action@v1.1` twice in the same workflow, which led to undefined behavior.
Validated that the new image build workflow succeeds by running in this PR (although I can't test the manifest merging until a run on main).

[BLD] build arm64 image on arm runner instead of in QEMU

---

rust/log-service/proptest-regressions/lib.txt
rust/log-service/src/lib.rs

This PR cherry-picks the commit 9331c11347fa2388e6d6d05279465fa945e8657f onto release/2025-06-13. If there are unresolved conflicts, please resolve them manually.

[HOTFIX] applying PR #4855 to release/2025-06-13

---

go/pkg/sysdb/coordinator/coordinator.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/grpc/collection_service.go
idl/chromadb/proto/coordinator.proto
rust/log-service/src/bin/chroma-update-collection-log-offset.rs
rust/log-service/src/lib.rs

This adds a tool to make the log offset match sysdb.  Then a test to make sure it cannot move things
backwards breaking invariants.
Added a test.
N/A

[ENH]  When the log offset is behind sysdb, this can repair it safely.

---

chromadb/api/async_fastapi.py
chromadb/api/base_http_client.py
chromadb/api/fastapi.py
chromadb/config.py
chromadb/test/test_api.py
clients/js/packages/chromadb-core/src/generated/models.ts
clients/new-js/packages/chromadb/src/api/types.gen.ts
clients/new-js/packages/chromadb/src/chroma-client.ts
clients/new-js/packages/chromadb/src/collection.ts
clients/new-js/packages/chromadb/src/utils.ts
clients/new-js/packages/chromadb/test/preflight.test.ts
rust/frontend/src/server.rs
rust/types/src/api_types.rs

This PR removes the base64 setting, and replaces it with a preflight check that the server has base64 enabled, and if it does will use it. The preflight check is cached on the client for reuse.
It also adds preflight checks to the js client, caching it on the client for reuse.

[CHORE] Add base64 encoding on preflight checks

---

rust/log-service/src/lib.rs

We put in an assert for testing and left it in.  It's triggering, indicating we got the bug.
CI
N/A

[BUG] remove a left-in assert for RLS

---

rust/wal3/src/manifest_manager.rs

If the manifest contains no fragments, the proper thing to do to get the log position is to consult
the initial offset and only then fall back to LogPosition::INITIAL.
Land this so staging can go green overnight.  Merge tests tomorrow.
n/a

[BUG]  Fix for empty manifests.

---

chromadb/test/distributed/test_log_failover.py
chromadb/test/property/test_fork.py
rust/log-service/src/lib.rs
rust/wal3/src/copy.rs
rust/wal3/src/manifest.rs
rust/wal3/src/manifest_manager.rs
rust/wal3/src/reader.rs
rust/wal3/tests/test_k8s_integration_0_properties.rs
rust/wal3/tests/test_k8s_integration_82_copy_empty_log_initializes.rs
rust/wal3/tests/test_k8s_integration_84_bootstrap_empty.rs
rust/wal3/tests/test_k8s_integration_98_garbage_alternate.rs

If all fragments are garbage collected, the manifest would revert to
FragmentSeqNo::BEGIN.  Track an initial sequence number and honor it.
CI
N/A

[BUG]  Track the threshold of garbage collected fragments

---

rust/log/src/grpc_log.rs

The Failed to Fetch error masks the true underlying cause.
cargo clippy locally; CI for the rest.
N/A

[ENH]  Make the Failed to Fetch log error verbose

---

rust/wal3/src/writer.rs

We identified this last night and I dropped it accidentally.
Basically, contention at the storage layer in upload_parquet needs to
fail out directly; there is no way to retry safely.
CI
N/A

[BUG]  Contention in S3 gets assumed to be retryable, leading the manifest to fail.

---

rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/s3.rs
rust/tracing/src/init_tracer.rs

Bumps the tracing level of `chroma-storage` to debug from trace.
I audited all spans in `rust/storage` to ensure all high-frequency code paths only have trace-level events and that any errors are correctly logged with the error level.
Confirmed that S3 spans no longer show up in Jaeger.
n/a

[ENH]: make S3 tracing spans less verbose by default

---

go/pkg/sysdb/grpc/collection_service.go

PR #4722 introduced a new field to the CheckCollectionsResponse, but
does not populate the slice/array necessary to return the result, ending
up in a null-ptr deref.  This PR populates the array at top of the loop.
CI + review
N/A

[BUG]  Panic on sysdb when calling CheckCollection

---

go/pkg/sysdb/grpc/proto_model_convert.go
idl/chromadb/proto/chroma.proto
rust/garbage_collector/src/helper.rs
rust/sysdb/src/sqlite.rs
rust/sysdb/src/sysdb.rs
rust/types/src/api_types.rs
rust/types/src/collection.rs
rust/worker/src/server.rs

- Organizing data of collections in s3 by s3 prefixes requires knowledge about database id in the write path. This PR populates and returns database id from sysdb in get_collections rpc
- We skip serializing and returning this from FE to client
- Even though the collection model is the same for both local and distributed, we don't set it in local currently. However, it can be done if needed
- ...
None

[ENH]: Return database id in get collections call from sysdb

---

docs/docs.trychroma.com/markdoc/content/cli/commands/db.md
rust/cli/src/commands/db.rs
rust/cli/src/utils.rs

Adding `chroma db connect --env-file` which sets environment variables required for connecting to ChromaCloud in the `.env` file in the current directory (or create it). The `chroma db connect --env-vars` option will output to the terminal.
Manual testing.
Included in this PR under CLI docs.

[ENH] CLI - Set Chroma env variables

---

rust/wal3/src/gc.rs
rust/wal3/src/manifest.rs
rust/wal3/src/manifest_manager.rs
rust/wal3/src/writer.rs
rust/wal3/tests/test_k8s_integration_0_properties.rs
rust/wal3/tests/test_k8s_integration_82_copy_empty_log_initializes.rs

The condition within wal3 for setting the initial_seq_no was broken.
The simpler condition is to set it to limit whenever limit is non-zero.
The start will always be <= limit by the guard at the top of the
function.  Therefore the only case this doesn't set the limit is when
limit is FragmentSeqNo(0), in which case we want an initial offset of 1.
CI
N/A

[BUG]  The condition for setting the manifest initial_seq_no was broken.

---

docs/docs.trychroma.com/markdoc/content/docs/querying-collections/full-text-search.md
docs/docs.trychroma.com/markdoc/content/sidebar-config.ts

[DOC] Regex docs

---

go/pkg/sysdb/coordinator/table_catalog.go
rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs
rust/garbage_collector/src/operators/delete_unused_logs.rs
rust/garbage_collector/src/operators/mod.rs
rust/garbage_collector/src/operators/truncate_dirty_log.rs
rust/log-service/src/lib.rs
rust/sysdb/src/test_sysdb.rs
rust/wal3/src/writer.rs
rust/wal3/tests/test_k8s_integration_82_copy_empty_log_initializes.rs
rust/wal3/tests/test_k8s_integration_90_garbage_collect.rs
rust/wal3/tests/test_k8s_integration_98_garbage_alternate.rs

- Extract log GC logic into its own operator
- Runs the GC operator at the end of GC orchestration
- Delete versions at sysdb operator waits until both file GC and log GC completes
- Updates the test sysdb impl so that the version history contains log offsets
- New log GC operator, including the logic to GC dirty log
- Log GC will only GC upto the minimum kept version of the collection
- Add an initial version history entry in version file

[ENH] Move Log GC to operator

---

rust/wal3/src/writer.rs

The background tasks of wal3 were leaked because the log service was not
calling shutdown when dropping a log.  This PR corrects that.
Local benchmark.  Will upload graph to GitHub PR.
N/A

[BUG]  Do not leak tokio tasks in the log service.

---

chromadb/test/property/test_add.py
rust/log-service/src/bin/chroma-inspect-dirty-log.rs
rust/log-service/src/lib.rs
rust/log/src/grpc_log.rs
rust/log/tests/log-offsets.rs
rust/wal3/src/cursors.rs
rust/wal3/src/writer.rs
rust/worker/tilt_config.yaml

The dirty log was not guaranteed to converge even in the absence of
further writes.  I confirmed this empirically with local testing and
inspection of the dirty log.  Post-patch it always converges within one
rollup.
CI

[ENH]  Make roll dirty log always converge to coalesce everything.

---

chromadb/__init__.py
chromadb/types.py

Make `CloudClient` arguments optional, and read them from the environment variables `CHROMA_TENANT`, `CHROMA_DATABASE`, and `CHROMA_API_KEY`
In a separate PR

[ENH] Read args from env variables for Python CloudClient

---

go/pkg/sysdb/grpc/collection_service_test.go
go/pkg/sysdb/metastore/db/dao/collection_test.go
go/pkg/sysdb/metastore/db/dao/daotest/collection.go
go/pkg/sysdb/metastore/db/dao/segment_test.go
go/pkg/sysdb/metastore/db/dao/test_utils.go

Sorry in advance for extra diff noise. I realized that the tests here are harder to work with than they should be (which is probably why we have so many gaps in the tests) so I refactored some things to move the needle in the right direction. I will follow up with more testing changes. 
This adds a test for the `CheckCollections` method. This would have caught the issue fixed in #4899. 
Along the way, I discovered how these tests need some love, so I started down this path by introducing a new `daotest` package that provides testing helpers for creating `Collection` values that are easier to configure. Instead of having to potentially debug all the tests that use `dao.CreateTestCollection`, I defined a "shim" that can be used as a stop-gap so that I can change the signature of this …

[TST] Add tests for CheckCollections, make test collection setup more flexible

---

rust/log/src/grpc_log.rs

If the same collection was returned twice, the results would be non-deterministic.
CI + a new passing unit test.
N/A

[BUG] Coalesce when multiple collections return the same info to compact

---

rust/log-service/src/lib.rs

If the cursor doesn't exist, enrich from the manifest.
This makes sure that the dirty log entries eventually reflect the
complete content of everything between the oldest uncompacted record and
the newest record.
CI
N/A

[BUG]  Enrich from the manifest if a cursor doesn't exist.

---

rust/frontend/src/quota/mod.rs

Bumps the default regex to 256, which has already been done on the management plane.
N/A

[CHORE]: bump default regex quota to 256

---

rust/log-service/src/lib.rs
rust/wal3/src/manifest.rs
rust/wal3/src/writer.rs

Both roll_dirty_log and mark_dirty append to the dirty log.  At high gc
rates, this can fail, and the operation will fail.  We can simply return
Ok(()) for any case where the log is durable.
CI
N/A

[ENH]  If the dirty log fails with LogContentionDurable, do not fail the operation.

---

clients/js/packages/chromadb-core/src/generated/models.ts
clients/new-js/packages/chromadb/src/api/types.gen.ts
rust/frontend/src/server.rs
rust/python_bindings/src/bindings.rs
rust/types/src/collection_configuration.rs
rust/types/src/hnsw_configuration.rs
rust/types/src/spann_configuration.rs

This PR fixes a bug where SPANN space was not read from the legacy metadata configuration if provided. The hnsw would read from the legacy config at sysdb, but SPANN was not configured to create the configuration using the legacy metadata configurations. This PR ensures that when neither hnsw nor spann configurations are specified in collection configuration, it will then read from legacy metadata

[BUG] Read from legacy metadata config when no collection config set

---

rust/wal3/src/batch_manager.rs
rust/wal3/src/writer.rs

In a commit back in March I took out the cancellation safety from append batch.
This re-adds that so that the batch only waits for itself, not until all work is done.
CI
N/A

[ENH]  Cancellation safety for append_batch.

---

clients/new-js/packages/chromadb/jest.config.ts
clients/new-js/packages/chromadb/package.json
clients/new-js/packages/chromadb/src/collection.ts
clients/new-js/pnpm-lock.yaml

Fix bug with forking where the forked collection's name was passed as the ID for the generated collection object.
Also added jest config to allow ONNX runtime to work for JS integration tests.

[BUG] Fix forking for js client

---

rust/index/src/spann/types.rs
rust/worker/src/execution/operators/projection.rs

- Getting version of a point from the versions map blockfile was sequential. Made it parallel I/O
- Similarly the final hydration of results in projection was sequential that is converted to parallel
- ...
None

[PERF] Make IO accesses parallel

---

rust/worker/src/execution/operators/filter.rs

- In query() if user did not supply any filters then no need to unnecessarily create the segment readers (thus reading roots from s3) and materialize the logs
- ...
None

[PERF]: Skip creating readers if filter is null

---

rust/storage/src/s3.rs
rust/wal3/src/gc.rs
rust/wal3/src/manifest.rs

It gives the false impression that non-success cases---even those
handled internally---are errors.  Further it forces traces to be
sampled.  Therefore, remove the err(Display) annotation.
N/A

[CLN] Remove err(Display) from wal3.

---

.github/workflows/_python-tests.yml
.github/workflows/release-chromadb.yml

We want to optimize our usage of Windows runners since they cost so much. The cost is due in large part to the amount of time our individual jobs take to run against Windows, but also the sheer number of jobs we run on Windows when we merge to main or push a tag. Details are below:
- Only run the Windows tests against the latest version of Python -- this greatly reduces the number of jobs we run on Windows for a single merge to main (reduces the total number of jobs by ~3x). The logic being that when we see failures for Python tests, we see them across all versions of Python and not just a single version _AND_ we are running the tests against the full matrix on Linux anyways.
- Optimizes the logic for when we run the smoke tests -- we were running them on merges …

[BLD] Optimize which tests we run on Windows

---

Cargo.lock
go/pkg/log/server/server.go
idl/chromadb/proto/logservice.proto
k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/values.yaml
rust/garbage_collector/Cargo.toml
rust/garbage_collector/garbage_collector_config.yaml
rust/garbage_collector/src/config.rs
rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs
rust/garbage_collector/src/lib.rs
rust/garbage_collector/src/operators/delete_unused_logs.rs
rust/garbage_collector/src/operators/truncate_dirty_log.rs
rust/garbage_collector/tests/proptest_helpers/garbage_collector_under_test.rs
rust/log-service/src/lib.rs
rust/log/src/config.rs
rust/log/src/grpc_log.rs
rust/log/src/log.rs
rust/wal3/README.md
rust/wal3/src/writer.rs

Wire up the garbage collector to do 3-phase GC.
CI
N/A

[ENH] Wire up garbage collector to do 3-phase GC.

---

.github/workflows/pr-check-title.yml
.github/workflows/pr.yml

This PR fixes a bug in CI where on PR title modifications, the workflow was not rerun, and instead required a code push to fix.
Fixes https://github.com/chroma-core/chroma/issues/3520

[CHORE] Fix pr title workflow to allow edits

---

rust/wal3/src/gc.rs
rust/wal3/src/writer.rs

~1e6 fragments on staging.  Materializing them all might be pushing the
service over the top.  Materialize the fragments lazily.
N/A

[ENH]  Do not materialize all fragments to delete.

---

clients/new-js/packages/chromadb/src/chroma-fetch.ts
clients/new-js/packages/chromadb/src/errors.ts

This is a simple script that simulates a naive mass upload to Chroma that will trigger our rate limiter
```
import { CloudClient } from "chromadb";
const client = new CloudClient({
apiKey: "...",
tenant: "...",
database: "test-db",
});
async function run() {
const collection = await client.getOrCreateCollection({
name: "ratelimit_test",
})
for (let i = 0; i < 100; i++) {
collection.upsert({
ids: [i.toString()],
documents: [`Document ${i}`],
});
}
}
run();
```
Users will get a vague "unable to connect" error:
```
/Users/kylediaz/Repos/chroma-core/smokey/node_modules/.pnpm/chromadb@3.0.4/node_modules/chromadb/dist/cjs/chromadb.cjs:1749
throw new ChromaConnectionError(
^
ChromaConnectionError: Unable to connect to the chromadb server. Please try again later.
at chromaFetch …
```

[ENH] Better JS client error messaging

---

rust/frontend/src/impls/service_based_frontend.rs
rust/log/src/sqlite_log.rs
rust/sqlite/src/config.rs
rust/sqlite/src/db.rs
rust/types/src/scalar_encoding.rs

This PR removes the push_logs_batch_size from sqlite config, and replaces it with max_batch_size. It sets up with OnceLock for thread safe lazy initialization with the existing get_max_batch_sizes() on frontend creation. 

[CLN] Add max_batch_size to sqlite_log, use in push_logs

---

rust/frontend/src/quota/mod.rs

- Changes `GenericQuotaError` from a 429 to a 422
- 

[CLN] Change GenericQuotaError from 429 to 422

---

chromadb/utils/batch_utils.py

This script failed batch_utils. This PR fixes it with the correct type checks
```
from chromadb.utils.batch_utils import create_batches
import numpy as np
client = chromadb.EphemeralClient()
collection = client.create_collection("foo")
ids = [str(i) for i in range(100_000)]
embeddings = np.random.rand(100_000, 128)
for (ids, embeddings, _, _) in create_batches(client, ids=ids, embeddings=embeddings):
collection.add(ids=ids, embeddings=embeddings)
for (ids, _, _, _) in create_batches(client, ids=ids):
collection.delete(ids=ids)
```

[CHORE] Fix type error in batch_utils

---

clients/js/packages/chromadb-core/src/generated/models.ts
rust/cli/src/client/collection.rs
rust/cli/src/commands/copy.rs
rust/frontend/src/base64_decode.rs
rust/frontend/src/executor/local.rs
rust/frontend/src/impls/in_memory_frontend.rs
rust/frontend/src/impls/service_based_frontend.rs
rust/frontend/src/server.rs
rust/frontend/src/types/errors.rs
rust/frontend/tests/proptest_helpers/arbitrary.rs
rust/python_bindings/src/bindings.rs
rust/types/src/api_types.rs

Replaces https://github.com/chroma-core/chroma/pull/5033. The rest of our system assumes that adds have non-empty embeddings.
n/a

[ENH]: require embeddings & require min embedding dimension on /add

---

clients/js/packages/chromadb-core/src/ChromaFetch.ts

When no payment method is present, data plane error message will be: 
`{"error":"ChromaError","message":"Billing limit exceeded. Log into trychroma.com or contact hello@trychroma.com to raise it."}`
This PR adds support for this type of error message to the JS client, so it is recognized as a quota error instead of a connection error.

[BUG] js client: handle 422 billing errors as QuotaExceeded instead of ChromaConnectionError

---

rust/log-service/src/lib.rs
rust/wal3/src/lib.rs

- Rust Log Service did not configure the max payload size, which defaults to 4MB. We would like to use 32MB payload size (which is the default for GRPC log client right now).
- We would like to bump the max frag size from 8MB to 64MB (2*GRPC max payload size)
- N/A
Planning to perform data ingestion after config change

[BUG] RLS should use 32MB GRPC payload size limit

---

rust/blockstore/src/arrow/blockfile.rs
rust/segment/src/blockfile_metadata.rs
rust/segment/src/blockfile_record.rs
rust/segment/src/types.rs
rust/worker/src/execution/operators/filter.rs

- Brute forcing list of ids or all the ids was sequential. We now parallelize all the block gets and then perform regex
- ...
None

[PERF]: Parallelize fetching blocks for brute force regex

---

rust/garbage_collector/src/operators/list_files_at_version.rs

One of our GC pods is currently OOMing and it seems like the majority of memory used is just to track all the futures for `get_all_block_ids()`:
This should not be an issue for the vast majority of collections, but there are currently 0.02% of collections with > 1k active versions and a handful with > 20k active versions.
n/a

[ENH]: limit number of concurrent get_all_block_ids() when using buffer_unordered()

---

rust/storage/src/s3.rs

This change disables AWS [stalled stream protection](https://github.com/awslabs/aws-sdk-rust/discussions/956). It is causing issues such as [this](https://github.com/awslabs/aws-sdk-rust/issues/1146) for downloads. We already have various timeouts in place to perform the intended functionality of stalled stream protection.
- Disabled AWS stalled stream protection
- N/A
N/A
- [v ] Tests pass locally with `pytest` for python, `yarn test` for js, `cargo test` for rust

[BUG]: Disable aws stalled stream protection

---

docs/docs.trychroma.com/markdoc/content/docs/collections/manage-collections.md

This PR updates the manage collections docs with the correct api reference for delete collection

[DOC] Update manage collections docs with correct delete collection info

---

Cargo.lock
k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/templates/query-service.yaml
k8s/distributed-chroma/values.dev.yaml
rust/garbage_collector/src/lib.rs
rust/worker/Cargo.toml
rust/worker/chroma_config.yaml
rust/worker/src/bin/query_service.rs
rust/worker/src/config.rs
rust/worker/src/server.rs

Similar to what we did in #4845, this adds the jemalloc pprof server to the query-service server so that we can do memory profiling for the service using Polar Signals.
Note: I also updated a place in the garbage collector's implementation where the port was hard-coded to 6060. 
- pprof server started when config given
Build should succeed and updating `chroma_config.yaml` with local tilt environment to test that pprof endpoint is up.

[CHORE] Add pprof server to query service

---

rust/blockstore/src/arrow/provider.rs

- Dedups inserts to the same key in foyer. This should prevent buffer overflows
- ...
None

[ENH]: Dedup inserts to the same key in foyer

---

rust/error/src/lib.rs
rust/garbage_collector/src/operators/list_files_at_version.rs
rust/log/src/grpc_log.rs
rust/log/src/log.rs
rust/system/src/execution/dispatcher.rs
rust/system/src/execution/operator.rs
rust/system/src/execution/orchestrator.rs
rust/worker/src/compactor/compaction_manager.rs
rust/worker/src/execution/operators/knn_merge.rs
rust/worker/src/execution/orchestration/compact.rs

This is logged because of err(Display) and a trace error.  Make the
trace not apply to NotFound response codes.  Make the err(Display) go
away as it's going to be redundant with the tracing::error.
CI
N/A

[ENH]  "Failed to fetch: status: NotFound" be gone.

---

rust/log-service/src/lib.rs
rust/log/src/grpc_log.rs
rust/wal3/src/manifest.rs
rust/wal3/src/reader.rs

This change solely removes log lines that generate the most spans
without adding sufficient information.
CI
N/A

[CLN]  Remove the the top most spammy log lines from rls/wal3.

---

rust/storage/src/s3.rs

Changing the name of the s3 get metric from `chroma.storage.s3.s3_get_foo` to be. a nicer `chroma.storage.s3_get_foo`.
- N/A
- N/A
N/A

[CHORE]: Fix s3 get metric name

---

.github/actions/rust/action.yaml

We use this Rust setup action in private repos with multiple Cargo workspaces. The cache is currently not utalized in these cases because the workspace paths need to be specified to the cache action. This allows callers to provide a list of workspaces that is forwarded to the cache action.
I observed that the Rust cache is still used in this repo for the checks that ran on this PR.

[BLD]: add workspaces option to reusable Rust action

---

bin/rust_single_node_integration_test_config.yaml
rust/frontend/sample_configs/distributed.yaml
rust/frontend/sample_configs/single_node_full.yaml
rust/frontend/sample_configs/tilt_config.yaml
rust/frontend/src/config.rs
rust/log-service/src/lib.rs
rust/tracing/src/init_tracer.rs
rust/worker/chroma_config.yaml
rust/worker/tilt_config.yaml

The tracing issues we've been chasing boil down to a _fun_ little quirk of Rust compiler, in which hyphens in crate names are converted to underscores automatically to make the crate names valid Rust identifiers.
N/A
Monitor staging to make sure missing traces start to reappear.
N/A

[CHORE]: update tracing filters to use underscores instead of hyphens

---

rust/garbage_collector/src/operators/delete_unused_files.rs

Cumulatively, this operation is very slow in production. Hoping that increasing the batch size to the maximum will speed it up.

[ENH]: bump GC delete batch size from 100 -> 1,000

---

go/cmd/logservice/main.go
go/pkg/leader/election.go
go/pkg/memberlist_manager/memberlist_manager.go
go/pkg/sysdb/grpc/server.go
k8s/distributed-chroma/templates/lease-watcher-role.yaml
k8s/distributed-chroma/templates/logservice.yaml
k8s/distributed-chroma/templates/sysdb-service.yaml

This change introduces leader election in the SysDB service in preparation to scale out this layer. After this change, only the leader monitors and updates the member list. Not that the leader election in question just reuses the Kubernetes leader election API so it is not strongly consistent and can lead to split-brain scenarios. These split-brain scenarios are not harmful here.
Since this change reuses the leader election code that's already in the log service, that code has been moved out of the log service directory.
- Gated member list service operations by a leader election.
- Described above. This should enable the SysDB service to scale out.
Observing log statements on local tilt.
N/A. Before scaling out the SysDB layer, make sure …

[ENH]: Leader election for SysDB

---

k8s/distributed-chroma/Chart.yaml

Bump helm chart. This should have been done as a part [of](https://github.com/chroma-core/chroma/pull/5104).
N/A
N/A
N/A
N/A

[BUG]: Bump helm chart version

---

Cargo.lock
rust/worker/Cargo.toml
rust/worker/src/compactor/compaction_manager.rs
rust/worker/src/compactor/config.rs
rust/worker/src/compactor/scheduler.rs
rust/worker/src/execution/orchestration/compact.rs

This change adds a dead letter queueing system to the compaction scheduler. If a compaction job on a collection fails `max_failure_count` times, it will be moved to a dead set that disables this collection from being compacted while it is in this set. As of this change, the only way to clear this set is by restarting the compaction process.
- Added a failing_jobs map in the CompactionManager to help keep track of jobs that have failed on consecutive attempts. 
- Added a dead_jobs set in the CompactionManager to record "dead" jobs.
- Described above.
- Added a metric `compactor_dead_jobs_count` to track the size of the dead jobs set.
Added a test in scheduler.rs.
Also manually tested by injecting failures in certain compaction jobs and …

[ENH]: Dead letter queuing for compaction jobs

---

docs/docs.trychroma.com/markdoc/content/integrations/embedding-models/openai.md

Fix docs typo on the OpenAI integration page

[DOC] Fix OpenAI docs typo

---

clients/new-js/packages/chromadb/src/chroma-client.ts
clients/new-js/packages/chromadb/src/collection-configuration.ts
docs/docs.trychroma.com/markdoc/content/docs/collections/manage-collections.md

Allow users to explicitly define `null` EF when creating collections. This is intended for users who want to provide embeddings directly to a collection and don't want to install the default embed package. 
In this PR

[ENH] Allow users to define null EFs on create collection

---

docs/docs.trychroma.com/markdoc/content/docs/overview/introduction.md

The markdoc renderer doesn't throw when there is a syntax error
Given that, the missing closing tag in this change prevented the rest of the page from rendering.
Separately, we should throw if the markdown renderer catches a syntax error like this.

[BUG] Fixes an issue with markdown syntax

---

Cargo.toml
rust/blockstore/src/arrow/provider.rs
rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/lib.rs

- Adds a dedupe closure API to the storage interface under `fetch`
- Fetch allows providing an async closure to be deduplicated 
- This changes off of a Shared future for deduplication, since the dispatcher runtimes and main runtime may share that future, leading to undefined behavior.
Existing tests cover this
Existing telemetry monitors this change
None

[ENH] Add dedupe closure to storage

---

Cargo.toml
rust/garbage_collector/src/construct_version_graph_orchestrator.rs
rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs
rust/system/src/execution/dispatcher.rs
rust/system/src/execution/operator.rs
rust/system/src/execution/orchestrator.rs
rust/system/src/utils/guard.rs
rust/system/src/utils/mod.rs
rust/worker/src/compactor/compaction_manager.rs
rust/worker/src/execution/operators/prefetch_record.rs
rust/worker/src/execution/operators/prefetch_segment.rs
rust/worker/src/execution/orchestration/compact.rs
rust/worker/src/execution/orchestration/count.rs
rust/worker/src/execution/orchestration/get.rs
rust/worker/src/execution/orchestration/knn.rs
rust/worker/src/execution/orchestration/knn_filter.rs
rust/worker/src/execution/orchestration/spann_knn.rs

This change implements cancellation for all tasks spawned by an Orchestrator when it is dropped or stopped. Any of these actions would trigger a cancellation token that is passed on to every task this Orchestrator spawns. All Tasks now are initialized with a CancellationToken that is passed from the Orchestrator that constructs them. The runtime of these Tasks have been modified to poll on these tokens. Some operators like Prefetch operators don't use this token as it is preferable for those to run to completion even if their overlying Orchestrators get killed.
Because of these changes, a timeout would end up dropping or stopping any running Orchestrators and cancel their in-flight tasks. Any tasks that remain in the dispatcher but are not started will remain in the dispatcher queue as an …

[ENH]: Propagate cancellation to all spawned Tasks

---

docs/docs.trychroma.com/components/markdoc/ask-ai.tsx
docs/docs.trychroma.com/components/markdoc/markdoc-renderer.tsx

Docs wouldn't render without an appropriate .txt files for the "Ask AI" button. This PR removes this restriction. If a .txt file is not available, the "Ask AI" button will render without the "copy" option and will ask the model to read the webpage itself instead of the exposed .txt file (can lead to worse performance by the model).

[DOC] Allow pages to render without a .txt

---

rust/sysdb/src/sysdb.rs

The soft-deleted compaction will return an error that's not
distinguishable from other errors.  It will percolate to the dispatcher
and be logged like every other error.
In #5064, we added a should_trace_error function on the chroma Error
trait, which will silence the error at the dispatcher.  This PR applies
that annotation to the failed precondition.
CI
N/A
We get paged today.
We don't get paged in the future.
N/A

[ENH]  Do not trace failed preconditions when flushing compaction.

---

Tiltfile
k8s/distributed-chroma/Chart.yaml
k8s/distributed-chroma/values.yaml
rust/garbage_collector/src/config.rs
rust/worker/chroma_config.yaml
rust/worker/tilt_config.yaml

- Load GC config under `garbage_collector` key if present. This is consistent to the behavior of other services
- N/A

[ENH] Extract gc config under specific key if present

---

rust/blockstore/src/arrow/provider.rs
rust/storage/Cargo.toml
rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/lib.rs

- This moves the actual network request into its own tokio task so that it if a parent task is cancelled the request can drive forward and still make progress for other callers. 
- Even if all callers are dropped, we still allow the request to make progress
- The spawned task is responsible for removing the task from the map, only under a panic will it not.
- If any waiters are cancelled the send() error to them is ignored and currently traced as an error as this should only happen under timeout situations. We can downgrade to a warn in the future
- 
- ...
Existing tests ensure the subsystem works, this is a non-functional change
None
Added error traces for …

[ENH] Move fetch to its own task for cancellation

---

chromadb/test/distributed/test_log_backpressure.py
rust/log/src/grpc_log.rs

This PR makes it so that a resources exhausted error from the grpc log
client gets translated into a Backoff error from the typed log client.
CI
N/A
We should be able to hit the backpressure limit and see it as a 429
instead of 500.
N/A

[ENH]  Change ResourcesExhaused into Backoff/429 for log client.

---

chromadb/chromadb_rust_bindings.pyi
clients/js/packages/chromadb-core/src/ChromaFetch.ts
clients/js/packages/chromadb-core/src/generated/models.ts
clients/new-js/packages/chromadb/src/api/types.gen.ts
rust/frontend/src/impls/in_memory_frontend.rs
rust/frontend/src/impls/service_based_frontend.rs
rust/frontend/src/server.rs
rust/frontend/tests/proptest_helpers/arbitrary.rs
rust/python_bindings/src/bindings.rs
rust/types/src/api_types.rs

- embeddings is mandatory in /upsert now. Previously it was optional, and led to users pushing records without embeddings thereby failing compaction subsequently.
- ...
Locally tested on tilt
None
Will babysit staging to see that nothing breaks
None

[BUG]: Make embeddings mandatory in /upsert

---

rust/garbage_collector/src/operators/delete_unused_logs.rs

This change adds the collection ID as a property of the garbage
collection error, so we can trace which collection is responsible for a
particular error.
CI
N/A
This is an observability PR.
N/A

[ENH]  Thread collection ID through the GC::Wal3 error.

---

rust/wal3/src/gc.rs
rust/wal3/tests/test_k8s_integration_98_garbage_alternate.rs

If the rust log service tries to GC something that's not within range,
it will throw this error, but without knowing the offset it's hard to
say how things have gone wrong.
CI
N/A
Improved.
N/A

[ENH]  Log the first_to_keep value that triggers an error.

---

rust/index/src/hnsw_provider.rs
rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/lib.rs
rust/storage/src/s3.rs

- Minor cleanup that  removes get_parallel and replaces it with an option
- None
Existing tests for parallel reads were ported to the new path
None required
None required
None required

[CLN] Remove get_parallel, replace with options for parallel

---

chromadb/test/configurations/test_collection_configuration.py
go/pkg/sysdb/coordinator/model/collection_configuration.go
go/pkg/sysdb/coordinator/table_catalog.go
go/pkg/sysdb/coordinator/table_catalog_test.go
go/pkg/sysdb/metastore/db/dao/collection.go
go/pkg/sysdb/metastore/db/dao/collection_test.go
rust/frontend/src/server.rs
rust/python_bindings/src/bindings.rs
rust/sysdb/src/sqlite.rs
rust/sysdb/src/sysdb.rs
rust/types/src/api_types.rs
rust/types/src/collection_configuration.rs
rust/types/src/spann_configuration.rs

Previously, the go code did not update the configuration str for collections because it was not passed as part of `generateCollectionUpdatesWithoutID`
This was fixed, and tests were added. It also cleans up the existing go types, and updates the rust types to use a similar InternalCollectionConfiguration for updates.
Tests were added to validate that both the modify worked, and on future fetches maintains the values. Db tests were also added to the dao
- [x ] Tests pass locally with `pytest` for python, `yarn test` for js, `cargo test` for rust

[BUG] Use InternalUpdateConfiguration in Rust, correctly update configuration in go

---

rust/log-service/src/lib.rs

The rust log service will now log information about
garbage_collect_phase2, specifically the collection or dirty log to be
operated upon.
Log lines, so if it compiles...
Just kidding: CI
N/A
It's meant to improve monitoring of other changes.
N/A

[ENH]  Log the collection or dirty log host as an info for gc phase 2.

---

rust/garbage_collector/src/config.rs
rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs
rust/garbage_collector/src/operators/delete_unused_logs.rs
rust/garbage_collector/tests/proptest_helpers/garbage_collector_under_test.rs

This introduces a new configuration for the purposes of skipping the
num-versions-to-keep rule in GC for the wal3 log only.  When the new
enable_dangerous_option_to_ignore_min_versions_for_wal3 is set, it will
try to do the right thing, and if it fails with the symptoms of the bug,
it will then try again using just the compaction offset.
Send through CI, enable on staging, then stop.
This is a migration of sorts.
I will watch staging where we currently see errors and will not see them
in the future.
N/A

[ENH]  Add a hack to allow us to move past some broken collections on staging.

---

rust/log-service/src/lib.rs

This log line is about 12x more spammy than the next-most spammy log
line, where spammy is determined by a histogram of log lines.
CI
N/A
Negative space isn't observable.
N/A

[CHORE] Remove a spammy log line in RLS.

---

.github/workflows/pr.yml
.github/workflows/release-chromadb.yml

This PR cherry-picks the commit https://github.com/chroma-core/chroma/commit/cf1a0134525207e1e98a97a07be23ad01c088a19 onto release/2025-07-25.

[HOTFIX] Applying PR 5149 to release/2025-07-25

---

rust/types/src/spann_configuration.rs

This PR lowers the default posting list sizes for spann from 200 to 50, as per testing. This is done by changing the default split threshold for clusters, and correspondingly changing the merge threshold

[ENH] Lower default posting list sizes for spann

---

rust/worker/tilt_config.yaml

- test_add.py is flakey. Turning it off until it is root caused
- ...
None
CI becomes green again
None

[ENH]: Turn off adaptive nsearch

---

rust/frontend/src/impls/service_based_frontend.rs
rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/tests/proptest_helpers/garbage_collector_under_test.rs
rust/log-service/src/lib.rs
rust/log/src/grpc_log.rs

I hypothesize that the connect_lazy code path (only take for log service
clients) is to blame for our hangs when there's churn in the rust log
service on staging.  Change to connect() rather than connect_lazy() so
the whole grpc handshake gets done before trying to use the connection.
CI
N/A
I plan to deploy to staging and then beat it up until the problem occurs
or the problem is doesn't manifest and is therefore likely to be gone.
N/A

[ENH]  The rust log service uses connect_lazy; change to connect strict

---

rust/blockstore/src/provider.rs
rust/index/src/spann/types.rs
rust/segment/src/blockfile_metadata.rs
rust/segment/src/blockfile_record.rs

- Parallelize sparse index fetches within a segment.
- N/A
TBD

[ENH]: Parallelize fetching sparse indexes of a segment

---

rust/blockstore/src/arrow/blockfile.rs
rust/worker/src/execution/operators/filter.rs
rust/worker/src/execution/operators/projection.rs

- Filter and Projection were missing tracing cold block gets because of join_all on futures. Will clean it up and revert it once we are done debugging
- ...
None
Tracing works on staging
None

[ENH]: Add more tracing in the filter path

---

Cargo.lock
rust/tracing/Cargo.toml
rust/tracing/src/init_tracer.rs
rust/tracing/src/lib.rs
rust/tracing/src/wrapped_metric_exporter.rs
rust/tracing/src/wrapped_span_exporter.rs

This adds new metrics for the total # of span & metric batches exported and segments the metrics based on success/error. This will help us be aware of when services drop spans/metrics.
I tested locally in Tilt by adding a 8MB test span and observing that the counter for span export errors was incremented.

[ENH]: add metrics for span & metric exporters

---

rust/garbage_collector/src/construct_version_graph_orchestrator.rs
rust/garbage_collector/src/garbage_collector_orchestrator.rs
rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs
rust/system/src/execution/orchestrator.rs
rust/worker/src/execution/orchestration/compact.rs
rust/worker/src/execution/orchestration/count.rs
rust/worker/src/execution/orchestration/get.rs
rust/worker/src/execution/orchestration/knn.rs
rust/worker/src/execution/orchestration/knn_filter.rs
rust/worker/src/execution/orchestration/spann_knn.rs

The garbage collector in production logs "The result channel should be set before take" before stalling. It is unclear if this panic is causing the stalling as I can't reproduce the stall locally, but the currently the `Orchestrator` trait makes a faulty assumption which should be fixed regardless. It assumes that `take_result_channel()` is called at most once. But this is impossible to guarentee under current semantics as it doesn't take ownership of `self`. For example, this triggers a panic:
```rust
#[async_trait]
impl Handler<TaskResult<ListFilesAtVersionOutput, ListFilesAtVersionError>>
for GarbageCollectorOrchestrator
{
type Result = ();
async fn handle(
&mut self,
message: TaskResult<ListFilesAtVersionOutput, ListFilesAtVersionError>,
ctx: …
```

[ENH]: make take_result_channel() return an option

---

.github/workflows/pr.yml
.github/workflows/release-chromadb.yml
.github/workflows/release-dev-javascript-client.yml
.github/workflows/release-helm-chart.yml
.github/workflows/release-javascript-client.yml
.github/workflows/trigger-deploy.yaml

I noticed that our Slack notifications for workflow failures are slightly inconsistent. This makes them all have the same payload structure which is:
```
Title (aka what failed)
Workflow: <name of the workflow>
Run: <link to run>
Ref: <link to ref>
Author: <if possible>
[Args like "Plane"]: 
...
```
This only changes the payload for the existing functionality, so is pretty safe.

[BLD] Make Slack notifications consistent

---

rust/frontend/src/server.rs

This adds the collection ID to the tags available for scorecarding
requests for the `fork_collection` call.
CI
N/A
N/A
N/A

[ENH]  Allow scorecarding of fork collection by collection or tenant.

---

rust/Dockerfile

This PR adds an `ENABLE_AVX512` flag to the rust Dockerfile to enable building the binary to force it to use AVX512 instructions, improving performance on devices that support AVX512 instructions

[ENH] Add flag on Dockerfile to use AVX512 instructions

---

docs/docs.trychroma.com/markdoc/content/integrations/chroma-integrations.md

This commit adds a new "Platform Integrations" section to the Integrations page, introducing support for WordPress through the AI Engine Pro plugin.

Add WordPress (AI Engine Pro) to Chroma integrations

---

rust/frontend/src/server.rs

- This adds spans for add/update/upsert specifically so that we can exclude buffering request body from span times. I have not added these to all endpoints since their input payloads should be nominal and variance in buffering their bodies could indicate system health issues. Additionally, this minimizes Span noise.
- None
Closes https://github.com/chroma-core/hosted-chroma/issues/3599
I manually checked the spans in tilt
No
These are observability changes and as such the core description covers this.
None.

[ENH] Upload spans

---

chromadb/test/property/invariants.py

- We reduced the PL size from 200 to 50 so now we are brute forcing 1/4th of what we used to do before. We also modified the rng_query() to correctly handle negative distances. Previously for IP, rng pruning would filter out everything so the code ended up creating a new center everytime a point was added. Now, it appends to existing centers and also duplicates the same point to different centers.
- Because of these, test_add is flakey sometimes with recall of < 99 for high k. One instance was obtained_recall=98% and k=50.
- This PR changes the recall threshold to 95% for test_add which is a more realistic threshold.
- ...
None
CI flakes are gone
None

[ENH]: Reduce recall threshold in test_add to 95

---

rust/cli/src/lib.rs

Closes #5216
- Short descriptive names of each CLI command
```bash
./target/debug/chroma --help                                                                                                                                                                                                                                                                                                                                                                                      21:44:01 
A CLI for Chroma
Usage: chroma <COMMAND>
Commands:
browse   Browse chroma collections
copy     Copy collection between local and Cloud chroma
db       Manage Chroma Cloud databases
docs     Navigate to Chroma online docs …
```

[CHORE]: Added short descriptions to CLI commands

---

rust/distance/src/types.rs

This PR updates the distance crate to prioritize AVX over SSE, and forces builds with AVX flags when ENABLE_AVX512 is set in the Dockerfile

[ENH] Use AVX in distance calculations

---

Cargo.lock
chromadb/__init__.py
chromadb/api/client.py
chromadb/auth/utils/__init__.py
chromadb/test/client/test_cloud_client.py

This PR updates the python CloudClient to auto-set tenant based on the API key.
to use the cloud client now with an api key scoped to a single db
```
client = chromadb.CloudClient(
api_key="ck-xxxxxxxxx"
)
```
and with an api key scoped to multiple dbs
```
client = chromadb.CloudClient(
database="right-db",
api_key="ck-xxxxxxxxx"
)
```
edge cases:
scoped api key to 1 db:
```
client = chromadb.CloudClient(
api_key="xxxxx"
)
client = chromadb.CloudClient(
tenant="right-tenant",
api_key="xxxxx"
)
client = chromadb.CloudClient(
tenant="wrong-tenant",
api_key="xxxxx"
)
client = chromadb.CloudClient(
database="wrong-db",
api_key="xxxxx"
)
client = chromadb.CloudClient(
database="right-db",
api_key="wrong-api-key"
)
```
scoped api key to multiple dbs
```
client = chromadb.CloudClient( …
```

[ENH] Auto-set tenant, scoped database in python CloudClient

---

rust/blockstore/src/arrow/blockfile.rs
rust/blockstore/src/types/reader.rs
rust/blockstore/tests/blockfile_writer_test.rs
rust/index/src/fulltext/types.rs
rust/index/src/spann/types.rs
rust/segment/src/blockfile_metadata.rs
rust/segment/src/blockfile_record.rs
rust/segment/src/distributed_spann.rs
rust/segment/src/types.rs
rust/types/src/regex/literal_expr.rs

- BlockfileReader's get_range() method used to return a Vec<Items>. The overhead of vector allocation and extend is non-trivial especially if the range is large. Regex brute force for e.g. has this overhead.
- This PR modifies the interface to return an iterator instead of a vector so that the overhead of materialization can be cut down
- get_all_data() is also updated to return an iterator and all callsites updated
- ...
None
Perf testing on staging
None

[PERF]: Modify get_range to return an iterator

---

rust/log-service/src/lib.rs

The tests flaked because compaction is now faster.  This will make the
test robust, but also make it so that DR does the right thing.
CI
N/A
N/A
N/A

[BUG]  Mark dirty on rollback of cursor to guarantee compaction picks it up.

---

rust/system/src/execution/dispatcher.rs
rust/system/src/executor.rs

This adds a metric for the queue depth of components (number of messages waiting to be handled by the component) and updates the dispatcher queue metrics to have a dynamic set of boundaries based on the current config.
This will help debug component/dispatcher queuing issues.
I validated that the metrics show up in Grafana when running with Tilt and that the values look reasonable.
_Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the [docs section](https://github.com/chroma-core/chroma/tree/main/docs/docs.trychro …

[ENH]: add metric for component queue depth & change dispatcher queue depth metric buckets

---

rust/Dockerfile

This PR allows Rust to build with avx and fma features, since they are off by default 

[ENH] Update Rust to allow build with AVX when flag is set

---

requirements_dev.txt

`DEVELOP.md` tells people to use maturin to build the rust codebase, so it should be a dev dependency.
Is `DEVELOP.md` even up to date with how we do development in this repo?

[BLD] Add maturin to dev dependencies

---

rust/system/src/execution/operator.rs
rust/system/src/execution/orchestrator.rs
rust/system/src/scheduler.rs
rust/system/src/types.rs

Summary from Claude, guided by me:
```claude
I've identified a critical deadlock pattern in the dispatcher-worker thread communication system. This is a classic bounded-buffer deadlock (not livelock or starvation).
The Deadlock Pattern:
1. WorkerThread (rust/system/src/execution/worker_thread.rs:58-61):
- After processing a task, sends TaskRequestMessage to dispatcher
- This send operation blocks if dispatcher's channel is full
2. Dispatcher (rust/system/src/execution/dispatcher.rs:199-204):
- When receiving tasks, if no workers are waiting, tries to send task to a worker
- This send operation blocks if worker's channel is full
Precise Computer Science Classification:
This is a circular wait deadlock with the following characteristics:
- Resource type: Bounded channel buffer space
- …
```

[BUG] Resolve deadlock in system crate?

---

rust/garbage_collector/src/construct_version_graph_orchestrator.rs
rust/garbage_collector/tests/proptest_helpers/garbage_collector_under_test.rs

There is a fork tree in prod that fails to garbage collect with the error `ExpectedNodeNotFound(CollectionUuid(***), None)`. This PR fixes construction of the version graph so this no longer happens.
I added some comments to this PR explaining what was happening.
Downloaded version files & lineage file for all collections in fork tree and locally repro'ed the issue. Validated that garbage collection ran successfully after these changes.
_Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the [docs …

[BUG]: fix missing node in constructed version graph for garbage collection

---

rust/index/src/spann/types.rs

- If finish() is called on spann segment on an empty index then hnsw GC fails. The old index that it is trying to GC is empty() thus it tries to malloc 0 bytes for new index and fails. Fixed to return early in this case
- ...
None
Test rebuild on staging
None

[BUG]: Don't GC hnsw if it is empty

---

rust/frontend/src/impls/service_based_frontend.rs
rust/frontend/src/server.rs
rust/metering/src/core.rs
rust/metering/src/lib.rs

We need to detect when tenants perform read operations on collections that are not theirs. To achieve this, we introduce an `ExternalCollectionRead` variant on the `MeterEvent` enum. For the get, query, and count paths, we conditionally create this context if the requesting tenant does not match the tenant that owns the requested resource. In the flushing logic, we first attempt to flush the current `CollectionReadContext`, and if that fails, we attempt to flush the new `ExternalCollectionReadContext`.
This will break hosted. The plan is to merge this PR and then shortly after merge the corresponding hosted PR: 
N/A
N/A

[ENH] add ExternalCollectionReadContext to MeterEvent enum

---

Cargo.lock
rust/jemalloc-pprof-server/Cargo.toml

Needed to be able to re-use the `chroma-jemalloc-pprof-server` crate elsewhere.

[CHORE]: bump jemalloc_pprof version

---

rust/types/src/api_types.rs
rust/worker/src/execution/operators/get_collection_and_segments.rs

There's another path that paged for soft-deleted collections.  Squash
that error so it doesn't trace at the top level.
CI
N/A
See pages decrease or unveil the next error.
N/A

[CHORE] Squash yet another soft-deleted collection path.

---

rust/Dockerfile

This PR restricts core dumps within docker containers to 0 bytes.  They will not dump.
CI
N/A
N/A
N/A

[CHORE]  Disable core dumps.

---

go/pkg/sysdb/metastore/s3/impl.go

Validated the new prefix in Minio's UI. I updated the only place in our codebase that constructs version & lineage prefixes. We store the full path to the version file.

[ENH]: update the version file prefix to match the prefix used by segments

---

rust/frontend/src/server.rs

Adding the "collection_id" attribute to the metrics causes an excessive number of events to be emitted. At some point we may even want to remove the "tenant_id" attribute (not sure it's really that useful).
Unit tests passing, otherwise untested. Manually inspected our metrics dashboards to ensure we aren't currently using these attributes.
N/S
Ensure dashboards remain unaffected.
N/A

[BUG] Reduce RFE metric cardinality

---

rust/log-service/src/lib.rs
rust/wal3/src/lib.rs
rust/wal3/src/manifest.rs
rust/wal3/src/manifest_manager.rs
rust/wal3/src/writer.rs

Prior to this commit, the code cached just the manifest.  By caching the
etag we can HEAD the manifest if it hasn't changed and get some latency
improvements for scout logs.
CI
I changed the cache key, so even if we had a disk cache it would be backwards-compatible.
N/A
N/A

[ENH][log]  Cache the manifest and etag.

---

Cargo.lock
Cargo.toml
rust/blockstore/src/arrow/block/delta/storage.rs
rust/blockstore/src/arrow/block/value/f32_value.rs
rust/blockstore/src/arrow/block/value/mod.rs
rust/blockstore/src/arrow/blockfile.rs
rust/blockstore/src/memory/reader_writer.rs
rust/blockstore/src/types/key.rs
rust/blockstore/src/types/reader.rs
rust/blockstore/src/types/value.rs
rust/index/Cargo.toml
rust/index/examples/sparse_wand_benchmark.rs
rust/index/src/lib.rs
rust/index/src/sparse/README.md
rust/index/src/sparse/mod.rs
rust/index/src/sparse/reader.rs
rust/index/src/sparse/types.rs
rust/index/src/sparse/writer.rs
rust/types/src/signed_rbm.rs

- N/A
- Implements prototype sparse vector reader and writer
- The implementation is based on the [Block-Max Wand](https://user.ceng.metu.edu.tr/~isikligil/ceng334/HW3/results/1881366/recover1/file_1.pdf) algorithm
- Some high level implementation info is provided in the `README.md` under the module directory
_Are all docstrings for user-facing APIs updated if required? Do we need to make documentation changes in the [docs …

[ENH] Implement sparse vector support

---

rust/blockstore/src/arrow/blockfile.rs
rust/blockstore/src/arrow/provider.rs
rust/index/src/spann/types.rs
rust/segment/src/blockfile_metadata.rs
rust/segment/src/blockfile_record.rs
rust/segment/src/types.rs
rust/tracing/src/util.rs
rust/worker/src/execution/operators/filter.rs
rust/worker/src/execution/operators/knn_projection.rs
rust/worker/src/execution/operators/limit.rs
rust/worker/src/execution/operators/projection.rs
rust/worker/src/execution/operators/spann_fetch_pl.rs
rust/worker/src/execution/orchestration/spann_knn.rs

- Removes really spammy spans
- Also adds ability to log slow operations by adding a RAII guard that tracks the duration of the operation. Used it to log slow cold block gets and slow sparse index fetches as an expt
- ...
None
Observe on staging
None

[CLN]: Remove spans + add tracing for slow operations

---

rust/frontend/src/impls/service_based_frontend.rs
rust/metering/src/errors.rs
rust/metering/src/lib.rs
rust/metering/src/receiver.rs

Adds a metric for metering events sent by the frontend to the metering event receiver.
- Tested in Jaeger
N/A
N/A
N/A

[CHORE] add metrics for metering events sent to receiver

---

rust/log-service/src/lib.rs
rust/types/src/api_types.rs
rust/wal3/src/writer.rs

Prior to this fix, a backoff error generated from pushing too many logs
would generate the scary, "log contention and your data may or may not
be durable."  Tested that it now generates a Backoff properly.  Then,
make Backoff map to a 429, not a 5xx.
Manual testing + CI
N/A
N/A
N/A

[BUG]  Proxy wal3's backoff error without log contention.

---

rust/storage/src/lib.rs
rust/storage/src/s3.rs

Amazon periodically tells us to slow down and that manifests as a
gruesome error trace.  Make a specific error type so callers can handle
the error.
CI
N/A
N/A
N/A

[ENH]  Explicitly convert SlowDown from S3 to StorageError::Backoff

---

rust/segment/src/blockfile_metadata.rs

- After collection fork, the sparse vector blockfile are put under the child collection prefix, which is inconsistent to the existing behavior where new blockfiles are put under the root collection prefix. Although the long term fix is to move all new blockfiles after fork under child collection prefix, as a temporary workaround we just put the sparse vector blockfiles under the root collection as well. 
- N/A
_Are all docstrings for user-facing APIs updated if required? Do we need …

[BUG] Sparse vector index incorrect blockfile path

---

rust/segment/src/blockfile_metadata.rs

This PR cherry-picks the commit 17e083add76c3d13289ffda328bfef6c1e955406 onto rc/2025-09-05. If there are unresolved conflicts, please resolve them manually.

[HOTFIX] applying PR #5418 to rc/2025-09-05

---

go/pkg/log/server/server.go

During the re-apply I dropped this change.  It's causing the go service
to fail with an error contacting the old log.
CI
N/A
errors meet zero
N/A

[BUG] No go errors for GetAllCollectionInfoToCompact.

---

docs/docs.trychroma.com/markdoc/content/cloud/quotas-limits.md

Update quota docs with max number of records per write operation
- ...
- ...

[DOC] Add quota for max # of records per write op

---

Cargo.lock
Cargo.toml
rust/index/src/config.rs
rust/index/src/hnsw.rs
rust/index/src/hnsw_provider.rs
rust/index/src/lib.rs
rust/index/src/spann/types.rs
rust/index/src/types.rs
rust/segment/src/distributed_spann.rs
rust/worker/benches/spann.rs
rust/worker/src/compactor/compaction_manager.rs

Added logic to load the HNSW sparse index without a disk intermediary by taking advantage of chroma/hnswlib's [corresponding change](https://github.com/chroma-core/hnswlib/commit/20f8c6123d744379e437161ed9071eb697c01f6f). This is gated by the `hnsw_provider` config feature flag `load_hnsw_from_memory` which is false by default.
- Loads the HNSW index from S3 without a disk intermediary by directly passing in the memory buffer given by S3.
This feature is false by default, but the tests in `hnsw_provider.rs` pass with it set to true and false.
_Are all …

[ENH]: Load HNSW index without disk intermediary

---

rust/index/src/hnsw.rs
rust/index/src/hnsw_provider.rs
rust/index/src/spann/types.rs
rust/index/src/types.rs
rust/segment/src/distributed_hnsw.rs
rust/worker/src/compactor/compaction_manager.rs

- This change opens up functionality for the Spann write path to also avoid using a disk intermediary for its HNSW indexes.
- As described above, this would still be gated by the `load_hnsw_from_memory` config flag for `hnsw_provider`.

[ENH]: Add HNSW loading from memory to the write path

---

clients/new-js/packages/chromadb/src/utils.ts

Adding validation for `SparseVector` metadata values in the JS client

[BUG] Allow SparseVector values in metadata for JS

---

Cargo.lock
rust/log-service/src/lib.rs
rust/storage/src/admissioncontrolleds3.rs
rust/storage/src/lib.rs
rust/storage/src/local.rs
rust/storage/src/object_store.rs
rust/storage/src/s3.rs
rust/wal3/src/manifest.rs
rust/wal3/src/reader.rs

This PR changes scout logs to consult the cache on ScoutLogs.  If the
manifest was recently in the cache, wal3/rls will perform a HEAD
operation to fetch the object into cache.
This PR contains tests written by Claude.
CI
N/A
N/A
N/A

[ENH]  ScoutLogs issues a HEAD if possible.

---

docs/docs.trychroma.com/markdoc/content/cloud/quotas-limits.md
rust/frontend/src/quota/mod.rs

- Updates cloud docs for latest embedding dimension + metadata quota limits
- Updates rust code for default embedding dimension quota. (Cannot update metadata quota limits here until refactor to support per-action defaults, instead of per-rule defaults). 
n/a
n/a
n/a
n/a

[ENH] increase cloud quotas in docs + defaults

---

docs/docs.trychroma.com/markdoc/content/integrations/chroma-integrations.md
docs/docs.trychroma.com/markdoc/content/integrations/frameworks/mem0.md

This PR adds an example for the mem0 and chromadb integration and use case.
- Adds mem0 <> chromadb example.
None
Yes it's documentation change.

Chroma <> mem0

---

chromadb/api/collection_configuration.py
chromadb/api/models/CollectionCommon.py
chromadb/api/types.py
chromadb/test/configurations/test_collection_configuration.py
chromadb/test/ef/test_ef.py
chromadb/utils/embedding_functions/__init__.py
chromadb/utils/embedding_functions/fastembed_sparse_embedding_function.py
chromadb/utils/embedding_functions/huggingface_sparse_embedding_function.py
chromadb/utils/embedding_functions/jina_embedding_function.py

This PR adds a new function embed_query on the base embeddingfunction type to allow embedding functions to define a secondary path to embed documents for query path. by default this will invoke the __call__ method.
this also adds a new protocol for SparseEmbeddingFunctions, and 2 new embedding functions: huggingface_sparse_embedding_function and fastembed_sparse_embedding_function

[ENH] add query config on collection configuration, splade, and bm25 efs

---

rust/worker/src/config.rs
rust/worker/src/execution/orchestration/sparse_knn.rs
rust/worker/src/server.rs

- N/A
- Adds a temporary config to always enable bm25 for certain tenants. This should be removed once we have collection schema ready.

[ENH] Tenant override for bm25

---

rust/js_bindings/package.json

Our published `chromadb-js-bindings-linux-x64-gnu` and `chromadb-js-bindings-linux-arm64-gnu` packages are currently over 400MB. Together they receive > 30k weekly downloads.
The majority of the binary size comes from debug symbols. The `chromadb` PyPi package ships with a similar set of bindings, but properly strips the debug symbols and [its wheels are < 20MB](https://pypi.org/project/chromadb/#files). This PR updates the JS bindings to strip the debug symbols as well.
_Are all docstrings for user-facing APIs updated if required? Do we need to make documentation …

[BLD]: strip debug symbols from JS bindings

---

chromadb/utils/embedding_functions/fastembed_sparse_embedding_function.py
chromadb/utils/embedding_functions/huggingface_sparse_embedding_function.py
chromadb/utils/sparse_embedding_utils.py

The Embedding functions assume the values returned from the model have indexes sorted in ascending order. This is not true for the BM25 model, so the embedding functions are both updated to sort prior to returning.
- ...
- ...

[CHORE] Sort SparseEmbeddings in EFs in ascending order

---

chromadb/test/ef/test_ef.py
chromadb/utils/embedding_functions/__init__.py
chromadb/utils/embedding_functions/bm25_embedding_function.py
chromadb/utils/embedding_functions/huggingface_sparse_embedding_function.py

This PR updates the fastembed embedding function with more parameters to support, and adds bm25 embedding function , which is a thin wrapper around the fastembed bm25 class
- ...
- ...

[ENH] Update Fastembed embedding function with more parameters, add bm25 embedding function

---

rust/garbage_collector/src/garbage_collector_component.rs
rust/garbage_collector/src/lib.rs
rust/garbage_collector/src/log_only_orchestrator.rs

This PR makes it so that if we run manual gc on a collection that has been fully hard deleted from
the sysdb, then the log will be deleted too.
CI + manual testing.
N/A
Tracing
N/A

[CHORE]  Hard delete for manually GC'ed collections

---

rust/storage/src/config.rs
rust/storage/src/s3.rs

This PR makes it so that we introduce two new configurations:  retry
count and stall_protection_ms.  The stall protection should be 2/3 of
the retry_timeout_ms according to examples gleamed from the Internet.
Certainly less so that it can kick in before the retry.
The current retry_timeout_ms is converted into a per-attempt value to
maximally preserve current behavior.
CI + Staging
N/A
Observe and tune the values on staging.
N/A

[ENH]  Improve our usage of the AWS S3 SDK.

---

rust/frontend/Cargo.toml
rust/tracing/Cargo.toml
rust/tracing/src/lib.rs

Move the middleware helper behind a `middleware` feature in `chroma-tracing`.

[CHORE] move middleware helper behind a feature in chroma-tracing

---

go/pkg/sysdb/metastore/db/dao/collection_metadata.go
go/pkg/sysdb/metastore/db/dao/collection_metadata_test.go

Prior to this PR, the `collection_metadata.updated_at` column was not correctly updated when a metadata attribute was changed.
Added a new test.

[BUG]: update `collection_metadata.updated_at` timestamp when row is updated

---

.github/workflows/pr.yml

This is to create a discussion. I'd like to hear from others as to whether this is a desired property of our GitHub Actions configuration.
This adds a concurrency group for our PR checks. This solves for the case where a developer pushes a commit to a PR, the build is triggered, then shortly thereafter (any time before the triggered build completes) another build is triggered but the previous is not cancelled. This change will cancel any inflight builds when a new commit for a PR is pushed. We are only doing this for PR checks as we don't necessarily want this behavior for our merges to main. 
- Cancels in-flight builds when new commits are pushed
Should have no effect on existing functionality.

[BLD] Add a concurrency group to our PR checks workflow

---

rust/garbage_collector/src/operators/fetch_sparse_index_files.rs

This isn't really an "error", more of a warning.
Mirroring implementation of similar fix: https://github.com/chroma-core/chroma/pull/5516
CI
N/A
Ensure traces are no longer generated for this condition.
N/A

[CHORE] Do not trace errors stemming from NotFound sparse indexes

---

rust/log-service/src/lib.rs

Add a read-only mode to the rust log service so it can be brought up for DR.
Tested in tilt:
```
rust-fronten… │   2025-09-30T15:03:08.056409Z ERROR  error: Failed to push logs: status: PermissionDenied, message: "service is in read-only mode", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 30 Sep 2025 15:03:07 GMT", "content-length": "0"} }
rust-fronten… │     at rust/log/src/log.rs:96
rust-fronten… │     in push_logs with tenant: "default_tenant", collection_id: CollectionUuid(e101eb7d-69e9-4473-9cee-27ced3c39b53)
rust-fronten… │     in collection_add
rust-fronten… │     in HTTP request with http.method: POST, http.uri: /api/v2/tenants/default_tenant/databases/test_54f26162-81f4-4f1b-9c18-8e884d5537f1/collections/e101eb7d-69e9-4473-9cee-2 …
```

[ENH]  Support a read-only mode for the rust log service.

---

idl/chromadb/proto/logservice.proto
rust/log-service/src/lib.rs

This is so that cops service can pull in the types and pretty-print
them.
CI
N/A
N/A
N/A

[ENH] Return JSON from InspectLogState.

---

chromadb/api/__init__.py
chromadb/api/async_api.py
chromadb/api/async_client.py
chromadb/api/client.py
chromadb/api/models/CollectionCommon.py
chromadb/api/types.py
chromadb/test/api/test_schema.py
chromadb/utils/embedding_functions/__init__.py
clients/new-js/packages/chromadb/src/api/types.gen.ts
rust/distance/src/types.rs
rust/frontend/src/executor/local.rs
rust/types/src/collection_configuration.rs
rust/types/src/collection_schema.rs
rust/types/src/hnsw_configuration.rs
rust/types/src/lib.rs
rust/types/src/spann_configuration.rs

- Adds the InternalSchema type in FE
- Axum and serde automatically parse json into this type
- Client side reconciliation of ef and space based on supplied value
- Server side merging of schema with collection config and erroring in various cases
- ...
Plenty of vibe coded tests
None
None
None

[ENH]: Schema type in FE

---

clients/new-js/packages/chromadb/src/api/types.gen.ts
idl/chromadb/proto/chroma.proto
idl/chromadb/proto/coordinator.proto
rust/cli/src/client/chroma_client.rs
rust/frontend/sample_configs/distributed.yaml
rust/frontend/src/config.rs
rust/frontend/src/executor/local.rs
rust/frontend/src/impls/in_memory_frontend.rs
rust/frontend/src/impls/service_based_frontend.rs
rust/frontend/src/server.rs
rust/frontend/tests/proptest_helpers/frontend_reference.rs
rust/frontend/tests/proptest_helpers/frontend_under_test.rs
rust/garbage_collector/src/construct_version_graph_orchestrator.rs
rust/garbage_collector/src/garbage_collector_orchestrator_v2.rs
rust/garbage_collector/src/helper.rs
rust/garbage_collector/tests/prop_test_local_files.rs
rust/garbage_collector/tests/proptest_helpers/garbage_collector_under_test.rs
rust/python_bindings/src/bindings.rs
rust/sysdb/src/sqlite.rs
rust/sysdb/src/sysdb.rs
rust/types/src/api_types.rs
rust/types/src/collection.rs
rust/types/src/collection_schema.rs
rust/worker/src/execution/orchestration/compact.rs

This PR adds the necessary proto & rust changes to support schema as part of the server for create and get collection. It also adds a config flag enable_schema to allow us to feature flag until we are ready to enable & use it.
- ...
- ...

[ENH] Add schema type to create_collection and Collection object type

---

.github/workflows/pr.yml

We've kept the code base remarkably clean, but it's not actually
enforced by CI that there are no clippy warnings.  This should fix that.
CI
N/A
N/A
N/A

[CHORE]  Make all clippy warnings errors.
